# Generated by Django 6.0.2 on 2026-03-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_user_commission_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, max_length=15, null=True, unique=True
            ),
        ),
    ]
