# Generated by Django 6.0.2 on 2026-03-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_snapshot", models.CharField(db_index=True, max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("PHONE_OTP", "Phone OTP"),
                            ("EMAIL_LINK", "Email Link"),
                        ],
                        db_index=True,
                        default="PHONE_OTP",
                        max_length=20,
                    ),
                ),
                (
                    "identifier_snapshot",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier used at request time, such as phone, email, or username.",
                        max_length=255,
                    ),
                ),
                (
                    "otp_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Store only the hashed OTP. Never store raw OTP values.",
                        max_length=255,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("USED", "Used"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("failed_attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                (
                    "requested_by_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("requested_user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="password_re_user_id_52ae42_idx",
                    ),
                    models.Index(
                        fields=["identifier_snapshot", "status", "created_at"],
                        name="password_re_identif_bb04ac_idx",
                    ),
                    models.Index(
                        fields=["channel", "status", "expires_at"],
                        name="password_re_channel_339878_idx",
                    ),
                ],
            },
        ),
    ]
