# Generated by Django 6.0.2 on 2026-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passwordresetrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="channel",
            field=models.CharField(
                choices=[
                    ("PHONE_OTP", "Phone OTP"),
                    ("EMAIL_OTP", "Email OTP"),
                    ("EMAIL_LINK", "Email Link"),
                ],
                db_index=True,
                default="PHONE_OTP",
                max_length=20,
            ),
        ),
    ]
