# Generated by Django 6.0.2 on 2026-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_passwordresetrequest_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetrequest",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="resend_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
