# Generated by Django 5.2.7 on 2026-05-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_inventory_opening_stock_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecapability',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARTNER', 'Partner'), ('CUSTOMER', 'Customer'), ('CASHIER', 'Cashier'), ('VENDOR', 'Vendor')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARTNER', 'Partner'), ('CUSTOMER', 'Customer'), ('CASHIER', 'Cashier'), ('VENDOR', 'Vendor')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
