# Generated by Django 6.0.2 on 2026-05-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_rolecapability_role_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedUsername",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=150, unique=True),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                (
                    "reserved_from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserved_usernames",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reserved_usernames",
                "ordering": ["-reserved_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["reserved_at"], name="reserved_us_reserve_8fa35b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsernameChangeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_username", models.CharField(max_length=150)),
                ("new_username", models.CharField(max_length=150)),
                (
                    "changed_by_role",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SELF", "Self"), ("ADMIN", "Admin")],
                        db_index=True,
                        default="SELF",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_username_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="username_change_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "username_change_audits",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "changed_at"],
                        name="username_ch_user_id_1a0454_idx",
                    ),
                    models.Index(
                        fields=["source", "changed_at"],
                        name="username_ch_source_32f321_idx",
                    ),
                ],
            },
        ),
    ]
