# Generated by Django 6.0.2 on 2026-04-10 02:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import service_desk.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0004_directsaleline_billinginvoice_source_reference_and_more'),
        ('crm', '0001_initial'),
        ('inventory', '0004_inventoryitem_delivery_stock_bridge_enabled_and_more'),
        ('subscriptions', '0039_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_no', models.CharField(db_index=True, default=service_desk.models.generate_service_case_no, max_length=40, unique=True)),
                ('case_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('SALES_RETURN', 'Sales Return'), ('DELIVERY_RETURN', 'Delivery Return'), ('EXCHANGE', 'Exchange'), ('SERVICE', 'Service')], db_index=True, default='COMPLAINT', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('AUTHORIZED', 'Authorized'), ('IN_SERVICE', 'In Service'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=12)),
                ('warranty_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('IN_WARRANTY', 'In Warranty'), ('OUT_OF_WARRANTY', 'Out Of Warranty'), ('GOODWILL', 'Goodwill')], db_index=True, default='UNKNOWN', max_length=20)),
                ('finance_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('POSTED', 'Posted')], db_index=True, default='NOT_REQUIRED', max_length=20)),
                ('stock_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('SETTLED', 'Settled')], db_index=True, default='NOT_REQUIRED', max_length=20)),
                ('credit_note_required', models.BooleanField(db_index=True, default=False)),
                ('debit_note_required', models.BooleanField(db_index=True, default=False)),
                ('stock_resolution_required', models.BooleanField(db_index=True, default=False)),
                ('issue_summary', models.CharField(max_length=200)),
                ('issue_details', models.TextField(blank=True, default='')),
                ('reporter_name_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('reporter_phone_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('service_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_service_desk_cases', to=settings.AUTH_USER_MODEL)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_service_desk_cases', to=settings.AUTH_USER_MODEL)),
                ('billing_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='billing.billinginvoice')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_service_desk_cases', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='billing.billingcreditnote')),
                ('debit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='billing.billingdebitnote')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='subscriptions.subscriptiondelivery')),
                ('direct_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='billing.directsale')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='inventory.inventoryitem')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_cases', to='crm.partymaster')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='subscriptions.product')),
                ('replacement_direct_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_service_desk_cases', to='billing.directsale')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_service_desk_cases', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='subscriptions.subscription')),
                ('support_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_cases', to='subscriptions.customersupportrequest')),
            ],
            options={
                'db_table': 'service_desk_cases',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeskCaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('disposition', models.CharField(choices=[('RESTOCK', 'Restock'), ('REPAIR', 'Repair'), ('REPLACE', 'Replace'), ('INSPECT', 'Inspect'), ('SCRAP', 'Scrap')], db_index=True, default='INSPECT', max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_case_lines', to='inventory.inventoryitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_desk_case_lines', to='subscriptions.product')),
                ('service_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='service_desk.servicedeskcase')),
            ],
            options={
                'db_table': 'service_desk_case_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['case_type', 'status', 'created_at'], name='service_des_case_ty_d9e74e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['party', 'created_at'], name='service_des_party_i_73413e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['support_request', 'created_at'], name='service_des_support_3ad12e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['direct_sale', 'created_at'], name='service_des_direct__7cf835_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['subscription', 'created_at'], name='service_des_subscri_266b72_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['delivery', 'created_at'], name='service_des_deliver_bcd9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['billing_invoice', 'created_at'], name='service_des_billing_2bb9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['assigned_to', 'status'], name='service_des_assigne_324695_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeskcase',
            index=models.Index(fields=['finance_status', 'stock_status'], name='service_des_finance_40ddcd_idx'),
        ),
    ]
