# Generated by Django 6.0.2 on 2026-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedeskcase',
            name='case_type',
            field=models.CharField(choices=[('COMPLAINT', 'Complaint'), ('SALES_RETURN', 'Sales Return'), ('DELIVERY_RETURN', 'Delivery Return'), ('EXCHANGE', 'Exchange'), ('SERVICE', 'Service'), ('DIRECT_SALE_DELIVERY', 'Direct Sale Delivery')], db_index=True, default='COMPLAINT', max_length=24),
        ),
    ]
