# Generated by Django 6.0.2 on 2026-05-06 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_directsale_customer_gst_type_and_more'),
        ('crm', '0003_rename_crm_customer_customer_921db4_idx_crm_custome_custome_bea333_idx_and_more'),
        ('service_desk', '0002_alter_servicedeskcase_case_type'),
        ('subscriptions', '0063_branddatasource_businessmediaasset_sociallink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('category', models.CharField(choices=[('SERVICE_REQUEST', 'Service Request'), ('RETURN_REQUEST', 'Return Request'), ('WARRANTY_CLAIM', 'Warranty Claim'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('PRODUCT_DAMAGE', 'Product Damage'), ('PAYMENT_ISSUE', 'Payment Issue'), ('EMI_QUERY', 'EMI Query'), ('RENT_QUERY', 'Rent Query'), ('LEASE_QUERY', 'Lease Query'), ('DIRECT_SALE_QUERY', 'Direct Sale Query'), ('DOCUMENT_CORRECTION', 'Document Correction'), ('CUSTOMER_PROFILE_UPDATE', 'Customer Profile Update'), ('LUCKY_DRAW_QUERY', 'Lucky Draw Query'), ('PARTNER_COMPLAINT', 'Partner Complaint'), ('GENERAL_SUPPORT', 'General Support')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_REVIEW', 'In Review'), ('WAITING_FOR_CUSTOMER', 'Waiting For Customer'), ('WAITING_FOR_INTERNAL_ACTION', 'Waiting For Internal Action'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], db_index=True, default='OPEN', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=12)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('CUSTOMER_PORTAL', 'Customer Portal'), ('ADMIN', 'Admin'), ('PHONE', 'Phone'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk In'), ('OTHER', 'Other')], db_index=True, default='CUSTOMER_PORTAL', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('preferred_contact_time', models.CharField(blank=True, default='', max_length=120)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='subscriptions.customer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='support_tickets/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_desk.supportticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket_attachments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service_desk.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_comments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('commented', 'Commented'), ('internal_note_added', 'Internal Note Added'), ('assigned', 'Assigned'), ('linked', 'Linked'), ('priority_changed', 'Priority Changed'), ('status_changed', 'Status Changed'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='service_desk.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('customer', 'Customer'), ('subscription', 'Subscription'), ('emi', 'EMI'), ('payment', 'Payment'), ('product', 'Product'), ('batch', 'Batch'), ('lucky_id', 'Lucky ID'), ('direct_sale', 'Direct Sale'), ('billing_invoice', 'Billing Invoice'), ('delivery', 'Delivery'), ('rent_contract', 'Rent Contract'), ('lease_contract', 'Lease Contract'), ('partner', 'Partner')], db_index=True, max_length=24)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.batch')),
                ('billing_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='billing.billinginvoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket_links_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.subscriptiondelivery')),
                ('direct_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='billing.directsale')),
                ('emi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.emi')),
                ('lease_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.leasesubscriptionprofile')),
                ('lucky_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.luckyid')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='crm.partymaster')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.payment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.product')),
                ('rent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.rentsubscriptionprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_ticket_links', to='subscriptions.subscription')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='service_desk.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_links',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer', 'status', 'created_at'], name='support_tic_custome_32a90b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='support_tic_status_7e44ef_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_9415d6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category', 'created_at'], name='support_tic_categor_88adc3_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketcomment',
            index=models.Index(fields=['ticket', 'is_internal', 'created_at'], name='support_tic_ticket__2a5215_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketevent',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0ab8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketlink',
            index=models.Index(fields=['ticket', 'link_type'], name='support_tic_ticket__b192a8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketlink',
            index=models.Index(fields=['subscription'], name='support_tic_subscri_f64fab_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketlink',
            index=models.Index(fields=['payment'], name='support_tic_payment_b8d481_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('customer__isnull', False)), fields=('ticket', 'link_type', 'customer'), name='uniq_support_link_ticket_customer'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('subscription__isnull', False)), fields=('ticket', 'link_type', 'subscription'), name='uniq_support_link_ticket_subscription'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('emi__isnull', False)), fields=('ticket', 'link_type', 'emi'), name='uniq_support_link_ticket_emi'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('ticket', 'link_type', 'payment'), name='uniq_support_link_ticket_payment'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('ticket', 'link_type', 'product'), name='uniq_support_link_ticket_product'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('ticket', 'link_type', 'batch'), name='uniq_support_link_ticket_batch'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('lucky_id__isnull', False)), fields=('ticket', 'link_type', 'lucky_id'), name='uniq_support_link_ticket_lucky_id'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('direct_sale__isnull', False)), fields=('ticket', 'link_type', 'direct_sale'), name='uniq_support_link_ticket_direct_sale'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_invoice__isnull', False)), fields=('ticket', 'link_type', 'billing_invoice'), name='uniq_support_link_ticket_billing_invoice'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery__isnull', False)), fields=('ticket', 'link_type', 'delivery'), name='uniq_support_link_ticket_delivery'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('rent_contract__isnull', False)), fields=('ticket', 'link_type', 'rent_contract'), name='uniq_support_link_ticket_rent_contract'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('lease_contract__isnull', False)), fields=('ticket', 'link_type', 'lease_contract'), name='uniq_support_link_ticket_lease_contract'),
        ),
        migrations.AddConstraint(
            model_name='supportticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('partner__isnull', False)), fields=('ticket', 'link_type', 'partner'), name='uniq_support_link_ticket_partner'),
        ),
    ]
