# Generated by Django 5.2.7 on 2026-07-09 19:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0006_servicedeskcase_payment_exception_acknowledged"),
        ("subscriptions", "0115_add_settlement_and_sla_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyExtendedPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_duration_months",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Additional months (typically 12, renewable)",
                    ),
                ),
                (
                    "plan_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="5-10% of product price",
                        max_digits=10,
                    ),
                ),
                (
                    "plan_cost_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="5.00 to 10.00 percent",
                        max_digits=4,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("coverage_start_date", models.DateField()),
                ("coverage_end_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="extended_warranty_plans",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_extended_plans",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "warranty_extended_plans",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warranty_labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Free for warranty; applies to extended warranty",
                        max_digits=10,
                    ),
                ),
                (
                    "out_of_warranty_labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000"),
                        help_text="₹500-2,000 range",
                        max_digits=10,
                    ),
                ),
                (
                    "home_service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Free within 5km, ₹500 beyond for warranty",
                        max_digits=10,
                    ),
                ),
                (
                    "travel_charge_beyond_5km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500"), max_digits=10
                    ),
                ),
                (
                    "home_visit_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Days for technician home visit (warranty period)",
                    ),
                ),
                (
                    "service_completion_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Days to complete repair/replacement"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_pricing",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "db_table": "service_pricing",
                "unique_together": {("product",)},
            },
        ),
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "warranty_type",
                    models.CharField(
                        choices=[
                            ("MANUFACTURING", "Manufacturing Defect (12-24 months)"),
                            ("STRUCTURAL", "Structural (3 years for furniture)"),
                            ("EXTENDED", "Extended Warranty (optional)"),
                        ],
                        default="MANUFACTURING",
                        max_length=20,
                    ),
                ),
                ("warranty_start_date", models.DateField()),
                ("warranty_end_date", models.DateField()),
                ("is_in_warranty", models.BooleanField(db_index=True, default=True)),
                ("defect_description", models.TextField()),
                ("defect_date_discovered", models.DateField()),
                (
                    "defect_classification",
                    models.CharField(
                        choices=[
                            ("MANUFACTURING_DEFECT", "Manufacturing Defect (COVERED)"),
                            ("WEAR_TEAR", "Wear & Tear (NOT COVERED)"),
                            ("USER_DAMAGE", "User Damage (NOT COVERED)"),
                            ("ENVIRONMENTAL", "Environmental Damage (LIMITED)"),
                            ("UNVERIFIED", "Unverified (pending assessment)"),
                        ],
                        db_index=True,
                        default="UNVERIFIED",
                        max_length=30,
                    ),
                ),
                (
                    "claim_submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_ASSESSMENT", "Under Assessment"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("assessment_notes", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recommended_remedy",
                    models.CharField(
                        choices=[
                            ("FREE_REPAIR", "Free Repair (warranty)"),
                            ("FREE_REPLACEMENT", "Free Replacement (warranty)"),
                            ("PAID_REPAIR", "Paid Repair (out-of-warranty)"),
                            ("PAID_REPLACEMENT", "Paid Replacement (out-of-warranty)"),
                            ("EXTENDED_WARRANTY", "Extended Warranty Enrollment"),
                            ("DECLINED", "Claim Declined"),
                        ],
                        default="FREE_REPAIR",
                        max_length=30,
                    ),
                ),
                (
                    "remedy_cost_labor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "remedy_cost_parts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "remedy_cost_travel",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "authorized_service_center",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "service_center_contact",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_warranty_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claims",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "service_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_claim",
                        to="service_desk.servicedeskcase",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warranty_claims",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_warranty_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "warranty_claims",
                "ordering": ["-claim_submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_in_warranty"],
                        name="warranty_cl_product_4ed289_idx",
                    ),
                    models.Index(
                        fields=["claim_status", "claim_submitted_at"],
                        name="warranty_cl_claim_s_3b8ac2_idx",
                    ),
                    models.Index(
                        fields=["defect_classification"],
                        name="warranty_cl_defect__f29d2b_idx",
                    ),
                ],
            },
        ),
    ]
