# Generated by Django 5.2.7 on 2026-07-09 19:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billinginvoice_tax_profile_snapshot_and_more"),
        ("service_desk", "0007_add_warranty_service_models"),
        ("subscriptions", "0116_add_warranty_coverage_and_service_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarrantyServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivery_date", models.DateField(db_index=True)),
                ("warranty_manufacturing_end", models.DateField(db_index=True)),
                ("warranty_structural_end", models.DateField(blank=True, null=True)),
                (
                    "is_in_manufacturing_warranty",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "is_in_structural_warranty",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "has_extended_warranty",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("total_service_calls", models.PositiveIntegerField(default=0)),
                ("total_warranty_claims", models.PositiveIntegerField(default=0)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_record",
                        to="subscriptions.subscriptiondelivery",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_record",
                        to="billing.billinginvoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_service_records",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "db_table": "warranty_service_records",
                "ordering": ["-delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="WarrantyServiceCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_call_date", models.DateField(db_index=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("REPAIR", "Repair"),
                            ("REPLACEMENT", "Replacement"),
                            ("MAINTENANCE", "Maintenance"),
                            ("INSPECTION", "Inspection"),
                        ],
                        default="REPAIR",
                        max_length=30,
                    ),
                ),
                (
                    "is_warranty_covered",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUFACTURING", "Manufacturing Warranty"),
                            ("STRUCTURAL", "Structural Warranty"),
                            ("EXTENDED", "Extended Warranty"),
                            ("PAID", "Paid Service"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "service_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total service cost (0 if warranty covered)",
                        max_digits=10,
                    ),
                ),
                ("technician_notes", models.TextField(blank=True, default="")),
                (
                    "service_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warranty_service_calls",
                        to="service_desk.servicedeskcase",
                    ),
                ),
                (
                    "warranty_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_calls",
                        to="service_desk.warrantyservicerecord",
                    ),
                ),
            ],
            options={
                "db_table": "warranty_service_calls",
                "ordering": ["-service_call_date"],
            },
        ),
        migrations.AddIndex(
            model_name="warrantyservicerecord",
            index=models.Index(
                fields=["product", "is_in_manufacturing_warranty"],
                name="warranty_se_product_c0ed9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyservicerecord",
            index=models.Index(
                fields=["delivery_date"], name="warranty_se_deliver_841ced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyservicerecord",
            index=models.Index(
                fields=["warranty_manufacturing_end"],
                name="warranty_se_warrant_9cca9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyservicecall",
            index=models.Index(
                fields=["warranty_record", "service_call_date"],
                name="warranty_se_warrant_6c9485_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyservicecall",
            index=models.Index(
                fields=["is_warranty_covered"], name="warranty_se_is_warr_9484f1_idx"
            ),
        ),
    ]
