# Generated by Django 5.2.7 on 2026-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_desk", "0009_alter_servicedeskcase_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warrantyclaim",
            name="preferred_date",
            field=models.DateField(
                blank=True, help_text="Date the customer asked for", null=True
            ),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="scheduled_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="service_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="technician_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
    ]
