# Generated by Django 5.0.7 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("path", models.CharField(db_index=True, editable=False, max_length=1024, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="catalog.catalogcategory")),
            ],
            options={"db_table": "catalog_categories", "ordering": ["path", "sort_order", "name", "id"]},
        ),
        migrations.CreateModel(
            name="AttributeDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=80)),
                ("input_type", models.CharField(choices=[("SELECT", "Select"), ("MULTI_SELECT", "Multi-select"), ("NUMBER", "Number"), ("TEXT", "Text"), ("BOOLEAN", "Boolean")], max_length=20)),
                ("options", models.JSONField(blank=True, default=list)),
                ("unit", models.CharField(blank=True, default="", max_length=30)),
                ("is_variant_attribute", models.BooleanField(db_index=True, default=False)),
                ("is_spec_attribute", models.BooleanField(db_index=True, default=True)),
                ("is_required", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("min_value", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("max_value", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("sku_code_map", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attribute_definitions", to="catalog.catalogcategory")),
            ],
            options={"db_table": "catalog_attribute_definitions", "ordering": ["category_id", "sort_order", "name", "id"]},
        ),
        migrations.AddIndex(model_name="catalogcategory", index=models.Index(fields=["parent", "is_active", "sort_order"], name="catalog_cat_parent__2814c3_idx")),
        migrations.AddIndex(model_name="attributedefinition", index=models.Index(fields=["category", "is_active", "sort_order"], name="catalog_att_categor_baa5e3_idx")),
        migrations.AddConstraint(model_name="attributedefinition", constraint=models.UniqueConstraint(fields=("category", "code"), name="uq_catalog_attribute_code_per_category")),
    ]
