# Generated by Django 5.2.7 on 2026-07-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attributedefinition",
            new_name="catalog_att_categor_862041_idx",
            old_name="catalog_att_categor_baa5e3_idx",
        ),
        migrations.RenameIndex(
            model_name="catalogcategory",
            new_name="catalog_cat_parent__2c19ec_idx",
            old_name="catalog_cat_parent__2814c3_idx",
        ),
    ]
