# Generated by Django 5.2.16 on 2026-09-26 07:44

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_att_categor_baa5e3_idx_catalog_att_categor_862041_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='regex_validation',
            field=models.CharField(blank=True, default='', help_text='Regex pattern for text validation', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='google_taxonomy_id',
            field=models.CharField(blank=True, default='', help_text='Standardized taxonomy ID for external marketplaces', max_length=50),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.catalogcategory'),
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['tree_id', 'lft'], name='catalog_catalogcategory_tr404a'),
        ),
    ]
