# Generated by Django 5.2.16 on 2026-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_attributedefinition_regex_validation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='catalogcategory',
            name='catalog_catalogcategory_tr404a',
        ),
    ]
