from django.urls import path

from api.v1.views.admin_password_reset_requests import (
    admin_password_reset_request_detail,
    admin_password_reset_request_invalidate,
    admin_password_reset_request_list,
    admin_password_reset_request_resend,
)
from api.v1.views.admin_policy_site import (
    AdminBusinessComplianceDocumentApprovePublicSummaryView,
    AdminBusinessComplianceDocumentApproveView,
    AdminBusinessComplianceDocumentDetailView,
    AdminBusinessComplianceDocumentExpireView,
    AdminBusinessComplianceDocumentListCreateView,
    AdminBusinessComplianceDocumentRejectView,
    AdminBusinessComplianceDocumentRevokePublicSummaryView,
    AdminBusinessComplianceDocumentSubmitReviewView,
    AdminBusinessComplianceReadinessView,
    AdminBusinessComplianceSeedRowsView,
    AdminBusinessComplianceTemplateListView,
    AdminPolicyCoverageView,
    AdminPolicyPageAcceptInternalView,
    AdminPolicyPageApproveView,
    AdminPolicyPageRejectView,
    AdminPolicyPageSubmitReviewView,
    AdminPolicyPageSyncGovernanceMetadataView,
)

urlpatterns = [
    path("settings/policies/coverage/", AdminPolicyCoverageView.as_view(), name="admin-policy-coverage"),
    path("public-site/policies/<int:pk>/submit-review/", AdminPolicyPageSubmitReviewView.as_view(), name="admin-policy-submit-review"),
    path("public-site/policies/<int:pk>/approve/", AdminPolicyPageApproveView.as_view(), name="admin-policy-approve"),
    path("public-site/policies/<int:pk>/reject/", AdminPolicyPageRejectView.as_view(), name="admin-policy-reject"),
    path("public-site/policies/<int:pk>/accept-internal/", AdminPolicyPageAcceptInternalView.as_view(), name="admin-policy-accept-internal"),
    path("public-site/policies/<int:pk>/sync-governance-metadata/", AdminPolicyPageSyncGovernanceMetadataView.as_view(), name="admin-policy-sync-governance-metadata"),
    path("settings/business-compliance/templates/", AdminBusinessComplianceTemplateListView.as_view(), name="admin-business-compliance-templates"),
    path("settings/business-compliance/seed-rows/", AdminBusinessComplianceSeedRowsView.as_view(), name="admin-business-compliance-seed-rows"),
    path("settings/business-compliance/readiness/", AdminBusinessComplianceReadinessView.as_view(), name="admin-business-compliance-readiness"),
    path("settings/business-compliance/documents/", AdminBusinessComplianceDocumentListCreateView.as_view(), name="admin-business-compliance-documents"),
    path("settings/business-compliance/documents/<int:pk>/", AdminBusinessComplianceDocumentDetailView.as_view(), name="admin-business-compliance-document-detail"),
    path("settings/business-compliance/documents/<int:pk>/submit-review/", AdminBusinessComplianceDocumentSubmitReviewView.as_view(), name="admin-business-compliance-document-submit-review"),
    path("settings/business-compliance/documents/<int:pk>/approve/", AdminBusinessComplianceDocumentApproveView.as_view(), name="admin-business-compliance-document-approve"),
    path("settings/business-compliance/documents/<int:pk>/reject/", AdminBusinessComplianceDocumentRejectView.as_view(), name="admin-business-compliance-document-reject"),
    path("settings/business-compliance/documents/<int:pk>/expire/", AdminBusinessComplianceDocumentExpireView.as_view(), name="admin-business-compliance-document-expire"),
    path("settings/business-compliance/documents/<int:pk>/approve-public-summary/", AdminBusinessComplianceDocumentApprovePublicSummaryView.as_view(), name="admin-business-compliance-document-approve-public-summary"),
    path("settings/business-compliance/documents/<int:pk>/revoke-public-summary/", AdminBusinessComplianceDocumentRevokePublicSummaryView.as_view(), name="admin-business-compliance-document-revoke-public-summary"),
    path("password-reset-requests/", admin_password_reset_request_list, name="admin-password-reset-request-list"),
    path("password-reset-requests/<int:request_id>/", admin_password_reset_request_detail, name="admin-password-reset-request-detail"),
    path("password-reset-requests/<int:request_id>/invalidate/", admin_password_reset_request_invalidate, name="admin-password-reset-request-invalidate"),
    path("password-reset-requests/<int:request_id>/resend/", admin_password_reset_request_resend, name="admin-password-reset-request-resend"),
]
