from django.urls import path

from api.v1.views.customer import (
    CustomerDashboard,
    CustomerDeliveryDetailView,
    CustomerDeliveryListView,
    CustomerDeliveryPdfView,
    CustomerKycDocumentListView,
    CustomerKycUpdateRequestView,
    CustomerPaymentDetailView,
    CustomerPaymentListView,
    CustomerPhotoUploadView,
    CustomerProfileView,
    CustomerReferralCreateView,
    CustomerReferralListView,
    CustomerSupportRequestDetailView,
    CustomerSupportRequestListCreateView,
    CustomerSubscriptionDetailView,
)
from api.v1.views.phase4_finance import (
    CustomerAccountStatementView,
    CustomerDirectSaleDetailView,
    CustomerDirectSaleListView,
    CustomerDirectSaleSummaryView,
    CustomerDepositPdfView,
    CustomerDocumentListView,
    CustomerFinanceSummaryView,
    CustomerInvoiceListView,
    CustomerLeaseContractPdfView,
    CustomerInvoicePdfView,
    CustomerPaymentScheduleView,
    CustomerRentContractPdfView,
    CustomerReceiptListView,
    CustomerReceiptPdfView,
    CustomerReturnInspectionPdfView,
)
from api.v1.views.paginated_registers import PaginatedCustomerSubscriptionListView
from api.v1.views.subscription_requests import (
    CustomerSubscriptionRequestCancelView,
    CustomerSubscriptionRequestDetailView,
    CustomerSubscriptionRequestListCreateView,
    CustomerSubscriptionRequestOptionsView,
)

urlpatterns = [
    path("dashboard/", CustomerDashboard.as_view()),
    path("profile/", CustomerProfileView.as_view()),
    path("profile/photo/", CustomerPhotoUploadView.as_view()),
    path("kyc/documents/", CustomerKycDocumentListView.as_view()),
    path("kyc/request-update/", CustomerKycUpdateRequestView.as_view()),
    path("referrals/", CustomerReferralListView.as_view()),
    path("referrals/create/", CustomerReferralCreateView.as_view()),
    path("subscriptions/", PaginatedCustomerSubscriptionListView.as_view()),
    path("subscriptions/<int:pk>/", CustomerSubscriptionDetailView.as_view()),
    path("subscription-request-options/", CustomerSubscriptionRequestOptionsView.as_view()),
    path("subscription-requests/", CustomerSubscriptionRequestListCreateView.as_view()),
    path("subscription-requests/<int:pk>/", CustomerSubscriptionRequestDetailView.as_view()),
    path("subscription-requests/<int:pk>/cancel/", CustomerSubscriptionRequestCancelView.as_view()),
    path("deliveries/", CustomerDeliveryListView.as_view()),
    path("deliveries/<int:pk>/", CustomerDeliveryDetailView.as_view()),
    path("deliveries/<int:pk>/pdf/", CustomerDeliveryPdfView.as_view()),
    path("payments/", CustomerPaymentListView.as_view()),
    path("payments/<int:pk>/", CustomerPaymentDetailView.as_view()),
    path("direct-sales/", CustomerDirectSaleListView.as_view()),
    path("direct-sales/summary/", CustomerDirectSaleSummaryView.as_view()),
    path("direct-sales/<int:pk>/", CustomerDirectSaleDetailView.as_view()),
    # Phase 4: customer finance + documents
    path("finance/summary/", CustomerFinanceSummaryView.as_view()),
    path("invoices/", CustomerInvoiceListView.as_view()),
    path("invoices/<int:pk>/pdf/", CustomerInvoicePdfView.as_view()),
    path("rent-contracts/<int:pk>/pdf/", CustomerRentContractPdfView.as_view()),
    path("lease-contracts/<int:pk>/pdf/", CustomerLeaseContractPdfView.as_view()),
    path("deposits/<int:pk>/pdf/", CustomerDepositPdfView.as_view()),
    path("returns/<int:pk>/inspection-pdf/", CustomerReturnInspectionPdfView.as_view()),
    path("receipts/", CustomerReceiptListView.as_view()),
    path("receipts/<int:pk>/pdf/", CustomerReceiptPdfView.as_view()),
    path("documents/", CustomerDocumentListView.as_view()),
    path("payment-schedule/", CustomerPaymentScheduleView.as_view()),
    path("account-statement/", CustomerAccountStatementView.as_view()),
    path("support-requests/", CustomerSupportRequestListCreateView.as_view()),
    path("support-requests/<int:pk>/", CustomerSupportRequestDetailView.as_view()),
]
