# Generated by Django 6.0.2 on 2026-04-28 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('DOC', 'Document'), ('PDF', 'PDF'), ('POLICY', 'Policy'), ('FAQ', 'FAQ'), ('CONTRACT_TEMPLATE', 'Contract Template'), ('INTERNAL_RUNBOOK', 'Internal Runbook'), ('PUBLIC_PAGE', 'Public Page'), ('SYSTEM_HELP', 'System Help')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=16)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('STAFF', 'Staff'), ('PARTNER', 'Partner'), ('CUSTOMER_PUBLIC', 'Customer Public'), ('PUBLIC', 'Public')], db_index=True, default='ADMIN_ONLY', max_length=24)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='ai_assistant/sources/%Y/%m/')),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_ai_knowledge_sources', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_ai_knowledge_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_knowledge_sources',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('ADMIN_ONLY', 'Admin Only'), ('STAFF', 'Staff'), ('PARTNER', 'Partner'), ('CUSTOMER_PUBLIC', 'Customer Public'), ('PUBLIC', 'Public')], db_index=True, default='ADMIN_ONLY', max_length=24)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_assistant.aiknowledgesource')),
            ],
            options={
                'db_table': 'ai_knowledge_chunks',
                'ordering': ['source_id', 'chunk_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('query', models.TextField()),
                ('normalized_query', models.TextField(blank=True, default='')),
                ('retrieval_mode', models.CharField(choices=[('KEYWORD', 'Keyword'), ('VECTOR', 'Vector'), ('HYBRID', 'Hybrid')], db_index=True, default='HYBRID', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('retrieved_chunk_ids', models.JSONField(blank=True, default=list)),
                ('answer_preview', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('denied_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_query_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful'), ('UNSAFE', 'Unsafe'), ('INCORRECT', 'Incorrect')], db_index=True, max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.aiquerylog')),
            ],
            options={
                'db_table': 'ai_feedback',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AIEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, help_text='JSON placeholder until pgvector is introduced in a later phase.', null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=128)),
                ('dimensions', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='ai_assistant.aiknowledgechunk')),
            ],
            options={
                'db_table': 'ai_embeddings',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['embedding_model'], name='ai_embeddin_embeddi_b269b9_idx'), models.Index(fields=['content_hash'], name='ai_embeddin_content_d3d386_idx')],
                'constraints': [models.UniqueConstraint(fields=('chunk', 'embedding_model', 'content_hash'), name='uq_ai_embedding_chunk_model_hash')],
            },
        ),
        migrations.AddIndex(
            model_name='aiknowledgesource',
            index=models.Index(fields=['status', 'visibility'], name='ai_knowledg_status_4bcf8e_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgesource',
            index=models.Index(fields=['source_type', 'status'], name='ai_knowledg_source__436ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgesource',
            index=models.Index(fields=['checksum'], name='ai_knowledg_checksu_dcb35c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['source', 'chunk_index'], name='ai_knowledg_source__ae8ede_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['visibility'], name='ai_knowledg_visibil_073e63_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiknowledgechunk',
            constraint=models.UniqueConstraint(fields=('source', 'chunk_index'), name='uq_ai_chunk_per_source_index'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['user', 'created_at'], name='ai_query_lo_user_id_aae3db_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['role', 'created_at'], name='ai_query_lo_role_fa3127_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['retrieval_mode', 'created_at'], name='ai_query_lo_retriev_5fce55_idx'),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['created_at'], name='ai_query_lo_created_009477_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['rating', 'created_at'], name='ai_feedback_rating_252fea_idx'),
        ),
    ]
