# Generated by Django 6.0.2 on 2026-04-08 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_accountingperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('note_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('stock_effect', models.BooleanField(db_index=True, default=False)),
                ('taxable_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
            ],
            options={
                'db_table': 'billing_debit_notes',
                'ordering': ['-note_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingDebitNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'db_table': 'billing_debit_note_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('billing_channel', models.CharField(choices=[('RETAIL', 'Retail'), ('EMI', 'EMI'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], db_index=True, default='RETAIL', max_length=20)),
                ('tax_mode', models.CharField(choices=[('GST', 'GST'), ('NON_GST', 'Non-GST')], db_index=True, default='NON_GST', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('received_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('place_of_supply_state_code', models.CharField(blank=True, default='', max_length=5)),
                ('customer_name_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('customer_phone_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('customer_gstin', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('printed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('printed_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'billing_invoices',
                'ordering': ['-invoice_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hsn_sac_code', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'billing_invoice_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('receipt_type', models.CharField(choices=[('RETAIL_RECEIPT', 'Retail Receipt'), ('EMI_PAYMENT_RECEIPT', 'EMI Payment Receipt')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
                ('receipt_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customer_name_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('customer_phone_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('printed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('printed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_receipt_documents',
                'ordering': ['-receipt_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('note_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('stock_effect', models.BooleanField(db_index=True, default=False)),
                ('taxable_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=12)),
                ('doc_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_credit_notes', to='accounting.documentsequence')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_credit_note', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'billing_credit_notes',
                'ordering': ['-note_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingCreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billingcreditnote')),
            ],
            options={
                'db_table': 'billing_credit_note_lines',
                'ordering': ['id'],
            },
        ),
    ]
