# Generated by Django 6.0.2 on 2026-04-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_accountingperiod_and_more'),
        ('billing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('subscriptions', '0033_alter_auditlog_action_type_subscriptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcreditnoteline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='billingdebitnote',
            name='doc_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_debit_notes', to='accounting.documentsequence'),
        ),
        migrations.AddField(
            model_name='billingdebitnote',
            name='posted_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_debit_note', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='billingdebitnoteline',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billingdebitnote'),
        ),
        migrations.AddField(
            model_name='billingdebitnoteline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_billing_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='subscriptions.customer'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='doc_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='accounting.documentsequence'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='accounting.financeaccount'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='posted_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='billingdebitnote',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='billingcreditnote',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='billinginvoiceline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='billinginvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='billinginvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoice_lines', to='subscriptions.product'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='billing_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='subscriptions.customer'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='accounting.financeaccount'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_document', to='subscriptions.payment'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='posted_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_document', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['invoice_date', 'status', 'customer'], name='billing_inv_invoice_498860_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['billing_channel', 'status'], name='billing_inv_billing_7e5e52_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdebitnote',
            index=models.Index(fields=['status', 'note_date'], name='billing_deb_status_16d305_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcreditnote',
            index=models.Index(fields=['status', 'note_date'], name='billing_cre_status_3318ba_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['receipt_type', 'receipt_date'], name='billing_rec_receipt_d745f6_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['status', 'receipt_date'], name='billing_rec_status_b9ada0_idx'),
        ),
    ]
