# Generated by Django 6.0.2 on 2026-04-09 05:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('subscriptions', '0034_product_sku_product_unit_of_measure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('PROFORMA', 'Proforma'), ('DEMAND_NOTE', 'Demand Note')], db_index=True, default='INVOICE', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_state', models.CharField(choices=[('PENDING_DELIVERY', 'Pending Delivery'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('RETURN_HOLD', 'Return Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_DELIVERY', max_length=24)),
                ('delivery_gate_required', models.BooleanField(db_index=True, default=True)),
                ('delivery_gate_status', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('invoice_eligible', models.BooleanField(db_index=True, default=False)),
                ('contract_reference_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('contract_start_date', models.DateField(db_index=True)),
                ('tenure_months', models.PositiveIntegerField(default=0)),
                ('contract_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('waived_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('next_due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product_code_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_synced_event', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profiles', to='subscriptions.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profiles', to='subscriptions.product')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profile', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'billing_profiles',
                'ordering': ['-contract_start_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingInstallmentMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_no', models.PositiveIntegerField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status_snapshot', models.CharField(db_index=True, max_length=20)),
                ('paid_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('waived_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_amount_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_count_snapshot', models.PositiveIntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, db_index=True, null=True)),
                ('emi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_mirror', to='subscriptions.emi')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='billing.billingprofile')),
            ],
            options={
                'db_table': 'billing_installment_mirrors',
                'ordering': ['month_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BillingSyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_model', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('SYNCED', 'Synced'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='SYNCED', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='billing.billingprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_sync_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_sync_events',
                'ordering': ['-synced_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['customer', 'activation_state'], name='billing_pro_custome_1f1980_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['product', 'invoice_eligible'], name='billing_pro_product_1a2a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['delivery_gate_status', 'invoice_eligible'], name='billing_pro_deliver_354a41_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginstallmentmirror',
            index=models.Index(fields=['billing_profile', 'month_no'], name='billing_ins_billing_c18e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginstallmentmirror',
            index=models.Index(fields=['status_snapshot', 'due_date'], name='billing_ins_status__961f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingsyncevent',
            index=models.Index(fields=['source_model', 'source_id', 'event_type'], name='billing_syn_source__ee37dc_idx'),
        ),
        migrations.AddIndex(
            model_name='billingsyncevent',
            index=models.Index(fields=['status', 'synced_at'], name='billing_syn_status_162c88_idx'),
        ),
    ]
