# Generated by Django 6.0.2 on 2026-04-09 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_assetcategory_creditnote_cancel_reason_and_more'),
        ('billing', '0003_billinginvoice_document_type_billingprofile_and_more'),
        ('inventory', '0004_inventoryitem_delivery_stock_bridge_enabled_and_more'),
        ('subscriptions', '0036_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product_code_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sku_snapshot', models.CharField(blank=True, default='', max_length=60)),
                ('unit_of_measure_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('hsn_sac_code', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'db_table': 'billing_direct_sale_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('DIRECT_SALE', 'Direct Sale'), ('SUBSCRIPTION', 'Subscription'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('NOTE_ADJUSTMENT', 'Note Adjustment')], db_index=True, default='MANUAL', max_length=24),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('DIRECT_SALE', 'Direct Sale'), ('SUBSCRIPTION', 'Subscription'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment'), ('NOTE_ADJUSTMENT', 'Note Adjustment')], db_index=True, default='MANUAL', max_length=24),
        ),
        migrations.CreateModel(
            name='DirectSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('sale_date', models.DateField(db_index=True)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('tax_mode', models.CharField(choices=[('GST', 'GST'), ('NON_GST', 'Non-GST')], db_index=True, default='NON_GST', max_length=10)),
                ('delivery_required', models.BooleanField(db_index=True, default=False)),
                ('delivery_reference', models.CharField(blank=True, default='', max_length=64)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('received_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer_name_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('customer_phone_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('customer_gstin', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_direct_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='subscriptions.customer')),
                ('doc_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='accounting.documentsequence')),
                ('finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='accounting.financeaccount')),
            ],
            options={
                'db_table': 'billing_direct_sales',
                'ordering': ['-sale_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='direct_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='billing.directsale'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='direct_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='billing.directsale'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['source_type', 'invoice_date'], name='billing_inv_source__22e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['direct_sale', 'status'], name='billing_inv_direct__5f6048_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['source_type', 'receipt_date'], name='billing_rec_source__19ff86_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['direct_sale', 'receipt_date'], name='billing_rec_direct__5a4b02_idx'),
        ),
        migrations.AddField(
            model_name='directsaleline',
            name='direct_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.directsale'),
        ),
        migrations.AddField(
            model_name='directsaleline',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sale_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='directsaleline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_sale_lines', to='subscriptions.product'),
        ),
        migrations.AddIndex(
            model_name='directsale',
            index=models.Index(fields=['sale_date', 'status', 'customer'], name='billing_dir_sale_da_4cfb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='directsale',
            index=models.Index(fields=['delivery_required', 'status'], name='billing_dir_deliver_916dc1_idx'),
        ),
    ]
