# Generated by Django 6.0.2 on 2026-04-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_employeeexpenseclaim_branch_and_more'),
        ('billing', '0004_directsaleline_billinginvoice_source_reference_and_more'),
        ('branch_control', '0001_initial'),
        ('subscriptions', '0041_payment_branch_payment_cash_counter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_invoices', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='directsale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='directsale',
            name='cash_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_sales', to='branch_control.cashcounter'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='cash_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_documents', to='branch_control.cashcounter'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['branch', 'invoice_date', 'status'], name='billing_inv_branch__281cad_idx'),
        ),
        migrations.AddIndex(
            model_name='directsale',
            index=models.Index(fields=['branch', 'sale_date', 'status'], name='billing_dir_branch__52856b_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdocument',
            index=models.Index(fields=['branch', 'receipt_date', 'status'], name='billing_rec_branch__ef27d2_idx'),
        ),
    ]
