# Generated by Django 6.0.2 on 2026-05-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billinginvoice_branch_directsale_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='directsale',
            name='idempotency_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
