# Generated by Django 5.2.7 on 2026-05-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_directsale_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directsale",
            name="customer_gst_type",
            field=models.CharField(
                choices=[
                    ("UNREGISTERED_CONSUMER", "Unregistered Consumer"),
                    ("REGISTERED_BUSINESS", "Registered Business"),
                ],
                db_index=True,
                default="UNREGISTERED_CONSUMER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_billing_address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_billing_address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_district",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_pincode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_place_of_supply",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="customer_snapshot_state",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_district",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_pincode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="directsale",
            name="delivery_snapshot_state",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="directsale",
            name="tax_calculation_mode",
            field=models.CharField(
                choices=[
                    ("NON_GST", "Non-GST"),
                    ("GST_INCLUSIVE", "GST Inclusive"),
                    ("GST_EXCLUSIVE", "GST Exclusive"),
                ],
                db_index=True,
                default="NON_GST",
                max_length=20,
            ),
        ),
    ]
