# Generated by Django 6.0.2 on 2026-05-07 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_returns_voids_reversals_center"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customercreditledger",
            new_name="billing_cus_custome_354f9e_idx",
            old_name="billing_cus_customer_a4b90f_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrefund",
            new_name="billing_cus_status_26922c_idx",
            old_name="billing_cus_status_31f0ca_idx",
        ),
        migrations.RenameIndex(
            model_name="customerrefund",
            new_name="billing_cus_custome_8edf7a_idx",
            old_name="billing_cus_customer_f8aa50_idx",
        ),
        migrations.RenameIndex(
            model_name="directsalereturn",
            new_name="billing_dir_status_925830_idx",
            old_name="billing_dir_status_b11cc6_idx",
        ),
        migrations.RenameIndex(
            model_name="directsalereturn",
            new_name="billing_dir_custome_e3a92b_idx",
            old_name="billing_dir_customer_780a4d_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasereturn",
            new_name="billing_pur_status_8b22a1_idx",
            old_name="billing_pur_status_1d2336_idx",
        ),
        migrations.RenameIndex(
            model_name="purchasereturn",
            new_name="billing_pur_vendor__7635f5_idx",
            old_name="billing_pur_vendor_5d703d_idx",
        ),
        migrations.AlterField(
            model_name="customercreditledger",
            name="entry_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturn",
            name="return_date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
