# Generated by Django 6.0.2 on 2026-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_purchasereturn_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directsale",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("CONFIRMED", "Confirmed"),
                    ("DELIVERED", "Delivered"),
                    ("INVOICED", "Invoiced"),
                    ("CANCELLED", "Cancelled"),
                    ("CANCELLED_PRE_INVOICE", "Cancelled (Pre-invoice)"),
                    ("CANCELLED_AFTER_DELIVERY", "Cancelled (After delivery)"),
                    ("REVERSED_POST_INVOICE", "Reversed (Post-invoice)"),
                    ("RETURNED", "Returned"),
                    ("EXCHANGED_CLOSED", "Exchange closed"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=32,
            ),
        ),
    ]
