# Generated by Django 5.2.7 on 2026-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_directsale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinginvoiceline',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directsale',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptdocument',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
