# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_smartcollectionrun"),
        ("contracts", "0002_initial"),
        ("customers", "0002_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="billinginstallmentmirror",
            name="emi",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_mirror",
                to="payments.emi",
            ),
        ),
        migrations.AlterField(
            model_name="billinginvoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_invoices",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="billinginvoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_invoices",
                to="contracts.subscription",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
