# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_alter_billinginstallmentmirror_emi_and_more"),
        ("contracts", "0002_initial"),
        ("customers", "0002_initial"),
        ("payments", "0001_initial"),
        ("products_core", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="billinginvoiceline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_invoice_lines",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_profiles",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_profiles",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="billingprofile",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_profile",
                to="contracts.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="customercreditledger",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_ledger_entries",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrefund",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_refunds",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="directsale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_sales",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="directsaleline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_sale_lines",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="directsalereturn",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_sale_returns",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="receiptdocument",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_documents",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="receiptdocument",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_document",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="receiptdocument",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_documents",
                to="contracts.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="smartcollectionrun",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="smart_collections",
                to="customers.customer",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
