# Generated by Django 5.2.7 on 2026-08-21 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_creditnoteapplication"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="creditnoteapplication",
            new_name="billing_cre_credit__8068c7_idx",
            old_name="billing_cre_credit__a1b2c3_idx",
        ),
        migrations.AlterField(
            model_name="creditnoteapplication",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
