# Generated by Django 5.2.7 on 2026-09-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0018_rename_billing_cre_credit__a1b2c3_idx_billing_cre_credit__8068c7_idx_and_more",
        ),
        ("inventory", "0031_backfill_pim_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturn",
            name="vendor_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_returns",
                to="inventory.vendorbill",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnline",
            name="vendor_bill_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_return_lines",
                to="inventory.vendorbillline",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturn",
            name="purchase_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_returns",
                to="inventory.purchasebill",
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturnline",
            name="purchase_bill_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_return_lines",
                to="inventory.purchasebillline",
            ),
        ),
    ]
