# Generated by Django 6.0.2 on 2026-05-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="system_noti_recipie_616b31_idx",
            old_name="system_noti_recipie_9d3e4f_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="system_noti_module_620ed7_idx",
            old_name="system_noti_module__7e8f90_idx",
        ),
        migrations.RenameIndex(
            model_name="systemjoblog",
            new_name="system_job__job_typ_42c7a8_idx",
            old_name="system_job__job_typ_6769c5_idx",
        ),
        migrations.RenameIndex(
            model_name="systemjoblog",
            new_name="system_job__finishe_9ca2d3_idx",
            old_name="system_job__finishe_8a1b2c_idx",
        ),
    ]
