# Generated by Django 5.2.7 on 2026-08-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_jobs",
            "0002_rename_system_noti_recipie_9d3e4f_idx_system_noti_recipie_616b31_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
