# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import subscriptions.base_models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="ContractRecontractEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_contract_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "new_contract_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_difference",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_already_paid",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "old_remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "new_remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("current_tenure_months", models.PositiveIntegerField()),
                ("preview_tenure_months", models.PositiveIntegerField()),
                (
                    "current_monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "proposed_monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("pending_emi_count", models.PositiveIntegerField(default=0)),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("UPGRADE_EXTRA_PAYABLE", "Upgrade Extra Payable"),
                            ("DOWNGRADE_CREDIT_REQUIRED", "Downgrade Credit Required"),
                            (
                                "SAME_PRICE_REFERENCE_CORRECTION",
                                "Same Price Reference Correction",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed"),
                            ("SUPERSEDED", "Superseded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PREVIEWED",
                        max_length=20,
                    ),
                ),
                ("effective_date_preview", models.DateField(blank=True, null=True)),
                ("preview_snapshot", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("blocked_reason", models.TextField(blank=True, null=True)),
                ("source_record_mutation", models.BooleanField(default=False)),
                (
                    "customer_consent_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("customer_consented_at", models.DateTimeField(blank=True, null=True)),
                ("customer_consent_note", models.TextField(blank=True, null=True)),
                (
                    "customer_consent_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "admin_approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_approved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_approval_note", models.TextField(blank=True, null=True)),
                ("admin_approval_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "contract_recontract_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContractRecontractFinancialImpactPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("UPGRADE_EXTRA_PAYABLE", "Upgrade Extra Payable"),
                            ("DOWNGRADE_CREDIT_REQUIRED", "Downgrade Credit Required"),
                            (
                                "SAME_PRICE_REFERENCE_CORRECTION",
                                "Same Price Reference Correction",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "accounting_preview_status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed"),
                            ("SUPERSEDED", "Superseded"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PREVIEWED",
                        max_length=20,
                    ),
                ),
                (
                    "reconciliation_preview_status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed"),
                            ("SUPERSEDED", "Superseded"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PREVIEWED",
                        max_length=20,
                    ),
                ),
                (
                    "price_difference",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "additional_receivable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "credit_or_reduction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "projected_customer_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "projected_future_emi_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("journal_preview", models.JSONField(blank=True, default=dict)),
                ("reconciliation_preview", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("blocked_reason", models.TextField(blank=True, null=True)),
                ("source_record_mutation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "contract_recontract_financial_impact_previews",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContractRecontractScheduleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.PositiveIntegerField()),
                ("original_due_date", models.DateField(blank=True, null=True)),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("proposed_due_date", models.DateField()),
                (
                    "proposed_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "proposed_principal_component",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "proposed_status",
                    models.CharField(
                        choices=[
                            ("PREVIEW_ONLY", "Preview Only"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        db_index=True,
                        default="PREVIEW_ONLY",
                        max_length=20,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            (
                                "EXISTING_PENDING_REPLACEMENT",
                                "Existing Pending Replacement",
                            ),
                            ("NEW_ADDITIONAL_EMI", "New Additional EMI"),
                            ("REDUCED_EMI", "Reduced EMI"),
                            ("CREDIT_OFFSET", "Credit Offset"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("source_record_mutation", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "contract_recontract_schedule_lines",
                "ordering": ["event_id", "line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContractReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(db_index=True, max_length=140, unique=True),
                ),
                ("display_reference", models.CharField(db_index=True, max_length=180)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE_EMI", "Advance EMI"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                            ("DIRECT_SALE", "Direct Sale"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "phone_snapshot",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=24
                    ),
                ),
                (
                    "customer_name_snapshot",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=180
                    ),
                ),
                (
                    "kyc_reference_snapshot",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Masked-safe KYC/customer reference snapshot only; never store raw KYC document values here.",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "product_summary_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "batch_snapshot",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                (
                    "lucky_id_snapshot",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "partner_snapshot",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "source_created_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "contract_references",
                "ordering": ["-source_created_at", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContractReferenceSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "contract_reference_sequences",
                "ordering": ["scope_key"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("DOWNLOAD", "Download"),
                            ("VERIFY", "Verify"),
                            ("REJECT", "Reject"),
                            ("REPLACE", "Replace"),
                            ("UPLOAD", "Upload"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "document_access_logs",
                "ordering": ["-accessed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LeaseSubscriptionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "security_deposit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20.00")),
                            django.core.validators.MaxValueValidator(Decimal("30.00")),
                        ],
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refundable_security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "buyout_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ownership_transfer_allowed", models.BooleanField(default=False)),
                (
                    "return_condition_status",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        db_index=True,
                        default="NOT_ASSESSED",
                        max_length=30,
                    ),
                ),
                (
                    "deduction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("REFUNDED", "Refunded"),
                            ("WITHHELD", "Withheld"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("return_inspection_notes", models.TextField(blank=True, default="")),
                ("handover_notes", models.TextField(blank=True, default="")),
                ("contract_terms_snapshot", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "lease_subscription_profiles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OperationalCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("BILLING_INVOICE", "Billing Invoice"),
                            ("BILLING_RECEIPT", "Billing Receipt"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("EMI_PAYMENT", "EMI Payment"),
                            ("DELIVERY", "Delivery"),
                            ("STOCK_REQUIREMENT", "Stock Requirement"),
                            ("PURCHASE_INVOICE", "Purchase Invoice"),
                            ("RENT_CONTRACT", "Rent Contract"),
                            ("LEASE_CONTRACT", "Lease Contract"),
                            ("RENT_LEASE_INVOICE", "Rent/Lease Invoice"),
                            ("PAYOUT_BATCH", "Payout Batch"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "amount_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status_before",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "status_after",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "cancellation_type",
                    models.CharField(
                        choices=[
                            ("CANCEL_DRAFT", "Cancel Draft"),
                            ("VOID_UNPOSTED", "Void Unposted"),
                            ("CANCEL_WITH_REVERSAL", "Cancel With Reversal"),
                            ("MANUAL_SETTLEMENT", "Manual Settlement"),
                            ("PAYMENT_REVERSAL", "Payment Reversal"),
                            ("DELIVERY_CANCEL", "Delivery Cancel"),
                            ("STOCK_REQUIREMENT_CANCEL", "Stock Requirement Cancel"),
                            ("CONTRACT_TERMINATION", "Contract Termination"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField()),
                ("internal_note", models.TextField(blank=True, default="")),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "reversal_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, null=True
                    ),
                ),
                (
                    "audit_log_reference",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
            ],
            options={
                "db_table": "operational_cancellations",
                "ordering": ["-cancelled_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentSubscriptionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "security_deposit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20.00")),
                            django.core.validators.MaxValueValidator(Decimal("30.00")),
                        ],
                    ),
                ),
                (
                    "security_deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refundable_security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "return_condition_status",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        db_index=True,
                        default="NOT_ASSESSED",
                        max_length=30,
                    ),
                ),
                (
                    "deduction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("REFUNDED", "Refunded"),
                            ("WITHHELD", "Withheld"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("return_inspection_notes", models.TextField(blank=True, default="")),
                ("handover_notes", models.TextField(blank=True, default="")),
                ("contract_terms_snapshot", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "rent_subscription_profiles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("tenure_months", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REQUESTED", "Requested"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("WON", "Won"),
                            ("COMPLETED", "Completed"),
                            ("DEFAULTED", "Defaulted"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("DELIVERY_PENDING", "Delivery Pending"),
                            ("HANDED_OVER", "Handed Over"),
                            ("RETURN_PENDING", "Return Pending"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("winner_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "waived_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "contract_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("RETURN_REQUESTED", "Return Requested"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("product_snapshot", models.JSONField(blank=True, null=True)),
                ("pricing_snapshot", models.JSONField(blank=True, null=True)),
                ("tax_profile_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "subscription_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True, unique=True
                    ),
                ),
                (
                    "terms_locked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "advance_delivery_unlocked",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "prepayment_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("prepayment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "agreement_pdf_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 hex digest of the signed contract PDF (CTRL-RENT-3).",
                        max_length=64,
                    ),
                ),
                (
                    "agreement_pdf_sealed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the agreement PDF hash was committed.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_KYC_ID", "Customer KYC ID"),
                            ("CUSTOMER_SIGNATURE", "Customer Signature"),
                            ("ADMIN_SIGNATURE", "Admin / Company Signature"),
                            ("RENT_CONTRACT_PDF", "Rent Contract PDF"),
                            ("LEASE_CONTRACT_PDF", "Lease Contract PDF"),
                            ("ADVANCE_EMI_CONTRACT_PDF", "Advance EMI Contract PDF"),
                            ("PAYMENT_RECEIPT_PDF", "Payment Receipt PDF"),
                            ("DELIVERY_HANDOVER_NOTE", "Delivery / Handover Note"),
                            ("RETURN_INSPECTION_REPORT", "Return Inspection Report"),
                            ("AMENDMENT_RECORD", "Contract Amendment Record"),
                            ("DIRECT_SALE_INVOICE_PDF", "Direct Sale Invoice PDF"),
                            (
                                "SECURITY_DEPOSIT_RECEIPT_PDF",
                                "Security Deposit Receipt PDF",
                            ),
                            (
                                "ASSET_HANDOVER_ACKNOWLEDGEMENT",
                                "Asset Handover Acknowledgement",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=subscriptions.base_models.subscription_document_upload_to
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("document_version", models.PositiveIntegerField(default=1)),
                ("regeneration_reason", models.TextField(blank=True, default="")),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "signed_status",
                    models.CharField(
                        choices=[
                            ("UNSIGNED", "Unsigned"),
                            ("SIGNED", "Signed"),
                            ("NOT_REQUIRED", "Not Required"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("SENSITIVE", "Sensitive"),
                            ("HIGHLY_SENSITIVE", "Highly Sensitive"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "subscription_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionGuarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("SPOUSE", "Spouse"),
                            ("PARENT", "Parent"),
                            ("SIBLING", "Sibling"),
                            ("FRIEND", "Friend"),
                            ("EMPLOYER", "Employer"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                ("aadhaar_no", models.CharField(blank=True, default="", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "subscriptions_guarantors",
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("ADDRESS_CHANGE", "Address Change"),
                            ("CONTACT_CORRECTION", "Contact Correction"),
                            ("LEGAL_DOCUMENT_CORRECTION", "Legal Document Correction"),
                            ("TENURE_EXTENSION", "Tenure Extension"),
                            ("SCHEDULE_CORRECTION", "Schedule Correction"),
                            ("PRODUCT_CHANGE", "Product Change"),
                            ("LUCKY_ID_CHANGE", "Lucky ID Change"),
                            ("BATCH_CHANGE", "Batch Change"),
                            ("DEPOSIT_ADJUSTMENT", "Deposit Adjustment"),
                            ("EMI_AMOUNT_CHANGE", "EMI Amount Change"),
                            ("CONTRACT_PRICE_CHANGE", "Contract Price Change"),
                            ("RENT_AMOUNT_CHANGE", "Rent Amount Change"),
                            ("LEASE_TERM_CHANGE", "Lease Term Change"),
                            ("OTHER", "Other"),
                            ("PRODUCT_UPGRADE", "Product Upgrade (Legacy)"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("IMPLEMENTED", "Implemented"),
                            ("CANCELLED", "Cancelled"),
                            ("APPLIED", "Applied (Legacy)"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("previous_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField()),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "amendment_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True, unique=True
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("EMI_SUBSCRIPTION", "EMI Subscription"),
                            ("RENT_LEASE", "Rent / Lease"),
                        ],
                        db_index=True,
                        default="EMI_SUBSCRIPTION",
                        max_length=24,
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("PARTNER", "Partner")],
                        db_index=True,
                        default="CUSTOMER",
                        max_length=16,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("requested_values", models.JSONField(blank=True, default=dict)),
                ("approved_values", models.JSONField(blank=True, default=dict)),
                ("implemented_values", models.JSONField(blank=True, default=dict)),
                ("admin_note", models.TextField(blank=True, default="")),
                (
                    "financial_impact_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("requires_emi_recalculation", models.BooleanField(default=False)),
                ("requires_inventory_review", models.BooleanField(default=False)),
                ("requires_lucky_id_review", models.BooleanField(default=False)),
                ("requires_accounting_review", models.BooleanField(default=False)),
                ("requires_rent_lease_review", models.BooleanField(default=False)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "implemented_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_contract_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_amendments",
                "ordering": ["-created_at", "-id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
