# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0016_alter_billinginvoiceline_product_and_more"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("contracts", "0002_initial"),
        ("customers", "0002_initial"),
        ("lucky_plan", "0002_initial"),
        ("payments", "0001_initial"),
        ("products_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
            model_name="contractrecontractevent",
            name="new_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recontract_events_as_new_product",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractevent",
            name="old_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recontract_events_as_old_product",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractfinancialimpactpreview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_recontract_financial_impact_previews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractfinancialimpactpreview",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_impact_previews",
                to="contracts.contractrecontractevent",
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractscheduleline",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_preview_lines",
                to="contracts.contractrecontractevent",
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractscheduleline",
            name="original_emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recontract_schedule_preview_lines",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="direct_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="billing.directsale",
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="billing.billinginvoice",
            ),
        ),
        migrations.AddField(
            model_name="documentaccesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="lease_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="contracts.leasesubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="operationalcancellation",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_operational_cancellations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationalcancellation",
            name="cancelled_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_operational_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationalcancellation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_cancellations",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="operationalcancellation",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_operational_cancellations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operationalcancellation",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_operational_cancellations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="rent_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="contracts.rentsubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="lucky_plan.batch",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="branch_control.branch",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="lucky_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="lucky_plan.luckyid",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="terms_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_subscription_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentsubscriptionprofile",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_profile",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="leasesubscriptionprofile",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_profile",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="contractreference",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contract_references",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="contractrecontractevent",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recontract_events",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="rent_lease_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_contract_amendments",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amendments",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_subscription_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_subscription_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_subscription_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentaccesslog",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="contracts.subscriptiondocument",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionguarantor",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guarantors",
                to="contracts.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractfinancialimpactpreview",
            index=models.Index(
                fields=["event", "accounting_preview_status"],
                name="recon_fin_prev_evt_acc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractfinancialimpactpreview",
            index=models.Index(
                fields=["event", "reconciliation_preview_status"],
                name="recon_fin_prev_evt_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractfinancialimpactpreview",
            index=models.Index(
                fields=["impact_type"], name="recon_fin_prev_impact_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractfinancialimpactpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("additional_receivable_amount__gte", 0)),
                name="chk_recon_fin_add_recv_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractfinancialimpactpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_or_reduction_amount__gte", 0)),
                name="chk_recon_fin_credit_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractfinancialimpactpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("projected_customer_balance__gte", 0)),
                name="chk_recon_fin_cust_bal_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractfinancialimpactpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("projected_future_emi_total__gte", 0)),
                name="chk_recon_fin_emi_total_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractfinancialimpactpreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_record_mutation", False)),
                name="chk_recon_fin_no_src_mut",
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractscheduleline",
            index=models.Index(
                fields=["event", "line_no"], name="recon_sch_ev_line_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractscheduleline",
            index=models.Index(
                fields=["event", "adjustment_type"], name="recon_sch_ev_adj_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractscheduleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("line_no__gt", 0)),
                name="chk_recontract_sched_line_gt0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractscheduleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_amount__gte", 0)),
                name="chk_recontract_sched_prop_amt_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractscheduleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_record_mutation", False)),
                name="chk_recontract_sched_no_src_mut",
            ),
        ),
        migrations.AddIndex(
            model_name="operationalcancellation",
            index=models.Index(
                fields=["source_type", "cancelled_at"],
                name="operational_source__f447aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationalcancellation",
            index=models.Index(
                fields=["customer", "cancelled_at"],
                name="operational_custome_5c75aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="operationalcancellation",
            index=models.Index(
                fields=["cancelled_by", "cancelled_at"],
                name="operational_cancell_69e4cf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalcancellation",
            constraint=models.UniqueConstraint(
                fields=("source_type", "source_id"),
                name="uq_operational_cancellation_source",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_572d44_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["batch"], name="subscriptio_batch_i_3df372_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["customer"], name="subscriptio_custome_4251b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["plan_type"], name="subscriptio_plan_ty_7d17a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["partner"], name="subscriptio_partner_dc390e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["start_date"], name="subscriptio_start_d_75cedf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["branch", "status"], name="subscriptio_branch__afa2df_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("batch__isnull", False),
                        ("plan_type", "EMI"),
                        ("status", "CANCELLED"),
                    ),
                    models.Q(
                        ("batch__isnull", False),
                        ("lucky_id__isnull", False),
                        ("plan_type", "EMI"),
                        models.Q(("status", "CANCELLED"), _negated=True),
                    ),
                    models.Q(("plan_type", "EMI"), _negated=True),
                    _connector="OR",
                ),
                name="chk_batch_and_lucky_required_for_emi",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan_type", "EMI")),
                fields=("lucky_id",),
                name="uq_subscription_per_lucky_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gt", 0)),
                name="chk_subscription_total_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_amount__gt", 0)),
                name="chk_subscription_monthly_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("tenure_months__gt", 0)),
                name="chk_subscription_tenure_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gte", 0)),
                name="chk_subscription_waived_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="rentsubscriptionprofile",
            index=models.Index(
                fields=["refund_status"], name="rent_subscr_refund__f2ae5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentsubscriptionprofile",
            index=models.Index(
                fields=["return_condition_status"],
                name="rent_subscr_return__453fcc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentsubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("security_deposit_percent__gte", Decimal("20.00")),
                    ("security_deposit_percent__lte", Decimal("30.00")),
                ),
                name="chk_rent_security_deposit_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentsubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("security_deposit_amount__gte", Decimal("0.00"))),
                name="chk_rent_security_deposit_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentsubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("deduction_amount__gte", Decimal("0.00"))),
                name="chk_rent_deduction_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentsubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_amount__gte", Decimal("0.00"))),
                name="chk_rent_refund_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="leasesubscriptionprofile",
            index=models.Index(
                fields=["refund_status"], name="lease_subsc_refund__cd4ef5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leasesubscriptionprofile",
            index=models.Index(
                fields=["return_condition_status"],
                name="lease_subsc_return__74cc65_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasesubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("security_deposit_percent__gte", Decimal("20.00")),
                    ("security_deposit_percent__lte", Decimal("30.00")),
                ),
                name="chk_lease_security_deposit_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasesubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("security_deposit_amount__gte", Decimal("0.00"))),
                name="chk_lease_security_deposit_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasesubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("deduction_amount__gte", Decimal("0.00"))),
                name="chk_lease_deduction_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="leasesubscriptionprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_amount__gte", Decimal("0.00"))),
                name="chk_lease_refund_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["contract_type"], name="contract_re_contrac_2e8cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["customer"], name="contract_re_custome_2cb10f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["phone_snapshot"], name="contract_re_phone_s_fc3a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["customer_name_snapshot"], name="contract_re_custome_3bef32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["kyc_reference_snapshot"], name="contract_re_kyc_ref_96c8f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["batch_snapshot"], name="contract_re_batch_s_c29929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["lucky_id_snapshot"], name="contract_re_lucky_i_67f6f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractreference",
            index=models.Index(
                fields=["source_created_at"], name="contract_re_source__a6852f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractevent",
            index=models.Index(
                fields=["amendment", "status"], name="recontract_am_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractevent",
            index=models.Index(
                fields=["subscription", "created_at"], name="recontract_sub_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecontractevent",
            index=models.Index(
                fields=["impact_type", "status"], name="recontract_impact_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_contract_total__gte", 0)),
                name="chk_recontract_old_total_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_contract_total__gte", 0)),
                name="chk_recontract_new_total_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_already_paid__gte", 0)),
                name="chk_recontract_paid_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("old_remaining_balance__gte", 0)),
                name="chk_recontract_old_bal_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_remaining_balance__gte", 0)),
                name="chk_recontract_new_bal_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_monthly_amount__gte", 0)),
                name="chk_recontract_cur_emi_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_monthly_amount__gte", 0)),
                name="chk_recontract_new_emi_gte0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_tenure_months__gt", 0)),
                name="chk_recontract_cur_ten_gt0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("preview_tenure_months__gt", 0)),
                name="chk_recontract_prev_ten_gt0",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractrecontractevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_record_mutation", False)),
                name="chk_recontract_no_src_mut",
            ),
        ),
        migrations.AddIndex(
            model_name="contractamendment",
            index=models.Index(
                fields=["subscription", "status"], name="contract_am_subscri_b9ee13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractamendment",
            index=models.Index(
                fields=["amendment_type", "status"],
                name="contract_am_amendme_c02dce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contractamendment",
            index=models.Index(
                fields=["contract_type", "status"], name="contract_am_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractamendment",
            index=models.Index(
                fields=["customer", "status"], name="contract_am_customer_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractamendment",
            index=models.Index(
                fields=["partner", "status"], name="contract_am_partner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiondocument",
            index=models.Index(
                fields=["subscription", "document_type"],
                name="subscriptio_subscri_b32760_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiondocument",
            index=models.Index(
                fields=["verification_status", "created_at"],
                name="subscriptio_verific_8f31ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionguarantor",
            index=models.Index(
                fields=["subscription", "is_primary"],
                name="subscriptio_subscri_08255d_idx",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
