# Generated by Django 5.2.16 on 2026-09-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_KYC_ID", "Customer KYC ID"),
                    ("CUSTOMER_PHOTO", "Customer Photo"),
                    ("CUSTOMER_SIGNATURE", "Customer Signature"),
                    ("ADMIN_SIGNATURE", "Admin / Company Signature"),
                    ("RENT_CONTRACT_PDF", "Rent Contract PDF"),
                    ("LEASE_CONTRACT_PDF", "Lease Contract PDF"),
                    ("ADVANCE_EMI_CONTRACT_PDF", "Advance EMI Contract PDF"),
                    ("PAYMENT_RECEIPT_PDF", "Payment Receipt PDF"),
                    ("DELIVERY_HANDOVER_NOTE", "Delivery / Handover Note"),
                    ("RETURN_INSPECTION_REPORT", "Return Inspection Report"),
                    ("AMENDMENT_RECORD", "Contract Amendment Record"),
                    ("DIRECT_SALE_INVOICE_PDF", "Direct Sale Invoice PDF"),
                    ("SECURITY_DEPOSIT_RECEIPT_PDF", "Security Deposit Receipt PDF"),
                    (
                        "ASSET_HANDOVER_ACKNOWLEDGEMENT",
                        "Asset Handover Acknowledgement",
                    ),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
