# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="ConsumerReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("WITHIN_WINDOW", "Within Return Window"),
                            ("OUTSIDE_WINDOW", "Outside Return Window"),
                            ("CPA_OVERRIDE", "CPA Override Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Date the product was delivered — used to calculate the return window."
                    ),
                ),
                (
                    "refund_deadline",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Latest date by which refund must be processed after return approval.",
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "consumer_return_requests",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DefectClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("SAFETY_CRITICAL", "Safety Critical"),
                        ],
                        db_index=True,
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "reported_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "cpa_override",
                    models.BooleanField(
                        default=False,
                        help_text="Set by admin to allow refund/exchange outside normal return window under CPA 2019.",
                    ),
                ),
                ("cpa_override_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "defect_claims",
                "ordering": ["-reported_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending — awaiting delivery"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_TRANSIT", "In transit"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Delivery failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "delivered_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "driver_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("delivery_address", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions_delivery",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductPossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_HANDOVER", "Pending Handover"),
                            ("WITH_CUSTOMER", "With Customer"),
                            ("RETURN_DUE", "Return Due"),
                            ("RETURNED", "Returned"),
                            ("UNDER_INSPECTION", "Under Inspection"),
                            ("MAINTENANCE", "Maintenance"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PENDING_HANDOVER",
                        max_length=25,
                    ),
                ),
                (
                    "handover_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "expected_return_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "actual_return_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("handover_condition_notes", models.TextField(blank=True, default="")),
                ("return_condition_notes", models.TextField(blank=True, default="")),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
            ],
            options={
                "db_table": "product_possessions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateTimeField(db_index=True)),
                ("photo_1", models.ImageField(upload_to="pod/photos/")),
                (
                    "photo_2",
                    models.ImageField(blank=True, null=True, upload_to="pod/photos/"),
                ),
                ("signature_image", models.ImageField(upload_to="pod/signatures/")),
                ("driver_name", models.CharField(max_length=100)),
                (
                    "driver_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("customer_signature_name", models.CharField(max_length=100)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CAPTURED", "Captured"),
                            ("VERIFIED", "Verified"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="CAPTURED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions_proof_of_delivery",
                "ordering": ["-delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseReturnInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Inspection"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Inspection Approved"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELLABLE", "Sellable – Return to stock"),
                            ("MAINTENANCE_REQUIRED", "Maintenance Required"),
                            ("DAMAGED", "Damaged – Damage recovery"),
                            ("SCRAPPED", "Scrapped – Write off"),
                        ],
                        db_index=True,
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "condition_recorded",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        db_index=True,
                        default="NOT_ASSESSED",
                        max_length=30,
                    ),
                ),
                ("damage_notes", models.TextField(blank=True, default="")),
                (
                    "damage_deduction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deposit_refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("deposit_refund_approved", models.BooleanField(default=False)),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("stock_routing_notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "rent_lease_return_inspections",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Repossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOTICE_ISSUED", "Notice Issued"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NOTICE_ISSUED",
                        max_length=20,
                    ),
                ),
                ("notice_issued_at", models.DateTimeField(db_index=True)),
                (
                    "notice_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "notice_document",
                    models.FileField(
                        blank=True, null=True, upload_to="repossession/notices/"
                    ),
                ),
                ("response_deadline", models.DateField(db_index=True)),
                (
                    "initiated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "asset_condition_on_return",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="NOT_ASSESSED",
                        max_length=20,
                    ),
                ),
                ("recovery_notes", models.TextField(blank=True, default="")),
                (
                    "outstanding_balance_at_repossession",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "db_table": "repossessions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCHEDULED", "Scheduled"),
                            (
                                "BLOCKED_STOCK_UNAVAILABLE",
                                "Blocked – Stock Unavailable",
                            ),
                            ("DISPATCHED", "Dispatched"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURN_REQUESTED", "Return Requested"),
                            ("RETURNED", "Returned"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "delivery_reference",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "dispatched_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "out_for_delivery_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "failed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "return_requested_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "returned_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "receiver_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "receiver_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("delivery_address_snapshot", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("stock_blocked_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "subscription_deliveries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AssetConditionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("BEFORE_HANDOVER", "Before Handover"),
                            ("AFTER_RETURN", "After Return"),
                            ("DAMAGE_REVIEW", "Damage Review"),
                            ("MAINTENANCE_REVIEW", "Maintenance Review"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "condition_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                            ("SCRAP", "Scrap"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assessed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_condition_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_asset_condition_snapshots",
                "ordering": ["-assessed_at", "-id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
