# Generated by Django 5.2.7 on 2026-08-20 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiondelivery",
            name="admin_override",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when admin force-released delivery bypassing eligibility gate.",
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondelivery",
            name="admin_override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptiondelivery",
            name="admin_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overridden_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondelivery",
            name="admin_override_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
