# Generated by Django 5.2.7 on 2026-09-07 02:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_add_admin_override_to_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="assessed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="assessed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessed_return_damage",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="assessment_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="damage_deduction_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="damage_deduction_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="damage_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GOOD", "Good — no deduction"),
                    ("MINOR", "Minor wear"),
                    ("MAJOR", "Major damage"),
                    ("SEVERE", "Severe damage"),
                ],
                db_index=True,
                default="",
                help_text="Blank until the item has been inspected.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="consumerreturnrequest",
            name="refundable_base_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Net paid at assessment time; the figure the deduction applied to.",
                max_digits=12,
            ),
        ),
    ]
