# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0053_alter_customeropeningoutstanding_customer_and_more"),
        ("commissions", "0001_initial"),
        ("contracts", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
            model_name="commission",
            name="emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="commissionpayoutbatch",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_payout_batches",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="commissionpayoutbatch",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_payout_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commissionpayoutline",
            name="commission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_line",
                to="commissions.commission",
            ),
        ),
        migrations.AddField(
            model_name="commissionpayoutline",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_payout_lines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commissionpayoutline",
            name="payout_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="commissions.commissionpayoutbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["partner", "status"], name="commissions_partner_d10229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["subscription", "status"], name="commissions_subscri_3d3ef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["payment"], name="commissions_payment_00b241_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionpayoutline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="commission_payout_line_amount_non_negative",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
