# Generated by Django 6.0.2 on 2026-04-08 07:42

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(db_index=True, default=accounting.models.generate_employee_code, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('joining_date', models.DateField(db_index=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'accounting_employee_profiles',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('gstin', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('state_code', models.CharField(blank=True, max_length=5, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'accounting_vendors',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=accounting.models.generate_chart_code, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_manual_posting', models.BooleanField(default=True)),
                ('system_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.chartofaccount')),
            ],
            options={
                'db_table': 'accounting_chart_of_accounts',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI')], db_index=True, max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('bank_last4', models.CharField(blank=True, default='', max_length=4)),
                ('upi_handle', models.CharField(blank=True, default='', max_length=255)),
                ('chart_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accounts', to='accounting.chartofaccount')),
            ],
            options={
                'db_table': 'accounting_finance_accounts',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_no', models.CharField(db_index=True, default=accounting.models.generate_entry_no, max_length=40, unique=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_type', models.CharField(choices=[('MANUAL', 'Manual'), ('EXPENSE', 'Expense'), ('SALARY', 'Salary'), ('MONEY_MOVEMENT', 'Money Movement'), ('SYSTEM_BRIDGE', 'System Bridge')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=10)),
                ('memo', models.TextField(blank=True, default='')),
                ('source_model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_accounting_journals', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_accounting_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_journal_entries',
                'ordering': ['-entry_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingBridgePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_model', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.CharField(db_index=True, max_length=100)),
                ('purpose', models.CharField(db_index=True, max_length=100)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bridge_posting', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_bridge_postings',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('chart_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.chartofaccount')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_journal_entry_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MoneyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_no', models.CharField(db_index=True, default=accounting.models.generate_movement_no, max_length=40, unique=True)),
                ('movement_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('from_finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_money_movements', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_money_movement', to='accounting.journalentry')),
                ('to_finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_money_movements', to='accounting.financeaccount')),
            ],
            options={
                'db_table': 'accounting_money_movements',
                'ordering': ['-movement_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalarySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('month', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductions_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAID_PARTIAL', 'Paid Partial'), ('PAID', 'Paid')], db_index=True, default='DRAFT', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_sheets', to='accounting.employeeprofile')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_salary_sheet', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_salary_sheets',
                'ordering': ['-year', '-month', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_salary_payment', to='accounting.journalentry')),
                ('salary_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='accounting.salarysheet')),
            ],
            options={
                'db_table': 'accounting_salary_payments',
                'ordering': ['-payment_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_no', models.CharField(db_index=True, default=accounting.models.generate_voucher_no, max_length=40, unique=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('bill_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='accounting.chartofaccount')),
                ('finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_expense_voucher', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_expense_vouchers',
                'ordering': ['-expense_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='accounting__account_744a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['parent'], name='accounting__parent__ec40f1_idx'),
        ),
        migrations.AddIndex(
            model_name='financeaccount',
            index=models.Index(fields=['kind', 'is_active'], name='accounting__kind_98f62e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type', 'status'], name='accounting__entry_t_40592b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_model', 'source_id'], name='accounting__source__0f5be5_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingbridgeposting',
            constraint=models.UniqueConstraint(fields=('source_model', 'source_id', 'purpose'), name='accounting_bridge_unique_source_purpose'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', Decimal('0.00'))), name='accounting_line_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', Decimal('0.00'))), name='accounting_line_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_amount__gt', Decimal('0.00')), ('credit_amount', Decimal('0.00'))), models.Q(('credit_amount__gt', Decimal('0.00')), ('debit_amount', Decimal('0.00'))), _connector='OR'), name='accounting_line_exactly_one_side_positive'),
        ),
        migrations.AddConstraint(
            model_name='salarysheet',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'month'), name='accounting_salary_sheet_unique_employee_period'),
        ),
        migrations.AddIndex(
            model_name='expensevoucher',
            index=models.Index(fields=['status', 'expense_date'], name='accounting__status_e0da62_idx'),
        ),
    ]
