# Generated by Django 6.0.2 on 2026-04-08 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('last_issued_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'accounting_document_sequences',
                'ordering': ['series_code', 'financial_year', 'id'],
                'indexes': [models.Index(fields=['financial_year', 'is_active'], name='accounting__financi_3f2a6f_idx')],
            },
        ),
    ]
