# Generated by Django 6.0.2 on 2026-04-08 11:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_reporting_indexes_and_sequences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('supplier_name', models.CharField(max_length=160)),
                ('supplier_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('supplier_address', models.TextField(blank=True, default='')),
                ('supplier_state_code', models.CharField(blank=True, default='', max_length=5)),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_address', models.TextField(blank=True, default='')),
                ('recipient_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('place_of_supply_state_code', models.CharField(blank=True, default='', max_length=5)),
                ('supply_kind', models.CharField(choices=[('INTRA', 'Intra State'), ('INTER', 'Inter State')], db_index=True, default='INTRA', max_length=10)),
                ('subtotal_taxable', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tax_invoices', to=settings.AUTH_USER_MODEL)),
                ('doc_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='accounting.documentsequence')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_tax_invoice', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_tax_invoices',
                'ordering': ['-invoice_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('note_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('taxable_adjustment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_adjustment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('doc_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='accounting.documentsequence')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_debit_note', to='accounting.journalentry')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='accounting.taxinvoice')),
            ],
            options={
                'db_table': 'accounting_debit_notes',
                'ordering': ['-note_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_no', models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True)),
                ('note_date', models.DateField(db_index=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('taxable_adjustment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_adjustment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('doc_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounting.documentsequence')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_credit_note', to='accounting.journalentry')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounting.taxinvoice')),
            ],
            options={
                'db_table': 'accounting_credit_notes',
                'ordering': ['-note_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('hsn_sac', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.taxinvoice')),
            ],
            options={
                'db_table': 'accounting_tax_invoice_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['status', 'invoice_date'], name='accounting__status_492ace_idx'),
        ),
        migrations.AddIndex(
            model_name='taxinvoice',
            index=models.Index(fields=['supply_kind', 'invoice_date'], name='accounting__supply__ae537c_idx'),
        ),
    ]
