# Generated by Django 6.0.2 on 2026-04-08 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_gst_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_type', models.CharField(choices=[('ITR_HANDOFF', 'ITR Handoff')], db_index=True, default='ITR_HANDOFF', max_length=30)),
                ('financial_year', models.CharField(blank=True, default='', max_length=9)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_export_pack_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_export_pack_jobs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['pack_type', 'status'], name='accounting__pack_ty_4205ac_idx'), models.Index(fields=['financial_year', 'status'], name='accounting__financi_02d158_idx')],
            },
        ),
    ]
