# Generated by Django 6.0.2 on 2026-04-08 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_itr_export_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lock_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_periods',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'entry_date'], name='accounting__status_12b9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['chart_account', 'id'], name='accounting__chart_a_68f6fc_idx'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_accounting_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['is_locked', 'start_date', 'end_date'], name='accounting__is_lock_312a26_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date'), name='accounting_period_unique_date_range'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='accounting_period_end_after_start'),
        ),
    ]
