# Generated by Django 6.0.2 on 2026-04-08 18:28

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_accountingperiod_and_more'),
        ('inventory', '0002_inventoryvaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('method', models.CharField(choices=[('SLM', 'Straight Line'), ('WDM', 'Written Down')], db_index=True, default='SLM', max_length=10)),
                ('useful_life_months', models.PositiveIntegerField(default=12)),
                ('rate_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_salvage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'accounting_asset_categories',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reversal_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_credit_note', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_debit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='reversal_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_debit_note', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_tax_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='reversal_journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_tax_invoice', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='exportpackjob',
            name='pack_type',
            field=models.CharField(choices=[('ITR_HANDOFF', 'ITR Handoff'), ('GST_HANDOFF', 'GST Handoff')], db_index=True, default='ITR_HANDOFF', max_length=30),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(db_index=True, default=accounting.models.generate_asset_code, max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField(db_index=True)),
                ('in_service_date', models.DateField(db_index=True)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed')], db_index=True, default='ACTIVE', max_length=12)),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.purchasebill')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounting.vendor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounting.assetcategory')),
            ],
            options={
                'db_table': 'accounting_assets',
                'ordering': ['asset_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_code', models.CharField(db_index=True, default=accounting.models.generate_depreciation_run_code, max_length=40, unique=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('executed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_depreciation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_depreciation_runs',
                'ordering': ['-period_end', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_lines', to='accounting.asset')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_line', to='accounting.journalentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.depreciationrun')),
            ],
            options={
                'db_table': 'accounting_depreciation_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostingLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_date', models.DateField(db_index=True, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('locked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_posting_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_posting_locks',
                'ordering': ['-lock_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_no', models.CharField(db_index=True, default=accounting.models.generate_vendor_settlement_no, max_length=40, unique=True)),
                ('settlement_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlements', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlement', to='accounting.journalentry')),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlements', to='inventory.purchasebill')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlements', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_settlements',
                'ordering': ['-settlement_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'in_service_date'], name='accounting__status_2fd8ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='depreciationrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='accounting_depr_run_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='depreciationline',
            constraint=models.UniqueConstraint(fields=('run', 'asset'), name='accounting_depreciation_line_unique_run_asset'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['vendor', 'settlement_date'], name='accounting__vendor__d60630_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['status', 'settlement_date'], name='accounting__status_60d8e0_idx'),
        ),
    ]
