# Generated by Django 6.0.2 on 2026-04-09 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_assetcategory_creditnote_cancel_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='source_document_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='source_event_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='trace_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accountingbridgeposting',
            name='voucher_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='accountingbridgeposting',
            index=models.Index(fields=['purpose', 'source_type', 'source_event_date'], name='accounting__purpose_036406_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingbridgeposting',
            index=models.Index(fields=['voucher_type', 'source_event_date'], name='accounting__voucher_dd3d98_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucher_type', 'source_type'], name='accounting__voucher_a66cda_idx'),
        ),
    ]
