# Generated by Django 6.0.2 on 2026-04-09 18:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingbridgeposting_source_document_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], db_index=True, default='PRESENT', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_employee_attendance',
                'ordering': ['-attendance_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active', 'department'], name='accounting__is_acti_ef167a_idx'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='accounting.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_employee_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['attendance_date', 'status'], name='accounting__attenda_19e8dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='accounting_employee_attendance_unique_employee_date'),
        ),
    ]
