# Generated by Django 6.0.2 on 2026-04-10 05:12

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_employeeattendance_employeeprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=120)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], db_index=True, max_length=12)),
                ('source_type', models.CharField(choices=[('BASE_SALARY', 'Base Salary'), ('COMPONENT', 'Component'), ('OVERTIME', 'Overtime'), ('LEAVE_DEDUCTION', 'Leave Deduction'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_salary_sheet_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='overtime_rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='standard_daily_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='EmployeeCompensationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=120)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], db_index=True, max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_components', to='accounting.employeeprofile')),
            ],
            options={
                'db_table': 'accounting_employee_compensation_components',
                'ordering': ['employee_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_no', models.CharField(db_index=True, default=accounting.models.generate_expense_claim_no, max_length=40, unique=True)),
                ('claim_date', models.DateField(db_index=True)),
                ('expense_date', models.DateField(db_index=True)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAID_PARTIAL', 'Paid Partial'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('bill_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_employee_expense_claims', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='accounting.employeeprofile')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_expense_claims', to='accounting.chartofaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_employee_expense_claim', to='accounting.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_employee_expense_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_employee_expense_claims',
                'ordering': ['-expense_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExpenseClaimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('expense_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.employeeexpenseclaim')),
                ('finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_expense_claim_payments', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_employee_expense_claim_payment', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_employee_expense_claim_payments',
                'ordering': ['-payment_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(db_index=True, default=accounting.models.generate_leave_request_no, max_length=40, unique=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('day_count', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='accounting.employeeprofile')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_leave_requests',
                'ordering': ['-start_date', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='accounting.leaverequest'),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_paid', models.BooleanField(db_index=True, default=True)),
                ('annual_allowance_days', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_leave_types',
                'ordering': ['code', 'id'],
                'indexes': [models.Index(fields=['is_active', 'is_paid'], name='accounting__is_acti_3c1d83_idx')],
            },
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='accounting.leavetype'),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('month', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('close_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_payroll_periods',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salarysheet',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_sheets', to='accounting.payrollperiod'),
        ),
        migrations.AddIndex(
            model_name='salarysheet',
            index=models.Index(fields=['payroll_period', 'status'], name='accounting__payroll_cb099a_idx'),
        ),
        migrations.AddField(
            model_name='salarysheetline',
            name='salary_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.salarysheet'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationcomponent',
            index=models.Index(fields=['employee', 'is_active', 'component_type'], name='accounting__employe_be27e4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpenseclaim',
            index=models.Index(fields=['employee', 'status', 'expense_date'], name='accounting__employe_5d5480_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpenseclaim',
            index=models.Index(fields=['claim_date', 'status'], name='accounting__claim_d_3ddbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpenseclaimpayment',
            index=models.Index(fields=['expense_claim', 'payment_date'], name='accounting__expense_2790cc_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status', 'start_date', 'end_date'], name='accounting__employe_2c0b14_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['leave_type', 'status'], name='accounting__leave_t_3f5367_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='accounting__status_f0374c_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='accounting_payroll_period_unique_year_month'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='accounting_payroll_period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='salarysheetline',
            index=models.Index(fields=['salary_sheet', 'component_type', 'source_type'], name='accounting__salary__39a373_idx'),
        ),
    ]
