# Generated by Django 6.0.2 on 2026-04-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_salarysheetline_employeeattendance_overtime_hours_and_more'),
        ('branch_control', '0001_initial'),
        ('inventory', '0005_alter_stockledger_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexpenseclaim',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_expense_claims', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='employeeexpenseclaimpayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_expense_claim_payments', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_accounts', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_settlements', to='branch_control.branch'),
        ),
        migrations.AddIndex(
            model_name='employeeexpenseclaim',
            index=models.Index(fields=['branch', 'expense_date'], name='accounting__branch__5366a8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpenseclaimpayment',
            index=models.Index(fields=['branch', 'payment_date'], name='accounting__branch__eea9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['branch', 'is_active'], name='accounting__branch__f28e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensevoucher',
            index=models.Index(fields=['branch', 'expense_date'], name='accounting__branch__3188aa_idx'),
        ),
        migrations.AddIndex(
            model_name='financeaccount',
            index=models.Index(fields=['branch', 'kind', 'is_active'], name='accounting__branch__9191a1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['branch', 'payment_date'], name='accounting__branch__28b34c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorsettlement',
            index=models.Index(fields=['branch', 'settlement_date'], name='accounting__branch__93580e_idx'),
        ),
    ]
