# Generated by Django 6.0.2 on 2026-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_employeeexpenseclaim_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
