# Generated by Django 6.0.2 on 2026-04-26 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_chartofaccount_notes_financeaccount_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentLeaseAccountingAccountMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "damage_recovery_income_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_damage_recovery_mappings",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "deposit_liability_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_deposit_liability_mappings",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "deposit_refund_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_deposit_refund_mappings",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "monthly_income_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_monthly_income_mappings",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "settlement_finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_account_mappings",
                        to="accounting.financeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_rent_lease_account_mappings",
                "ordering": ["-is_active", "-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="uq_single_active_rent_lease_account_mapping",
                    )
                ],
            },
        ),
    ]
