# Generated by Django 6.0.2 on 2026-04-27 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_rentleaseaccountingaccountmapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAccountCoaMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CASH_COLLECTION", "Cash Collection"),
                            ("UPI_COLLECTION", "UPI Collection"),
                            ("BANK_COLLECTION", "Bank Collection"),
                            ("CUSTOMER_RECEIVABLE", "Customer Receivable"),
                            (
                                "SECURITY_DEPOSIT_LIABILITY",
                                "Security Deposit Liability",
                            ),
                            ("EMI_INCOME", "Advance EMI Income"),
                            ("RENT_INCOME", "Rent Income"),
                            ("LEASE_INCOME", "Lease Income"),
                            ("DIRECT_SALE_INCOME", "Direct Sale Income"),
                            ("WAIVER_LOSS", "Waiver/Loss"),
                            ("COMMISSION_PAYABLE", "Commission Payable"),
                            ("DAMAGE_RECOVERY", "Damage Recovery"),
                            ("INVENTORY_ASSET", "Inventory Asset"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "chart_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_account_mappings",
                        to="accounting.chartofaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_finance_coa_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coa_mappings",
                        to="accounting.financeaccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_finance_coa_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_finance_account_coa_mappings",
                "ordering": ["purpose", "-is_default", "-is_active", "id"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "is_active"],
                        name="accounting__purpose_b7aee3_idx",
                    ),
                    models.Index(
                        fields=["is_default", "is_active"],
                        name="accounting__is_defa_a6f694_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("finance_account", "purpose"),
                        name="uq_active_finance_account_purpose_mapping",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("is_default", True)),
                        fields=("purpose",),
                        name="uq_default_mapping_per_purpose",
                    ),
                ],
            },
        ),
    ]
