# Generated by Django 6.0.2 on 2026-04-29 18:56

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_financeaccountcoamapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="cost_center_code",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="daily_wage_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("PERMANENT_MONTHLY", "Permanent Monthly Staff"),
                    ("TEMPORARY", "Temporary Staff"),
                    ("DAILY_WAGE", "Daily Wage Worker"),
                    ("HOURLY", "Hourly Worker"),
                    ("PIECE_RATE", "Piece-rate Worker"),
                    ("MANUFACTURING", "Manufacturing Worker"),
                    ("SERVICE", "Service Worker"),
                ],
                db_index=True,
                default="PERMANENT_MONTHLY",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="hourly_wage_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="kyc_id_number",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="kyc_id_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="kyc_verified",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="payroll_expense_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_profiles_payroll_expense",
                to="accounting.chartofaccount",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="piece_rate_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="piece_rate_unit_label",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="salary_effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="temporary_contract_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_PROOF", "ID Proof"),
                            ("ADDRESS_PROOF", "Address Proof"),
                            ("SALARY_AGREEMENT", "Salary Agreement"),
                            ("APPOINTMENT_LETTER", "Appointment Letter"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "document_no",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=accounting.models.employee_document_upload_to
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="accounting.employeeprofile",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_employee_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounting_employee_documents",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status", "document_type"],
                        name="accounting__employe_25dc9b_idx",
                    )
                ],
            },
        ),
    ]
