# Generated by Django 6.0.2 on 2026-04-30 17:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_journalentrygroup_and_journal_link"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="journalentrygroup",
            new_name="accounting__source__f104b3_idx",
            old_name="accounting_j_source__5b4e91_idx",
        ),
        migrations.RenameIndex(
            model_name="journalentrygroup",
            new_name="accounting__transac_2da61d_idx",
            old_name="accounting_j_transac_70571f_idx",
        ),
        migrations.AlterField(
            model_name="journalentrygroup",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="journalentrygroup",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
