# Generated by Django 5.2.7 on 2026-05-07 20:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_vendor_categories(apps, schema_editor):
    VendorCategory = apps.get_model("accounting", "VendorCategory")
    defaults = [
        "FURNITURE_DEALER",
        "FURNITURE_MANUFACTURER",
        "WOOD_SUPPLIER",
        "STEEL_SUPPLIER",
        "IRON_SUPPLIER",
        "FOAM_SUPPLIER",
        "FABRIC_SUPPLIER",
        "ELECTRONICS_SUPPLIER",
        "HARDWARE_SUPPLIER",
        "GLASS_SUPPLIER",
        "TRANSPORT_VENDOR",
        "SERVICE_VENDOR",
        "PACKAGING_VENDOR",
        "GENERAL_VENDOR",
    ]
    for code in defaults:
        VendorCategory.objects.get_or_create(
            code=code,
            defaults={"name": code.replace("_", " ").title(), "description": "", "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_financeaccountcoamapping_purpose'),
        ('subscriptions', '0064_operationalcancellation_manual_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='vendor',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='vendor',
            name='warranty_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('OFFICE', 'Office'), ('MANUFACTURING_UNIT', 'Manufacturing Unit'), ('WAREHOUSE', 'Warehouse'), ('SERVICE_CENTER', 'Service Center')], db_index=True, default='OFFICE', max_length=30)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_addresses',
                'ordering': ['vendor_id', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.vendorcategory')),
            ],
            options={
                'db_table': 'accounting_vendor_categories',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='accounting.vendorcategory'),
        ),
        migrations.CreateModel(
            name='VendorLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('PURCHASE_BILL', 'Purchase Bill'), ('PAYMENT_TO_VENDOR', 'Payment To Vendor'), ('PURCHASE_RETURN', 'Purchase Return'), ('DEBIT_NOTE', 'Debit Note'), ('CREDIT_ADJUSTMENT', 'Credit Adjustment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=30)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('source_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('posted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_ledger_entries',
                'ordering': ['vendor_id', '-posted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_sku', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('product_name', models.CharField(max_length=180)),
                ('category_text', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('material', models.CharField(blank=True, default='', max_length=120)),
                ('size_description', models.CharField(blank=True, default='', max_length=160)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('base_quote_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_order_qty', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('internal_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to='subscriptions.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_products',
                'ordering': ['vendor_id', 'product_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('source_type', models.CharField(choices=[('CUSTOMER_ENQUIRY', 'Customer Enquiry'), ('DIRECT_SALE_ORDER', 'Direct Sale Order'), ('ONLINE_ORDER', 'Online Order'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=30)),
                ('source_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('customer_pincode', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('customer_city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('customer_district', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('customer_state', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=180)),
                ('category_text', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('QUOTING', 'Quoting'), ('PARTIALLY_QUOTED', 'Partially Quoted'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_quote_requests', to='subscriptions.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_quote_requests', to='subscriptions.product')),
            ],
            options={
                'db_table': 'accounting_vendor_quote_requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quality_note', models.TextField(blank=True, default='')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='REQUESTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_vendor_quotes', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='accounting.vendor')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounting.vendorquoterequest')),
            ],
            options={
                'db_table': 'accounting_vendor_quotes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_service_areas',
                'ordering': ['vendor_id', 'state', 'district', 'city', 'id'],
            },
        ),
        migrations.RunPython(seed_vendor_categories, migrations.RunPython.noop),
    ]
