# Generated by Django 5.2.7 on 2026-05-07 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_vendor_contact_person_vendor_credit_period_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorquote',
            constraint=models.UniqueConstraint(fields=('quote_request', 'vendor'), name='vendor_quote_unique_request_vendor'),
        ),
    ]
