# Generated by Django 6.0.2 on 2026-05-08 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_customer_purchase_enquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpurchaseenquiry",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
