# Generated by Django 6.0.2 on 2026-05-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_accountingpostingprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountingpostingprofile',
            new_name='accounting__is_acti_57aa2d_idx',
            old_name='accounting__is_acti_5bfb74_idx',
        ),
    ]
