# Generated by Django 5.2.7 on 2026-05-13 07:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_rename_accounting__is_acti_5bfb74_idx_accounting__is_acti_57aa2d_idx'),
        ('subscriptions', '0067_rentleasebillingdemand_tax_profile_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('GST_UNREGISTERED', 'GST Unregistered'), ('GST_REGULAR', 'GST Regular'), ('GST_COMPOSITION', 'GST Composition')], db_index=True, default='GST_UNREGISTERED', max_length=32)),
                ('legal_name', models.CharField(blank=True, default='', max_length=180)),
                ('gstin', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('state_code', models.CharField(blank=True, default='', max_length=5)),
                ('state_name', models.CharField(blank=True, default='', max_length=120)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_business_tax_profiles',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['mode', 'is_active'], name='accounting__mode_08d7b5_idx'), models.Index(fields=['effective_from', 'effective_to'], name='accounting__effecti_9846e6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uq_single_active_business_tax_profile')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_compliance_alert_thresholds',
                'ordering': ['key', 'id'],
                'indexes': [models.Index(fields=['is_active', 'key'], name='accounting__is_acti_41883e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor')], db_index=True, max_length=20)),
                ('party_id', models.PositiveIntegerField(db_index=True)),
                ('tax_type', models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('REGISTERED', 'Registered'), ('COMPOSITION', 'Composition')], db_index=True, default='UNREGISTERED', max_length=20)),
                ('legal_name', models.CharField(blank=True, default='', max_length=180)),
                ('gstin', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=20)),
                ('state_code', models.CharField(blank=True, default='', max_length=5)),
                ('state_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounting_party_tax_profiles',
                'ordering': ['party_type', 'party_id', '-id'],
                'indexes': [models.Index(fields=['party_type', 'party_id', 'is_active'], name='accounting__party_t_d87427_idx'), models.Index(fields=['tax_type', 'is_active'], name='accounting__tax_typ_d46ced_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('party_type', 'party_id'), name='uq_active_party_tax_profile')],
            },
        ),
        migrations.CreateModel(
            name='ProductTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=40)),
                ('tax_category', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service'), ('MIXED', 'Mixed')], db_index=True, default='GOODS', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_profiles', to='subscriptions.product')),
            ],
            options={
                'db_table': 'accounting_product_tax_profiles',
                'ordering': ['product_id', '-effective_from', '-id'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='accounting__product_761536_idx'), models.Index(fields=['effective_from', 'effective_to'], name='accounting__effecti_46f192_idx')],
            },
        ),
    ]
