# Generated by Django 6.0.2 on 2026-06-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_operational_accounting_posting_bridge"),
        ("accounting", "0027_seed_default_non_gst_business_tax_profile"),
    ]

    operations = []
