# Generated by Django 5.2.7 on 2026-06-06 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_document_sequence_financial_year_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='financial_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.financialyear'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['financial_year', 'status'], name='accounting__financi_e85f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['accounting_period', 'status'], name='accounting__account_6333e8_idx'),
        ),
    ]
