# Generated by Django 6.0.2 on 2026-06-16 17:09

import accounting.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_journalentry_accounting_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('BANK_PROOF', 'Bank Proof'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('document_reference', models.CharField(blank=True, default='', max_length=80)),
                ('file', models.FileField(upload_to=accounting.models._staff_kyc_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], db_index=True, default='SUBMITTED', max_length=30)),
                ('upload_source', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='accounting.employeeprofile')),
                ('resubmission_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='accounting.staffkycdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staff_kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounting_staff_kyc_documents',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'status'], name='accounting__employe_c1d3f8_idx'), models.Index(fields=['employee', 'document_type'], name='accounting__employe_491dd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('GST_CERTIFICATE', 'GST Certificate'), ('BANK_PROOF', 'Bank Proof'), ('INCORPORATION_CERTIFICATE', 'Incorporation Certificate'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('document_reference', models.CharField(blank=True, default='', max_length=80)),
                ('file', models.FileField(upload_to=accounting.models._vendor_kyc_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], db_index=True, default='SUBMITTED', max_length=30)),
                ('upload_source', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('resubmission_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='accounting.vendorkycdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vendor_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='accounting.vendor')),
            ],
            options={
                'db_table': 'accounting_vendor_kyc_documents',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='accounting__vendor__0fb679_idx'), models.Index(fields=['vendor', 'document_type'], name='accounting__vendor__5e4f74_idx')],
            },
        ),
    ]
