# Generated by Django 5.2.7 on 2026-06-24 04:09

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_core_finance_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costallocationdetail',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='deferredtax',
            name='book_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='deferredtax',
            name='dta_dtl_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='deferredtax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='deferredtax',
            name='temporary_difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='expensevoucher',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank'), ('CARD', 'Card')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='fixedassetdepreciation',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='fixedassetdepreciation',
            name='net_book_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='fixedassetdepreciation',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='initial_lease_liability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='rou_asset_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='tcscollection',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tcscollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tdsdeduction',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tdsdeduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
