# Generated by Django 5.2.7 on 2026-06-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_alter_costallocationdetail_allocation_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='lease_payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash/bank/payment clearing account credited when lease payments are posted.', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_payment_records', to='accounting.chartofaccount'),
        ),
    ]
