# Generated by Django 5.2.7 on 2026-07-01 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0045_vendor_settlement_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="salary_pay_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of month salary is paid (1-28).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(28),
                ],
            ),
        ),
    ]
