# Generated by Django 5.2.7 on 2026-07-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0046_employee_salary_pay_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffadvancerecovery",
            name="recovery_source",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash / Bank Recovery"),
                    ("SALARY_DEDUCTION", "Salary Deduction"),
                ],
                db_index=True,
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffadvancerecovery",
            name="salary_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_advance_recoveries",
                to="accounting.salarysheet",
            ),
        ),
        migrations.AlterField(
            model_name="staffadvancerecovery",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff_advance_recoveries",
                to="accounting.financeaccount",
            ),
        ),
    ]
