# Generated by Django 5.2.7 on 2026-07-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0047_staff_advance_salary_recovery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarysheetline",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("BASE_SALARY", "Base Salary"),
                    ("COMPONENT", "Component"),
                    ("OVERTIME", "Overtime"),
                    ("LEAVE_DEDUCTION", "Leave Deduction"),
                    ("STAFF_ADVANCE_DEDUCTION", "Staff Advance Deduction"),
                    ("MANUAL", "Manual"),
                ],
                db_index=True,
                default="MANUAL",
                max_length=30,
            ),
        ),
    ]
