# Generated by Django 5.2.7 on 2026-07-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0048_salary_line_staff_advance_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxinvoice",
            name="irn",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="GST e-invoice IRN. Once set, invoice fields are immutable (INV-4).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="taxinvoice",
            name="irn_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when IRN was generated by the e-invoice portal.",
                null=True,
            ),
        ),
    ]
