# Generated by Django 5.2.7 on 2026-07-26 17:59

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0050_seed_default_leave_types"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("subscriptions", "0136_alter_auditlog_action_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customeropeningoutstanding",
            name="collected_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sum of real collections posted against this opening receivable.",
                max_digits=12,
            ),
        ),
        # NOTE: `customer` FK and the UnifiedPayableIdempotency model were added to
        # models.py earlier without their own migration, so this is the migration
        # of record that creates them on fresh databases (tests, production). The
        # dev database already had them out-of-band and already has this migration
        # marked applied, so it will not re-run these operations there.
        migrations.AddField(
            model_name="customeropeningoutstanding",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_outstandings",
                to="subscriptions.customer",
            ),
        ),
        migrations.CreateModel(
            name="LegacyReceivableCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_no",
                    models.CharField(
                        default=accounting.models.generate_legacy_receivable_collection_no,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_method", models.CharField(default="CASH", max_length=20)),
                ("receipt_date", models.DateField(blank=True, null=True)),
                (
                    "reference_no",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_receivable_collections",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "cash_counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_receivable_collections",
                        to="branch_control.cashcounter",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_receivable_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legacy_receivable_collections",
                        to="accounting.financeaccount",
                    ),
                ),
                (
                    "posted_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_receivable_collections",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="accounting.customeropeningoutstanding",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_legacy_receivable_collections",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedPayableIdempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=160)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed")],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_payable_idempotency_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "unified_payable_idempotency",
                "unique_together": {("user", "key")},
            },
        ),
    ]
