# Generated by Django 5.2.7 on 2026-07-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0051_customeropeningoutstanding_collected_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensevoucher",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
