# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0052_alter_expensevoucher_payment_mode"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="customeropeningoutstanding",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_outstandings",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerpurchaseenquiry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_purchase_enquiries",
                to="customers.customer",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
