# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0053_alter_customeropeningoutstanding_customer_and_more"),
        ("contracts", "0002_initial"),
        ("crm", "0009_alter_customerinteraction_customer_and_more"),
        ("customers", "0002_initial"),
        ("products_core", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="customerpurchaseenquiry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_purchase_enquiries",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="customerpurchaseenquiry",
            name="public_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_purchase_enquiries",
                to="crm.publiclead",
            ),
        ),
        migrations.AlterField(
            model_name="leasecontract",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_contract",
                to="contracts.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="producttaxprofile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_profiles",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="vendorproduct",
            name="internal_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_products",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="vendorquoterequest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_quote_requests",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="vendorquoterequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_quote_requests",
                to="products_core.product",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
