# Generated by Django 5.2.7 on 2026-08-14 06:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0055_owner_fund_injection"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerfundinjection",
            name="interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual interest rate in %",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ownerfundinjection",
            name="interest_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FLAT", "Flat Rate"),
                    ("REDUCING", "Reducing Balance"),
                    ("NONE", "Interest-Free"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ownerfundinjection",
            name="repayment_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("LUMP_SUM", "Lump Sum at End"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ownerfundinjection",
            name="repayment_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ownerfundinjection",
            name="tenure_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ownerfundinjection",
            name="total_interest",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
