# Generated by Django 5.2.7 on 2026-08-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0058_customeropeningoutstanding_admin_verified"),
        ("migration_center", "0002_alter_migrationbatch_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeropeningoutstanding",
            name="migration_row",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_opening_outstandings",
                to="migration_center.migrationstagingrow",
            ),
        ),
    ]
