# Generated by Django 5.2.7 on 2026-09-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0060_financeaccount_opening_balance_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financeaccountcoamapping",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("CASH_COLLECTION", "Cash Collection"),
                    ("UPI_COLLECTION", "UPI Collection"),
                    ("BANK_COLLECTION", "Bank Collection"),
                    (
                        "PAYMENT_GATEWAY_COLLECTION",
                        "Payment Gateway Settlement Collection",
                    ),
                    ("CUSTOMER_RECEIVABLE", "Customer Receivable"),
                    ("SECURITY_DEPOSIT_LIABILITY", "Security Deposit Liability"),
                    (
                        "CUSTOMER_ADVANCE_UNEARNED_REVENUE",
                        "Customer Advance / Unearned Revenue",
                    ),
                    ("EMI_INCOME", "Advance EMI Income"),
                    ("RENT_INCOME", "Rent Income"),
                    ("LEASE_INCOME", "Lease Income"),
                    ("DIRECT_SALE_INCOME", "Direct Sale Income"),
                    ("DELIVERY_CHARGES_INCOME", "Delivery Charges Income"),
                    ("WAIVER_LOSS", "Waiver/Loss"),
                    ("COMMISSION_PAYABLE", "Commission Payable"),
                    ("COMMISSION_EXPENSE", "Commission Expense"),
                    ("DAMAGE_RECOVERY", "Damage Recovery"),
                    ("DELIVERY_EXPENSE", "Delivery Expense"),
                    ("SALARY_EXPENSE", "Salary Expense"),
                    ("INVENTORY_ASSET", "Inventory Asset"),
                    ("RENTAL_ASSET_IN_SERVICE", "Rental Assets In Service (On Hire)"),
                    ("ADVANCE_FORFEITURE_INCOME", "Advance Forfeiture Income"),
                    ("BAD_DEBT_EXPENSE", "Bad Debt Written Off"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
