# Generated by Django 5.2.7 on 2026-09-12 02:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0061_alter_financeaccountcoamapping_purpose"),
        ("inventory", "0029_backfill_stock_tracking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorsettlement",
            name="is_advance",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="VendorAdvanceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("allocation_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="accounting.vendorsettlement",
                    ),
                ),
                (
                    "purchase_bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_advance_allocations",
                        to="inventory.purchasebill",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="accounting.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_vendor_advance_allocations",
                "ordering": ["-allocation_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "allocation_date"],
                        name="accounting__vendor__40871b_idx",
                    )
                ],
            },
        ),
    ]
