# Generated by Django 5.2.7 on 2026-07-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0117_compliance_invariants_p1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBreachLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("breach_description", models.TextField()),
                ("data_types_affected", models.JSONField()),
                ("affected_customer_count", models.PositiveIntegerField()),
                ("discovered_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("contained_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True)),
                ("remediation_steps", models.TextField(blank=True)),
                ("authority_notified", models.BooleanField(default=False)),
                (
                    "notification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("BOTH", "Email & SMS"),
                        ],
                        max_length=100,
                    ),
                ),
                ("notification_template", models.TextField(blank=True)),
            ],
            options={
                "db_table": "data_breach_logs",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_category",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_PROFILE", "Customer Profile"),
                            ("PAYMENT_RECORDS", "Payment Records"),
                            ("KYC_DOCUMENTS", "KYC Documents"),
                            ("COMMUNICATION", "Email/SMS History"),
                            ("SUPPORT_TICKETS", "Support Tickets"),
                            ("ANALYTICS", "Analytics Data"),
                            ("CALL_RECORDINGS", "Call Recordings"),
                            ("WEBSITE_LOGS", "Website Logs"),
                            ("BACKUPS", "Backup Copies"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "retention_months",
                    models.PositiveIntegerField(help_text="Months to retain"),
                ),
                ("legal_requirement", models.CharField(blank=True, max_length=255)),
                ("auto_delete", models.BooleanField(default=True)),
                ("notify_before_delete", models.BooleanField(default=False)),
                ("notify_days_before", models.PositiveIntegerField(default=30)),
            ],
            options={
                "db_table": "data_retention_policies",
            },
        ),
        migrations.CreateModel(
            name="CookieConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "browser_fingerprint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("essential_allowed", models.BooleanField(default=True)),
                ("analytics_allowed", models.BooleanField(default=False)),
                ("marketing_allowed", models.BooleanField(default=False)),
                ("third_party_allowed", models.BooleanField(default=False)),
                ("consent_given_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_consents",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "cookie_consents",
                "ordering": ["-consent_given_at"],
            },
        ),
        migrations.CreateModel(
            name="DataAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("INFORMATION", "Right to Information / Access (s.11)"),
                            ("CORRECTION", "Right to Correction / Erasure (s.12)"),
                            ("GRIEVANCE", "Right to Grievance Redressal (s.13)"),
                            ("NOMINATION", "Right to Nominate (s.14)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Request Received"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("APPEALED", "Under Appeal"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("due_date", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_format",
                    models.CharField(
                        choices=[
                            ("JSON", "JSON"),
                            ("CSV", "CSV"),
                            ("PDF", "PDF"),
                            ("EMAIL", "Email"),
                        ],
                        default="JSON",
                        max_length=20,
                    ),
                ),
                (
                    "response_file",
                    models.FileField(blank=True, null=True, upload_to="data_requests/"),
                ),
                ("response_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "data_access_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DPOGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grievance_type",
                    models.CharField(
                        choices=[
                            ("CONSENT_VIOLATION", "Consent Violation"),
                            ("DATA_BREACH", "Data Breach"),
                            ("DENIED_REQUEST", "Denied Data Request"),
                            ("PRIVACY_VIOLATION", "Privacy Violation"),
                            ("RETENTION_EXCESS", "Excessive Retention"),
                            ("UNAUTHORIZED_SHARING", "Unauthorized Data Sharing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("filed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("stage_1_due", models.DateTimeField()),
                ("stage_1_completed_at", models.DateTimeField(blank=True, null=True)),
                ("stage_2_due", models.DateTimeField()),
                ("stage_2_completed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FILED", "Filed"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated to Authority"),
                        ],
                        db_index=True,
                        default="FILED",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to_dpo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpo_grievances",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "dpo_grievances",
                "ordering": ["-filed_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_marketing", models.BooleanField(default=True)),
                ("sms_marketing", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("product_recommendations", models.BooleanField(default=True)),
                ("behavioral_tracking", models.BooleanField(default=False)),
                ("analytics_tracking", models.BooleanField(default=True)),
                ("profiling", models.BooleanField(default=False)),
                ("third_party_sharing", models.BooleanField(default=False)),
                ("do_not_sell", models.BooleanField(default=False)),
                ("limit_retention", models.BooleanField(default=False)),
                ("data_portability", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_preference",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "privacy_preferences",
            },
        ),
        migrations.CreateModel(
            name="CustomerConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing Communications"),
                            ("ANALYTICS", "Analytics & Tracking"),
                            ("COOKIES", "Cookie Tracking"),
                            ("PROFILING", "Behavioral Profiling"),
                            ("EMAIL", "Email Communications"),
                            ("SMS", "SMS Notifications"),
                            ("SURVEY", "Customer Surveys"),
                            ("LOYALTY", "Loyalty Program"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GIVEN", "Consent Given"),
                            ("WITHDRAWN", "Consent Withdrawn"),
                            ("EXPIRED", "Consent Expired"),
                            ("PENDING", "Pending Confirmation"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notice_version",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Version identifier of the privacy notice shown at consent time (e.g. 'v2.1').",
                        max_length=40,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        default="en",
                        help_text="ISO 639-1 language code of the notice presented (e.g. 'en', 'hi', 'ta').",
                        max_length=10,
                    ),
                ),
                (
                    "purpose_text",
                    models.TextField(help_text="Clear statement of purpose"),
                ),
                ("given_at", models.DateTimeField(blank=True, null=True)),
                ("given_by_ip", models.CharField(blank=True, max_length=45)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "given_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEB", "Website"),
                            ("MOBILE_APP", "Mobile App"),
                            ("PHONE", "Phone Call"),
                            ("IN_STORE", "In-Store"),
                            ("EMAIL", "Email Link"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_consents",
                "ordering": ["-given_at"],
                "unique_together": {("customer", "consent_type")},
            },
        ),
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data_categories", models.JSONField()),
                (
                    "access_reason",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("SUPPORT", "Customer Support"),
                            ("VERIFICATION", "KYC/Verification"),
                            ("PAYMENT", "Payment Processing"),
                            ("DELIVERY", "Delivery Fulfillment"),
                            ("RECOVERY", "Recovery/Collection"),
                            ("SYSTEM", "System Maintenance"),
                        ],
                        max_length=100,
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("duration_seconds", models.PositiveIntegerField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_access_logs",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "accessed_at"],
                        name="data_access_custome_90616d_idx",
                    ),
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="data_access_user_id_f81eee_idx",
                    ),
                ],
            },
        ),
    ]
