# Generated by Django 5.2.7 on 2026-07-10 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0001_initial_dpdp_models"),
        ("subscriptions", "0119_compliance_phase3_pay_rent_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataErasureGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("PARTIALLY_COMPLETED", "Partially Completed"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=25,
                    ),
                ),
                (
                    "request_reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "due_date",
                    models.DateField(
                        help_text="Statutory deadline: 30 days from request (DPDP 2023 s.12)."
                    ),
                ),
                (
                    "fields_to_erase",
                    models.JSONField(
                        default=list,
                        help_text="Data categories the customer wants erased.",
                    ),
                ),
                (
                    "fields_retained",
                    models.JSONField(
                        default=list,
                        help_text="Fields retained for legal obligation, with reasons.",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("audit_notes", models.TextField(blank=True, default="")),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_erasure_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="erasure_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_erasure_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_erasure_guards",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="BreachNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breach_reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("INVESTIGATING", "Investigating"),
                            ("NOTIFIED_BOARD", "Notified — Data Protection Board"),
                            ("NOTIFIED_PRINCIPALS", "Notified — Affected Principals"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="IDENTIFIED",
                        max_length=30,
                    ),
                ),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("description", models.TextField()),
                ("data_categories_affected", models.JSONField(default=list)),
                (
                    "estimated_principals_affected",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "board_notified_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "principals_notified_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("containment_measures", models.TextField(blank=True, default="")),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_breaches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "breach_notifications",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "status"],
                        name="breach_noti_severit_2dcdcb_idx",
                    ),
                    models.Index(
                        fields=["detected_at"], name="breach_noti_detecte_5cb31e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("data_category", models.CharField(db_index=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("AWAITING_APPROVAL", "Awaiting Approval"),
                            ("APPROVED", "Approved"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=25,
                    ),
                ),
                ("scheduled_purge_date", models.DateField(db_index=True)),
                ("records_targeted", models.PositiveIntegerField(default=0)),
                ("records_purged", models.PositiveIntegerField(default=0)),
                (
                    "retention_policy_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("execution_log", models.JSONField(blank=True, default=list)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purge_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_purge_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_retention_schedules",
                "ordering": ["-scheduled_purge_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_purge_date"],
                        name="data_retent_status_9c814c_idx",
                    )
                ],
            },
        ),
    ]
