# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("privacy", "0002_dpdp_erasure_breach_retention"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="cookieconsent",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cookie_consents",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerconsent",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="dataaccesslog",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="dataaccessrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_requests",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="dataerasureguard",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="erasure_requests",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="dpogrievance",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dpo_grievances",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="privacypreference",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privacy_preference",
                to="customers.customer",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
