# Generated by Django 5.2.7 on 2026-09-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_customer_customer_source"),
        ("privacy", "0003_alter_cookieconsent_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing Communications"),
                            ("ANALYTICS", "Analytics & Tracking"),
                            ("COOKIES", "Cookie Tracking"),
                            ("PROFILING", "Behavioral Profiling"),
                            ("EMAIL", "Email Communications"),
                            ("SMS", "SMS Notifications"),
                            ("SURVEY", "Customer Surveys"),
                            ("LOYALTY", "Loyalty Program"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Granted"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("purpose_text", models.TextField(blank=True)),
                ("notice_version", models.CharField(blank=True, max_length=32)),
                ("language_code", models.CharField(blank=True, max_length=8)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("source_ip", models.CharField(blank=True, max_length=45)),
                ("given_via", models.CharField(blank=True, max_length=32)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_events",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "consent_events",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["customer", "consent_type", "-occurred_at"],
                        name="consent_eve_custome_3771d9_idx",
                    ),
                    models.Index(
                        fields=["action", "-occurred_at"],
                        name="consent_eve_action_ad2465_idx",
                    ),
                ],
            },
        ),
    ]
