# Generated by Django 5.2.7 on 2026-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0004_consentevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="databreachlog",
            name="board_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databreachlog",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="databreachlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                db_index=True,
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="databreachlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("REPORTED", "Reported"),
                    ("INVESTIGATING", "Investigating"),
                    ("NOTIFIED_BOARD", "Data Protection Board notified"),
                    ("NOTIFIED_PRINCIPALS", "Data principals notified"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="REPORTED",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="databreachlog",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
