# Generated by Django 6.0.2 on 2026-02-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckyid',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='luckyid',
            unique_together=set(),
        ),
    ]
