# Generated by Django 6.0.2 on 2026-02-25 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_luckyid_options_alter_luckyid_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_customer_batch',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='max_slots',
        ),
        migrations.AlterField(
            model_name='commission',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_PROVIDED', 'Not Provided'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_type', 'EMI')), fields=('customer', 'batch'), name='unique_customer_batch_emi'),
        ),
    ]
