# Generated by Django 6.0.2 on 2026-02-26 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_unique_customer_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emi',
            index=models.Index(fields=['status'], name='emis_status_51b573_idx'),
        ),
        migrations.AddIndex(
            model_name='emi',
            index=models.Index(fields=['due_date'], name='emis_due_dat_fa734d_idx'),
        ),
        migrations.AddIndex(
            model_name='emi',
            index=models.Index(fields=['subscription'], name='emis_subscri_302ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['batch'], name='subscriptio_batch_i_3df372_idx'),
        ),
    ]
