# Generated by Django 6.0.2 on 2026-02-27 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_emi_emis_status_51b573_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emi',
            name='emis_subscri_302ecc_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialledger',
            name='subscriptio_emi_id_91e83b_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialledger',
            name='subscriptio_entry_t_43b583_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_referen_84b5bb_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('SUB_CREATED', 'Subscription Created'), ('EMI_PAID', 'EMI Paid'), ('DRAW_EXECUTED', 'Draw Executed'), ('EMI_WAIVED', 'EMI Waived'), ('COMMISSION_CREATED', 'Commission Created')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='draw_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpayout',
            name='commission_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.batch'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lucky_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.luckyid'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='partnerpayout',
            unique_together={('payout_batch', 'partner')},
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='batches_status_9b1a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_closed'], name='batches_is_clos_5e08b4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status'], name='customers_kyc_sta_38146a_idx'),
        ),
        migrations.AddIndex(
            model_name='luckyid',
            index=models.Index(fields=['batch', 'status'], name='lucky_ids_batch_i_6857d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code'], name='products_product_15b636_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer'], name='subscriptio_custome_4251b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('total_slots__gt', 0)), name='chk_batch_total_slots_positive'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('duration_months__gt', 0)), name='chk_batch_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('draw_day__gte', 1), ('draw_day__lte', 28)), name='chk_batch_draw_day_range'),
        ),
        migrations.AddConstraint(
            model_name='emi',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_emi_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='emi',
            constraint=models.CheckConstraint(condition=models.Q(('month_no__gt', 0)), name='chk_emi_month_positive'),
        ),
        migrations.AddConstraint(
            model_name='luckyid',
            constraint=models.CheckConstraint(condition=models.Q(('lucky_number__gte', 0), ('lucky_number__lte', 99)), name='chk_lucky_number_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_type', 'EMI')), fields=('lucky_id',), name='uq_subscription_per_lucky_id'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='chk_subscription_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_amount__gt', 0)), name='chk_subscription_monthly_positive'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('tenure_months__gt', 0)), name='chk_subscription_tenure_positive'),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs',
        ),
        migrations.AlterModelTable(
            name='commission',
            table='commissions',
        ),
        migrations.AlterModelTable(
            name='commissionpayoutbatch',
            table='commission_payout_batches',
        ),
        migrations.AlterModelTable(
            name='financialledger',
            table='financial_ledger',
        ),
        migrations.AlterModelTable(
            name='partnerpayout',
            table='partner_payouts',
        ),
    ]
