# Generated by Django 6.0.2 on 2026-03-02 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_remove_emi_emis_subscri_302ecc_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="batch",
            name="batches_is_clos_5e08b4_idx",
        ),
        migrations.AddField(
            model_name="financialledger",
            name="entry_direction",
            field=models.CharField(
                choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                default="CREDIT",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("OPEN", "Open"),
                    ("FULL", "Full"),
                    ("DRAW_IN_PROGRESS", "Draw In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lucky_id__isnull", False), ("plan_type", "EMI")),
                    models.Q(("plan_type", "EMI"), _negated=True),
                    _connector="OR",
                ),
                name="chk_lucky_id_required_for_emi",
            ),
        ),
        migrations.RemoveField(
            model_name="batch",
            name="is_closed",
        ),
    ]
