# Generated by Django 6.0.2 on 2026-03-06 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_remove_batch_batches_is_clos_5e08b4_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_customer_batch_emi",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="chk_lucky_id_required_for_emi",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("batch__isnull", False),
                        ("lucky_id__isnull", False),
                        ("plan_type", "EMI"),
                    ),
                    models.Q(("plan_type", "EMI"), _negated=True),
                    _connector="OR",
                ),
                name="chk_batch_and_lucky_required_for_emi",
            ),
        ),
    ]
