# Generated by Django 6.0.2 on 2026-03-06 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0007_remove_subscription_unique_customer_batch_emi_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="commission",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="commissionpayoutbatch",
            options={"ordering": ["-month", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="emi",
            options={"ordering": ["subscription_id", "month_no"]},
        ),
        migrations.AlterModelOptions(
            name="financialledger",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="luckydraw",
            options={"ordering": ["-draw_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="luckyid",
            options={"ordering": ["batch_id", "lucky_number"]},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-payment_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddField(
            model_name="emi",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SUB_CREATED", "Subscription Created"),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="is_settled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PAID", "Paid"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="commissionpayoutbatch",
            name="month",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="commissionpayoutbatch",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_commission_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("NOT_PROVIDED", "Not Provided"),
                    ("PENDING", "Pending Verification"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emi",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="emi",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("WAIVED", "Waived"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="entry_direction",
            field=models.CharField(
                choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="financialledger",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("EMI_PAYMENT", "EMI Payment"),
                    ("EMI_WAIVER", "EMI Waiver"),
                    ("PAYMENT_REVERSAL", "Payment Reversal"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                db_index=True,
                default="EMI_PAYMENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="luckydraw",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="luckydraw",
            name="is_revealed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="luckyid",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="luckyid",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ASSIGNED", "Assigned"),
                    ("WON", "Won"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayout",
            name="is_paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="partnerpayout",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions.customer",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("UPI", "UPI"), ("BANK", "Bank")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.batch",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="lucky_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.luckyid",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="monthly_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_type",
            field=models.CharField(
                choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.product",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("WON", "Won"),
                    ("COMPLETED", "Completed"),
                    ("DEFAULTED", "Defaulted"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="audit_logs_action__94af82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "object_id"], name="audit_logs_model_n_656046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["start_date"], name="batches_start_d_8bfe41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["batch_code"], name="batches_batch_c_5ac928_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["partner", "status"], name="commissions_partner_d10229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["is_settled"], name="commissions_is_sett_e9b528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionpayoutbatch",
            index=models.Index(fields=["month"], name="commission__month_cd1b43_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_name_25d5e3_idx"),
        ),
        migrations.AddIndex(
            model_name="emi",
            index=models.Index(
                fields=["subscription", "month_no"], name="emis_subscri_71f273_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(fields=["emi"], name="financial_l_emi_id_be37ba_idx"),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["entry_type"], name="financial_l_entry_t_1f32e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["entry_direction"], name="financial_l_entry_d_9f528f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["created_at"], name="financial_l_created_259daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["batch", "draw_month"], name="lucky_draws_batch_i_f5df98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["is_revealed"], name="lucky_draws_is_reve_ff5fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckyid",
            index=models.Index(
                fields=["batch", "lucky_number"], name="lucky_ids_batch_i_3a0e18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerpayout",
            index=models.Index(
                fields=["partner", "is_paid"], name="partner_pay_partner_14d32a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["method"], name="payments_method_aea958_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["subscription"], name="payments_subscri_9bd444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["customer"], name="payments_custome_8fefc3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["emi"], name="payments_emi_id_7a0603_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["plan_type"], name="subscriptio_plan_ty_7d17a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["partner"], name="subscriptio_partner_dc390e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["start_date"], name="subscriptio_start_d_75cedf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commission_percentage__gte", 0),
                    ("commission_percentage__lte", 100),
                ),
                name="chk_commission_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="commission",
            constraint=models.CheckConstraint(
                condition=models.Q(("commission_amount__gte", 0)),
                name="chk_commission_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionpayoutbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="chk_commission_payout_batch_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("draw_month__gt", 0)),
                name="chk_draw_month_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerpayout",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_commission__gte", 0)),
                name="chk_partner_payout_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gt", 0)),
                name="chk_product_base_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gte", 0)),
                name="chk_subscription_waived_non_negative",
            ),
        ),
    ]
