# Generated by Django 6.0.2 on 2026-03-09 19:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_phase8_additive_contract_extension_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("PARTIAL", "Partial"),
                            ("OVERPAID", "Overpaid"),
                            ("UNLINKED", "Unlinked"),
                            ("MISMATCH", "Mismatch"),
                            ("FLAGGED", "Flagged"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "variance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_reconciliations",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("AUTO_MATCHED", "Auto Matched"),
                            ("MANUAL_MATCHED", "Manual Matched"),
                            ("FLAGGED", "Flagged"),
                            ("NOTE_ADDED", "Note Added"),
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("STATUS_CHANGED", "Status Changed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=20)),
                ("new_status", models.CharField(blank=True, default="", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "payment_reconciliation_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_emi_enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_lease_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_rent_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["subcategory"], name="products_subcate_6be120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="products_is_acti_cb485f_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="matched_emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliations",
                to="subscriptions.emi",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation",
                to="subscriptions.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reconciliations_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliationevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reconciliation_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliationevent",
            name="reconciliation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="subscriptions.paymentreconciliation",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(fields=["status"], name="payment_rec_status_ccdb77_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["is_flagged"], name="payment_rec_is_flag_67b563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["is_locked"], name="payment_rec_is_lock_acce56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["created_at"], name="payment_rec_created_b22b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["payment"], name="payment_rec_payment_0128fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["matched_emi"], name="payment_rec_matched_0e74d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_amount__gte", 0)),
                name="chk_reconciliation_expected_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", 0)),
                name="chk_reconciliation_paid_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["event_type"], name="payment_rec_event_t_a67c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["created_at"], name="payment_rec_created_56304f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["reconciliation"], name="payment_rec_reconci_c05e6a_idx"
            ),
        ),
    ]
