# Generated by Django 6.0.2 on 2026-03-18 08:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0010_paymentreconciliation_paymentreconciliationevent_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commissionpayoutbatch",
            name="commission__month_cd1b43_idx",
        ),
        migrations.RemoveConstraint(
            model_name="commissionpayoutbatch",
            name="chk_commission_payout_batch_total_non_negative",
        ),
        migrations.AlterUniqueTogether(
            name="partnerpayout",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="partnerpayout",
            name="partner_pay_partner_14d32a_idx",
        ),
        migrations.RemoveConstraint(
            model_name="partnerpayout",
            name="chk_partner_payout_total_non_negative",
        ),
        migrations.AlterModelOptions(
            name="commission",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="commission",
            name="uq_partner_emi_commission",
        ),
        migrations.RemoveConstraint(
            model_name="commission",
            name="chk_commission_percentage_range",
        ),
        migrations.RemoveConstraint(
            model_name="commission",
            name="chk_commission_amount_non_negative",
        ),
        migrations.RemoveIndex(
            model_name="commission",
            name="commissions_is_sett_e9b528_idx",
        ),
        migrations.AddField(
            model_name="commission",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="commission",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission",
                to="subscriptions.payment",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="reversal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="commission",
            name="settlement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commission",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="commission",
            name="commission_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="commission",
            name="emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="subscriptions.emi",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SETTLED", "Settled"),
                    ("REVERSED", "Reversed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["subscription", "status"], name="commissions_subscri_3d3ef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commission",
            index=models.Index(
                fields=["payment"], name="commissions_payment_00b241_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="partnerpayout",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="partnerpayout",
            name="payout_batch",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="commission_percentage",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="is_settled",
        ),
        migrations.DeleteModel(
            name="CommissionPayoutBatch",
        ),
        migrations.DeleteModel(
            name="PartnerPayout",
        ),
    ]
