# Generated by Django 6.0.2 on 2026-03-22 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_customer_kyc_review_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["kyc_reviewed_at"], name="customers_kyc_rev_e3f8c4_idx"
            ),
        ),
    ]
