# Generated by Django 6.0.2 on 2026-03-23 17:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_customer_customers_kyc_rev_e3f8c4_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="luckydraw",
            name="revealed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="waived_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="waived_emi_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="waiver_scope",
            field=models.CharField(default="FUTURE_EMI_ONLY", max_length=40),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="winner_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winning_draws",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SUB_CREATED", "Subscription Created"),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["revealed_at"], name="lucky_draws_reveale_4fd4bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_emi_count__gte", 0)),
                name="chk_lucky_draw_waived_emi_count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gte", 0)),
                name="chk_lucky_draw_waived_amount_non_negative",
            ),
        ),
    ]
