# Generated by Django 6.0.2 on 2026-03-26 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0016_luckydraw_revealed_at_luckydraw_waived_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerCollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("UPI", "UPI"), ("BANK", "Bank")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_emi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_collection_requests_approved",
                        to="subscriptions.emi",
                    ),
                ),
                (
                    "approved_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_collection_request",
                        to="subscriptions.payment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_collection_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_collection_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_partner_collection_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_collection_requests",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "partner_collection_requests",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status"],
                        name="partner_col_partner_02b528_idx",
                    ),
                    models.Index(
                        fields=["subscription", "status"],
                        name="partner_col_subscri_fe82d6_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="partner_col_custome_07b038_idx",
                    ),
                    models.Index(
                        fields=["payment_date"], name="partner_col_payment_e7c095_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="partner_col_created_31b043_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="chk_partner_collection_request_amount_positive",
                    )
                ],
            },
        ),
    ]
