from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0019_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, default="", max_length=255)),
                ("business_code", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("primary_email", models.EmailField(blank=True, default="", max_length=254)),
                ("primary_phone", models.CharField(blank=True, default="", max_length=20)),
                ("alternate_phone", models.CharField(blank=True, default="", max_length=20)),
                ("website_url", models.URLField(blank=True, default="")),
                ("address_line_1", models.CharField(blank=True, default="", max_length=255)),
                ("address_line_2", models.CharField(blank=True, default="", max_length=255)),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(default="India", max_length=80)),
                ("gstin", models.CharField(blank=True, default="", max_length=32)),
                ("pan_number", models.CharField(blank=True, default="", max_length=32)),
                ("invoice_prefix", models.CharField(blank=True, default="", max_length=20)),
                ("receipt_prefix", models.CharField(blank=True, default="", max_length=20)),
                ("default_currency_code", models.CharField(default="INR", max_length=10)),
                ("timezone_name", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={"db_table": "business_profiles", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("branch_type", models.CharField(choices=[("HEAD_OFFICE", "Head Office"), ("BRANCH", "Branch"), ("WAREHOUSE", "Warehouse"), ("COLLECTION_POINT", "Collection Point")], db_index=True, default="BRANCH", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("manager_name", models.CharField(blank=True, default="", max_length=120)),
                ("address_line_1", models.CharField(blank=True, default="", max_length=255)),
                ("address_line_2", models.CharField(blank=True, default="", max_length=255)),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("postal_code", models.CharField(blank=True, default="", max_length=20)),
                ("country", models.CharField(default="India", max_length=80)),
                ("is_head_office", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("opened_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={"db_table": "branches", "ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="FinanceAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("account_type", models.CharField(choices=[("CASH", "Cash"), ("BANK", "Bank"), ("UPI", "UPI"), ("OTHER", "Other")], db_index=True, default="CASH", max_length=10)),
                ("account_holder_name", models.CharField(blank=True, default="", max_length=255)),
                ("provider_name", models.CharField(blank=True, default="", max_length=255)),
                ("bank_name", models.CharField(blank=True, default="", max_length=255)),
                ("branch_name", models.CharField(blank=True, default="", max_length=255)),
                ("masked_account_number", models.CharField(blank=True, default="", max_length=64)),
                ("ifsc_code", models.CharField(blank=True, default="", max_length=32)),
                ("upi_handle", models.CharField(blank=True, default="", max_length=128)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={"db_table": "finance_accounts", "ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="ChartAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("account_category", models.CharField(choices=[("ASSET", "Asset"), ("LIABILITY", "Liability"), ("INCOME", "Income"), ("EXPENSE", "Expense"), ("EQUITY", "Equity")], db_index=True, max_length=20)),
                ("account_group", models.CharField(choices=[("CASH", "Cash"), ("BANK", "Bank"), ("RECEIVABLE", "Receivable"), ("PAYABLE", "Payable"), ("REVENUE", "Revenue"), ("COMMISSION", "Commission"), ("WAIVER", "Waiver"), ("TAX", "Tax"), ("EXPENSE", "Expense"), ("SUSPENSE", "Suspense"), ("EQUITY", "Equity")], db_index=True, max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("allow_manual_posting", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="subscriptions.chartaccount")),
            ],
            options={"db_table": "chart_accounts", "ordering": ["display_order", "code", "id"]},
        ),
        migrations.CreateModel(
            name="CashDesk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("desk_type", models.CharField(choices=[("CASH", "Cash"), ("BANK", "Bank"), ("UPI", "UPI"), ("MIXED", "Mixed")], db_index=True, default="CASH", max_length=10)),
                ("allow_cash_collection", models.BooleanField(default=True)),
                ("allow_bank_collection", models.BooleanField(default=False)),
                ("allow_upi_collection", models.BooleanField(default=False)),
                ("receipt_printer_name", models.CharField(blank=True, default="", max_length=255)),
                ("device_label", models.CharField(blank=True, default="", max_length=255)),
                ("is_default_for_branch", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cash_desks", to="subscriptions.branch")),
                ("default_finance_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cash_desks", to="subscriptions.financeaccount")),
            ],
            options={"db_table": "cash_desks", "ordering": ["branch_id", "name", "id"]},
        ),
        migrations.CreateModel(
            name="StaffOperationalAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_scope", models.CharField(choices=[("ADMIN", "Admin"), ("CASHIER", "Cashier"), ("PARTNER", "Partner"), ("MANAGER", "Manager"), ("FINANCE_REVIEWER", "Finance Reviewer")], db_index=True, default="CASHIER", max_length=30)),
                ("can_collect_payments", models.BooleanField(default=False)),
                ("can_verify_payments", models.BooleanField(default=False)),
                ("can_manage_branches", models.BooleanField(default=False)),
                ("can_manage_cash_desks", models.BooleanField(default=False)),
                ("can_manage_finance_accounts", models.BooleanField(default=False)),
                ("can_manage_chart_accounts", models.BooleanField(default=False)),
                ("can_run_go_live_reset", models.BooleanField(default=False)),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="staff_operational_assignments", to="subscriptions.branch")),
                ("default_cash_desk", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="staff_operational_assignments", to="subscriptions.cashdesk")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="operational_assignments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "staff_operational_assignments", "ordering": ["-created_at", "-id"]},
        ),
    ]
