# Generated by Django 6.0.2 on 2026-03-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclead',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_public_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='contacted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='converted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_leads', to='subscriptions.product'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('SUB_CREATED', 'Subscription Created'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiclead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20),
        ),
    ]
