# Generated by Django 6.0.2 on 2026-03-29 17:35

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0023_publiclead_ops_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSupportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("category", models.CharField(choices=[("PAYMENT_ISSUE", "Payment Issue"), ("RECEIPT_ISSUE", "Receipt Issue"), ("EMI_ISSUE", "EMI Issue"), ("SUBSCRIPTION_QUERY", "Subscription Query"), ("DRAW_QUERY", "Draw Query"), ("OTHER", "Other")], db_index=True, default="OTHER", max_length=30)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under Review"), ("CLOSED", "Closed")], db_index=True, default="SUBMITTED", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="support_requests", to="subscriptions.customer")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="support_requests", to="subscriptions.payment")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="support_requests", to="subscriptions.subscription")),
            ],
            options={
                "db_table": "customer_support_requests",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["customer", "created_at"], name="customer_su_custome_c95449_idx"),
                    models.Index(fields=["status", "created_at"], name="customer_su_status_31a001_idx"),
                    models.Index(fields=["category", "created_at"], name="customer_su_categor_ec5b37_idx"),
                    models.Index(fields=["payment"], name="customer_su_payment_b110e2_idx"),
                    models.Index(fields=["subscription"], name="customer_su_subscri_ef15a6_idx"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    ("SUB_CREATED", "Subscription Created"),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
    ]
