# Generated by Django 6.0.2 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0027_customersupportrequest_resolution_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("USER_ACTIVATED", "User Activated"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("PARTNER_COMMISSION_SET", "Partner Commission Set"),
                    ("PARTNER_COMMISSION_UPDATED", "Partner Commission Updated"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("LEAD_CUSTOMER_LINKED", "Lead Customer Linked"),
                    ("LEAD_SUBSCRIPTION_LINKED", "Lead Subscription Linked"),
                    ("LEAD_CONVERTED", "Lead Converted"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    (
                        "SUPPORT_REQUEST_STATUS_UPDATED",
                        "Support Request Status Updated",
                    ),
                    ("SUPPORT_REQUEST_ASSIGNED", "Support Request Assigned"),
                    ("SUPPORT_REQUEST_NOTE_UPDATED", "Support Request Notes Updated"),
                    ("SUPPORT_REQUEST_RESOLVED", "Support Request Resolved"),
                    (
                        "SUPPORT_REQUEST_RESOLUTION_RECORDED",
                        "Support Request Resolution Recorded",
                    ),
                    ("SUB_CREATED", "Subscription Created"),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
    ]
