# Generated by Django 6.0.2 on 2026-03-30 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_PASSWORD_RESET', 'User Password Reset'), ('PARTNER_COMMISSION_SET', 'Partner Commission Set'), ('PARTNER_COMMISSION_UPDATED', 'Partner Commission Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('LEAD_CUSTOMER_LINKED', 'Lead Customer Linked'), ('LEAD_SUBSCRIPTION_LINKED', 'Lead Subscription Linked'), ('LEAD_CONVERTED', 'Lead Converted'), ('SUPPORT_REQUEST_CREATED', 'Support Request Created'), ('SUPPORT_REQUEST_STATUS_UPDATED', 'Support Request Status Updated'), ('SUPPORT_REQUEST_ASSIGNED', 'Support Request Assigned'), ('SUPPORT_REQUEST_NOTE_UPDATED', 'Support Request Notes Updated'), ('SUPPORT_REQUEST_RESOLVED', 'Support Request Resolved'), ('SUPPORT_REQUEST_RESOLUTION_RECORDED', 'Support Request Resolution Recorded'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERY_UPDATED', 'Delivery Updated'), ('DELIVERY_STATUS_CHANGED', 'Delivery Status Changed'), ('DELIVERY_DISPATCHED', 'Delivery Dispatched'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('DELIVERY_RETURN_REQUESTED', 'Delivery Return Requested'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('SUB_CREATED', 'Subscription Created'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('COMMISSION_PAYOUT_BATCH_CREATED', 'Commission Payout Batch Created'), ('COMMISSION_PAYOUT_BATCH_FINALIZED', 'Commission Payout Batch Finalized'), ('COMMISSION_PAYOUT_BATCH_CANCELLED', 'Commission Payout Batch Cancelled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('DISPATCHED', 'Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=30)),
                ('delivery_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('return_requested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_address_snapshot', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_subscription_deliveries', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='subscriptions.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_subscription_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_deliveries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_153f04_idx'), models.Index(fields=['status', 'created_at'], name='subscriptio_status_ca6375_idx'), models.Index(fields=['scheduled_date'], name='subscriptio_schedul_2bcabb_idx'), models.Index(fields=['delivered_at'], name='subscriptio_deliver_713088_idx'), models.Index(fields=['delivery_reference'], name='subscriptio_deliver_3c6791_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'SCHEDULED', 'DISPATCHED', 'OUT_FOR_DELIVERY', 'RETURN_REQUESTED'])), fields=('subscription',), name='uq_active_subscription_delivery_per_subscription')],
            },
        ),
    ]
