# Generated by Django 6.0.2 on 2026-04-07 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_PASSWORD_RESET', 'User Password Reset'), ('PARTNER_COMMISSION_SET', 'Partner Commission Set'), ('PARTNER_COMMISSION_UPDATED', 'Partner Commission Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('LEAD_CUSTOMER_LINKED', 'Lead Customer Linked'), ('LEAD_SUBSCRIPTION_LINKED', 'Lead Subscription Linked'), ('LEAD_CONVERTED', 'Lead Converted'), ('SUPPORT_REQUEST_CREATED', 'Support Request Created'), ('SUPPORT_REQUEST_STATUS_UPDATED', 'Support Request Status Updated'), ('SUPPORT_REQUEST_ASSIGNED', 'Support Request Assigned'), ('SUPPORT_REQUEST_NOTE_UPDATED', 'Support Request Notes Updated'), ('SUPPORT_REQUEST_RESOLVED', 'Support Request Resolved'), ('SUPPORT_REQUEST_RESOLUTION_RECORDED', 'Support Request Resolution Recorded'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERY_UPDATED', 'Delivery Updated'), ('DELIVERY_STATUS_CHANGED', 'Delivery Status Changed'), ('DELIVERY_DISPATCHED', 'Delivery Dispatched'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('DELIVERY_RETURN_REQUESTED', 'Delivery Return Requested'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('SUB_CREATED', 'Subscription Created'), ('SUBSCRIPTION_REQUEST_CREATED', 'Subscription Request Created'), ('SUBSCRIPTION_REQUEST_APPROVED', 'Subscription Request Approved'), ('SUBSCRIPTION_REQUEST_REJECTED', 'Subscription Request Rejected'), ('SUBSCRIPTION_REQUEST_CANCELLED', 'Subscription Request Cancelled'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('WINNER_STATE_SYNCED', 'Winner State Synced'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('COMMISSION_PAYOUT_BATCH_CREATED', 'Commission Payout Batch Created'), ('COMMISSION_PAYOUT_BATCH_FINALIZED', 'Commission Payout Batch Finalized'), ('COMMISSION_PAYOUT_BATCH_CANCELLED', 'Commission Payout Batch Cancelled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('requester_role_snapshot', models.CharField(db_index=True, max_length=20)),
                ('requested_customer_name', models.CharField(blank=True, default='', max_length=100)),
                ('requested_customer_phone', models.CharField(blank=True, default='', max_length=15)),
                ('requested_customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('requested_customer_address', models.TextField(blank=True, default='')),
                ('requested_customer_city', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_lucky_number', models.PositiveSmallIntegerField()),
                ('requested_tenure_months_snapshot', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('approved_subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_request', to='subscriptions.subscription')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='subscriptions.batch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='subscriptions.customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='subscriptions.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_requests',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['requester', 'status'], name='subscriptio_request_37d4c5_idx'), models.Index(fields=['partner', 'status'], name='subscriptio_partner_169d21_idx'), models.Index(fields=['customer', 'status'], name='subscriptio_custome_353a13_idx'), models.Index(fields=['product', 'batch'], name='subscriptio_product_ce98dd_idx'), models.Index(fields=['batch', 'status'], name='subscriptio_batch_i_5a2a23_idx'), models.Index(fields=['created_at'], name='subscriptio_created_2723b6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('preferred_lucky_number__gte', 0), ('preferred_lucky_number__lte', 99)), name='chk_subscription_request_lucky_number_range'), models.CheckConstraint(condition=models.Q(('requested_tenure_months_snapshot__gt', 0)), name='chk_subscription_request_tenure_positive')],
            },
        ),
    ]
