# Generated by Django 6.0.2 on 2026-04-09 04:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_product_catalog_master(apps, schema_editor):
    Product = apps.get_model("subscriptions", "Product")
    ProductCategoryMaster = apps.get_model("subscriptions", "ProductCategoryMaster")
    ProductSubcategoryMaster = apps.get_model("subscriptions", "ProductSubcategoryMaster")

    for product in Product.objects.all().iterator():
        category_name = (product.category or "").strip()
        subcategory_name = (product.subcategory or "").strip()
        update_fields: list[str] = []

        category_obj = None
        if category_name:
            category_obj = ProductCategoryMaster.objects.filter(name__iexact=category_name).first()
            if category_obj is None:
                category_obj = ProductCategoryMaster.objects.create(name=category_name, is_active=True)
            if product.category_master_id != category_obj.id:
                product.category_master_id = category_obj.id
                update_fields.append("category_master")

        if subcategory_name and category_obj is not None:
            subcategory_obj = ProductSubcategoryMaster.objects.filter(
                category=category_obj,
                name__iexact=subcategory_name,
            ).first()
            if subcategory_obj is None:
                subcategory_obj = ProductSubcategoryMaster.objects.create(
                    category=category_obj,
                    name=subcategory_name,
                    is_active=True,
                )
            if product.subcategory_master_id != subcategory_obj.id:
                product.subcategory_master_id = subcategory_obj.id
                update_fields.append("subcategory_master")

        if not (product.unit_of_measure or "").strip():
            product.unit_of_measure = "PCS"
            update_fields.append("unit_of_measure")

        if update_fields:
            product.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0033_alter_auditlog_action_type_subscriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='PCS', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'product_category_master',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='product_cat_is_acti_039988_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='subscriptions.productcategorymaster'),
        ),
        migrations.CreateModel(
            name='ProductSubcategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='subscriptions.productcategorymaster')),
            ],
            options={
                'db_table': 'product_subcategory_master',
                'ordering': ['category__name', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='subscriptions.productsubcategorymaster'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_of_measure'], name='products_unit_of_e0dcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='productsubcategorymaster',
            index=models.Index(fields=['category', 'is_active', 'name'], name='product_sub_categor_3b0a87_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsubcategorymaster',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uq_product_subcategory_per_category'),
        ),
        migrations.RunPython(seed_product_catalog_master, migrations.RunPython.noop),
    ]
