# Generated by Django 6.0.2 on 2026-04-09 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_product_unit_of_measure_master(apps, schema_editor):
    Product = apps.get_model("subscriptions", "Product")
    ProductUnitOfMeasureMaster = apps.get_model("subscriptions", "ProductUnitOfMeasureMaster")

    for product in Product.objects.all().iterator():
        unit_code = (product.unit_of_measure or "").strip().upper() or "PCS"
        unit_master = ProductUnitOfMeasureMaster.objects.filter(code__iexact=unit_code).first()
        if unit_master is None:
            unit_master = ProductUnitOfMeasureMaster.objects.create(
                code=unit_code,
                name=unit_code,
                is_active=True,
            )

        update_fields: list[str] = []
        if product.unit_of_measure != unit_code:
            product.unit_of_measure = unit_code
            update_fields.append("unit_of_measure")
        if product.unit_of_measure_master_id != unit_master.id:
            product.unit_of_measure_master_id = unit_master.id
            update_fields.append("unit_of_measure_master")

        if update_fields:
            product.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0034_product_sku_product_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_PASSWORD_RESET', 'User Password Reset'), ('PARTNER_COMMISSION_SET', 'Partner Commission Set'), ('PARTNER_COMMISSION_UPDATED', 'Partner Commission Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('LEAD_CUSTOMER_LINKED', 'Lead Customer Linked'), ('LEAD_SUBSCRIPTION_LINKED', 'Lead Subscription Linked'), ('LEAD_CONVERTED', 'Lead Converted'), ('SUPPORT_REQUEST_CREATED', 'Support Request Created'), ('SUPPORT_REQUEST_STATUS_UPDATED', 'Support Request Status Updated'), ('SUPPORT_REQUEST_ASSIGNED', 'Support Request Assigned'), ('SUPPORT_REQUEST_NOTE_UPDATED', 'Support Request Notes Updated'), ('SUPPORT_REQUEST_RESOLVED', 'Support Request Resolved'), ('SUPPORT_REQUEST_RESOLUTION_RECORDED', 'Support Request Resolution Recorded'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERY_UPDATED', 'Delivery Updated'), ('DELIVERY_STATUS_CHANGED', 'Delivery Status Changed'), ('DELIVERY_DISPATCHED', 'Delivery Dispatched'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('DELIVERY_RETURN_REQUESTED', 'Delivery Return Requested'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('SUB_CREATED', 'Subscription Created'), ('SUBSCRIPTION_REQUEST_CREATED', 'Subscription Request Created'), ('SUBSCRIPTION_REQUEST_APPROVED', 'Subscription Request Approved'), ('SUBSCRIPTION_REQUEST_REJECTED', 'Subscription Request Rejected'), ('SUBSCRIPTION_REQUEST_CANCELLED', 'Subscription Request Cancelled'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('WINNER_STATE_SYNCED', 'Winner State Synced'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('COMMISSION_PAYOUT_BATCH_CREATED', 'Commission Payout Batch Created'), ('COMMISSION_PAYOUT_BATCH_FINALIZED', 'Commission Payout Batch Finalized'), ('COMMISSION_PAYOUT_BATCH_CANCELLED', 'Commission Payout Batch Cancelled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PRODUCT_INVENTORY_PROFILE_PREPARED', 'Product Inventory Profile Prepared'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductUnitOfMeasureMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'product_unit_of_measure_master',
                'ordering': ['code', 'id'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='product_uni_is_acti_0aa9b9_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='subscriptions.productunitofmeasuremaster'),
        ),
        migrations.RunPython(seed_product_unit_of_measure_master, migrations.RunPython.noop),
    ]
