# Generated by Django 6.0.2 on 2026-04-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingbridgeposting_source_document_no_and_more'),
        ('subscriptions', '0036_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayoutbatch',
            name='finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_payout_batches', to='accounting.financeaccount'),
        ),
        migrations.AddField(
            model_name='commissionpayoutbatch',
            name='reference_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
