# Generated by Django 6.0.2 on 2026-04-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_directsaleline_billinginvoice_source_reference_and_more'),
        ('subscriptions', '0037_commissionpayoutbatch_finance_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclead',
            name='converted_direct_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_public_leads', to='billing.directsale'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_PASSWORD_RESET', 'User Password Reset'), ('PARTNER_COMMISSION_SET', 'Partner Commission Set'), ('PARTNER_COMMISSION_UPDATED', 'Partner Commission Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('LEAD_CUSTOMER_LINKED', 'Lead Customer Linked'), ('LEAD_SUBSCRIPTION_LINKED', 'Lead Subscription Linked'), ('LEAD_DIRECT_SALE_LINKED', 'Lead Direct Sale Linked'), ('LEAD_CONVERTED', 'Lead Converted'), ('CRM_PARTY_CREATED', 'CRM Party Created'), ('CRM_PARTY_LINKED', 'CRM Party Linked'), ('CRM_INTERACTION_CREATED', 'CRM Interaction Created'), ('CRM_INTERACTION_UPDATED', 'CRM Interaction Updated'), ('SUPPORT_REQUEST_CREATED', 'Support Request Created'), ('SUPPORT_REQUEST_STATUS_UPDATED', 'Support Request Status Updated'), ('SUPPORT_REQUEST_ASSIGNED', 'Support Request Assigned'), ('SUPPORT_REQUEST_NOTE_UPDATED', 'Support Request Notes Updated'), ('SUPPORT_REQUEST_RESOLVED', 'Support Request Resolved'), ('SUPPORT_REQUEST_RESOLUTION_RECORDED', 'Support Request Resolution Recorded'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERY_UPDATED', 'Delivery Updated'), ('DELIVERY_STATUS_CHANGED', 'Delivery Status Changed'), ('DELIVERY_DISPATCHED', 'Delivery Dispatched'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('DELIVERY_RETURN_REQUESTED', 'Delivery Return Requested'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('SUB_CREATED', 'Subscription Created'), ('SUBSCRIPTION_REQUEST_CREATED', 'Subscription Request Created'), ('SUBSCRIPTION_REQUEST_APPROVED', 'Subscription Request Approved'), ('SUBSCRIPTION_REQUEST_REJECTED', 'Subscription Request Rejected'), ('SUBSCRIPTION_REQUEST_CANCELLED', 'Subscription Request Cancelled'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('WINNER_STATE_SYNCED', 'Winner State Synced'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('COMMISSION_PAYOUT_BATCH_CREATED', 'Commission Payout Batch Created'), ('COMMISSION_PAYOUT_BATCH_FINALIZED', 'Commission Payout Batch Finalized'), ('COMMISSION_PAYOUT_BATCH_CANCELLED', 'Commission Payout Batch Cancelled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PRODUCT_INVENTORY_PROFILE_PREPARED', 'Product Inventory Profile Prepared'), ('INVENTORY_ITEM_CREATED', 'Inventory Item Created'), ('INVENTORY_ITEM_UPDATED', 'Inventory Item Updated'), ('STOCK_LOCATION_CREATED', 'Stock Location Created'), ('STOCK_LOCATION_UPDATED', 'Stock Location Updated'), ('STOCK_ADJUSTMENT_CREATED', 'Stock Adjustment Created'), ('STOCK_ADJUSTMENT_UPDATED', 'Stock Adjustment Updated'), ('STOCK_ADJUSTMENT_APPROVED', 'Stock Adjustment Approved'), ('STOCK_ADJUSTMENT_POSTED', 'Stock Adjustment Posted'), ('OPENING_STOCK_IMPORTED', 'Opening Stock Imported'), ('DELIVERY_INVENTORY_BRIDGE_SYNCED', 'Delivery Inventory Bridge Synced'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.AddIndex(
            model_name='publiclead',
            index=models.Index(fields=['converted_direct_sale', 'created_at'], name='public_lead_convert_4f1fd8_idx'),
        ),
    ]
