# Generated by Django 6.0.2 on 2026-04-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_control', '0001_initial'),
        ('subscriptions', '0040_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branch_control.cashcounter'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='branch_control.branch'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'payment_date'], name='payments_branch__c4c434_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cash_counter', 'payment_date'], name='payments_cash_co_bbfaea_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['branch', 'status'], name='subscriptio_branch__afa2df_idx'),
        ),
    ]
