# Generated by Django 6.0.2 on 2026-04-19 07:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0045_public_business_profile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leasesubscriptionprofile",
            new_name="lease_subsc_refund__cd4ef5_idx",
            old_name="lease_subsc_refund__0f0e9a_idx",
        ),
        migrations.RenameIndex(
            model_name="leasesubscriptionprofile",
            new_name="lease_subsc_return__74cc65_idx",
            old_name="lease_subsc_return__532f5f_idx",
        ),
        migrations.RenameIndex(
            model_name="rentsubscriptionprofile",
            new_name="rent_subscr_refund__f2ae5b_idx",
            old_name="rent_subscr_refund__c7fb72_idx",
        ),
        migrations.RenameIndex(
            model_name="rentsubscriptionprofile",
            new_name="rent_subscr_return__453fcc_idx",
            old_name="rent_subscr_return__5c6c3c_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptiondocument",
            new_name="subscriptio_subscri_b32760_idx",
            old_name="subscriptio_subscrip_c7f2d9_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptiondocument",
            new_name="subscriptio_verific_8f31ff_idx",
            old_name="subscriptio_verific_4ea3d4_idx",
        ),
        migrations.AlterField(
            model_name="leasesubscriptionprofile",
            name="security_deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("20.00")),
                    django.core.validators.MaxValueValidator(Decimal("30.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rentsubscriptionprofile",
            name="security_deposit_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("20.00")),
                    django.core.validators.MaxValueValidator(Decimal("30.00")),
                ],
            ),
        ),
    ]
