# Generated by Django 6.0.2 on 2026-04-22 07:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_chartofaccount_notes_financeaccount_notes"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        (
            "subscriptions",
            "0046_rename_lease_subsc_refund__0f0e9a_idx_lease_subsc_refund__cd4ef5_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unapplied_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("UPI", "UPI"), ("BANK", "Bank")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNAPPLIED", "Unapplied"),
                            ("PARTIALLY_APPLIED", "Partially Applied"),
                            ("FULLY_APPLIED", "Fully Applied"),
                        ],
                        db_index=True,
                        default="UNAPPLIED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("allocation_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "customer_advances",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvanceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("allocation_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "customer_advance_allocations",
                "ordering": ["-allocation_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_payments",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["finance_account", "payment_date"],
                name="payments_finance_5c7ddd_idx",
            ),
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advances",
                to="branch_control.branch",
            ),
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="cash_counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advances",
                to="branch_control.cashcounter",
            ),
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advances_collected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advances",
                to="subscriptions.customer",
            ),
        ),
        migrations.AddField(
            model_name="customeradvance",
            name="finance_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advances",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="advance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="subscriptions.customeradvance",
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advance_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advance_allocations",
                to="subscriptions.emi",
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advance_allocation",
                to="subscriptions.payment",
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advance_allocations",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["customer", "payment_date"],
                name="customer_ad_custome_da4bb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["finance_account", "payment_date"],
                name="customer_ad_finance_d9c06b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["status", "payment_date"], name="customer_ad_status_88b726_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_no__isnull", False)),
                fields=("reference_no",),
                name="uq_customer_advance_reference_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_customer_advance_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.CheckConstraint(
                condition=models.Q(("unapplied_amount__gte", 0)),
                name="chk_customer_advance_unapplied_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["advance", "allocation_date"],
                name="customer_ad_advance_fb3ef4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["subscription", "allocation_date"],
                name="customer_ad_subscri_83e84d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["emi", "allocation_date"], name="customer_ad_emi_id_1b76d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvanceallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_customer_advance_allocation_amount_positive",
            ),
        ),
    ]
