# Generated by Django 6.0.2 on 2026-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0047_customeradvance_customeradvanceallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiclead',
            name='follow_up_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='follow_up_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='follow_up_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='publiclead',
            name='intent',
            field=models.CharField(choices=[('GENERAL', 'General'), ('QUOTATION', 'Quotation'), ('ESTIMATE', 'Estimate'), ('DIRECT_SALE', 'Direct Sale'), ('SUBSCRIPTION', 'Subscription')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
