# Generated by Django 6.0.2 on 2026-04-25 19:26

import django.db.models.deletion
import django.utils.timezone
import subscriptions.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0048_publiclead_follow_up_note_publiclead_follow_up_on_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerKycDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("VOTER_ID", "Voter ID"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=subscriptions.models.customer_kyc_doc_upload_to
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "customer_kyc_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "commission_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Set true only when admin global referral commission feature is enabled.",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("commission_approved", models.BooleanField(default=False)),
                ("commission_approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer_referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by_partner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_created_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Human-readable short code for receipts/contracts (auto-generated if blank).",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "Public Self-Registration"),
                    ("ADMIN", "Admin Created"),
                    ("PARTNER", "Partner Created"),
                    ("IMPORT", "Imported"),
                ],
                db_index=True,
                default="ADMIN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=subscriptions.models.customer_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("PUBLIC_SITE_UPDATED", "Public Site Updated"),
                    ("USER_ACTIVATED", "User Activated"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("PARTNER_COMMISSION_SET", "Partner Commission Set"),
                    ("PARTNER_COMMISSION_UPDATED", "Partner Commission Updated"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("LEAD_CUSTOMER_LINKED", "Lead Customer Linked"),
                    ("LEAD_SUBSCRIPTION_LINKED", "Lead Subscription Linked"),
                    ("LEAD_DIRECT_SALE_LINKED", "Lead Direct Sale Linked"),
                    ("LEAD_CONVERTED", "Lead Converted"),
                    ("CRM_PARTY_CREATED", "CRM Party Created"),
                    ("CRM_PARTY_LINKED", "CRM Party Linked"),
                    ("CRM_INTERACTION_CREATED", "CRM Interaction Created"),
                    ("CRM_INTERACTION_UPDATED", "CRM Interaction Updated"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    (
                        "SUPPORT_REQUEST_STATUS_UPDATED",
                        "Support Request Status Updated",
                    ),
                    ("SUPPORT_REQUEST_ASSIGNED", "Support Request Assigned"),
                    ("SUPPORT_REQUEST_NOTE_UPDATED", "Support Request Notes Updated"),
                    ("SUPPORT_REQUEST_RESOLVED", "Support Request Resolved"),
                    (
                        "SUPPORT_REQUEST_RESOLUTION_RECORDED",
                        "Support Request Resolution Recorded",
                    ),
                    ("SERVICE_DESK_CASE_CREATED", "Service Desk Case Created"),
                    ("SERVICE_DESK_CASE_UPDATED", "Service Desk Case Updated"),
                    (
                        "SERVICE_DESK_CASE_STATUS_UPDATED",
                        "Service Desk Case Status Updated",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURN_REQUESTED",
                        "Service Desk Case Delivery Return Requested",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURNED",
                        "Service Desk Case Delivery Returned",
                    ),
                    (
                        "SERVICE_DESK_CASE_CREDIT_NOTE_POSTED",
                        "Service Desk Case Credit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_DEBIT_NOTE_POSTED",
                        "Service Desk Case Debit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_REPLACEMENT_LINKED",
                        "Service Desk Case Replacement Linked",
                    ),
                    ("DELIVERY_CREATED", "Delivery Created"),
                    ("DELIVERY_UPDATED", "Delivery Updated"),
                    ("DELIVERY_STATUS_CHANGED", "Delivery Status Changed"),
                    ("DELIVERY_DISPATCHED", "Delivery Dispatched"),
                    ("DELIVERY_COMPLETED", "Delivery Completed"),
                    ("DELIVERY_FAILED", "Delivery Failed"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                    ("DELIVERY_RETURN_REQUESTED", "Delivery Return Requested"),
                    ("DELIVERY_RETURNED", "Delivery Returned"),
                    ("SUB_CREATED", "Subscription Created"),
                    ("SUBSCRIPTION_REQUEST_CREATED", "Subscription Request Created"),
                    ("SUBSCRIPTION_REQUEST_APPROVED", "Subscription Request Approved"),
                    ("SUBSCRIPTION_REQUEST_REJECTED", "Subscription Request Rejected"),
                    (
                        "SUBSCRIPTION_REQUEST_CANCELLED",
                        "Subscription Request Cancelled",
                    ),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("WINNER_STATE_SYNCED", "Winner State Synced"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    (
                        "COMMISSION_PAYOUT_BATCH_CREATED",
                        "Commission Payout Batch Created",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_FINALIZED",
                        "Commission Payout Batch Finalized",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_CANCELLED",
                        "Commission Payout Batch Cancelled",
                    ),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    (
                        "PRODUCT_INVENTORY_PROFILE_PREPARED",
                        "Product Inventory Profile Prepared",
                    ),
                    ("INVENTORY_ITEM_CREATED", "Inventory Item Created"),
                    ("INVENTORY_ITEM_UPDATED", "Inventory Item Updated"),
                    ("STOCK_LOCATION_CREATED", "Stock Location Created"),
                    ("STOCK_LOCATION_UPDATED", "Stock Location Updated"),
                    ("STOCK_ADJUSTMENT_CREATED", "Stock Adjustment Created"),
                    ("STOCK_ADJUSTMENT_UPDATED", "Stock Adjustment Updated"),
                    ("STOCK_ADJUSTMENT_APPROVED", "Stock Adjustment Approved"),
                    ("STOCK_ADJUSTMENT_POSTED", "Stock Adjustment Posted"),
                    ("OPENING_STOCK_IMPORTED", "Opening Stock Imported"),
                    (
                        "DELIVERY_INVENTORY_BRIDGE_SYNCED",
                        "Delivery Inventory Bridge Synced",
                    ),
                    ("MANUFACTURING_BOM_CREATED", "Manufacturing BOM Created"),
                    ("MANUFACTURING_BOM_UPDATED", "Manufacturing BOM Updated"),
                    (
                        "MANUFACTURING_BOM_STATUS_UPDATED",
                        "Manufacturing BOM Status Updated",
                    ),
                    ("PRODUCTION_JOB_CREATED", "Production Job Created"),
                    ("PRODUCTION_JOB_UPDATED", "Production Job Updated"),
                    ("PRODUCTION_JOB_STATUS_UPDATED", "Production Job Status Updated"),
                    (
                        "PRODUCTION_MATERIAL_MOVEMENT_POSTED",
                        "Production Material Movement Posted",
                    ),
                    ("PRODUCTION_OUTPUT_POSTED", "Production Output Posted"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                    ("CUSTOMER_CREATED", "Customer Created"),
                    ("CUSTOMER_QUICK_CREATED", "Customer Quick-Created (No Email)"),
                    ("CUSTOMER_EMAIL_ADDED", "Customer Email Added"),
                    ("CUSTOMER_EMAIL_CHANGED", "Customer Email Changed"),
                    ("CUSTOMER_PHOTO_UPDATED", "Customer Profile Photo Updated"),
                    (
                        "CUSTOMER_KYC_DOCUMENT_SUBMITTED",
                        "Customer KYC Document Submitted",
                    ),
                    ("CUSTOMER_KYC_APPROVED", "Customer KYC Approved"),
                    ("CUSTOMER_KYC_REJECTED", "Customer KYC Rejected"),
                    ("CUSTOMER_REFERRAL_CREATED", "Customer Referral Created"),
                    (
                        "CUSTOMER_REFERRAL_COMMISSION_APPROVED",
                        "Customer Referral Commission Approved",
                    ),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("NOT_PROVIDED", "Not Provided"),
                    ("PENDING", "Pending Verification"),
                    ("SUBMITTED", "Submitted – Awaiting Review"),
                    ("VERIFIED", "Verified"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_source"], name="customers_custome_59bf06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_code"], name="customers_custome_fdedee_idx"
            ),
        ),
        migrations.AddField(
            model_name="customerkycdocument",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_documents",
                to="subscriptions.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerkycdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerkycdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerreferral",
            name="commission_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_referral_commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerreferral",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_customer_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerreferral",
            name="referred",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referred_by_referrals",
                to="subscriptions.customer",
            ),
        ),
        migrations.AddField(
            model_name="customerreferral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals_made",
                to="subscriptions.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["customer", "status"], name="customer_ky_custome_36b037_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["customer", "document_type"],
                name="customer_ky_custome_82503c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["status", "created_at"], name="customer_ky_status_7b80f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["referrer", "created_at"], name="customer_re_referre_9e55ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["referred"], name="customer_re_referre_2f1ff7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["commission_approved"], name="customer_re_commiss_d33c59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreferral",
            constraint=models.UniqueConstraint(
                fields=("referrer", "referred"), name="uq_customer_referral_pair"
            ),
        ),
    ]
