# Generated by Django 6.0.2 on 2026-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0049_customer_phase1_additive"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_direct_sale_enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("UPCOMING", "Upcoming"),
                    ("DISCONTINUED", "Discontinued"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondelivery",
            name="stock_blocked_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="subscriptiondelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SCHEDULED", "Scheduled"),
                    ("BLOCKED_STOCK_UNAVAILABLE", "Blocked – Stock Unavailable"),
                    ("DISPATCHED", "Dispatched"),
                    ("OUT_FOR_DELIVERY", "Out for Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("RETURN_REQUESTED", "Return Requested"),
                    ("RETURNED", "Returned"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
