# Generated by Django 6.0.2 on 2026-04-26 07:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0050_phase2_product_lifecycle_delivery_blocked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="terms_locked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="terms_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_subscription_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="document_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_subscription_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscriptiondocument",
            name="regeneration_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("PUBLIC_SITE_UPDATED", "Public Site Updated"),
                    ("USER_ACTIVATED", "User Activated"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("PARTNER_COMMISSION_SET", "Partner Commission Set"),
                    ("PARTNER_COMMISSION_UPDATED", "Partner Commission Updated"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("LEAD_CUSTOMER_LINKED", "Lead Customer Linked"),
                    ("LEAD_SUBSCRIPTION_LINKED", "Lead Subscription Linked"),
                    ("LEAD_DIRECT_SALE_LINKED", "Lead Direct Sale Linked"),
                    ("LEAD_CONVERTED", "Lead Converted"),
                    ("CRM_PARTY_CREATED", "CRM Party Created"),
                    ("CRM_PARTY_LINKED", "CRM Party Linked"),
                    ("CRM_INTERACTION_CREATED", "CRM Interaction Created"),
                    ("CRM_INTERACTION_UPDATED", "CRM Interaction Updated"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    (
                        "SUPPORT_REQUEST_STATUS_UPDATED",
                        "Support Request Status Updated",
                    ),
                    ("SUPPORT_REQUEST_ASSIGNED", "Support Request Assigned"),
                    ("SUPPORT_REQUEST_NOTE_UPDATED", "Support Request Notes Updated"),
                    ("SUPPORT_REQUEST_RESOLVED", "Support Request Resolved"),
                    (
                        "SUPPORT_REQUEST_RESOLUTION_RECORDED",
                        "Support Request Resolution Recorded",
                    ),
                    ("SERVICE_DESK_CASE_CREATED", "Service Desk Case Created"),
                    ("SERVICE_DESK_CASE_UPDATED", "Service Desk Case Updated"),
                    (
                        "SERVICE_DESK_CASE_STATUS_UPDATED",
                        "Service Desk Case Status Updated",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURN_REQUESTED",
                        "Service Desk Case Delivery Return Requested",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURNED",
                        "Service Desk Case Delivery Returned",
                    ),
                    (
                        "SERVICE_DESK_CASE_CREDIT_NOTE_POSTED",
                        "Service Desk Case Credit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_DEBIT_NOTE_POSTED",
                        "Service Desk Case Debit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_REPLACEMENT_LINKED",
                        "Service Desk Case Replacement Linked",
                    ),
                    ("DELIVERY_CREATED", "Delivery Created"),
                    ("DELIVERY_UPDATED", "Delivery Updated"),
                    ("DELIVERY_STATUS_CHANGED", "Delivery Status Changed"),
                    ("DELIVERY_DISPATCHED", "Delivery Dispatched"),
                    ("DELIVERY_COMPLETED", "Delivery Completed"),
                    ("DELIVERY_FAILED", "Delivery Failed"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                    ("DELIVERY_RETURN_REQUESTED", "Delivery Return Requested"),
                    ("DELIVERY_RETURNED", "Delivery Returned"),
                    ("SUB_CREATED", "Subscription Created"),
                    ("SUBSCRIPTION_REQUEST_CREATED", "Subscription Request Created"),
                    ("SUBSCRIPTION_REQUEST_APPROVED", "Subscription Request Approved"),
                    ("SUBSCRIPTION_REQUEST_REJECTED", "Subscription Request Rejected"),
                    (
                        "SUBSCRIPTION_REQUEST_CANCELLED",
                        "Subscription Request Cancelled",
                    ),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("WINNER_STATE_SYNCED", "Winner State Synced"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    (
                        "COMMISSION_PAYOUT_BATCH_CREATED",
                        "Commission Payout Batch Created",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_FINALIZED",
                        "Commission Payout Batch Finalized",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_CANCELLED",
                        "Commission Payout Batch Cancelled",
                    ),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    (
                        "PRODUCT_INVENTORY_PROFILE_PREPARED",
                        "Product Inventory Profile Prepared",
                    ),
                    ("INVENTORY_ITEM_CREATED", "Inventory Item Created"),
                    ("INVENTORY_ITEM_UPDATED", "Inventory Item Updated"),
                    ("STOCK_LOCATION_CREATED", "Stock Location Created"),
                    ("STOCK_LOCATION_UPDATED", "Stock Location Updated"),
                    ("STOCK_ADJUSTMENT_CREATED", "Stock Adjustment Created"),
                    ("STOCK_ADJUSTMENT_UPDATED", "Stock Adjustment Updated"),
                    ("STOCK_ADJUSTMENT_APPROVED", "Stock Adjustment Approved"),
                    ("STOCK_ADJUSTMENT_POSTED", "Stock Adjustment Posted"),
                    ("OPENING_STOCK_IMPORTED", "Opening Stock Imported"),
                    (
                        "DELIVERY_INVENTORY_BRIDGE_SYNCED",
                        "Delivery Inventory Bridge Synced",
                    ),
                    ("MANUFACTURING_BOM_CREATED", "Manufacturing BOM Created"),
                    ("MANUFACTURING_BOM_UPDATED", "Manufacturing BOM Updated"),
                    (
                        "MANUFACTURING_BOM_STATUS_UPDATED",
                        "Manufacturing BOM Status Updated",
                    ),
                    ("PRODUCTION_JOB_CREATED", "Production Job Created"),
                    ("PRODUCTION_JOB_UPDATED", "Production Job Updated"),
                    ("PRODUCTION_JOB_STATUS_UPDATED", "Production Job Status Updated"),
                    (
                        "PRODUCTION_MATERIAL_MOVEMENT_POSTED",
                        "Production Material Movement Posted",
                    ),
                    ("PRODUCTION_OUTPUT_POSTED", "Production Output Posted"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                    ("CUSTOMER_CREATED", "Customer Created"),
                    ("CUSTOMER_QUICK_CREATED", "Customer Quick-Created (No Email)"),
                    ("CUSTOMER_EMAIL_ADDED", "Customer Email Added"),
                    ("CUSTOMER_EMAIL_CHANGED", "Customer Email Changed"),
                    ("CUSTOMER_PHOTO_UPDATED", "Customer Profile Photo Updated"),
                    (
                        "CUSTOMER_KYC_DOCUMENT_SUBMITTED",
                        "Customer KYC Document Submitted",
                    ),
                    ("CUSTOMER_KYC_APPROVED", "Customer KYC Approved"),
                    ("CUSTOMER_KYC_REJECTED", "Customer KYC Rejected"),
                    ("CUSTOMER_REFERRAL_CREATED", "Customer Referral Created"),
                    (
                        "CUSTOMER_REFERRAL_COMMISSION_APPROVED",
                        "Customer Referral Commission Approved",
                    ),
                    ("CONTRACT_NUMBERED", "Contract Number Assigned"),
                    ("CONTRACT_TERMS_LOCKED", "Contract Financial Terms Locked"),
                    ("CONTRACT_APPROVED", "Contract Approved"),
                    ("CONTRACT_ACTIVATED", "Contract Activated"),
                    ("CONTRACT_CANCELLED", "Contract Cancelled"),
                    ("CONTRACT_CLOSED", "Contract Closed"),
                    ("CONTRACT_AMENDMENT_REQUESTED", "Contract Amendment Requested"),
                    ("CONTRACT_AMENDMENT_APPROVED", "Contract Amendment Approved"),
                    ("CONTRACT_AMENDMENT_REJECTED", "Contract Amendment Rejected"),
                    ("CONTRACT_AMENDMENT_APPLIED", "Contract Amendment Applied"),
                    ("CONTRACT_PRODUCT_HANDED_OVER", "Product Handed Over"),
                    ("CONTRACT_PRODUCT_RETURNED", "Product Returned"),
                    ("CONTRACT_RETURN_INSPECTION_STARTED", "Return Inspection Started"),
                    (
                        "CONTRACT_RETURN_INSPECTION_COMPLETED",
                        "Return Inspection Completed",
                    ),
                    ("CONTRACT_DEPOSIT_REFUND_APPROVED", "Deposit Refund Approved"),
                    ("CONTRACT_DOCUMENT_GENERATED", "Contract Document Generated"),
                    ("CONTRACT_DOCUMENT_REGENERATED", "Contract Document Regenerated"),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REQUESTED", "Requested"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("WON", "Won"),
                    ("COMPLETED", "Completed"),
                    ("DEFAULTED", "Defaulted"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("DELIVERY_PENDING", "Delivery Pending"),
                    ("HANDED_OVER", "Handed Over"),
                    ("RETURN_PENDING", "Return Pending"),
                    ("RETURNED", "Returned"),
                    ("CANCELLED", "Cancelled"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_KYC_ID", "Customer KYC ID"),
                    ("CUSTOMER_SIGNATURE", "Customer Signature"),
                    ("ADMIN_SIGNATURE", "Admin / Company Signature"),
                    ("RENT_CONTRACT_PDF", "Rent Contract PDF"),
                    ("LEASE_CONTRACT_PDF", "Lease Contract PDF"),
                    ("ADVANCE_EMI_CONTRACT_PDF", "Advance EMI Contract PDF"),
                    ("PAYMENT_RECEIPT_PDF", "Payment Receipt PDF"),
                    ("DELIVERY_HANDOVER_NOTE", "Delivery / Handover Note"),
                    ("RETURN_INSPECTION_REPORT", "Return Inspection Report"),
                    ("AMENDMENT_RECORD", "Contract Amendment Record"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("TENURE_EXTENSION", "Tenure Extension"),
                            ("PRODUCT_UPGRADE", "Product Upgrade"),
                            ("ADDRESS_CHANGE", "Address Change"),
                            ("SCHEDULE_CORRECTION", "Schedule Correction"),
                            ("DEPOSIT_ADJUSTMENT", "Deposit Adjustment"),
                            ("LEGAL_DOCUMENT_CORRECTION", "Legal Document Correction"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("new_values", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_contract_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_contract_amendments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "contract_amendments",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "status"],
                        name="contract_am_subscri_b9ee13_idx",
                    ),
                    models.Index(
                        fields=["amendment_type", "status"],
                        name="contract_am_amendme_c02dce_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_HANDOVER", "Pending Handover"),
                            ("WITH_CUSTOMER", "With Customer"),
                            ("RETURN_DUE", "Return Due"),
                            ("RETURNED", "Returned"),
                            ("UNDER_INSPECTION", "Under Inspection"),
                            ("MAINTENANCE", "Maintenance"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PENDING_HANDOVER",
                        max_length=25,
                    ),
                ),
                (
                    "handover_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "expected_return_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "actual_return_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("handover_condition_notes", models.TextField(blank=True, default="")),
                ("return_condition_notes", models.TextField(blank=True, default="")),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_possessions",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "handed_over_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handed_over_possessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="possessions",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "returned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_possession_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_possession",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "product_possessions",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "expected_return_date"],
                        name="product_pos_status_d5b8a4_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="product_pos_custome_6f49c5_idx",
                    ),
                    models.Index(
                        fields=["product", "status"],
                        name="product_pos_product_b48bed_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseReturnInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Inspection"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("APPROVED", "Inspection Approved"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELLABLE", "Sellable – Return to stock"),
                            ("MAINTENANCE_REQUIRED", "Maintenance Required"),
                            ("DAMAGED", "Damaged – Damage recovery"),
                            ("SCRAPPED", "Scrapped – Write off"),
                        ],
                        db_index=True,
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "condition_recorded",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        db_index=True,
                        default="NOT_ASSESSED",
                        max_length=30,
                    ),
                ),
                ("damage_notes", models.TextField(blank=True, default="")),
                (
                    "damage_deduction_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deposit_refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("deposit_refund_approved", models.BooleanField(default=False)),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("stock_routing_notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_return_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conducted_return_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_inspection",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "rent_lease_return_inspections",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "outcome"],
                        name="rent_lease__status_999cb0_idx",
                    ),
                    models.Index(
                        fields=["subscription", "status"],
                        name="rent_lease__subscri_07d329_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("damage_deduction_amount__gte", Decimal("0.00"))
                        ),
                        name="chk_return_inspection_deduction_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deposit_refund_amount__gte", Decimal("0.00"))
                        ),
                        name="chk_return_inspection_refund_non_negative",
                    ),
                ],
            },
        ),
    ]
