# Generated by Django 6.0.2 on 2026-04-26 13:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0052_alter_auditlog_action_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptiondocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER_KYC_ID", "Customer KYC ID"),
                    ("CUSTOMER_SIGNATURE", "Customer Signature"),
                    ("ADMIN_SIGNATURE", "Admin / Company Signature"),
                    ("RENT_CONTRACT_PDF", "Rent Contract PDF"),
                    ("LEASE_CONTRACT_PDF", "Lease Contract PDF"),
                    ("ADVANCE_EMI_CONTRACT_PDF", "Advance EMI Contract PDF"),
                    ("PAYMENT_RECEIPT_PDF", "Payment Receipt PDF"),
                    ("DELIVERY_HANDOVER_NOTE", "Delivery / Handover Note"),
                    ("RETURN_INSPECTION_REPORT", "Return Inspection Report"),
                    ("AMENDMENT_RECORD", "Contract Amendment Record"),
                    ("DIRECT_SALE_INVOICE_PDF", "Direct Sale Invoice PDF"),
                    ("SECURITY_DEPOSIT_RECEIPT_PDF", "Security Deposit Receipt PDF"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="RentLeaseBillingDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("RENT_MONTHLY", "Rent Monthly Demand"),
                            ("LEASE_MONTHLY", "Lease Monthly Demand"),
                            ("SECURITY_DEPOSIT", "Security Deposit Demand"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "billing_period_end",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("due_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "held_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refundable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deducted_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reference_key",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rent_lease_demands",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "rent_lease_billing_demands",
                "ordering": ["-due_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseDepositTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEMAND_CREATED", "Demand Created"),
                            ("COLLECTED", "Deposit Collected"),
                            ("REFUND_APPROVED", "Refund Approved"),
                            ("REFUNDED", "Refunded"),
                            ("DEDUCTION", "Deduction"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_deposit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_transactions",
                        to="subscriptions.rentleasebillingdemand",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_transactions",
                        to="subscriptions.rentleasereturninspection",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_deposit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_transactions",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "rent_lease_deposit_transactions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["subscription", "demand_type"],
                name="rent_lease__subscri_b99e1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["status", "due_date"], name="rent_lease__status_5728ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["billing_period_start", "billing_period_end"],
                name="rent_lease__billing_88f25d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("collected_amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_collected_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("deducted_amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_deducted_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["subscription", "transaction_type"],
                name="rent_lease__subscri_13035a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["created_at"], name="rent_lease__created_5f59ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="chk_deposit_transaction_amount_non_negative",
            ),
        ),
    ]
