# Generated by Django 6.0.2 on 2026-04-29 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billinginvoice_branch_directsale_branch_and_more'),
        ('subscriptions', '0053_alter_subscriptiondocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scope_key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'contract_reference_sequences',
                'ordering': ['scope_key'],
            },
        ),
        migrations.CreateModel(
            name='ContractReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_no', models.CharField(db_index=True, max_length=140, unique=True)),
                ('display_reference', models.CharField(db_index=True, max_length=180)),
                ('contract_type', models.CharField(choices=[('ADVANCE_EMI', 'Advance EMI'), ('RENT', 'Rent'), ('LEASE', 'Lease'), ('DIRECT_SALE', 'Direct Sale')], db_index=True, max_length=20)),
                ('phone_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('customer_name_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('kyc_reference_snapshot', models.CharField(blank=True, db_index=True, help_text='Masked-safe KYC/customer reference snapshot only; never store raw KYC document values here.', max_length=120, null=True)),
                ('product_summary_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('batch_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('lucky_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('partner_snapshot', models.CharField(blank=True, default='', max_length=180)),
                ('source_created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='subscriptions.customer')),
                ('direct_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='billing.directsale')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='billing.billinginvoice')),
                ('lease_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='subscriptions.leasesubscriptionprofile')),
                ('rent_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='subscriptions.rentsubscriptionprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_references', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'contract_references',
                'ordering': ['-source_created_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['contract_type'], name='contract_re_contrac_2e8cac_idx'), models.Index(fields=['customer'], name='contract_re_custome_2cb10f_idx'), models.Index(fields=['phone_snapshot'], name='contract_re_phone_s_fc3a35_idx'), models.Index(fields=['customer_name_snapshot'], name='contract_re_custome_3bef32_idx'), models.Index(fields=['kyc_reference_snapshot'], name='contract_re_kyc_ref_96c8f0_idx'), models.Index(fields=['batch_snapshot'], name='contract_re_batch_s_c29929_idx'), models.Index(fields=['lucky_id_snapshot'], name='contract_re_lucky_i_67f6f0_idx'), models.Index(fields=['source_created_at'], name='contract_re_source__a6852f_idx')],
            },
        ),
    ]
