# Generated by Django 6.0.2 on 2026-04-29 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0054_contractreferencesequence_contractreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedCollectionIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('key', models.CharField(max_length=160)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=16)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_collection_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_collection_idempotency',
                'indexes': [models.Index(fields=['user', 'status'], name='unified_col_user_id_446e3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_unified_collection_idem_user_key')],
            },
        ),
    ]
