# Generated by Django 6.0.2 on 2026-04-30 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0055_unified_collection_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when batch draw eligibility is frozen (LOCKED or beyond).', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('FULL', 'Full'), ('READY_TO_LOCK', 'Ready To Lock'), ('LOCKED', 'Locked'), ('DRAW_IN_PROGRESS', 'Draw In Progress'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_COMPLETED', 'Draw Completed'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='DrawCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('snapshot_version', models.PositiveIntegerField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('public_commit_hash', models.CharField(max_length=64)),
                ('seed_commitment', models.CharField(max_length=64)),
                ('committed_at', models.DateTimeField(db_index=True)),
                ('algorithm_version', models.CharField(default='pass7-v1', max_length=32)),
                ('status', models.CharField(choices=[('COMMITTED', 'Committed')], default='COMMITTED', max_length=20)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draw_commit', to='subscriptions.batch')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_draw_commits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'draw_commits',
            },
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='draw_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lucky_draws', to='subscriptions.drawcommit'),
        ),
        migrations.CreateModel(
            name='DrawEligibilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('snapshot_version', models.PositiveIntegerField(db_index=True)),
                ('sort_order', models.PositiveIntegerField()),
                ('contract_reference', models.CharField(blank=True, default='', max_length=64)),
                ('emi_schedule_summary', models.JSONField(default=dict)),
                ('row_hash', models.CharField(max_length=128)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_eligibility_snapshots', to='subscriptions.batch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_eligibility_snapshots', to='subscriptions.customer')),
                ('lucky_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_eligibility_snapshots', to='subscriptions.luckyid')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_eligibility_snapshots', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_eligibility_snapshots', to='subscriptions.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_eligibility_snapshots', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'draw_eligibility_snapshots',
                'ordering': ['snapshot_version', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['batch', 'snapshot_version'], name='draw_eligib_batch_i_bbbd48_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'snapshot_version', 'subscription'), name='uq_draw_eligibility_batch_version_subscription')],
            },
        ),
    ]
