# Generated by Django 6.0.2 on 2026-04-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0057_businesseventlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_event_t_ba4439_idx",
            old_name="business_eve_event_t_d43f6b_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_custome_ef06e3_idx",
            old_name="business_eve_custome_95bdf8_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_subscri_de7999_idx",
            old_name="business_eve_subscri_f4ea7f_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_payment_8bb53b_idx",
            old_name="business_eve_payment_8466f8_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_contrac_682257_idx",
            old_name="business_eve_contrac_f7f695_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_batch_i_681eef_idx",
            old_name="business_eve_batch_i_d012f2_idx",
        ),
        migrations.RenameIndex(
            model_name="businesseventlog",
            new_name="business_ev_lucky_i_249ce0_idx",
            old_name="business_eve_lucky_i_30b153_idx",
        ),
    ]
