# Generated by Django 5.2.7 on 2026-05-05 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0061_dry_run_validation_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OperationalCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('DIRECT_SALE', 'Direct Sale'), ('BILLING_INVOICE', 'Billing Invoice'), ('BILLING_RECEIPT', 'Billing Receipt'), ('SUBSCRIPTION', 'Subscription'), ('EMI_PAYMENT', 'EMI Payment'), ('DELIVERY', 'Delivery'), ('STOCK_REQUIREMENT', 'Stock Requirement'), ('PURCHASE_INVOICE', 'Purchase Invoice'), ('RENT_CONTRACT', 'Rent Contract'), ('LEASE_CONTRACT', 'Lease Contract'), ('RENT_LEASE_INVOICE', 'Rent/Lease Invoice'), ('PAYOUT_BATCH', 'Payout Batch'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_before', models.CharField(blank=True, default='', max_length=40)),
                ('status_after', models.CharField(blank=True, default='', max_length=40)),
                ('cancellation_type', models.CharField(choices=[('CANCEL_DRAFT', 'Cancel Draft'), ('VOID_UNPOSTED', 'Void Unposted'), ('CANCEL_WITH_REVERSAL', 'Cancel With Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('DELIVERY_CANCEL', 'Delivery Cancel'), ('STOCK_REQUIREMENT_CANCEL', 'Stock Requirement Cancel'), ('CONTRACT_TERMINATION', 'Contract Termination')], db_index=True, max_length=40)),
                ('reason', models.TextField()),
                ('internal_note', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reversal_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('audit_log_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_operational_cancellations', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_operational_records', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_cancellations', to='subscriptions.customer')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_operational_cancellations', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_operational_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_cancellations',
                'ordering': ['-cancelled_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'cancelled_at'], name='operational_source__f447aa_idx'), models.Index(fields=['customer', 'cancelled_at'], name='operational_custome_5c75aa_idx'), models.Index(fields=['cancelled_by', 'cancelled_at'], name='operational_cancell_69e4cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id'), name='uq_operational_cancellation_source')],
            },
        ),
    ]
