# Generated by Django 5.2.7 on 2026-05-06 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0062_alter_emi_status_operationalcancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('MANUAL', 'Manual'), ('GOOGLE_BUSINESS', 'Google Business Profile'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('JUSTDIAL', 'Justdial'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_configured', models.BooleanField(db_index=True, default=False)),
                ('configuration_hint', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'brand_data_sources',
                'ordering': ['provider', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('LOGO', 'Logo'), ('STOREFRONT', 'Storefront'), ('GALLERY', 'Gallery'), ('VIDEO', 'Video'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('media_url', models.URLField()),
                ('source_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'business_media_assets',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('YOUTUBE', 'YouTube'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp'), ('JUSTDIAL', 'Justdial'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'brand_social_links',
                'ordering': ['platform', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('PUBLIC_SITE_UPDATED', 'Public Site Updated'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_PASSWORD_RESET', 'User Password Reset'), ('PARTNER_COMMISSION_SET', 'Partner Commission Set'), ('PARTNER_COMMISSION_UPDATED', 'Partner Commission Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_STATUS_UPDATED', 'Lead Status Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_NOTE_UPDATED', 'Lead Notes Updated'), ('LEAD_CUSTOMER_LINKED', 'Lead Customer Linked'), ('LEAD_SUBSCRIPTION_LINKED', 'Lead Subscription Linked'), ('LEAD_DIRECT_SALE_LINKED', 'Lead Direct Sale Linked'), ('LEAD_CONVERTED', 'Lead Converted'), ('CRM_PARTY_CREATED', 'CRM Party Created'), ('CRM_PARTY_LINKED', 'CRM Party Linked'), ('CRM_INTERACTION_CREATED', 'CRM Interaction Created'), ('CRM_INTERACTION_UPDATED', 'CRM Interaction Updated'), ('SUPPORT_REQUEST_CREATED', 'Support Request Created'), ('SUPPORT_REQUEST_STATUS_UPDATED', 'Support Request Status Updated'), ('SUPPORT_REQUEST_ASSIGNED', 'Support Request Assigned'), ('SUPPORT_REQUEST_NOTE_UPDATED', 'Support Request Notes Updated'), ('SUPPORT_REQUEST_RESOLVED', 'Support Request Resolved'), ('SUPPORT_REQUEST_RESOLUTION_RECORDED', 'Support Request Resolution Recorded'), ('SERVICE_DESK_CASE_CREATED', 'Service Desk Case Created'), ('SERVICE_DESK_CASE_UPDATED', 'Service Desk Case Updated'), ('SERVICE_DESK_CASE_STATUS_UPDATED', 'Service Desk Case Status Updated'), ('SERVICE_DESK_CASE_DELIVERY_RETURN_REQUESTED', 'Service Desk Case Delivery Return Requested'), ('SERVICE_DESK_CASE_DELIVERY_RETURNED', 'Service Desk Case Delivery Returned'), ('SERVICE_DESK_CASE_CREDIT_NOTE_POSTED', 'Service Desk Case Credit Note Posted'), ('SERVICE_DESK_CASE_DEBIT_NOTE_POSTED', 'Service Desk Case Debit Note Posted'), ('SERVICE_DESK_CASE_REPLACEMENT_LINKED', 'Service Desk Case Replacement Linked'), ('DELIVERY_CREATED', 'Delivery Created'), ('DELIVERY_UPDATED', 'Delivery Updated'), ('DELIVERY_STATUS_CHANGED', 'Delivery Status Changed'), ('DELIVERY_DISPATCHED', 'Delivery Dispatched'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_CANCELLED', 'Delivery Cancelled'), ('DELIVERY_RETURN_REQUESTED', 'Delivery Return Requested'), ('DELIVERY_RETURNED', 'Delivery Returned'), ('SUB_CREATED', 'Subscription Created'), ('SUBSCRIPTION_REQUEST_CREATED', 'Subscription Request Created'), ('SUBSCRIPTION_REQUEST_APPROVED', 'Subscription Request Approved'), ('SUBSCRIPTION_REQUEST_REJECTED', 'Subscription Request Rejected'), ('SUBSCRIPTION_REQUEST_CANCELLED', 'Subscription Request Cancelled'), ('EMI_PAID', 'EMI Paid'), ('EMI_WAIVED', 'EMI Waived'), ('DRAW_EXECUTED', 'Draw Executed'), ('DRAW_COMMITTED', 'Draw Committed'), ('DRAW_REVEALED', 'Draw Revealed'), ('DRAW_CERTIFICATE_PUBLISHED', 'Draw Certificate Published'), ('DRAW_PUBLIC_VERIFIED', 'Public Draw Verification Generated'), ('DRAW_PUBLIC_RESULT_PUBLISHED', 'Public Draw Result Published'), ('WINNER_WAIVER_APPLIED', 'Winner Waiver Applied'), ('WINNER_STATE_SYNCED', 'Winner State Synced'), ('COMMISSION_CREATED', 'Commission Created'), ('COMMISSION_SETTLED', 'Commission Settled'), ('COMMISSION_PAYOUT_BATCH_CREATED', 'Commission Payout Batch Created'), ('COMMISSION_PAYOUT_BATCH_FINALIZED', 'Commission Payout Batch Finalized'), ('COMMISSION_PAYOUT_BATCH_CANCELLED', 'Commission Payout Batch Cancelled'), ('PAYMENT_RECONCILED', 'Payment Reconciled'), ('PAYMENT_FLAGGED', 'Payment Flagged'), ('PRODUCT_INVENTORY_PROFILE_PREPARED', 'Product Inventory Profile Prepared'), ('INVENTORY_ITEM_CREATED', 'Inventory Item Created'), ('INVENTORY_ITEM_UPDATED', 'Inventory Item Updated'), ('STOCK_LOCATION_CREATED', 'Stock Location Created'), ('STOCK_LOCATION_UPDATED', 'Stock Location Updated'), ('STOCK_ADJUSTMENT_CREATED', 'Stock Adjustment Created'), ('STOCK_ADJUSTMENT_UPDATED', 'Stock Adjustment Updated'), ('STOCK_ADJUSTMENT_APPROVED', 'Stock Adjustment Approved'), ('STOCK_ADJUSTMENT_POSTED', 'Stock Adjustment Posted'), ('VENDOR_CONTACT_CREATED', 'Vendor Contact Created'), ('PURCHASE_ORDER_CREATED', 'Purchase Order Created'), ('PURCHASE_ORDER_UPDATED', 'Purchase Order Updated'), ('PURCHASE_ORDER_CANCELLED', 'Purchase Order Cancelled'), ('GOODS_RECEIPT_CREATED', 'Goods Receipt Created'), ('GOODS_RECEIPT_POSTED', 'Goods Receipt Posted'), ('VENDOR_BILL_CREATED', 'Vendor Bill Created'), ('VENDOR_BILL_POSTED', 'Vendor Bill Posted'), ('VENDOR_PAYMENT_CREATED', 'Vendor Payment Created'), ('VENDOR_PAYMENT_POSTED', 'Vendor Payment Posted'), ('OPENING_STOCK_IMPORTED', 'Opening Stock Imported'), ('DELIVERY_INVENTORY_BRIDGE_SYNCED', 'Delivery Inventory Bridge Synced'), ('MANUFACTURING_BOM_CREATED', 'Manufacturing BOM Created'), ('MANUFACTURING_BOM_UPDATED', 'Manufacturing BOM Updated'), ('MANUFACTURING_BOM_STATUS_UPDATED', 'Manufacturing BOM Status Updated'), ('PRODUCTION_JOB_CREATED', 'Production Job Created'), ('PRODUCTION_JOB_UPDATED', 'Production Job Updated'), ('PRODUCTION_JOB_STATUS_UPDATED', 'Production Job Status Updated'), ('PRODUCTION_MATERIAL_MOVEMENT_POSTED', 'Production Material Movement Posted'), ('PRODUCTION_OUTPUT_POSTED', 'Production Output Posted'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_VERIFIED', 'Password Reset Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_FAILED', 'Password Reset Failed'), ('PASSWORD_RESET_EXPIRED', 'Password Reset Expired'), ('PASSWORD_RESET_LOCKED', 'Password Reset Locked'), ('PASSWORD_RESET_RESENT', 'Password Reset Resent'), ('PASSWORD_RESET_INVALIDATED', 'Password Reset Invalidated'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_QUICK_CREATED', 'Customer Quick-Created (No Email)'), ('CUSTOMER_EMAIL_ADDED', 'Customer Email Added'), ('CUSTOMER_EMAIL_CHANGED', 'Customer Email Changed'), ('CUSTOMER_PHOTO_UPDATED', 'Customer Profile Photo Updated'), ('CUSTOMER_KYC_DOCUMENT_SUBMITTED', 'Customer KYC Document Submitted'), ('CUSTOMER_KYC_APPROVED', 'Customer KYC Approved'), ('CUSTOMER_KYC_REJECTED', 'Customer KYC Rejected'), ('CUSTOMER_REFERRAL_CREATED', 'Customer Referral Created'), ('CUSTOMER_REFERRAL_COMMISSION_APPROVED', 'Customer Referral Commission Approved'), ('CONTRACT_NUMBERED', 'Contract Number Assigned'), ('CONTRACT_TERMS_LOCKED', 'Contract Financial Terms Locked'), ('CONTRACT_APPROVED', 'Contract Approved'), ('CONTRACT_ACTIVATED', 'Contract Activated'), ('CONTRACT_CANCELLED', 'Contract Cancelled'), ('CONTRACT_CLOSED', 'Contract Closed'), ('CONTRACT_AMENDMENT_REQUESTED', 'Contract Amendment Requested'), ('CONTRACT_AMENDMENT_APPROVED', 'Contract Amendment Approved'), ('CONTRACT_AMENDMENT_REJECTED', 'Contract Amendment Rejected'), ('CONTRACT_AMENDMENT_APPLIED', 'Contract Amendment Applied'), ('CONTRACT_POSSESSION_CREATED', 'Product Possession Record Created'), ('CONTRACT_POSSESSION_UPDATED', 'Product Possession Status Updated'), ('CONTRACT_RETURN_INSPECTION_CREATED', 'Return Inspection Created'), ('CONTRACT_RETURN_INSPECTION_APPROVED', 'Return Inspection Approved'), ('CONTRACT_DOCUMENT_REGENERATED', 'Contract Document Regenerated')], db_index=True, default='SUB_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='BrandImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('REVIEWED', 'Reviewed'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], db_index=True, default='PREVIEW', max_length=20)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_import_batches', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='subscriptions.branddatasource')),
            ],
            options={
                'db_table': 'brand_import_batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BrandImportedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('BRAND_IDENTITY', 'Brand Identity'), ('CONTACT_LOCATION', 'Contact & Location'), ('SOCIAL_LINK', 'Social Link'), ('MEDIA_ASSET', 'Media Asset'), ('PUBLIC_CONTENT', 'Public Content')], db_index=True, max_length=30)),
                ('field_key', models.CharField(db_index=True, max_length=80)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPLIED', 'Applied')], db_index=True, default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_brand_import_items', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='subscriptions.brandimportbatch')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_brand_import_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand_imported_items',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BrandProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_profile_snapshots', to=settings.AUTH_USER_MODEL)),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='subscriptions.brandimportbatch')),
            ],
            options={
                'db_table': 'brand_profile_snapshots',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PublicContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_blocks', to='subscriptions.brandimportbatch')),
            ],
            options={
                'db_table': 'public_content_blocks',
                'ordering': ['key', 'id'],
            },
        ),
    ]
