# Generated by Django 5.2.7 on 2026-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0066_customerkycdocument_file_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentleasebillingdemand',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
