# Generated by Django 6.0.2 on 2026-05-14 09:31

import django.db.models.deletion
import django.utils.timezone
import subscriptions.models_business_setup
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0067_rentleasebillingdemand_tax_profile_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('RENTAL_AGREEMENT', 'Rental Agreement'), ('OWNERSHIP_PROOF', 'Ownership Proof'), ('UDYAM_CERTIFICATE', 'Udyam Certificate'), ('GST_CERTIFICATE', 'GST Certificate'), ('SHOP_LICENSE', 'Shop License'), ('BANK_PROOF', 'Bank Proof'), ('PAN_OR_TAX_PROOF', 'PAN/Tax Proof'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=subscriptions.models_business_setup.business_compliance_document_upload_to)),
                ('public_visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC_SUMMARY_ONLY', 'Public Summary Only')], db_index=True, default='PRIVATE', max_length=24)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NOT_PROVIDED', 'Not Provided')], db_index=True, default='PENDING', max_length=20)),
                ('public_summary', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_business_compliance_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_business_compliance_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_compliance_documents',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['document_type', 'verification_status'], name='business_co_documen_0928fb_idx'), models.Index(fields=['public_visibility', 'verification_status'], name='business_co_public__4d0948_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('PRIVACY', 'Privacy'), ('REFUND', 'Refund / Cancellation'), ('WARRANTY', 'Warranty'), ('DELIVERY', 'Delivery'), ('RENT_LEASE', 'Rental / Lease'), ('LUCKY_PLAN', 'Lucky Plan EMI'), ('DIRECT_SALE', 'Direct Sale'), ('PAYMENT', 'Payment'), ('SERVICE', 'Service / Repair'), ('GRIEVANCE', 'Grievance'), ('COMPLIANCE', 'Compliance'), ('CUSTOMER_SUPPORT', 'Customer Support')], db_index=True, default='GENERAL', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('effective_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_policy_pages', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_policy_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_policy_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_pages',
                'ordering': ['slug', '-version', '-id'],
                'indexes': [models.Index(fields=['slug', 'status'], name='policy_page_slug_52ae13_idx'), models.Index(fields=['category', 'status'], name='policy_page_categor_6d2e8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='unique_policy_slug_version'), models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('slug',), name='unique_published_policy_slug')],
            },
        ),
    ]
