# Generated by Django 6.0.2 on 2026-05-14 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0068_businesscompliancedocument_policypage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDataBackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('FULL_DATABASE_LOGICAL', 'Full database logical'), ('SELECTED_SCOPES_EXPORT', 'Selected scopes export')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('scopes', models.JSONField(default=list)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('row_counts', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_business_backup_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_data_backup_jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDataRestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PREVIEWED', max_length=12)),
                ('package_type', models.CharField(blank=True, default='', max_length=64)),
                ('package_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('selected_scopes', models.JSONField(default=list)),
                ('preview', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_business_restore_jobs', to=settings.AUTH_USER_MODEL)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_jobs', to='subscriptions.businessdatabackupjob')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_business_restore_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_data_restore_jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
