# Generated by Django 6.0.2 on 2026-05-27 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0075_contract_recontract_admin_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRecontractScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('original_due_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_due_date', models.DateField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_principal_component', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposed_status', models.CharField(choices=[('PREVIEW_ONLY', 'Preview Only'), ('SUPERSEDED', 'Superseded')], db_index=True, default='PREVIEW_ONLY', max_length=20)),
                ('adjustment_type', models.CharField(choices=[('EXISTING_PENDING_REPLACEMENT', 'Existing Pending Replacement'), ('NEW_ADDITIONAL_EMI', 'New Additional EMI'), ('REDUCED_EMI', 'Reduced EMI'), ('CREDIT_OFFSET', 'Credit Offset')], db_index=True, max_length=40)),
                ('source_record_mutation', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_preview_lines', to='subscriptions.contractrecontractevent')),
                ('original_emi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recontract_schedule_preview_lines', to='subscriptions.emi')),
            ],
            options={
                'db_table': 'contract_recontract_schedule_lines',
                'ordering': ['event_id', 'line_no', 'id'],
                'indexes': [models.Index(fields=['event', 'line_no'], name='recon_sch_ev_line_idx'), models.Index(fields=['event', 'adjustment_type'], name='recon_sch_ev_adj_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('line_no__gt', 0)), name='chk_recontract_sched_line_gt0'), models.CheckConstraint(condition=models.Q(('proposed_amount__gte', 0)), name='chk_recontract_sched_prop_amt_gte0'), models.CheckConstraint(condition=models.Q(('source_record_mutation', False)), name='chk_recontract_sched_no_src_mut')],
            },
        ),
    ]
