# Generated by Django 6.0.2 on 2026-05-27 02:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0076_contractrecontractscheduleline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRecontractFinancialImpactPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_type', models.CharField(choices=[('UPGRADE_EXTRA_PAYABLE', 'Upgrade Extra Payable'), ('DOWNGRADE_CREDIT_REQUIRED', 'Downgrade Credit Required'), ('SAME_PRICE_REFERENCE_CORRECTION', 'Same Price Reference Correction')], db_index=True, max_length=40)),
                ('accounting_preview_status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('SUPERSEDED', 'Superseded'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='PREVIEWED', max_length=20)),
                ('reconciliation_preview_status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('SUPERSEDED', 'Superseded'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], db_index=True, default='PREVIEWED', max_length=20)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_receivable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit_or_reduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('projected_customer_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('projected_future_emi_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('journal_preview', models.JSONField(blank=True, default=dict)),
                ('reconciliation_preview', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('source_record_mutation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recontract_financial_impact_previews', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_impact_previews', to='subscriptions.contractrecontractevent')),
            ],
            options={
                'db_table': 'contract_recontract_financial_impact_previews',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event', 'accounting_preview_status'], name='recon_fin_prev_evt_acc_idx'), models.Index(fields=['event', 'reconciliation_preview_status'], name='recon_fin_prev_evt_rec_idx'), models.Index(fields=['impact_type'], name='recon_fin_prev_impact_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('additional_receivable_amount__gte', 0)), name='chk_recon_fin_add_recv_gte0'), models.CheckConstraint(condition=models.Q(('credit_or_reduction_amount__gte', 0)), name='chk_recon_fin_credit_gte0'), models.CheckConstraint(condition=models.Q(('projected_customer_balance__gte', 0)), name='chk_recon_fin_cust_bal_gte0'), models.CheckConstraint(condition=models.Q(('projected_future_emi_total__gte', 0)), name='chk_recon_fin_emi_total_gte0'), models.CheckConstraint(condition=models.Q(('source_record_mutation', False)), name='chk_recon_fin_no_src_mut')],
            },
        ),
    ]
