# Generated by Django 5.2.7 on 2026-06-12 23:22

import django.db.models.deletion
import subscriptions.models
from django.conf import settings
from django.db import migrations, models


def backfill_deposit_source_contract_fields(apps, schema_editor):
    RentLeaseDepositTransaction = apps.get_model("subscriptions", "RentLeaseDepositTransaction")
    for tx in RentLeaseDepositTransaction.objects.select_related("subscription").all().iterator():
        updates = []
        if not tx.transaction_number:
            tx.transaction_number = f"RLD-BACKFILL-{tx.pk}"
            updates.append("transaction_number")
        if tx.subscription_id:
            if not tx.customer_id:
                tx.customer_id = tx.subscription.customer_id
                updates.append("customer")
            if not tx.plan_type:
                tx.plan_type = tx.subscription.plan_type
                updates.append("plan_type")
        if not tx.transaction_date and tx.created_at:
            tx.transaction_date = tx.created_at.date()
            updates.append("transaction_date")
        if updates:
            tx.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_journalentry_accounting_period_and_more'),
        ('subscriptions', '0082_merge_rentleasecollection_policy_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentleasecollection',
            new_name='rent_lease__subscri_1e69df_idx',
            old_name='rlc_sub_date_idx',
        ),
        migrations.RenameIndex(
            model_name='rentleasecollection',
            new_name='rent_lease__demand__f30002_idx',
            old_name='rlc_demand_status_idx',
        ),
        migrations.RenameIndex(
            model_name='rentleasecollection',
            new_name='rent_lease__custome_29420e_idx',
            old_name='rlc_customer_date_idx',
        ),
        migrations.RenameIndex(
            model_name='rentleasecollection',
            new_name='rent_lease__plan_ty_041c43_idx',
            old_name='rlc_plan_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='rentleasecollection',
            new_name='rent_lease__finance_78107b_idx',
            old_name='rlc_finance_date_idx',
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_deposit_source_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_lease_deposit_transactions', to='subscriptions.customer'),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='external_reference_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='finance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_lease_deposit_transactions', to='accounting.financeaccount'),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('EMI', 'EMI'), ('RENT', 'Rent'), ('LEASE', 'Lease')], db_index=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='reversal_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VOIDED', 'Voided'), ('REVERSED', 'Reversed')], db_index=True, default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='transaction_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rentleasedeposittransaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_deposit_source_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentleasecollection',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rentleasecollection',
            name='plan_type',
            field=models.CharField(choices=[('EMI', 'EMI'), ('RENT', 'Rent'), ('LEASE', 'Lease')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='rentleasedeposittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEMAND_CREATED', 'Demand Created'), ('COLLECTED', 'Deposit Collected'), ('DEPOSIT_RECEIPT', 'Deposit Receipt'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUNDED', 'Refunded'), ('DEPOSIT_REFUND', 'Deposit Refund'), ('DEDUCTION', 'Deduction'), ('DEPOSIT_ADJUSTMENT', 'Deposit Adjustment')], db_index=True, max_length=24),
        ),
        migrations.RunPython(backfill_deposit_source_contract_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rentleasedeposittransaction',
            name='transaction_number',
            field=models.CharField(db_index=True, default=subscriptions.models.generate_rent_lease_deposit_transaction_number, max_length=64),
        ),
        migrations.AddIndex(
            model_name='rentleasedeposittransaction',
            index=models.Index(fields=['customer', 'transaction_date'], name='rent_lease__custome_cafa82_idx'),
        ),
        migrations.AddIndex(
            model_name='rentleasedeposittransaction',
            index=models.Index(fields=['plan_type', 'status', 'transaction_date'], name='rent_lease__plan_ty_97a4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='rentleasedeposittransaction',
            index=models.Index(fields=['finance_account', 'transaction_date'], name='rent_lease__finance_5bdf51_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentleasedeposittransaction',
            constraint=models.CheckConstraint(condition=models.Q(('plan_type', ''), ('plan_type', 'RENT'), ('plan_type', 'LEASE'), _connector='OR'), name='chk_deposit_transaction_plan_type'),
        ),
        migrations.AddConstraint(
            model_name='rentleasedeposittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_number', ''), _negated=True), fields=('transaction_number',), name='uq_deposit_transaction_number'),
        ),
        migrations.AddConstraint(
            model_name='rentleasedeposittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uq_deposit_transaction_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='rentleasedeposittransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference_no', ''), _negated=True), fields=('external_reference_no',), name='uq_deposit_transaction_external_ref'),
        ),
    ]
