# Generated by Django 6.0.2 on 2026-06-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0087_kyc_contract_gating_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkycdocument',
            name='resubmission_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='subscriptions.customerkycdocument'),
        ),
        migrations.AddField(
            model_name='customerkycdocument',
            name='upload_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerkycdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], db_index=True, default='SUBMITTED', max_length=30),
        ),
    ]
