# Generated by Django 6.0.2 on 2026-06-16 17:09

import django.db.models.deletion
import django.utils.timezone
import subscriptions.models_kyc_workflow
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0088_kyc_workflow_additive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor'), ('STAFF', 'Staff')], db_index=True, max_length=20)),
                ('owner_id', models.PositiveIntegerField(db_index=True)),
                ('document_model', models.CharField(blank=True, default='', max_length=80)),
                ('document_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted for Review'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_RESUBMISSION', 'Resubmission Requested'), ('EXCEPTION_APPROVE', 'Exception Approved (Admin Override)'), ('EXPIRE', 'Expired'), ('UPLOAD', 'Document Uploaded')], db_index=True, max_length=30)),
                ('old_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('upload_source', models.CharField(blank=True, choices=[('ADMIN_UPLOAD', 'Admin Upload'), ('SELF_SERVICE_UPLOAD', 'Self-Service Upload'), ('CRM_UPLOAD', 'CRM Upload'), ('SUBSCRIPTION_REGISTRATION', 'Subscription Registration')], default='', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_review_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_review_actions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id', 'created_at'], name='kyc_review__owner_t_9c5bcc_idx'), models.Index(fields=['owner_type', 'action'], name='kyc_review__owner_t_a33a46_idx'), models.Index(fields=['document_model', 'document_id'], name='kyc_review__documen_9f115c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter ID'), ('GST_CERTIFICATE', 'GST Certificate'), ('BANK_PROOF', 'Bank Proof'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('document_reference', models.CharField(blank=True, default='', max_length=80)),
                ('file', models.FileField(upload_to=subscriptions.models_kyc_workflow.partner_kyc_doc_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], db_index=True, default='SUBMITTED', max_length=30)),
                ('upload_source', models.CharField(blank=True, choices=[('ADMIN_UPLOAD', 'Admin Upload'), ('SELF_SERVICE_UPLOAD', 'Self-Service Upload'), ('CRM_UPLOAD', 'CRM Upload'), ('SUBSCRIPTION_REGISTRATION', 'Subscription Registration')], db_index=True, default='ADMIN_UPLOAD', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('partner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('resubmission_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='subscriptions.partnerkycdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_partner_kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_kyc_documents',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['partner_user', 'status'], name='partner_kyc_partner_7ac2b0_idx'), models.Index(fields=['partner_user', 'document_type'], name='partner_kyc_partner_44f668_idx')],
            },
        ),
    ]
