# Generated by Django 5.2.7 on 2026-06-17 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0089_kyc_review_action_partner_kyc_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_model", models.CharField(db_index=True, max_length=120)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                ("action_key", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("before_snapshot", models.JSONField(default=dict)),
                ("after_snapshot", models.JSONField(default=dict)),
                ("request_reason", models.TextField(blank=True, default="")),
                ("decision_reason", models.TextField(blank=True, default="")),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_approval_requests",
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "risk_level"],
                        name="ctrl_appr_status_risk_idx",
                    ),
                    models.Index(
                        fields=["source_model", "source_id", "status"],
                        name="ctrl_appr_src_status_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "status"],
                        name="ctrl_appr_reqby_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("source_model", "source_id", "action_key"),
                        name="ctrl_appr_unique_pending_per_src_action",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=120)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("BOOL", "Boolean"),
                            ("INT", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("STRING", "String"),
                            ("JSON", "JSON"),
                        ],
                        default="BOOL",
                        max_length=10,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("BRANCH", "Branch"),
                            ("PLAN_TYPE", "Plan Type"),
                            ("ROLE", "Role"),
                        ],
                        db_index=True,
                        default="GLOBAL",
                        max_length=12,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_policies_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_business_policies",
                "ordering": ["key", "scope_type", "scope_key"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "key", "scope_type"],
                        name="ctrl_pol_active_key_scope_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("key", "scope_type", "scope_key"),
                        name="ctrl_policy_unique_active_key_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ControlException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exception_key", models.CharField(db_index=True, max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("source_model", models.CharField(db_index=True, max_length=120)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=240)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledged_control_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_exceptions",
                "ordering": ["-detected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="ctrl_exc_status_severity_idx",
                    ),
                    models.Index(
                        fields=["exception_key", "status"],
                        name="ctrl_exc_key_status_idx",
                    ),
                    models.Index(
                        fields=["source_model", "source_id"], name="ctrl_exc_source_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("exception_key", "source_model", "source_id"),
                        name="ctrl_exc_unique_open_per_src",
                    )
                ],
            },
        ),
    ]
