# Generated by Django 5.2.7 on 2026-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0090_control_foundation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="after_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="before_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="businesspolicy",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="controlexception",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
