# Generated by Django 5.2.7 on 2026-06-17 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("subscriptions", "0091_control_foundation_blank_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCloseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_date", models.DateField(db_index=True)),
                ("is_dry_run", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRY_RUN", "Dry Run"),
                            ("EXECUTED", "Executed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="DRY_RUN",
                        max_length=10,
                    ),
                ),
                ("blocking_check_count", models.IntegerField(default=0)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_close_runs",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_close_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_daily_close_runs",
                "ordering": ["-run_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyCloseCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_key", models.CharField(db_index=True, max_length=80)),
                ("label", models.CharField(max_length=240)),
                ("passed", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("BLOCKING", "Blocking"),
                        ],
                        default="BLOCKING",
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "close_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="subscriptions.dailycloserun",
                    ),
                ),
            ],
            options={
                "db_table": "control_daily_close_check_results",
                "ordering": ["close_run", "id"],
            },
        ),
        migrations.CreateModel(
            name="CashCounterSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField(db_index=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "declared_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("VARIANCE_PENDING_APPROVAL", "Variance Pending Approval"),
                            ("APPROVED_VARIANCE", "Approved Variance"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=28,
                    ),
                ),
                (
                    "variance_approval_request_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_counter_sessions",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "cash_counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="branch_control.cashcounter",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_counter_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_cash_counter_sessions",
                "ordering": ["-session_date", "-opened_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["session_date", "status"],
                        name="ctrl_ccs_date_status_idx",
                    ),
                    models.Index(
                        fields=["cash_counter", "session_date"],
                        name="ctrl_ccs_counter_date_idx",
                    ),
                    models.Index(
                        fields=["cashier", "session_date"],
                        name="ctrl_ccs_cashier_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("cash_counter", "cashier", "session_date"),
                        name="ctrl_ccs_unique_open_per_counter_cashier_date",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dailycloserun",
            index=models.Index(
                fields=["run_date", "status"], name="ctrl_dcr_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyclosecheckresult",
            index=models.Index(
                fields=["close_run", "passed"], name="ctrl_dccr_run_passed_idx"
            ),
        ),
    ]
