# Generated by Django 6.0.2 on 2026-06-17 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_control', '0002_seed_primary_branch_and_backfill_context'),
        ('subscriptions', '0092_cash_counter_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEndCloseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(db_index=True)),
                ('is_dry_run', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('DRY_RUN', 'Dry Run'), ('EXECUTED', 'Executed'), ('BLOCKED', 'Blocked')], db_index=True, default='DRY_RUN', max_length=20)),
                ('run_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='month_end_close_runs', to='branch_control.branch')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_end_close_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_month_end_close_runs',
                'ordering': ['-run_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MonthEndCloseCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_key', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('BLOCKING', 'Blocking')], db_index=True, default='INFO', max_length=10)),
                ('passed', models.BooleanField(db_index=True, default=True)),
                ('count', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='subscriptions.monthendcloserun')),
            ],
            options={
                'db_table': 'control_month_end_close_check_results',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='monthendcloserun',
            index=models.Index(fields=['period_year', 'period_month', 'status'], name='control_mon_period__b8254b_idx'),
        ),
        migrations.AddIndex(
            model_name='monthendcloserun',
            index=models.Index(fields=['period_year', 'period_month', 'is_dry_run'], name='control_mon_period__489736_idx'),
        ),
        migrations.AddIndex(
            model_name='monthendclosecheckresult',
            index=models.Index(fields=['run', 'severity', 'passed'], name='control_mon_run_id_02dce6_idx'),
        ),
    ]
