# Generated by Django 5.2.7 on 2026-06-17 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_inventoryitem_costing_method_and_more"),
        ("subscriptions", "0094_document_vault_p3a"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("PUBLIC_SITE_UPDATED", "Public Site Updated"),
                    ("USER_ACTIVATED", "User Activated"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("PARTNER_COMMISSION_SET", "Partner Commission Set"),
                    ("PARTNER_COMMISSION_UPDATED", "Partner Commission Updated"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("LEAD_CUSTOMER_LINKED", "Lead Customer Linked"),
                    ("LEAD_SUBSCRIPTION_LINKED", "Lead Subscription Linked"),
                    ("LEAD_DIRECT_SALE_LINKED", "Lead Direct Sale Linked"),
                    ("LEAD_CONVERTED", "Lead Converted"),
                    ("CRM_PARTY_CREATED", "CRM Party Created"),
                    ("CRM_PARTY_LINKED", "CRM Party Linked"),
                    ("CRM_INTERACTION_CREATED", "CRM Interaction Created"),
                    ("CRM_INTERACTION_UPDATED", "CRM Interaction Updated"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    (
                        "SUPPORT_REQUEST_STATUS_UPDATED",
                        "Support Request Status Updated",
                    ),
                    ("SUPPORT_REQUEST_ASSIGNED", "Support Request Assigned"),
                    ("SUPPORT_REQUEST_NOTE_UPDATED", "Support Request Notes Updated"),
                    ("SUPPORT_REQUEST_RESOLVED", "Support Request Resolved"),
                    (
                        "SUPPORT_REQUEST_RESOLUTION_RECORDED",
                        "Support Request Resolution Recorded",
                    ),
                    ("SERVICE_DESK_CASE_CREATED", "Service Desk Case Created"),
                    ("SERVICE_DESK_CASE_UPDATED", "Service Desk Case Updated"),
                    (
                        "SERVICE_DESK_CASE_STATUS_UPDATED",
                        "Service Desk Case Status Updated",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURN_REQUESTED",
                        "Service Desk Case Delivery Return Requested",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURNED",
                        "Service Desk Case Delivery Returned",
                    ),
                    (
                        "SERVICE_DESK_CASE_CREDIT_NOTE_POSTED",
                        "Service Desk Case Credit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_DEBIT_NOTE_POSTED",
                        "Service Desk Case Debit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_REPLACEMENT_LINKED",
                        "Service Desk Case Replacement Linked",
                    ),
                    ("DELIVERY_CREATED", "Delivery Created"),
                    ("DELIVERY_UPDATED", "Delivery Updated"),
                    ("DELIVERY_STATUS_CHANGED", "Delivery Status Changed"),
                    ("DELIVERY_DISPATCHED", "Delivery Dispatched"),
                    ("DELIVERY_COMPLETED", "Delivery Completed"),
                    ("DELIVERY_FAILED", "Delivery Failed"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                    ("DELIVERY_RETURN_REQUESTED", "Delivery Return Requested"),
                    ("DELIVERY_RETURNED", "Delivery Returned"),
                    ("SUB_CREATED", "Subscription Created"),
                    ("SUBSCRIPTION_REQUEST_CREATED", "Subscription Request Created"),
                    ("SUBSCRIPTION_REQUEST_APPROVED", "Subscription Request Approved"),
                    ("SUBSCRIPTION_REQUEST_REJECTED", "Subscription Request Rejected"),
                    (
                        "SUBSCRIPTION_REQUEST_CANCELLED",
                        "Subscription Request Cancelled",
                    ),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("DRAW_CERTIFICATE_PUBLISHED", "Draw Certificate Published"),
                    ("DRAW_PUBLIC_VERIFIED", "Public Draw Verification Generated"),
                    ("DRAW_PUBLIC_RESULT_PUBLISHED", "Public Draw Result Published"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("WINNER_STATE_SYNCED", "Winner State Synced"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    (
                        "COMMISSION_PAYOUT_BATCH_CREATED",
                        "Commission Payout Batch Created",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_FINALIZED",
                        "Commission Payout Batch Finalized",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_CANCELLED",
                        "Commission Payout Batch Cancelled",
                    ),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    (
                        "PRODUCT_INVENTORY_PROFILE_PREPARED",
                        "Product Inventory Profile Prepared",
                    ),
                    ("INVENTORY_ITEM_CREATED", "Inventory Item Created"),
                    ("INVENTORY_ITEM_UPDATED", "Inventory Item Updated"),
                    ("STOCK_LOCATION_CREATED", "Stock Location Created"),
                    ("STOCK_LOCATION_UPDATED", "Stock Location Updated"),
                    ("STOCK_ADJUSTMENT_CREATED", "Stock Adjustment Created"),
                    ("STOCK_ADJUSTMENT_UPDATED", "Stock Adjustment Updated"),
                    ("STOCK_ADJUSTMENT_APPROVED", "Stock Adjustment Approved"),
                    ("STOCK_ADJUSTMENT_POSTED", "Stock Adjustment Posted"),
                    ("VENDOR_CONTACT_CREATED", "Vendor Contact Created"),
                    ("PURCHASE_ORDER_CREATED", "Purchase Order Created"),
                    ("PURCHASE_ORDER_UPDATED", "Purchase Order Updated"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase Order Cancelled"),
                    ("GOODS_RECEIPT_CREATED", "Goods Receipt Created"),
                    ("GOODS_RECEIPT_POSTED", "Goods Receipt Posted"),
                    ("VENDOR_BILL_CREATED", "Vendor Bill Created"),
                    ("VENDOR_BILL_POSTED", "Vendor Bill Posted"),
                    ("VENDOR_PAYMENT_CREATED", "Vendor Payment Created"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor Payment Posted"),
                    ("OPENING_STOCK_IMPORTED", "Opening Stock Imported"),
                    (
                        "DELIVERY_INVENTORY_BRIDGE_SYNCED",
                        "Delivery Inventory Bridge Synced",
                    ),
                    ("MANUFACTURING_BOM_CREATED", "Manufacturing BOM Created"),
                    ("MANUFACTURING_BOM_UPDATED", "Manufacturing BOM Updated"),
                    (
                        "MANUFACTURING_BOM_STATUS_UPDATED",
                        "Manufacturing BOM Status Updated",
                    ),
                    ("PRODUCTION_JOB_CREATED", "Production Job Created"),
                    ("PRODUCTION_JOB_UPDATED", "Production Job Updated"),
                    ("PRODUCTION_JOB_STATUS_UPDATED", "Production Job Status Updated"),
                    (
                        "PRODUCTION_MATERIAL_MOVEMENT_POSTED",
                        "Production Material Movement Posted",
                    ),
                    ("PRODUCTION_OUTPUT_POSTED", "Production Output Posted"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                    ("CUSTOMER_CREATED", "Customer Created"),
                    ("CUSTOMER_QUICK_CREATED", "Customer Quick-Created (No Email)"),
                    ("CUSTOMER_EMAIL_ADDED", "Customer Email Added"),
                    ("CUSTOMER_EMAIL_CHANGED", "Customer Email Changed"),
                    ("CUSTOMER_PHOTO_UPDATED", "Customer Profile Photo Updated"),
                    (
                        "CUSTOMER_KYC_DOCUMENT_SUBMITTED",
                        "Customer KYC Document Submitted",
                    ),
                    ("CUSTOMER_KYC_APPROVED", "Customer KYC Approved"),
                    ("CUSTOMER_KYC_REJECTED", "Customer KYC Rejected"),
                    (
                        "CUSTOMER_KYC_EXCEPTION_APPROVED",
                        "Customer KYC Exception Approved (Admin Override)",
                    ),
                    ("CUSTOMER_REFERRAL_CREATED", "Customer Referral Created"),
                    (
                        "CUSTOMER_REFERRAL_COMMISSION_APPROVED",
                        "Customer Referral Commission Approved",
                    ),
                    ("CONTRACT_NUMBERED", "Contract Number Assigned"),
                    ("CONTRACT_TERMS_LOCKED", "Contract Financial Terms Locked"),
                    ("CONTRACT_APPROVED", "Contract Approved"),
                    ("CONTRACT_ACTIVATED", "Contract Activated"),
                    ("CONTRACT_CANCELLED", "Contract Cancelled"),
                    ("CONTRACT_CLOSED", "Contract Closed"),
                    ("CONTRACT_AMENDMENT_REQUESTED", "Contract Amendment Requested"),
                    ("CONTRACT_AMENDMENT_APPROVED", "Contract Amendment Approved"),
                    ("CONTRACT_AMENDMENT_REJECTED", "Contract Amendment Rejected"),
                    ("CONTRACT_AMENDMENT_APPLIED", "Contract Amendment Applied"),
                    (
                        "CONTRACT_AMENDMENT_IMPLEMENTED",
                        "Contract Amendment Implemented",
                    ),
                    (
                        "CONTRACT_POSSESSION_CREATED",
                        "Product Possession Record Created",
                    ),
                    (
                        "CONTRACT_POSSESSION_UPDATED",
                        "Product Possession Status Updated",
                    ),
                    ("CONTRACT_RETURN_INSPECTION_CREATED", "Return Inspection Created"),
                    (
                        "CONTRACT_RETURN_INSPECTION_APPROVED",
                        "Return Inspection Approved",
                    ),
                    ("CONTRACT_DOCUMENT_REGENERATED", "Contract Document Regenerated"),
                    ("RENTAL_ASSET_CREATED", "Rental Asset Created"),
                    ("RENTAL_ASSET_RESERVED", "Rental Asset Reserved"),
                    ("RENTAL_ASSET_HANDED_OVER", "Rental Asset Handed Over"),
                    ("RENTAL_ASSET_RETURNED", "Rental Asset Returned"),
                    ("RENTAL_ASSET_UNDER_REPAIR", "Rental Asset Sent for Repair"),
                    ("RENTAL_ASSET_RETIRED", "Rental Asset Retired"),
                    (
                        "RENTAL_ASSET_CONDITION_SNAPSHOT",
                        "Asset Condition Snapshot Recorded",
                    ),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RentalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("serial_no", models.CharField(blank=True, default="", max_length=80)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("HANDED_OVER", "Handed Over"),
                            ("RETURNED", "Returned"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                            ("SCRAP", "Scrap"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rental_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rented_assets",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="inventory.stocklocation",
                    ),
                ),
                (
                    "current_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_rental_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_rental_assets",
                "ordering": ["asset_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="AssetConditionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("BEFORE_HANDOVER", "Before Handover"),
                            ("AFTER_RETURN", "After Return"),
                            ("DAMAGE_REVIEW", "Damage Review"),
                            ("MAINTENANCE_REVIEW", "Maintenance Review"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "condition_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                            ("SCRAP", "Scrap"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "assessed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_condition_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="condition_snapshots",
                        to="subscriptions.subscriptiondocument",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_condition_snapshots",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="condition_snapshots",
                        to="subscriptions.rentalasset",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_asset_condition_snapshots",
                "ordering": ["-assessed_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["status", "condition_grade"],
                name="subscriptio_status_2488c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["product", "status"], name="subscriptio_product_a0485b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["current_customer", "status"],
                name="subscriptio_current_177708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["current_subscription", "status"],
                name="subscriptio_current_f0bdc5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_subscription__isnull", False),
                        ("status", "HANDED_OVER"),
                    ),
                    models.Q(("status", "HANDED_OVER"), _negated=True),
                    _connector="OR",
                ),
                name="rental_asset_handedover_requires_subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="assetconditionsnapshot",
            index=models.Index(
                fields=["asset", "stage", "assessed_at"],
                name="subscriptio_asset_i_a90835_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assetconditionsnapshot",
            index=models.Index(
                fields=["subscription", "stage"], name="subscriptio_subscri_b4d074_idx"
            ),
        ),
    ]
