# Generated by Django 5.2.7 on 2026-06-17 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0095_rental_asset_lifecycle_p3b"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "last_calculated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profile",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_customer_risk_profiles",
                "ordering": ["-last_calculated_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["risk_band", "last_calculated_at"],
                        name="subscriptio_risk_ba_46839d_idx",
                    )
                ],
            },
        ),
    ]
