# Generated by Django 5.2.7 on 2026-06-21 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0096_customer_risk_profile_p3c"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_code",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("EXPIRED", "Expired"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All Customers"),
                            ("NEW_CUSTOMER", "New Customer"),
                            ("EXISTING_CUSTOMER", "Existing Customer"),
                            ("PARTNER_REFERRED", "Partner Referred"),
                            ("HIGH_TRUST_CUSTOMER", "High Trust Customer"),
                        ],
                        db_index=True,
                        default="ALL",
                        max_length=22,
                    ),
                ),
                (
                    "max_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "display_priority",
                    models.PositiveIntegerField(db_index=True, default=100),
                ),
                ("is_public_visible", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_packages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_packages_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_offer_packages",
                "ordering": ["display_priority", "package_code"],
            },
        ),
        migrations.CreateModel(
            name="OfferPackageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Discount"),
                            ("FLAT", "Flat Amount"),
                            ("PERCENT", "Percentage"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "offer_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="subscriptions.offerpackage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_package_lines",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "db_table": "growth_offer_package_lines",
                "ordering": ["offer_package_id", "product_id"],
            },
        ),
        migrations.CreateModel(
            name="PlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_code",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("EMI", "EMI (Lucky Plan)"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "tenure_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "default_down_payment_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "default_security_deposit_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "default_grace_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "is_lucky_plan_eligible",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("requires_batch", models.BooleanField(default=False)),
                ("requires_lucky_id", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_templates_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_plan_templates",
                "ordering": ["plan_type", "template_code"],
            },
        ),
        migrations.AddField(
            model_name="offerpackage",
            name="plan_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offer_packages",
                to="subscriptions.plantemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="plantemplate",
            index=models.Index(
                fields=["is_active", "plan_type"], name="growth_pt_active_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerpackage",
            index=models.Index(
                fields=["status", "audience_type"], name="growth_op_status_audience_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerpackage",
            index=models.Index(
                fields=["start_date", "end_date"], name="growth_op_date_range_idx"
            ),
        ),
    ]
