# Generated by Django 5.2.7 on 2026-06-21 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0097_growth_offers_p5a"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGrowthRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("RENEWAL", "Renewal"),
                            ("UPGRADE", "Upgrade"),
                            ("EXCHANGE", "Exchange"),
                            ("PLAN_CONVERSION", "Plan Conversion"),
                            ("EARLY_DELIVERY_INTEREST", "Early Delivery Interest"),
                            ("RENT_TO_LEASE_INTEREST", "Rent-to-Lease Interest"),
                            (
                                "LEASE_TO_PURCHASE_INTEREST",
                                "Lease-to-Purchase Interest",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("CONVERTED", "Converted"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=14,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("risk_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "approval_required",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_as_current",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "desired_offer_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="subscriptions.offerpackage",
                    ),
                ),
                (
                    "desired_plan_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="subscriptions.plantemplate",
                    ),
                ),
                (
                    "requested_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_as_requested",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "source_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_customer_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowthRequestDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUEST_MORE_INFO", "Request More Info"),
                            ("CANCEL", "Cancel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_request_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "growth_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="subscriptions.customergrowthrequest",
                    ),
                ),
            ],
            options={
                "db_table": "growth_request_decisions",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowthRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("SERVICE", "Service"),
                            ("DISCOUNT", "Discount"),
                            ("NOTE", "Note"),
                        ],
                        default="PRODUCT",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "growth_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="subscriptions.customergrowthrequest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_request_lines",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "db_table": "growth_request_lines",
                "ordering": ["growth_request_id", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["customer", "status"], name="growth_req_cust_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["status", "priority"], name="growth_req_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["request_type", "status"], name="growth_req_type_status_idx"
            ),
        ),
    ]
