# Generated by Django 5.2.7 on 2026-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0098_growth_requests_p5b"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="preferred_reminder_channel",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Customer's preferred channel for payment reminders (SMS / WHATSAPP / EMAIL / CALL). Blank = no preference recorded.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="whatsapp_opted_in",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when the customer has explicitly opted in to receive WhatsApp reminders.",
            ),
        ),
    ]
