# Generated by Django 5.2.7 on 2026-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0101_kyc_expiry_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emischeme",
            new_name="subscriptio_is_acti_53d840_idx",
            old_name="scheme_active_dates_idx",
        ),
        migrations.RenameIndex(
            model_name="recoverycase",
            new_name="subscriptio_stage_0d6793_idx",
            old_name="recovery_stage_date_idx",
        ),
        migrations.RenameIndex(
            model_name="recoverycase",
            new_name="subscriptio_assigne_b6250a_idx",
            old_name="recovery_assigned_stage_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionguarantor",
            new_name="subscriptio_subscri_08255d_idx",
            old_name="sub_guarantor_sub_primary_idx",
        ),
        migrations.RemoveField(
            model_name="emischeme",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="recoverycase",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="subscriptionguarantor",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL", "Full Settlement"),
                    ("PARTIAL", "Partial Settlement"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emischeme",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products.",
                related_name="emi_schemes",
                to="subscriptions.product",
            ),
        ),
        migrations.AlterField(
            model_name="emischeme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emischeme",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of subscriptions this scheme can be applied to. Null = unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emischeme",
            name="plan_type",
            field=models.CharField(
                blank=True,
                choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                default="",
                help_text="Leave blank to apply to all plan types.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="emischeme",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percent value, flat rupee amount, or number of installments to waive.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="recoverycase",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionguarantor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
