# Generated by Django 5.2.7 on 2026-06-24 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0106_customer_dispute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerdispute",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="customerdispute",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
