# Generated by Django 5.2.7 on 2026-06-27 07:54

import subscriptions.models_document_print_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0109_business_rule_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentprintsettings",
            name="authorized_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=subscriptions.models_document_print_settings.document_print_signature_upload_to,
            ),
        ),
    ]
