# Generated by Django 5.2.7 on 2026-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0110_authorized_signature_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="pincode",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_sac_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
    ]
