# Generated by Django 5.2.7 on 2026-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0112_email_smtp_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategorymaster",
            options={"ordering": ["sort_order", "name", "id"]},
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="public_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="public/category/"
            ),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="public_title",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="seo_description",
            field=models.CharField(blank=True, default="", max_length=320),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="productcategorymaster",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="productcategorymaster",
            index=models.Index(
                fields=["is_public", "is_active", "sort_order"],
                name="product_cat_is_publ_6d7888_idx",
            ),
        ),
    ]
