# Generated by Django 5.2.7 on 2026-07-09 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0114_backfill_category_slugs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdispute",
            name="open_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerdispute",
            name="resolution_decision",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customerdispute",
            name="resolve_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerdispute",
            name="review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerdispute",
            name="review_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_approval_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
