# Generated by Django 5.2.7 on 2026-07-09 19:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0115_add_settlement_and_sla_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extended_warranty_cost_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7.5"),
                help_text="Extended warranty cost as % of product price",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Enable warranty coverage for this product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months_extended_max",
            field=models.PositiveIntegerField(
                default=12, help_text="Max months for extended warranty plan"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months_manufacturing",
            field=models.PositiveIntegerField(
                default=12, help_text="Manufacturing defect warranty (months)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months_structural",
            field=models.PositiveIntegerField(
                default=36,
                help_text="Structural warranty for furniture (months, 0 = none)",
            ),
        ),
    ]
