# Generated by Django 5.2.7 on 2026-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0116_add_warranty_coverage_and_service_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emi",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("OVERDUE", "Overdue"),
                    ("PAID", "Paid"),
                    ("WAIVED", "Waived"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
