# Generated by Django 5.2.7 on 2026-07-10 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0117_compliance_invariants_p1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="grace_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Days after EMI due_date before status flips to OVERDUE (CTRL-LP-7).",
            ),
        ),
        migrations.CreateModel(
            name="DefectClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MINOR", "Minor"),
                            ("MAJOR", "Major"),
                            ("SAFETY_CRITICAL", "Safety Critical"),
                        ],
                        db_index=True,
                        default="MINOR",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("RESOLVED", "Resolved"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "reported_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "cpa_override",
                    models.BooleanField(
                        default=False,
                        help_text="Set by admin to allow refund/exchange outside normal return window under CPA 2019.",
                    ),
                ),
                ("cpa_override_reason", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                (
                    "cpa_override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpa_overridden_defect_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filed_defect_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_defect_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defect_claims",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "defect_claims",
                "ordering": ["-reported_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ConsumerReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("WITHIN_WINDOW", "Within Return Window"),
                            ("OUTSIDE_WINDOW", "Outside Return Window"),
                            ("CPA_OVERRIDE", "CPA Override Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        help_text="Date the product was delivered — used to calculate the return window."
                    ),
                ),
                (
                    "refund_deadline",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Latest date by which refund must be processed after return approval.",
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filed_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "defect_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="subscriptions.defectclaim",
                    ),
                ),
            ],
            options={
                "db_table": "consumer_return_requests",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DrawAuthorisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("draw_month", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AUTHORISED", "Authorised"),
                            ("REJECTED", "Rejected"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "authorised_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("revocation_reason", models.TextField(blank=True, default="")),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Eligible-pool snapshot at time of authorisation request.",
                    ),
                ),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorised_draws",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_authorisations",
                        to="subscriptions.batch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_draw_authorisations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draw_authorisations",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmiWaiverSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("waived_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("settlement_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "emi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiver_settlements",
                        to="subscriptions.emi",
                    ),
                ),
                (
                    "lucky_draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiver_settlements",
                        to="subscriptions.luckydraw",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emi_waiver_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waiver_settlements",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "emi_waiver_settlements",
                "ordering": ["-settlement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Repossession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOTICE_ISSUED", "Notice Issued"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NOTICE_ISSUED",
                        max_length=20,
                    ),
                ),
                ("notice_issued_at", models.DateTimeField(db_index=True)),
                (
                    "notice_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "notice_document",
                    models.FileField(
                        blank=True, null=True, upload_to="repossession/notices/"
                    ),
                ),
                ("response_deadline", models.DateField(db_index=True)),
                (
                    "initiated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                (
                    "asset_condition_on_return",
                    models.CharField(
                        choices=[
                            ("NOT_ASSESSED", "Not Assessed"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="NOT_ASSESSED",
                        max_length=20,
                    ),
                ),
                ("recovery_notes", models.TextField(blank=True, default="")),
                (
                    "outstanding_balance_at_repossession",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_repossessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_repossessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice_issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_repossession_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repossession",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "repossessions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="defectclaim",
            index=models.Index(
                fields=["subscription", "status"], name="defect_clai_subscri_de44fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defectclaim",
            index=models.Index(
                fields=["severity", "status"], name="defect_clai_severit_4f2b77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="defectclaim",
            index=models.Index(
                fields=["reported_at"], name="defect_clai_reporte_1b90ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerreturnrequest",
            index=models.Index(
                fields=["subscription", "status"], name="consumer_re_subscri_5baaf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerreturnrequest",
            index=models.Index(
                fields=["refund_deadline"], name="consumer_re_refund__fa5a18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consumerreturnrequest",
            index=models.Index(
                fields=["delivery_date"], name="consumer_re_deliver_12f6b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drawauthorisation",
            index=models.Index(
                fields=["batch", "status"], name="draw_author_batch_i_07ff37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drawauthorisation",
            index=models.Index(
                fields=["authorised_at"], name="draw_author_authori_30ddc7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawauthorisation",
            constraint=models.CheckConstraint(
                condition=models.Q(("draw_month__gt", 0)),
                name="chk_draw_auth_month_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drawauthorisation",
            unique_together={("batch", "draw_month")},
        ),
        migrations.AddIndex(
            model_name="emiwaiversettlement",
            index=models.Index(
                fields=["subscription", "settlement_date"],
                name="emi_waiver__subscri_c4f0b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emiwaiversettlement",
            index=models.Index(
                fields=["lucky_draw"], name="emi_waiver__lucky_d_3b5b86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emiwaiversettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gt", 0)),
                name="chk_emi_waiver_settlement_amount_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emiwaiversettlement",
            unique_together={("lucky_draw", "emi")},
        ),
        migrations.AddIndex(
            model_name="repossession",
            index=models.Index(fields=["status"], name="repossessio_status_41b79a_idx"),
        ),
        migrations.AddIndex(
            model_name="repossession",
            index=models.Index(
                fields=["notice_issued_at"], name="repossessio_notice__501288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repossession",
            index=models.Index(
                fields=["response_deadline"], name="repossessio_respons_833a0e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="repossession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outstanding_balance_at_repossession__gte", 0),
                    ("outstanding_balance_at_repossession__isnull", True),
                    _connector="OR",
                ),
                name="chk_repossession_balance_non_negative",
            ),
        ),
    ]
