# Generated by Django 5.2.7 on 2026-07-10 19:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0049_compliance_phase3_pay_rent_contract"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("subscriptions", "0118_compliance_phase2_lp_rent_consumer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositForfeitureTaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("invoice_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "forfeited_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST rate applicable on the forfeited deposit (%).",
                        max_digits=5,
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("forfeiture_reason", models.TextField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "deposit_forfeiture_tax_invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Caller-supplied idempotency key; duplicate submissions with the same key are rejected.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="agreement_pdf_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 hex digest of the signed contract PDF (CTRL-RENT-3).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="agreement_pdf_sealed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the agreement PDF hash was committed.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uq_payment_idempotency_key",
            ),
        ),
        migrations.AddField(
            model_name="depositforfeituretaxinvoice",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancelled_forfeiture_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depositforfeituretaxinvoice",
            name="issued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_forfeiture_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="depositforfeituretaxinvoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_forfeiture_invoices",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="depositforfeituretaxinvoice",
            index=models.Index(
                fields=["subscription", "status"], name="deposit_for_subscri_4cd361_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depositforfeituretaxinvoice",
            index=models.Index(
                fields=["invoice_date"], name="deposit_for_invoice_607d11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depositforfeituretaxinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("forfeited_amount__gt", 0)),
                name="chk_forfeiture_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositforfeituretaxinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_invoice_amount__gt", 0)),
                name="chk_forfeiture_total_positive",
            ),
        ),
    ]
