# Generated by Django 5.2.7 on 2026-07-11 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0049_compliance_phase3_pay_rent_contract"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("subscriptions", "0119_compliance_phase3_pay_rent_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("emi__isnull", False)),
                fields=("emi",),
                name="uq_payment_per_emi",
            ),
        ),
    ]
