# Generated by Django 5.2.7 on 2026-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0120_ctrl_lp5_lp8_rent2_lock_gates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscompliancedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RENTAL_AGREEMENT", "Rental Agreement"),
                    ("OWNERSHIP_PROOF", "Ownership Proof"),
                    ("UDYAM_CERTIFICATE", "Udyam Certificate"),
                    ("GST_CERTIFICATE", "GST Certificate"),
                    ("SHOP_LICENSE", "Shop License"),
                    ("BANK_PROOF", "Bank Proof"),
                    ("PAN_OR_TAX_PROOF", "PAN/Tax Proof"),
                    ("CA_OPINION", "CA Written Opinion"),
                    ("ADVOCATE_OPINION", "Advocate Legal Opinion"),
                    ("LEGAL_NOTICE", "Legal Notice"),
                    ("COURT_ORDER", "Court Order / Judgment"),
                    ("LEGAL_AGREEMENT", "Signed Legal Agreement / Contract"),
                    ("SCHEME_APPROVAL_LETTER", "Scheme Approval Letter"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
