# Generated by Django 5.2.7 on 2026-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0121_alter_businesscompliancedocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("FINISHED_GOOD", "Finished Good"),
                    ("RAW_MATERIAL", "Raw Material"),
                    ("ACCESSORY", "Accessory"),
                    ("SERVICE", "Service"),
                    ("ADD_ON", "Add-on"),
                ],
                db_index=True,
                default="FINISHED_GOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_type",
            field=models.CharField(
                choices=[
                    ("STOCK_ITEM", "Stock Item"),
                    ("MADE_TO_ORDER", "Made to Order"),
                    ("NON_STOCK", "Non-Stock"),
                ],
                db_index=True,
                default="STOCK_ITEM",
                max_length=20,
            ),
        ),
    ]
