# Generated by Django 5.2.7 on 2026-07-12 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0122_add_item_type_stock_type_to_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ACCESSORY", "Accessory"),
                            ("RAW_MATERIAL", "Raw Material"),
                            ("SERVICE", "Service"),
                            ("ADD_ON", "Add-on"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_products",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "relationship_type"],
                        name="subscriptio_product_7df90d_idx",
                    ),
                    models.Index(
                        fields=["related_product"],
                        name="subscriptio_related_63bc7d_idx",
                    ),
                ],
                "unique_together": {
                    ("product", "related_product", "relationship_type")
                },
            },
        ),
    ]
