# Generated by Django 5.0.7 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("subscriptions", "0123_add_product_relationship_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_specs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="catalog_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="products", to="catalog.catalogcategory"),
        ),
    ]
