# Generated by Django 5.2.7 on 2026-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0125_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="uq_payment_per_emi",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="authorized_signatory_designation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Designation of the signatory (e.g. Proprietor, Director, Partner).",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="authorized_signatory_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Full name of the person authorized to sign invoices and legal documents.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="bank_branch",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="bank_ifsc_code",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOLE_PROPRIETORSHIP", "Sole Proprietorship"),
                    ("PARTNERSHIP", "Partnership Firm"),
                    ("LLP", "Limited Liability Partnership (LLP)"),
                    ("PRIVATE_LIMITED", "Private Limited Company"),
                    ("OPC", "One Person Company (OPC)"),
                    ("PUBLIC_LIMITED", "Public Limited Company"),
                    ("HUF", "Hindu Undivided Family (HUF)"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="cin_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company Identification Number (Pvt Ltd / LLP only). Printed on letterheads under Companies Act 2013.",
                max_length=21,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="shop_act_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shop & Establishment Act registration number (Shops Act license).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="tan_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tax Deduction Account Number. Required if the business deducts TDS.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="trade_license_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Trade License issued by the local municipal authority.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="udyam_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Udyam / MSME Registration Number (e.g. UDYAM-MH-00-0000000).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="upi_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UPI ID for QR / payment link on receipts (e.g. businessname@upi).",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Year the business was established (e.g. 2010). Printed on letterheads.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="commissionpayoutbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("FINALIZED", "Finalized"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
