# Generated by Django 5.2.7 on 2026-07-16 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0127_partner_collection_request_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="flag_reason",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="flagged_at",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="flagged_by",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="is_flagged_bad",
        ),
        migrations.CreateModel(
            name="PartnerCustomerKycRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("KYC_UPGRADE", "KYC Verification Request"),
                            ("LOGIN_ID_SETUP", "Login ID Setup Request"),
                            ("KYC_DOCUMENT_UPLOAD", "KYC Document Upload Request"),
                        ],
                        db_index=True,
                        default="KYC_UPGRADE",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MORE_INFO", "More Information Needed"),
                            ("IN_PROGRESS", "In Progress"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_kyc_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_kyc_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_partner_kyc_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["partner", "status"],
                        name="subscriptio_partner_09117e_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="subscriptio_custome_13fece_idx",
                    ),
                ],
            },
        ),
    ]
