# Generated by Django 5.2.7 on 2026-07-17 04:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billinginvoice_tax_profile_snapshot_and_more"),
        ("subscriptions", "0128_partner_customer_kyc_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "requester_role_snapshot",
                    models.CharField(db_index=True, max_length=20),
                ),
                (
                    "requested_customer_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requested_customer_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "requested_customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "requested_customer_address",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "requested_customer_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE_EMI", "Advance EMI"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                            ("DIRECT_SALE", "Direct Sale"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "preferred_lucky_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "requested_tenure_months_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "approved_direct_sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_request",
                        to="billing.directsale",
                    ),
                ),
                (
                    "approved_subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_request",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_requests",
                        to="subscriptions.batch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_product_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_requests",
                        to="subscriptions.product",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_product_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_requests",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["requester", "status"],
                        name="product_req_request_f0fc57_idx",
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="product_req_custome_2a9f9c_idx",
                    ),
                    models.Index(
                        fields=["request_type", "status"],
                        name="product_req_request_598809_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="product_req_created_b78d40_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("preferred_lucky_number__isnull", True),
                            models.Q(
                                ("preferred_lucky_number__gte", 0),
                                ("preferred_lucky_number__lte", 99),
                            ),
                            _connector="OR",
                        ),
                        name="chk_product_request_lucky_number_range",
                    )
                ],
            },
        ),
    ]
