# Generated by Django 5.2.7 on 2026-07-17 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0130_workbenchitem_workbenchaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PincodeDatabase",
            fields=[
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pin",
                                message="PIN must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pincode_database",
                "indexes": [
                    models.Index(fields=["city"], name="pincode_dat_city_92a913_idx"),
                    models.Index(fields=["state"], name="pincode_dat_state_e05de3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("OFFICE", "Office"),
                            ("OTHER", "Other"),
                        ],
                        default="HOME",
                        max_length=10,
                    ),
                ),
                ("line1", models.CharField(help_text="Street address", max_length=200)),
                (
                    "line2",
                    models.CharField(
                        blank=True, help_text="Apartment, suite, etc.", max_length=200
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        help_text="6-digit postal index number",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pin",
                                message="PIN must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_delivery_address", models.BooleanField(default=True)),
                ("is_billing_address", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="subscriptions.customer",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "is_primary"],
                        name="addresses_custome_0997af_idx",
                    ),
                    models.Index(
                        fields=["postal_code"], name="addresses_postal__0e4029_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="addresses_city_39f647_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_codes",
                    models.JSONField(
                        default=list, help_text="List of service postal codes"
                    ),
                ),
                (
                    "delivery_days",
                    models.IntegerField(default=3, help_text="Standard delivery days"),
                ),
                (
                    "delivery_cost_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_cost_per_km",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_zones",
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"],
                        name="service_zon_vendor__176bfb_idx",
                    ),
                    models.Index(fields=["city"], name="service_zon_city_5679c5_idx"),
                ],
                "unique_together": {("vendor", "city", "state")},
            },
        ),
    ]
