# Generated by Django 5.2.7 on 2026-07-17 10:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billinginvoice_tax_profile_snapshot_and_more"),
        ("subscriptions", "0131_add_address_pincode_workbench"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated request number (e.g., ORQ-2026-00001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE_EMI", "Advance EMI"),
                            ("DIRECT_SALE", "Direct Sale"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "preferred_tenure",
                    models.IntegerField(blank=True, help_text="Months", null=True),
                ),
                ("preferred_lucky_number", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="quantity * unit_price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST percentage (default 18%)",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="sub_total + gst_amount + delivery_cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUOTE_SENT", "Quote Sent"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("quote_generated_at", models.DateTimeField(blank=True, null=True)),
                ("quote_expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_online_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_direct_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_request",
                        to="billing.directsale",
                    ),
                ),
                (
                    "approved_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_request",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_requests",
                        to="subscriptions.batch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_requests",
                        to="subscriptions.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_requests",
                        to="subscriptions.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Request",
                "verbose_name_plural": "Online Requests",
                "db_table": "online_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineRequestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUOTE_GENERATED", "Quote Generated"),
                            ("QUOTE_SENT", "Quote Sent"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_request_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="subscriptions.onlinerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Request Action",
                "verbose_name_plural": "Online Request Actions",
                "db_table": "online_request_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="onlinerequest",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="online_requ_custome_3ec599_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onlinerequest",
            index=models.Index(
                fields=["status", "-created_at"], name="online_requ_status_0cc26f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinerequest",
            index=models.Index(
                fields=["request_type", "-created_at"],
                name="online_requ_request_8926a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onlinerequest",
            index=models.Index(
                fields=["approved_by", "status"], name="online_requ_approve_922f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinerequestaction",
            index=models.Index(
                fields=["request", "-created_at"], name="online_requ_request_641e9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="onlinerequestaction",
            index=models.Index(
                fields=["action_type"], name="online_requ_action__7e3519_idx"
            ),
        ),
    ]
