# Generated by Django 5.2.7 on 2026-07-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_billinginvoice_tax_profile_snapshot_and_more"),
        ("subscriptions", "0132_add_online_request_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinerequest",
            name="approved_lease_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Lease-specific profile (if subscription is LEASE type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request",
                to="subscriptions.leasesubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="approved_rent_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Rent-specific profile (if subscription is RENT type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request",
                to="subscriptions.rentsubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="converted_product_request",
            field=models.OneToOneField(
                blank=True,
                help_text="ProductRequest created when quote is accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request_source",
                to="subscriptions.productrequest",
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="converted_subscription_request",
            field=models.OneToOneField(
                blank=True,
                help_text="SubscriptionRequest created when quote is accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request_source",
                to="subscriptions.subscriptionrequest",
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="source_public_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Original PublicLead if this request came from public enquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_requests_from_lead",
                to="subscriptions.publiclead",
            ),
        ),
        migrations.AddField(
            model_name="productrequest",
            name="approved_lease_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Lease-specific profile (if subscription is LEASE type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_request",
                to="subscriptions.leasesubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="productrequest",
            name="approved_rent_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Rent-specific profile (if subscription is RENT type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_request",
                to="subscriptions.rentsubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="productrequest",
            name="source_public_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Original PublicLead if this request came from public enquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_requests_from_lead",
                to="subscriptions.publiclead",
            ),
        ),
        migrations.AddField(
            model_name="publiclead",
            name="converted_online_request",
            field=models.ForeignKey(
                blank=True,
                help_text="OnlineRequest created when enquiry moved to quote workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_lead_source",
                to="subscriptions.onlinerequest",
            ),
        ),
        migrations.AddField(
            model_name="publiclead",
            name="converted_product_request",
            field=models.ForeignKey(
                blank=True,
                help_text="ProductRequest created when quote accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_lead_source",
                to="subscriptions.productrequest",
            ),
        ),
        migrations.AddField(
            model_name="publiclead",
            name="converted_subscription_request",
            field=models.ForeignKey(
                blank=True,
                help_text="SubscriptionRequest created when quote accepted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_lead_source",
                to="subscriptions.subscriptionrequest",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="approved_direct_sale",
            field=models.OneToOneField(
                blank=True,
                help_text="Direct sale/invoice created",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_request",
                to="billing.directsale",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="approved_lease_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Lease-specific profile (if subscription is LEASE type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_request",
                to="subscriptions.leasesubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="approved_rent_profile",
            field=models.OneToOneField(
                blank=True,
                help_text="Rent-specific profile (if subscription is RENT type)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_request",
                to="subscriptions.rentsubscriptionprofile",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionrequest",
            name="source_public_lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Original PublicLead if this request came from public enquiry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_requests_from_lead",
                to="subscriptions.publiclead",
            ),
        ),
        migrations.AlterField(
            model_name="onlinerequest",
            name="approved_direct_sale",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct sale/invoice created",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request",
                to="billing.directsale",
            ),
        ),
        migrations.AlterField(
            model_name="onlinerequest",
            name="approved_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription created (Advance EMI, Rent, or Lease)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="online_request",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="approved_direct_sale",
            field=models.OneToOneField(
                blank=True,
                help_text="Direct sale/invoice created",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_request",
                to="billing.directsale",
            ),
        ),
        migrations.AlterField(
            model_name="productrequest",
            name="approved_subscription",
            field=models.OneToOneField(
                blank=True,
                help_text="Subscription created (Advance EMI, Rent, or Lease)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_request",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="publiclead",
            name="converted_customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer account created when public lead registers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_public_leads",
                to="subscriptions.customer",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="approved_subscription",
            field=models.OneToOneField(
                blank=True,
                help_text="Subscription created (Advance EMI, Rent, or Lease)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_request",
                to="subscriptions.subscription",
            ),
        ),
    ]
