# Generated by Django 5.2.7 on 2026-07-18 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0133_onlinerequest_approved_lease_profile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinerequest",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft - Awaiting Quote"),
                    ("QUOTED", "Quoted - Awaiting Approval"),
                    ("APPROVED", "Approved - Contract Created"),
                    ("CONVERTED", "Converted - Sale/Subscription Active"),
                    ("REJECTED", "Rejected"),
                    ("LOST", "Lost Lead"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Unified workflow status (separate from status field)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="approved_entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_SALE", "Direct Sale"),
                    ("SUBSCRIPTION", "EMI/Subscription"),
                    ("RENT", "Rent Contract"),
                    ("LEASE", "Lease Contract"),
                ],
                help_text="Which contract type was approved",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="auto_conversion_enabled",
            field=models.BooleanField(
                default=True, help_text="Auto-create contract on approval"
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="conversion_notes",
            field=models.TextField(
                blank=True, help_text="Notes about conversion/approval"
            ),
        ),
        migrations.AddField(
            model_name="onlinerequest",
            name="expected_close_date",
            field=models.DateField(
                blank=True, help_text="Expected sale close date", null=True
            ),
        ),
        migrations.CreateModel(
            name="CRMPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("ENQUIRY", "Online Enquiry"),
                            ("QUOTED", "Quoted"),
                            ("APPROVED", "Approved"),
                            ("CONVERTED", "Converted to Contract"),
                            ("ACTIVE", "Active Sale/Subscription"),
                            ("LOST", "Lost"),
                            ("WON", "Won"),
                        ],
                        db_index=True,
                        default="LEAD",
                        max_length=20,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "EMI/Subscription"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "EMI/Subscription"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        help_text="Which contract type was created",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "converted_entity_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of DirectSale/Subscription/RentProfile/LeaseProfile",
                        null=True,
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount quoted to customer",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confirmed contract value",
                        max_digits=12,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=50, help_text="Sales probability percentage"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, help_text="Expected date for conversion", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_pipeline_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        help_text="Original public lead",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_pipeline",
                        to="subscriptions.publiclead",
                    ),
                ),
                (
                    "online_request",
                    models.OneToOneField(
                        blank=True,
                        help_text="Online enquiry from customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_pipeline",
                        to="subscriptions.onlinerequest",
                    ),
                ),
            ],
            options={
                "db_table": "crm_pipeline",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["current_stage", "created_at"],
                        name="crm_pipelin_current_7c26d2_idx",
                    ),
                    models.Index(
                        fields=["approved_by", "approved_at"],
                        name="crm_pipelin_approve_c67207_idx",
                    ),
                    models.Index(
                        fields=["lead", "current_stage"],
                        name="crm_pipelin_lead_id_601ad3_idx",
                    ),
                ],
            },
        ),
    ]
