# Generated by Django 5.2.7 on 2026-07-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0136_alter_auditlog_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeradvance",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customeradvancerefund",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="partnercollectionrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rentleasecollection",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rentleasedeposittransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Cash"),
                    ("UPI", "UPI"),
                    ("BANK", "Bank"),
                    ("CARD", "Card"),
                    ("TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("DEPOSIT", "Bank Deposit"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
    ]
