# Generated by Django 5.2.7 on 2026-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0137_alter_customeradvance_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrelationship",
            name="is_price_included_in_parent",
            field=models.BooleanField(
                default=True,
                help_text="If true, the cost is included in the parent's base price. If false, it acts as an extra add-on cost.",
            ),
        ),
    ]
