# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0054_alter_customerpurchaseenquiry_product_and_more"),
        ("billing", "0016_alter_billinginvoiceline_product_and_more"),
        ("brochures", "0005_alter_brochureenquiryproduct_product_and_more"),
        ("contracts", "0002_initial"),
        ("crm", "0010_alter_lead_interested_product_and_more"),
        ("customers", "0002_initial"),
        ("inventory", "0024_alter_inventoryitem_product_and_more"),
        ("lucky_plan", "0002_initial"),
        ("payments", "0001_initial"),
        ("privacy", "0003_alter_cookieconsent_customer_and_more"),
        ("products_core", "0001_initial"),
        ("products_pim", "0005_alter_pimproduct_source_product"),
        (
            "reconciliation",
            "0004_alter_financialsourcelifecycleevent_related_cancellation_and_more",
        ),
        ("reminders", "0006_alter_paymentreminder_target_customer_and_more"),
        ("service_desk", "0009_alter_servicedeskcase_delivery_and_more"),
        ("settlements", "0002_alter_settlementallocation_payment"),
        ("subscriptions", "0138_productrelationship_is_price_included_in_parent"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
            model_name="address",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="assetconditionsnapshot",
            name="assessed_by",
        ),
        migrations.RemoveField(
            model_name="assetconditionsnapshot",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="assetconditionsnapshot",
            name="document",
        ),
        migrations.RemoveField(
            model_name="assetconditionsnapshot",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="luckyid",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="drawcommit",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="drawauthorisation",
            name="batch",
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="lucky_plan.batch",
            ),
        ),
        migrations.RemoveField(
            model_name="luckydraw",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="batch",
        ),
        migrations.AlterField(
            model_name="workbenchitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workbench_items",
                to="lucky_plan.batch",
            ),
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="cash_counter",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="cashier",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="closed_by",
        ),
        migrations.RemoveField(
            model_name="cashcountersession",
            name="opened_by",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="emi",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="commissionpayoutline",
            name="commission",
        ),
        migrations.RemoveField(
            model_name="commissionpayoutbatch",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="commissionpayoutbatch",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="commissionpayoutline",
            name="payout_batch",
        ),
        migrations.RemoveField(
            model_name="commissionpayoutline",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="consumerreturnrequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="consumerreturnrequest",
            name="defect_claim",
        ),
        migrations.RemoveField(
            model_name="consumerreturnrequest",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="consumerreturnrequest",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="implemented_by",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="rent_lease_contract",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="amendment",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="admin_approved_by",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="customer_consented_by",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="new_product",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="old_product",
        ),
        migrations.RemoveField(
            model_name="contractrecontractevent",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="contractrecontractfinancialimpactpreview",
            name="event",
        ),
        migrations.RemoveField(
            model_name="contractrecontractscheduleline",
            name="event",
        ),
        migrations.RemoveField(
            model_name="contractrecontractfinancialimpactpreview",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contractrecontractscheduleline",
            name="original_emi",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="direct_sale",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="lease_contract",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="rent_contract",
        ),
        migrations.RemoveField(
            model_name="contractreference",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="contract_reference",
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="contract_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="contracts.contractreference",
            ),
        ),
        migrations.DeleteModel(
            name="ContractReferenceSequence",
        ),
        migrations.RemoveField(
            model_name="crmpipeline",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="crmpipeline",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="crmpipeline",
            name="online_request",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_by_partner_user",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_by_user",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="kyc_reviewed_by",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="pep_flagged_by",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_customer",
        ),
        migrations.RemoveField(
            model_name="partnercustomerkycrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customeradvancerefund",
            name="customer",
        ),
        migrations.AlterField(
            model_name="customergrowthrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests",
                to="customers.customer",
            ),
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerdispute",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerreferral",
            name="referrer",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="customer",
        ),
        migrations.AlterField(
            model_name="workbenchitem",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workbench_items",
                to="customers.customer",
            ),
        ),
        migrations.RemoveField(
            model_name="customerkycdocument",
            name="customer",
        ),
        migrations.AlterField(
            model_name="amlscreeningrecord",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aml_screenings",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="customers.customer",
            ),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="productpossession",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerriskprofile",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="operationalcancellation",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customerreferral",
            name="referred",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="current_customer",
        ),
        migrations.RemoveField(
            model_name="customersupportrequest",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="cash_counter",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="collected_by",
        ),
        migrations.RemoveField(
            model_name="customeradvance",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="customeradvancerefund",
            name="advance",
        ),
        migrations.RemoveField(
            model_name="customeradvanceallocation",
            name="advance",
        ),
        migrations.RemoveField(
            model_name="customeradvanceallocation",
            name="allocated_by",
        ),
        migrations.RemoveField(
            model_name="customeradvanceallocation",
            name="emi",
        ),
        migrations.RemoveField(
            model_name="customeradvanceallocation",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="customeradvanceallocation",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="customeradvancerefund",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customeradvancerefund",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="customeradvancerefund",
            name="voided_by",
        ),
        migrations.RemoveField(
            model_name="customerdispute",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="customerdispute",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customerdispute",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="customerkycdocument",
            name="resubmission_of",
        ),
        migrations.RemoveField(
            model_name="customerkycdocument",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="customerkycdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="customerreferral",
            name="commission_approved_by",
        ),
        migrations.RemoveField(
            model_name="customerreferral",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="customersupportrequest",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="customersupportrequest",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="customersupportrequest",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="customersupportrequest",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="dailycloserun",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="dailycloserun",
            name="run_by",
        ),
        migrations.AlterField(
            model_name="dailyclosecheckresult",
            name="close_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_results",
                to="payments.dailycloserun",
            ),
        ),
        migrations.RemoveField(
            model_name="defectclaim",
            name="cpa_override_by",
        ),
        migrations.RemoveField(
            model_name="defectclaim",
            name="reported_by",
        ),
        migrations.RemoveField(
            model_name="defectclaim",
            name="resolved_by",
        ),
        migrations.RemoveField(
            model_name="defectclaim",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="proofofdelivery",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="depositforfeituretaxinvoice",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="depositforfeituretaxinvoice",
            name="issued_by",
        ),
        migrations.RemoveField(
            model_name="depositforfeituretaxinvoice",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="documentaccesslog",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentaccesslog",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="drawauthorisation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="drawauthorisation",
            name="authorised_by",
        ),
        migrations.RemoveField(
            model_name="drawauthorisation",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="drawcommit",
            name="committed_by",
        ),
        migrations.RemoveField(
            model_name="luckydraw",
            name="draw_commit",
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="lucky_id",
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="product",
        ),
        migrations.RemoveField(
            model_name="draweligibilitysnapshot",
            name="subscription",
        ),
        migrations.AlterUniqueTogether(
            name="emi",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="emi",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="approved_emi",
        ),
        migrations.RemoveField(
            model_name="paymentreconciliation",
            name="matched_emi",
        ),
        migrations.RemoveField(
            model_name="financialledger",
            name="emi",
        ),
        migrations.RemoveField(
            model_name="emiwaiversettlement",
            name="emi",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="emi",
        ),
        migrations.RemoveField(
            model_name="emischeme",
            name="applicable_products",
        ),
        migrations.RemoveField(
            model_name="emischeme",
            name="created_by",
        ),
        migrations.AlterUniqueTogether(
            name="emiwaiversettlement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="emiwaiversettlement",
            name="lucky_draw",
        ),
        migrations.RemoveField(
            model_name="emiwaiversettlement",
            name="settled_by",
        ),
        migrations.RemoveField(
            model_name="emiwaiversettlement",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="financialledger",
            name="journal_group",
        ),
        migrations.RemoveField(
            model_name="financialledger",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="kycreviewaction",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="leasesubscriptionprofile",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="approved_lease_profile",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="approved_lease_profile",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="approved_lease_profile",
        ),
        migrations.AlterUniqueTogether(
            name="luckydraw",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="luckydraw",
            name="winner_lucky_id",
        ),
        migrations.RemoveField(
            model_name="luckydraw",
            name="winner_subscription",
        ),
        migrations.RemoveField(
            model_name="luckydraw",
            name="winner_verified_by",
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="lucky_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="lucky_plan.luckyid",
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="lucky_id",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="approved_direct_sale",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="approved_rent_profile",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="approved_subscription",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="converted_product_request",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="converted_subscription_request",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="product",
        ),
        migrations.RemoveField(
            model_name="onlinerequest",
            name="source_public_lead",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_online_request",
        ),
        migrations.RemoveField(
            model_name="onlinerequestaction",
            name="request",
        ),
        migrations.RemoveField(
            model_name="onlinerequestaction",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="operationalcancellation",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="operationalcancellation",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="operationalcancellation",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="operationalcancellation",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="approved_payment",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="partnercollectionrequest",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="partnercustomerkycrequest",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="partnercustomerkycrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="partnerkycdocument",
            name="partner_user",
        ),
        migrations.RemoveField(
            model_name="partnerkycdocument",
            name="resubmission_of",
        ),
        migrations.RemoveField(
            model_name="partnerkycdocument",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="partnerkycdocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="cash_counter",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="collected_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="verified_by",
        ),
        migrations.RemoveField(
            model_name="paymentreconciliation",
            name="payment",
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="payments.payment",
            ),
        ),
        migrations.RemoveField(
            model_name="paymentreconciliation",
            name="reconciled_by",
        ),
        migrations.RemoveField(
            model_name="paymentreconciliationevent",
            name="reconciliation",
        ),
        migrations.RemoveField(
            model_name="paymentreconciliationevent",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="product",
            name="catalog_category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_master",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subcategory_master",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_of_measure_master",
        ),
        migrations.RemoveField(
            model_name="productrelationship",
            name="related_product",
        ),
        migrations.RemoveField(
            model_name="productpossession",
            name="product",
        ),
        migrations.AlterField(
            model_name="customergrowthrequest",
            name="current_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests_as_current",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="offerpackageline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offer_package_lines",
                to="products_core.product",
            ),
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="product",
        ),
        migrations.AlterField(
            model_name="growthrequestline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_request_lines",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="customergrowthrequest",
            name="requested_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests_as_requested",
                to="products_core.product",
            ),
        ),
        migrations.RemoveField(
            model_name="productrelationship",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="product",
        ),
        migrations.AlterField(
            model_name="workbenchitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workbench_items",
                to="products_core.product",
            ),
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="product",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="product",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productsubcategorymaster",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productpossession",
            name="handed_over_by",
        ),
        migrations.RemoveField(
            model_name="productpossession",
            name="returned_to",
        ),
        migrations.RemoveField(
            model_name="productpossession",
            name="subscription",
        ),
        migrations.AlterUniqueTogether(
            name="productrelationship",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="approved_direct_sale",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="approved_rent_profile",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="approved_subscription",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="productrequest",
            name="source_public_lead",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_product_request",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_by",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_direct_sale",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_subscription",
        ),
        migrations.RemoveField(
            model_name="publiclead",
            name="converted_subscription_request",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="source_public_lead",
        ),
        migrations.RemoveField(
            model_name="recoverycase",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="recoverycase",
            name="settlement_approved_by",
        ),
        migrations.RemoveField(
            model_name="recoverycase",
            name="settlement_requested_by",
        ),
        migrations.RemoveField(
            model_name="recoverycase",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="current_location",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="current_subscription",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="inventory_item",
        ),
        migrations.RemoveField(
            model_name="rentalasset",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="rentleasebillingdemand",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="demand",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="demand",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentleasecollection",
            name="voided_by",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="finance_account",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="inspection",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentleasedeposittransaction",
            name="voided_by",
        ),
        migrations.RemoveField(
            model_name="rentleasereturninspection",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="rentleasereturninspection",
            name="inspected_by",
        ),
        migrations.RemoveField(
            model_name="rentleasereturninspection",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="rentsubscriptionprofile",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="approved_rent_profile",
        ),
        migrations.RemoveField(
            model_name="repossession",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="repossession",
            name="initiated_by",
        ),
        migrations.RemoveField(
            model_name="repossession",
            name="notice_issued_by",
        ),
        migrations.RemoveField(
            model_name="repossession",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="cancelled_by",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="terms_locked_by",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="approved_subscription",
        ),
        migrations.AlterField(
            model_name="customergrowthrequest",
            name="source_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests",
                to="contracts.subscription",
            ),
        ),
        migrations.RemoveField(
            model_name="subscriptionguarantor",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptiondocument",
            name="subscription",
        ),
        migrations.AlterField(
            model_name="businesseventlog",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_events",
                to="contracts.subscription",
            ),
        ),
        migrations.RemoveField(
            model_name="subscriptiondelivery",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="subscriptiondelivery",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="subscriptiondelivery",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="subscriptiondocument",
            name="generated_by",
        ),
        migrations.RemoveField(
            model_name="subscriptiondocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="subscriptiondocument",
            name="verified_by",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="approved_direct_sale",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="partner",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="requester",
        ),
        migrations.RemoveField(
            model_name="subscriptionrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="unifiedcollectionidempotency",
            name="user",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User Created"),
                    ("USER_UPDATED", "User Updated"),
                    ("PUBLIC_SITE_UPDATED", "Public Site Updated"),
                    ("EMAIL_SMTP_SETTINGS_UPDATED", "Email SMTP Settings Updated"),
                    ("EMAIL_SMTP_TEST_SENT", "Email SMTP Test Sent"),
                    ("USER_ACTIVATED", "User Activated"),
                    ("USER_DEACTIVATED", "User Deactivated"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("PARTNER_COMMISSION_SET", "Partner Commission Set"),
                    ("PARTNER_COMMISSION_UPDATED", "Partner Commission Updated"),
                    ("LEAD_CREATED", "Lead Created"),
                    ("LEAD_STATUS_UPDATED", "Lead Status Updated"),
                    ("LEAD_ASSIGNED", "Lead Assigned"),
                    ("LEAD_NOTE_UPDATED", "Lead Notes Updated"),
                    ("LEAD_CUSTOMER_LINKED", "Lead Customer Linked"),
                    ("LEAD_SUBSCRIPTION_LINKED", "Lead Subscription Linked"),
                    ("LEAD_DIRECT_SALE_LINKED", "Lead Direct Sale Linked"),
                    ("LEAD_CONVERTED", "Lead Converted"),
                    ("CRM_PARTY_CREATED", "CRM Party Created"),
                    ("CRM_PARTY_LINKED", "CRM Party Linked"),
                    ("CRM_INTERACTION_CREATED", "CRM Interaction Created"),
                    ("CRM_INTERACTION_UPDATED", "CRM Interaction Updated"),
                    ("SUPPORT_REQUEST_CREATED", "Support Request Created"),
                    (
                        "SUPPORT_REQUEST_STATUS_UPDATED",
                        "Support Request Status Updated",
                    ),
                    ("SUPPORT_REQUEST_ASSIGNED", "Support Request Assigned"),
                    ("SUPPORT_REQUEST_NOTE_UPDATED", "Support Request Notes Updated"),
                    ("SUPPORT_REQUEST_RESOLVED", "Support Request Resolved"),
                    (
                        "SUPPORT_REQUEST_RESOLUTION_RECORDED",
                        "Support Request Resolution Recorded",
                    ),
                    ("SERVICE_DESK_CASE_CREATED", "Service Desk Case Created"),
                    ("SERVICE_DESK_CASE_UPDATED", "Service Desk Case Updated"),
                    (
                        "SERVICE_DESK_CASE_STATUS_UPDATED",
                        "Service Desk Case Status Updated",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURN_REQUESTED",
                        "Service Desk Case Delivery Return Requested",
                    ),
                    (
                        "SERVICE_DESK_CASE_DELIVERY_RETURNED",
                        "Service Desk Case Delivery Returned",
                    ),
                    (
                        "SERVICE_DESK_CASE_CREDIT_NOTE_POSTED",
                        "Service Desk Case Credit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_DEBIT_NOTE_POSTED",
                        "Service Desk Case Debit Note Posted",
                    ),
                    (
                        "SERVICE_DESK_CASE_REPLACEMENT_LINKED",
                        "Service Desk Case Replacement Linked",
                    ),
                    ("DELIVERY_CREATED", "Delivery Created"),
                    ("DELIVERY_UPDATED", "Delivery Updated"),
                    ("DELIVERY_STATUS_CHANGED", "Delivery Status Changed"),
                    ("DELIVERY_DISPATCHED", "Delivery Dispatched"),
                    ("DELIVERY_COMPLETED", "Delivery Completed"),
                    ("DELIVERY_FAILED", "Delivery Failed"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                    ("DELIVERY_RETURN_REQUESTED", "Delivery Return Requested"),
                    ("DELIVERY_RETURNED", "Delivery Returned"),
                    ("SUB_CREATED", "Subscription Created"),
                    ("SUBSCRIPTION_REQUEST_CREATED", "Subscription Request Created"),
                    ("SUBSCRIPTION_REQUEST_APPROVED", "Subscription Request Approved"),
                    ("SUBSCRIPTION_REQUEST_REJECTED", "Subscription Request Rejected"),
                    (
                        "SUBSCRIPTION_REQUEST_CANCELLED",
                        "Subscription Request Cancelled",
                    ),
                    ("SUBSCRIPTION_REQUEST_HELD", "Subscription Request Put On Hold"),
                    (
                        "SUBSCRIPTION_REQUEST_AMENDMENT_REQUESTED",
                        "Subscription Request Amendment Requested",
                    ),
                    ("PRODUCT_REQUEST_APPROVED", "Product Request Approved"),
                    ("PRODUCT_REQUEST_REJECTED", "Product Request Rejected"),
                    ("PRODUCT_REQUEST_CANCELLED", "Product Request Cancelled"),
                    ("PRODUCT_REQUEST_EDITED", "Product Request Edited"),
                    ("EMI_PAID", "EMI Paid"),
                    ("EMI_WAIVED", "EMI Waived"),
                    ("DRAW_EXECUTED", "Draw Executed"),
                    ("DRAW_COMMITTED", "Draw Committed"),
                    ("DRAW_REVEALED", "Draw Revealed"),
                    ("DRAW_CERTIFICATE_PUBLISHED", "Draw Certificate Published"),
                    ("LUCKY_ID_BULK_ASSIGNED", "Lucky ID Bulk Assigned"),
                    ("LUCKY_ID_REASSIGNED", "Lucky ID Reassigned"),
                    ("DRAW_PUBLIC_VERIFIED", "Public Draw Verification Generated"),
                    ("DRAW_PUBLIC_RESULT_PUBLISHED", "Public Draw Result Published"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("WINNER_STATE_SYNCED", "Winner State Synced"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    (
                        "COMMISSION_PAYOUT_BATCH_CREATED",
                        "Commission Payout Batch Created",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_FINALIZED",
                        "Commission Payout Batch Finalized",
                    ),
                    (
                        "COMMISSION_PAYOUT_BATCH_CANCELLED",
                        "Commission Payout Batch Cancelled",
                    ),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    (
                        "PRODUCT_INVENTORY_PROFILE_PREPARED",
                        "Product Inventory Profile Prepared",
                    ),
                    ("CATALOG_CREATED", "Catalog Record Created"),
                    ("CATALOG_UPDATED", "Catalog Record Updated"),
                    ("INVENTORY_ITEM_CREATED", "Inventory Item Created"),
                    ("INVENTORY_ITEM_UPDATED", "Inventory Item Updated"),
                    ("STOCK_LOCATION_CREATED", "Stock Location Created"),
                    ("STOCK_LOCATION_UPDATED", "Stock Location Updated"),
                    ("STOCK_ADJUSTMENT_CREATED", "Stock Adjustment Created"),
                    ("STOCK_ADJUSTMENT_UPDATED", "Stock Adjustment Updated"),
                    ("STOCK_ADJUSTMENT_APPROVED", "Stock Adjustment Approved"),
                    ("STOCK_ADJUSTMENT_POSTED", "Stock Adjustment Posted"),
                    ("VENDOR_CONTACT_CREATED", "Vendor Contact Created"),
                    ("PURCHASE_ORDER_CREATED", "Purchase Order Created"),
                    ("PURCHASE_ORDER_UPDATED", "Purchase Order Updated"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase Order Cancelled"),
                    ("GOODS_RECEIPT_CREATED", "Goods Receipt Created"),
                    ("GOODS_RECEIPT_POSTED", "Goods Receipt Posted"),
                    ("VENDOR_BILL_CREATED", "Vendor Bill Created"),
                    ("VENDOR_BILL_POSTED", "Vendor Bill Posted"),
                    ("VENDOR_PAYMENT_CREATED", "Vendor Payment Created"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor Payment Posted"),
                    ("OPENING_STOCK_IMPORTED", "Opening Stock Imported"),
                    (
                        "DELIVERY_INVENTORY_BRIDGE_SYNCED",
                        "Delivery Inventory Bridge Synced",
                    ),
                    ("MANUFACTURING_BOM_CREATED", "Manufacturing BOM Created"),
                    ("MANUFACTURING_BOM_UPDATED", "Manufacturing BOM Updated"),
                    (
                        "MANUFACTURING_BOM_STATUS_UPDATED",
                        "Manufacturing BOM Status Updated",
                    ),
                    ("PRODUCTION_JOB_CREATED", "Production Job Created"),
                    ("PRODUCTION_JOB_UPDATED", "Production Job Updated"),
                    ("PRODUCTION_JOB_STATUS_UPDATED", "Production Job Status Updated"),
                    (
                        "PRODUCTION_MATERIAL_MOVEMENT_POSTED",
                        "Production Material Movement Posted",
                    ),
                    ("PRODUCTION_OUTPUT_POSTED", "Production Output Posted"),
                    ("SOLOPRENEUR_DAILY_CLOSE", "Solopreneur Daily Close"),
                    ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                    ("PASSWORD_RESET_VERIFIED", "Password Reset Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PASSWORD_RESET_FAILED", "Password Reset Failed"),
                    ("PASSWORD_RESET_EXPIRED", "Password Reset Expired"),
                    ("PASSWORD_RESET_LOCKED", "Password Reset Locked"),
                    ("PASSWORD_RESET_RESENT", "Password Reset Resent"),
                    ("PASSWORD_RESET_INVALIDATED", "Password Reset Invalidated"),
                    ("CUSTOMER_CREATED", "Customer Created"),
                    ("CUSTOMER_QUICK_CREATED", "Customer Quick-Created (No Email)"),
                    ("CUSTOMER_EMAIL_ADDED", "Customer Email Added"),
                    ("CUSTOMER_EMAIL_CHANGED", "Customer Email Changed"),
                    ("CUSTOMER_PHOTO_UPDATED", "Customer Profile Photo Updated"),
                    (
                        "CUSTOMER_KYC_DOCUMENT_SUBMITTED",
                        "Customer KYC Document Submitted",
                    ),
                    ("CUSTOMER_KYC_APPROVED", "Customer KYC Approved"),
                    ("CUSTOMER_KYC_REJECTED", "Customer KYC Rejected"),
                    (
                        "CUSTOMER_KYC_EXCEPTION_APPROVED",
                        "Customer KYC Exception Approved (Admin Override)",
                    ),
                    ("CUSTOMER_REFERRAL_CREATED", "Customer Referral Created"),
                    (
                        "CUSTOMER_REFERRAL_COMMISSION_APPROVED",
                        "Customer Referral Commission Approved",
                    ),
                    ("CONTRACT_NUMBERED", "Contract Number Assigned"),
                    ("CONTRACT_TERMS_LOCKED", "Contract Financial Terms Locked"),
                    ("CONTRACT_APPROVED", "Contract Approved"),
                    ("CONTRACT_ACTIVATED", "Contract Activated"),
                    ("CONTRACT_CANCELLED", "Contract Cancelled"),
                    ("CONTRACT_CLOSED", "Contract Closed"),
                    ("CONTRACT_AMENDMENT_REQUESTED", "Contract Amendment Requested"),
                    ("CONTRACT_AMENDMENT_APPROVED", "Contract Amendment Approved"),
                    ("CONTRACT_AMENDMENT_REJECTED", "Contract Amendment Rejected"),
                    ("CONTRACT_AMENDMENT_APPLIED", "Contract Amendment Applied"),
                    (
                        "CONTRACT_AMENDMENT_IMPLEMENTED",
                        "Contract Amendment Implemented",
                    ),
                    (
                        "CONTRACT_POSSESSION_CREATED",
                        "Product Possession Record Created",
                    ),
                    (
                        "CONTRACT_POSSESSION_UPDATED",
                        "Product Possession Status Updated",
                    ),
                    ("CONTRACT_RETURN_INSPECTION_CREATED", "Return Inspection Created"),
                    (
                        "CONTRACT_RETURN_INSPECTION_APPROVED",
                        "Return Inspection Approved",
                    ),
                    ("CONTRACT_DOCUMENT_REGENERATED", "Contract Document Regenerated"),
                    ("RENTAL_ASSET_CREATED", "Rental Asset Created"),
                    ("RENTAL_ASSET_RESERVED", "Rental Asset Reserved"),
                    ("RENTAL_ASSET_HANDED_OVER", "Rental Asset Handed Over"),
                    ("RENTAL_ASSET_RETURNED", "Rental Asset Returned"),
                    ("RENTAL_ASSET_UNDER_REPAIR", "Rental Asset Sent for Repair"),
                    ("RENTAL_ASSET_RETIRED", "Rental Asset Retired"),
                    (
                        "RENTAL_ASSET_CONDITION_SNAPSHOT",
                        "Asset Condition Snapshot Recorded",
                    ),
                ],
                db_index=True,
                default="SUB_CREATED",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="AssetConditionSnapshot",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="CashCounterSession",
        ),
        migrations.DeleteModel(
            name="Commission",
        ),
        migrations.DeleteModel(
            name="CommissionPayoutBatch",
        ),
        migrations.DeleteModel(
            name="CommissionPayoutLine",
        ),
        migrations.DeleteModel(
            name="ConsumerReturnRequest",
        ),
        migrations.DeleteModel(
            name="ContractAmendment",
        ),
        migrations.DeleteModel(
            name="ContractRecontractEvent",
        ),
        migrations.DeleteModel(
            name="ContractRecontractFinancialImpactPreview",
        ),
        migrations.DeleteModel(
            name="ContractRecontractScheduleLine",
        ),
        migrations.DeleteModel(
            name="ContractReference",
        ),
        migrations.DeleteModel(
            name="CRMPipeline",
        ),
        migrations.DeleteModel(
            name="CustomerRiskProfile",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="CustomerAdvance",
        ),
        migrations.DeleteModel(
            name="CustomerAdvanceAllocation",
        ),
        migrations.DeleteModel(
            name="CustomerAdvanceRefund",
        ),
        migrations.DeleteModel(
            name="CustomerDispute",
        ),
        migrations.DeleteModel(
            name="CustomerKycDocument",
        ),
        migrations.DeleteModel(
            name="CustomerReferral",
        ),
        migrations.DeleteModel(
            name="CustomerSupportRequest",
        ),
        migrations.DeleteModel(
            name="DailyCloseRun",
        ),
        migrations.DeleteModel(
            name="DefectClaim",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="ProofOfDelivery",
        ),
        migrations.DeleteModel(
            name="DepositForfeitureTaxInvoice",
        ),
        migrations.DeleteModel(
            name="DocumentAccessLog",
        ),
        migrations.DeleteModel(
            name="DrawAuthorisation",
        ),
        migrations.DeleteModel(
            name="DrawCommit",
        ),
        migrations.DeleteModel(
            name="DrawEligibilitySnapshot",
        ),
        migrations.DeleteModel(
            name="Emi",
        ),
        migrations.DeleteModel(
            name="EMIScheme",
        ),
        migrations.DeleteModel(
            name="EmiWaiverSettlement",
        ),
        migrations.DeleteModel(
            name="FinancialLedger",
        ),
        migrations.DeleteModel(
            name="KycReviewAction",
        ),
        migrations.DeleteModel(
            name="LeaseSubscriptionProfile",
        ),
        migrations.DeleteModel(
            name="LuckyDraw",
        ),
        migrations.DeleteModel(
            name="LuckyId",
        ),
        migrations.DeleteModel(
            name="OnlineRequest",
        ),
        migrations.DeleteModel(
            name="OnlineRequestAction",
        ),
        migrations.DeleteModel(
            name="OperationalCancellation",
        ),
        migrations.DeleteModel(
            name="PartnerCollectionRequest",
        ),
        migrations.DeleteModel(
            name="PartnerCustomerKycRequest",
        ),
        migrations.DeleteModel(
            name="PartnerKycDocument",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentReconciliation",
        ),
        migrations.DeleteModel(
            name="PaymentReconciliationEvent",
        ),
        migrations.DeleteModel(
            name="ProductUnitOfMeasureMaster",
        ),
        migrations.DeleteModel(
            name="ProductRelationship",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductCategoryMaster",
        ),
        migrations.DeleteModel(
            name="ProductSubcategoryMaster",
        ),
        migrations.DeleteModel(
            name="ProductPossession",
        ),
        migrations.DeleteModel(
            name="ProductRequest",
        ),
        migrations.DeleteModel(
            name="PublicLead",
        ),
        migrations.DeleteModel(
            name="RecoveryCase",
        ),
        migrations.DeleteModel(
            name="RentalAsset",
        ),
        migrations.DeleteModel(
            name="RentLeaseBillingDemand",
        ),
        migrations.DeleteModel(
            name="RentLeaseCollection",
        ),
        migrations.DeleteModel(
            name="RentLeaseDepositTransaction",
        ),
        migrations.DeleteModel(
            name="RentLeaseReturnInspection",
        ),
        migrations.DeleteModel(
            name="RentSubscriptionProfile",
        ),
        migrations.DeleteModel(
            name="Repossession",
        ),
        migrations.DeleteModel(
            name="SubscriptionGuarantor",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.DeleteModel(
            name="SubscriptionDelivery",
        ),
        migrations.DeleteModel(
            name="SubscriptionDocument",
        ),
        migrations.DeleteModel(
            name="SubscriptionRequest",
        ),
        migrations.DeleteModel(
            name="UnifiedCollectionIdempotency",
        ),
            ],
            database_operations=[]
        )
    ]
