# Generated by Django 5.2.7 on 2026-07-31 17:50

from django.db import migrations

# The 18 business-setup models moved to the `business_setup` app (state-only).
_MOVED_MODELS = [
    "businessprofile", "businessrulepolicy", "publicbusinessprofile", "policypage",
    "businesscompliancedocument", "branddatasource", "brandimportbatch",
    "brandimporteditem", "brandprofilesnapshot", "sociallink", "businessmediaasset",
    "publiccontentblock", "businessdatabackupjob", "businessdatarestorejob",
    "policygovernancemetadata", "businesscompliancedocumentreviewstate",
    "documentprintsettings", "emailsmtpsettings",
]


def repoint_contenttypes(apps, schema_editor):
    # Merge-aware repoint subscriptions -> business_setup (see Phase A lesson).
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in _MOVED_MODELS:
        old = ContentType.objects.filter(app_label="subscriptions", model=model).first()
        if old is None:
            continue
        if ContentType.objects.filter(app_label="business_setup", model=model).exists():
            old.delete()
        else:
            old.app_label = "business_setup"
            old.save(update_fields=["app_label"])


def unrepoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="business_setup", model__in=_MOVED_MODELS).update(
        app_label="subscriptions"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0141_growth_split_state"),
        ("business_setup", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    # State-only for all 23: the 18 moved models' tables stay (recreated in
    # business_setup/0001) and the 5 dead-cluster tables are physically dropped
    # separately in 0143. No DDL here.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name="cashdesk",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="staffoperationalassignment",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="brandimportbatch",
            name="source",
        ),
        migrations.RemoveField(
            model_name="brandimportbatch",
            name="imported_by",
        ),
        migrations.RemoveField(
            model_name="brandimporteditem",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="brandprofilesnapshot",
            name="source_batch",
        ),
        migrations.RemoveField(
            model_name="publiccontentblock",
            name="source_batch",
        ),
        migrations.RemoveField(
            model_name="brandimporteditem",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="brandimporteditem",
            name="rejected_by",
        ),
        migrations.RemoveField(
            model_name="brandprofilesnapshot",
            name="applied_by",
        ),
        migrations.RemoveField(
            model_name="businesscompliancedocument",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="businesscompliancedocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="businesscompliancedocumentreviewstate",
            name="document",
        ),
        migrations.RemoveField(
            model_name="businesscompliancedocumentreviewstate",
            name="public_summary_approved_by",
        ),
        migrations.RemoveField(
            model_name="businessdatabackupjob",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="businessdatarestorejob",
            name="backup_job",
        ),
        migrations.RemoveField(
            model_name="businessdatarestorejob",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="businessdatarestorejob",
            name="requested_by",
        ),
        migrations.DeleteModel(
            name="BusinessMediaAsset",
        ),
        migrations.RemoveField(
            model_name="documentprintsettings",
            name="business_profile",
        ),
        migrations.RemoveField(
            model_name="businessrulepolicy",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="cashdesk",
            name="default_finance_account",
        ),
        migrations.RemoveField(
            model_name="staffoperationalassignment",
            name="default_cash_desk",
        ),
        migrations.RemoveField(
            model_name="chartaccount",
            name="parent",
        ),
        migrations.DeleteModel(
            name="EmailSMTPSettings",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="archived_by",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="internal_accepted_by",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="policy",
        ),
        migrations.RemoveField(
            model_name="policygovernancemetadata",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="policypage",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="policypage",
            name="published_by",
        ),
        migrations.RemoveField(
            model_name="policypage",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="PublicBusinessProfile",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
        migrations.RemoveField(
            model_name="staffoperationalassignment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
        migrations.DeleteModel(
            name="BrandDataSource",
        ),
        migrations.DeleteModel(
            name="BrandImportBatch",
        ),
        migrations.DeleteModel(
            name="PublicContentBlock",
        ),
        migrations.DeleteModel(
            name="BrandImportedItem",
        ),
        migrations.DeleteModel(
            name="BrandProfileSnapshot",
        ),
        migrations.DeleteModel(
            name="BusinessComplianceDocument",
        ),
        migrations.DeleteModel(
            name="BusinessComplianceDocumentReviewState",
        ),
        migrations.DeleteModel(
            name="BusinessDataBackupJob",
        ),
        migrations.DeleteModel(
            name="BusinessDataRestoreJob",
        ),
        migrations.DeleteModel(
            name="BusinessProfile",
        ),
        migrations.DeleteModel(
            name="DocumentPrintSettings",
        ),
        migrations.DeleteModel(
            name="BusinessRulePolicy",
        ),
        migrations.DeleteModel(
            name="FinanceAccount",
        ),
        migrations.DeleteModel(
            name="CashDesk",
        ),
        migrations.DeleteModel(
            name="ChartAccount",
        ),
        migrations.DeleteModel(
            name="PolicyGovernanceMetadata",
        ),
        migrations.DeleteModel(
            name="PolicyPage",
        ),
        migrations.DeleteModel(
            name="StaffOperationalAssignment",
        ),
            ],
        ),
        migrations.RunPython(repoint_contenttypes, unrepoint_contenttypes),
    ]
