# Generated by Django 5.2.7 on 2026-07-31 19:03

from django.db import migrations

_MOVED_MODELS = [
    "approvalrequest", "businesspolicy", "controlexception",
    "monthendcloserun", "monthendclosecheckresult", "dailyclosecheckresult",
]


def repoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in _MOVED_MODELS:
        old = ContentType.objects.filter(app_label="subscriptions", model=model).first()
        if old is None:
            continue
        if ContentType.objects.filter(app_label="finance_control", model=model).exists():
            old.delete()
        else:
            old.app_label = "finance_control"
            old.save(update_fields=["app_label"])


def unrepoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="finance_control", model__in=_MOVED_MODELS).update(
        app_label="subscriptions"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0143_drop_dead_finance_cluster"),
        ("finance_control", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name="businesspolicy",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="businesspolicy",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="controlexception",
            name="acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="dailyclosecheckresult",
            name="close_run",
        ),
        migrations.RemoveField(
            model_name="monthendclosecheckresult",
            name="run",
        ),
        migrations.RemoveField(
            model_name="monthendcloserun",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="monthendcloserun",
            name="run_by",
        ),
        migrations.DeleteModel(
            name="ApprovalRequest",
        ),
        migrations.DeleteModel(
            name="BusinessPolicy",
        ),
        migrations.DeleteModel(
            name="ControlException",
        ),
        migrations.DeleteModel(
            name="DailyCloseCheckResult",
        ),
        migrations.DeleteModel(
            name="MonthEndCloseCheckResult",
        ),
        migrations.DeleteModel(
            name="MonthEndCloseRun",
        ),
            ],
        ),
        migrations.RunPython(repoint_contenttypes, unrepoint_contenttypes),
    ]
