# Generated by Django 5.2.7 on 2026-07-31 19:39

from django.db import migrations

# ServiceZone/PincodeDatabase -> customers; WorkbenchItem/WorkbenchAction -> crm.
_MOVED = {
    "servicezone": "customers", "pincodedatabase": "customers",
    "workbenchitem": "crm", "workbenchaction": "crm",
}


def repoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, target in _MOVED.items():
        old = ContentType.objects.filter(app_label="subscriptions", model=model).first()
        if old is None:
            continue
        if ContentType.objects.filter(app_label=target, model=model).exists():
            old.delete()
        else:
            old.app_label = target
            old.save(update_fields=["app_label"])


def unrepoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, target in _MOVED.items():
        ContentType.objects.filter(app_label=target, model=model).update(app_label="subscriptions")


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0144_move_finance_control_state"),
        ("customers", "0003_fold_address_from_subscriptions"),
        ("crm", "0011_fold_workbench_from_subscriptions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.DeleteModel(
            name="PincodeDatabase",
        ),
        migrations.RemoveField(
            model_name="workbenchaction",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="workbenchaction",
            name="workbench_item",
        ),
        migrations.RemoveField(
            model_name="workbenchitem",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="workbenchitem",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="workbenchitem",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="workbenchitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="ServiceZone",
        ),
        migrations.DeleteModel(
            name="WorkbenchAction",
        ),
        migrations.DeleteModel(
            name="WorkbenchItem",
        ),
            ],
        ),
        migrations.RunPython(repoint_contenttypes, unrepoint_contenttypes),
    ]
