# Generated by Django 5.2.7 on 2026-07-31 19:44

from django.db import migrations

_MOVED_MODELS = ["auditlog", "businesseventlog"]


def repoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in _MOVED_MODELS:
        old = ContentType.objects.filter(app_label="subscriptions", model=model).first()
        if old is None:
            continue
        if ContentType.objects.filter(app_label="audit", model=model).exists():
            old.delete()
        else:
            old.app_label = "audit"
            old.save(update_fields=["app_label"])


def unrepoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="audit", model__in=_MOVED_MODELS).update(app_label="subscriptions")


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0145_move_address_workbench_state"),
        ("audit", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name="businesseventlog",
            name="actor_user",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="contract_reference",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="lucky_id",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="businesseventlog",
            name="subscription",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="BusinessEventLog",
        ),
            ],
        ),
        migrations.RunPython(repoint_contenttypes, unrepoint_contenttypes),
    ]
