# Generated by Django 5.2.7 on 2026-07-31 20:05

from django.db import migrations

_MOVED = {"amlscreeningrecord": "customers", "dryrunvalidationjob": "business_setup"}


def repoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, target in _MOVED.items():
        old = ContentType.objects.filter(app_label="subscriptions", model=model).first()
        if old is None:
            continue
        if ContentType.objects.filter(app_label=target, model=model).exists():
            old.delete()
        else:
            old.app_label = target
            old.save(update_fields=["app_label"])


def unrepoint_contenttypes(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model, target in _MOVED.items():
        ContentType.objects.filter(app_label=target, model=model).update(app_label="subscriptions")


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0146_move_audit_state"),
        ("customers", "0004_fold_aml_from_subscriptions"),
        ("business_setup", "0002_fold_dryrun_from_subscriptions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name="dryrunvalidationjob",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="AMLScreeningRecord",
        ),
        migrations.DeleteModel(
            name="DryRunValidationJob",
        ),
            ],
        ),
        migrations.RunPython(repoint_contenttypes, unrepoint_contenttypes),
    ]
