from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0147_move_aml_dryrun_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("SUBSCRIPTION_CREATED", "Subscription Created"),
                    ("SUBSCRIPTION_UPDATED", "Subscription Updated"),
                    ("SUBSCRIPTION_CANCELLED", "Subscription Cancelled"),
                    ("SUBSCRIPTION_COMPLETED", "Subscription Completed"),
                    ("SUBSCRIPTION_DEFAULTED", "Subscription Defaulted"),
                    ("SUBSCRIPTION_RESUMED", "Subscription Resumed"),
                    ("SUBSCRIPTION_PAUSED", "Subscription Paused"),
                    ("PAYMENT_CREATED", "Payment Created"),
                    ("PAYMENT_UPDATED", "Payment Updated"),
                    ("PAYMENT_CANCELLED", "Payment Cancelled"),
                    ("EMI_CREATED", "EMI Created"),
                    ("EMI_UPDATED", "EMI Updated"),
                    ("EMI_STATUS_CHANGED", "EMI Status Changed"),
                    ("LUCKY_DRAW_CREATED", "Lucky Draw Created"),
                    ("LUCKY_DRAW_RESULT_DECLARED", "Lucky Draw Result Declared"),
                    ("LUCKY_ID_ASSIGNED", "Lucky ID Assigned"),
                    ("LUCKY_ID_BULK_ASSIGNED", "Lucky ID Bulk Assigned"),
                    ("LUCKY_ID_REASSIGNED", "Lucky ID Reassigned"),
                    ("DRAW_PUBLIC_VERIFIED", "Public Draw Verification Generated"),
                    ("DRAW_PUBLIC_RESULT_PUBLISHED", "Public Draw Result Published"),
                    ("WINNER_WAIVER_APPLIED", "Winner Waiver Applied"),
                    ("WINNER_STATE_SYNCED", "Winner State Synced"),
                    ("COMMISSION_CREATED", "Commission Created"),
                    ("COMMISSION_SETTLED", "Commission Settled"),
                    ("COMMISSION_PAYOUT_BATCH_CREATED", "Commission Payout Batch Created"),
                    ("COMMISSION_PAYOUT_BATCH_FINALIZED", "Commission Payout Batch Finalized"),
                    ("COMMISSION_PAYOUT_BATCH_CANCELLED", "Commission Payout Batch Cancelled"),
                    ("COMMISSION_PAYOUT_BATCH_PAID", "Commission Payout Batch Paid"),
                    ("CREDIT_NOTE_APPLIED", "Credit Note Applied to Invoice"),
                    ("PAYMENT_RECONCILED", "Payment Reconciled"),
                    ("PAYMENT_FLAGGED", "Payment Flagged"),
                    ("PRODUCT_INVENTORY_PROFILE_PREPARED", "Product Inventory Profile Prepared"),
                    ("CATALOG_CREATED", "Catalog Record Created"),
                    ("CATALOG_UPDATED", "Catalog Record Updated"),
                    ("INVENTORY_ITEM_CREATED", "Inventory Item Created"),
                    ("INVENTORY_ITEM_UPDATED", "Inventory Item Updated"),
                    ("STOCK_MOVEMENT_CREATED", "Stock Movement Created"),
                    ("STOCK_ADJUSTMENT_POSTED", "Stock Adjustment Posted"),
                    ("PURCHASE_ORDER_CREATED", "Purchase Order Created"),
                    ("PURCHASE_ORDER_APPROVED", "Purchase Order Approved"),
                    ("PURCHASE_ORDER_CANCELLED", "Purchase Order Cancelled"),
                    ("PURCHASE_BILL_CREATED", "Purchase Bill Created"),
                    ("PURCHASE_BILL_POSTED", "Purchase Bill Posted"),
                    ("VENDOR_PAYMENT_CREATED", "Vendor Payment Created"),
                    ("VENDOR_PAYMENT_POSTED", "Vendor Payment Posted"),
                    ("DELIVERY_CHALLAN_CREATED", "Delivery Challan Created"),
                    ("DELIVERY_CHALLAN_DISPATCHED", "Delivery Challan Dispatched"),
                    ("DELIVERY_CHALLAN_DELIVERED", "Delivery Challan Delivered"),
                    ("DELIVERY_CHALLAN_CANCELLED", "Delivery Challan Cancelled"),
                    ("SUBSCRIPTION_REQUEST_CREATED", "Subscription Request Created"),
                    ("SUBSCRIPTION_REQUEST_APPROVED", "Subscription Request Approved"),
                    ("SUBSCRIPTION_REQUEST_REJECTED", "Subscription Request Rejected"),
                    ("SUBSCRIPTION_DELIVERY_CREATED", "Subscription Delivery Created"),
                    ("SUBSCRIPTION_DELIVERY_DISPATCHED", "Subscription Delivery Dispatched"),
                    ("SUBSCRIPTION_DELIVERY_COMPLETED", "Subscription Delivery Completed"),
                    ("SUBSCRIPTION_DELIVERY_CANCELLED", "Subscription Delivery Cancelled"),
                    ("PRODUCT_REQUEST_CREATED", "Product Request Created"),
                    ("PRODUCT_REQUEST_APPROVED", "Product Request Approved"),
                    ("PRODUCT_REQUEST_REJECTED", "Product Request Rejected"),
                    ("PRODUCT_REQUEST_CANCELLED", "Product Request Cancelled"),
                    ("PRODUCT_REQUEST_FULFILLED", "Product Request Fulfilled"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
