import { expect, test } from "@playwright/test";

import { authStatePath } from "./helpers/smoke-data";

test.use({ storageState: authStatePath("admin") });

const dayCloseFixture = {
  id: 901,
  close_no: "CDC-PRINT-901",
  cashier: 41,
  cashier_username: "cashier.print",
  branch: 2,
  branch_code: "ASN",
  branch_name: "Asansol Main Branch",
  cash_counter: 5,
  cash_counter_name: "Main Cash Counter",
  finance_account: 7,
  finance_account_name: "Main Cash Desk",
  business_date: "2026-05-24",
  opening_cash: "2000.00",
  system_cash_total: "12500.00",
  counted_cash: "12400.00",
  variance: "-100.00",
  status: "APPROVED",
  closed_by: 41,
  closed_by_username: "cashier.print",
  closed_at: "2026-05-24T21:10:00+05:30",
  approved_by: 1,
  approved_by_username: "admin",
  approved_at: "2026-05-24T21:30:00+05:30",
  notes: "Cash short by ₹100. Manager reviewed evidence.",
  metadata: {
    expected_total: "12500.00",
    declared_total: "12400.00",
    upi_collected: "3200.00",
    bank_card_total: "1500.00",
    payment_count: 18,
    receipt_count: 18,
    voided_receipt_count: 1,
    cancelled_receipt_count: 0,
    reversed_receipt_count: 0,
    reconciliation_status: "NEEDS_REVIEW",
    payment_method_summary: [
      { method: "Cash", count: 10, amount: "12500.00" },
      { method: "UPI", count: 6, amount: "3200.00" },
      { method: "Bank / Card", count: 2, amount: "1500.00" },
    ],
  },
  created_at: "2026-05-24T21:00:00+05:30",
  updated_at: "2026-05-24T21:30:00+05:30",
};

async function mockDayCloseApis(page: Parameters<typeof test>[0]["page"]) {
  await page.route("**/admin/settlements/cashier-day-closes/901/", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(dayCloseFixture) });
  });
  await page.route("**/admin/settlements/cashier-day-closes/**", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ count: 1, next: null, previous: null, results: [dayCloseFixture] }),
    });
  });
}

async function expectNoDashboardChrome(page: Parameters<typeof test>[0]["page"]) {
  await expect(page.getByRole("button", { name: "Open quick actions" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: /Open command palette/i })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: /sidebar navigation/i })).toHaveCount(0);
}

async function expectPrintControlsHiddenDuringPrint(page: Parameters<typeof test>[0]["page"]) {
  await page.emulateMedia({ media: "print" });
  await expect(page.getByRole("button", { name: "Print / Save PDF" })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "Back to day-close review" })).toBeHidden();
  await expect(page.getByText("Read-only cashier day-close report generated from existing backend payloads.")).toBeHidden();
  await page.emulateMedia({ media: "screen" });
}

test("cashier day close print route renders branded unbalanced report", async ({ page }) => {
  await mockDayCloseApis(page);

  await page.goto("/admin/settlements/day-closes/901/print");

  await expect(page.getByText("Subidha Furniture").first()).toBeVisible();
  await expect(page.getByText("CASHIER DAY CLOSE REPORT")).toBeVisible();
  await expect(page.getByText("CDC-PRINT-901").first()).toBeVisible();
  await expect(page.getByText("UNBALANCED")).toBeVisible();
  await expect(page.getByText("cashier.print").first()).toBeVisible();
  await expect(page.getByText("Asansol Main Branch").first()).toBeVisible();
  await expect(page.getByText("Main Cash Counter").first()).toBeVisible();
  await expect(page.getByText("May 24, 2026").first()).toBeVisible();
  await expect(page.getByText("Opening Cash")).toBeVisible();
  await expect(page.getByText("Cash Collected / System Cash")).toBeVisible();
  await expect(page.getByText("UPI Collected")).toBeVisible();
  await expect(page.getByText("Bank / Card Collected")).toBeVisible();
  await expect(page.getByText("Variance / Shortage / Excess")).toBeVisible();
  await expect(page.getByText("This cashier day close has a non-zero variance")).toBeVisible();
  await expect(page.getByText("Payment Method Summary")).toBeVisible();
  await expect(page.getByText("Cash").first()).toBeVisible();
  await expect(page.getByText("UPI").first()).toBeVisible();
  await expect(page.getByText("Bank / Card").first()).toBeVisible();
  await expect(page.getByText("NEEDS_REVIEW")).toBeVisible();
  await expect(page.getByText("Cashier Signature")).toBeVisible();
  await expect(page.getByText("Manager / Admin Signature")).toBeVisible();
  await expect(page.getByText("Generated by SUBIDHA CORE")).toBeVisible();
  await expect(page.getByRole("button", { name: "Print / Save PDF" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Back to day-close review" })).toBeVisible();
  await expectNoDashboardChrome(page);
  await expectPrintControlsHiddenDuringPrint(page);
});

test("day close register exposes report print link", async ({ page }) => {
  await mockDayCloseApis(page);

  await page.goto("/admin/settlements/day-closes");

  await expect(page.getByText("CDC-PRINT-901").first()).toBeVisible();
  const printLink = page.getByRole("link", { name: "Day Close Report PDF / Print" }).first();
  await expect(printLink).toBeVisible();
  await expect(printLink).toHaveAttribute("href", "/admin/settlements/day-closes/901/print");
});

test("day close review exposes report print action", async ({ page }) => {
  await mockDayCloseApis(page);

  await page.goto("/admin/settlements/day-closes/901");

  await expect(page.getByText("CDC-PRINT-901").first()).toBeVisible();
  const printLink = page.getByRole("link", { name: "Day Close Report PDF / Print" }).first();
  await expect(printLink).toBeVisible();
  await expect(printLink).toHaveAttribute("href", "/admin/settlements/day-closes/901/print");
});
