# Generated by Django 5.2.7 on 2026-07-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0001_initial"),
        ("subscriptions", "0136_alter_auditlog_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pimproduct",
            name="source_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pim",
                to="subscriptions.product",
            ),
        ),
    ]
