# Generated by Django 5.2.7 on 2026-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0003_backfill_source_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="pimproduct",
            name="variant_generating_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="used_for_variants",
                to="products_pim.categoryattribute",
            ),
        ),
    ]
