# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0001_initial"),
        ("products_pim", "0004_pimproduct_variant_generating_attributes"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="pimproduct",
            name="source_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pim",
                to="products_core.product",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
