# Generated by Django 5.2.7 on 2026-08-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0005_alter_pimproduct_source_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pim/variants/"),
        ),
    ]
