# Generated by Django 5.2.7 on 2026-08-05 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0002_product_video"),
        ("products_pim", "0006_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pimproduct",
            name="brand",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="pimproduct",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="operational_product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pim_variant",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="ProductAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pim/assets/")),
                ("is_hero", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mapped_attribute_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapped_assets",
                        to="products_pim.attributeoption",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="products_pim.pimproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Asset",
                "verbose_name_plural": "Product Assets",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
