# Generated by Django 5.2.7 on 2026-08-16 03:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_parents(apps, schema_editor):
    """
    Link PimProducts whose code matches a ProductVariant.sku to the
    base PimProduct that owns that variant.
    """
    PimProduct = apps.get_model("products_pim", "PimProduct")
    ProductVariant = apps.get_model("products_pim", "ProductVariant")

    # Build map: variant_sku → parent pim_product_id
    sku_to_parent = {
        v.sku: v.product_id
        for v in ProductVariant.objects.select_related("product").all()
    }

    updated = []
    for pim in PimProduct.objects.filter(parent__isnull=True):
        parent_id = sku_to_parent.get(pim.code)
        if parent_id and parent_id != pim.pk:
            pim.parent_id = parent_id
            updated.append(pim)

    if updated:
        PimProduct.objects.bulk_update(updated, ["parent_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0008_pimproduct_locked_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pimproduct",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_pim_products",
                to="products_pim.pimproduct",
            ),
        ),
        migrations.AlterField(
            model_name="pimproduct",
            name="locked_attributes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Attribute IDs manually locked by operator",
            ),
        ),
        migrations.RunPython(backfill_parents, migrations.RunPython.noop),
    ]
