# Generated by Django 5.2.7 on 2026-08-16 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0009_pimproduct_parent_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pimproduct",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
