# Generated by Django 5.2.7 on 2026-08-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0010_pimproduct_base_price_default_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributeoption",
            name="extra_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
