# Generated by Django 5.2.7 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0013_pimproduct_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmediaitem",
            name="ios_file",
            field=models.FileField(blank=True, null=True, upload_to="pim/models/ios/"),
        ),
        migrations.AlterField(
            model_name="productmediaitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("VIDEO", "Video"),
                    ("MODEL_3D", "3D model (AR)"),
                ],
                default="IMAGE",
                max_length=10,
            ),
        ),
    ]
