# Generated by Django 5.2.7 on 2026-09-13

import django.core.validators
from django.db import migrations, models


def _ar_size_field():
    return models.DecimalField(
        blank=True,
        decimal_places=1,
        max_digits=5,
        null=True,
        validators=[
            django.core.validators.MinValueValidator(1),
            django.core.validators.MaxValueValidator(500),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("products_pim", "0014_productmediaitem_ar_model"),
    ]

    operations = [
        migrations.AddField(model_name="pimproduct", name="ar_depth_cm", field=_ar_size_field()),
        migrations.AddField(model_name="pimproduct", name="ar_height_cm", field=_ar_size_field()),
        migrations.AddField(model_name="pimproduct", name="ar_width_cm", field=_ar_size_field()),
    ]
