# Generated by Django 5.2.16 on 2026-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_pim', '0015_pimproduct_ar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimproduct',
            name='extended_warranty_cost_percentage',
            field=models.DecimalField(decimal_places=2, default=7.5, help_text='Extended warranty cost as % of product price', max_digits=4),
        ),
        migrations.AddField(
            model_name='pimproduct',
            name='warranty_enabled',
            field=models.BooleanField(default=True, help_text='Enable warranty coverage for this product'),
        ),
        migrations.AddField(
            model_name='pimproduct',
            name='warranty_months_extended_max',
            field=models.PositiveIntegerField(default=12, help_text='Max months for extended warranty plan'),
        ),
        migrations.AddField(
            model_name='pimproduct',
            name='warranty_months_manufacturing',
            field=models.PositiveIntegerField(default=12, help_text='Manufacturing defect warranty (months)'),
        ),
        migrations.AddField(
            model_name='pimproduct',
            name='warranty_months_structural',
            field=models.PositiveIntegerField(default=36, help_text='Structural warranty for furniture (months, 0 = none)'),
        ),
    ]
