# Generated by Django 5.2.16 on 2026-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_pim', '0016_pimproduct_extended_warranty_cost_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmediaitem',
            name='file',
            field=models.URLField(blank=True, default='', help_text='CDN URL to the asset', max_length=500),
        ),
        migrations.AlterField(
            model_name='productmediaitem',
            name='ios_file',
            field=models.URLField(blank=True, help_text='CDN URL to iOS specific asset', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, help_text='CDN URL to image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='video',
            field=models.URLField(blank=True, help_text='CDN URL to video', max_length=500, null=True),
        ),
    ]
