# Generated by Django 5.2.7 on 2026-06-27 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldSuggestionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_key", models.CharField(db_index=True, max_length=64)),
                ("input_normalized", models.CharField(db_index=True, max_length=255)),
                ("suggested_value", models.CharField(max_length=120)),
                (
                    "suggested_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SEED", "Seeded dataset"),
                            ("LEARNED", "Learned from suggestion"),
                            ("CONFIRMED", "Confirmed by user"),
                        ],
                        db_index=True,
                        default="CONFIRMED",
                        max_length=12,
                    ),
                ),
                ("hit_count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "smart_field_suggestion_mappings",
                "ordering": ["field_key", "-hit_count", "id"],
                "indexes": [
                    models.Index(
                        fields=["field_key", "input_normalized"],
                        name="smart_field_field_k_1a04a1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field_key", "input_normalized"),
                        name="uq_field_key_input",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HsnCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                ("keywords", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "smart_hsn_codes",
                "ordering": ["code", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uq_smart_hsn_code")
                ],
            },
        ),
        migrations.CreateModel(
            name="PincodeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pincode", models.CharField(db_index=True, max_length=10)),
                (
                    "office_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                ("state_code", models.CharField(blank=True, default="", max_length=5)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SEED", "Seeded dataset"),
                            ("LEARNED", "Learned from suggestion"),
                            ("CONFIRMED", "Confirmed by user"),
                        ],
                        db_index=True,
                        default="SEED",
                        max_length=12,
                    ),
                ),
                ("hit_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "smart_pincode_locations",
                "ordering": ["pincode", "-hit_count", "city", "id"],
                "indexes": [
                    models.Index(
                        fields=["pincode", "-hit_count"],
                        name="smart_pinco_pincode_1a703c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pincode", "city", "district", "state"),
                        name="uq_pincode_city_district_state",
                    )
                ],
            },
        ),
    ]
