"use client";
import { useEffect, useMemo, useState } from "react";
import type { EnterpriseColumnDef } from "@/components/enterprise/columns";
import EnterpriseDataTable from "@/components/enterprise/EnterpriseDataTable";
import { accountingErrorMessage } from "@/components/accounting/shared";
import PortalPage from "@/components/ui/PortalPage";
import { WorkspaceSection } from "@/components/ui/workspace";
import { ROUTES } from "@/lib/routes";
import { listVendorBills, listVendorPayments, type VendorBill, type VendorPayment } from "@/services/inventory";
export default function AdminVendorPayablesPage(){const [bills,setBills]=useState<VendorBill[]>([]);const [payments,setPayments]=useState<VendorPayment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);useEffect(()=>{let active=true;async function load(){try{const [billPayload,paymentPayload]=await Promise.all([listVendorBills(),listVendorPayments()]);if(!active)return;setBills(billPayload.results);setPayments(paymentPayload.results);}catch(err){if(!active)return;setError(accountingErrorMessage(err,"Failed to load vendor payables."));}finally{if(active)setLoading(false);}}void load();return()=>{active=false;};},[]);const rows=useMemo(()=>{const paidByVendor:Record<number,number>={};for(const row of payments){if(row.status!=="POSTED")continue;paidByVendor[row.vendor]=(paidByVendor[row.vendor]||0)+Number(row.amount||0);}return bills.filter((row)=>row.status!=="CANCELLED").map((row)=>{const total=Number(row.grand_total||0);const paid=paidByVendor[row.vendor]||0;const outstanding=Math.max(0,total-paid);return {...row,paid:paid.toFixed(2),outstanding:outstanding.toFixed(2)};});},[bills,payments]);const columns:EnterpriseColumnDef<VendorBill & {paid:string;outstanding:string;}>[]=[{key:"bill_no",header:"Bill No"},{key:"vendor_name",header:"Vendor"},{key:"grand_total",header:"Bill Total"},{key:"paid",header:"Posted Paid"},{key:"outstanding",header:"Outstanding"},{key:"status",header:"Status"}];return <PortalPage title="Vendor Payables" subtitle="Operational payable visibility from posted procurement documents." breadcrumbs={[{label:"Admin",href:ROUTES.admin.dashboard},{label:"Purchases",href:ROUTES.admin.purchases},{label:"Vendor Payables"}]}><WorkspaceSection title="Payables" description="Payables are computed from vendor bills and posted vendor payments; no synthetic balances are used."><EnterpriseDataTable data={rows} columns={columns} loading={loading} error={error} emptyTitle="No payable rows" emptyDescription="Post vendor bills to create payable obligations."/></WorkspaceSection></PortalPage>;}
