# Generated by Django 6.0.2 on 2026-04-09 19:02

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '0002_paymentreminder_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_no', models.CharField(db_index=True, default=crm.models.generate_party_no, max_length=40, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=160)),
                ('party_kind', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('HOUSEHOLD', 'Household'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=20)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('primary_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes_summary', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_parties',
                'ordering': ['display_name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_name'], name='crm_parties_is_acti_59fd18_idx'), models.Index(fields=['primary_phone', 'display_name'], name='crm_parties_primary_c280bb_idx'), models.Index(fields=['primary_email', 'display_name'], name='crm_parties_primary_5d2aaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(choices=[('LEAD', 'Lead'), ('CUSTOMER', 'Customer'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor'), ('STAFF', 'Staff')], db_index=True, max_length=20)),
                ('source_app_label', models.CharField(db_index=True, max_length=40)),
                ('source_model', models.CharField(db_index=True, max_length=80)),
                ('source_pk', models.PositiveIntegerField(db_index=True)),
                ('source_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crm.partymaster')),
            ],
            options={
                'db_table': 'crm_party_links',
                'ordering': ['role_type', '-created_at', '-id'],
                'indexes': [models.Index(fields=['party', 'role_type'], name='crm_party_l_party_i_16d600_idx'), models.Index(fields=['source_model', 'source_pk'], name='crm_party_l_source__a0d7eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('role_type', 'source_app_label', 'source_model', 'source_pk'), name='crm_party_link_unique_source_role')],
            },
        ),
        migrations.CreateModel(
            name='PartyInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('GENERAL', 'General'), ('CONTACT_NOTE', 'Contact Note'), ('FOLLOW_UP', 'Follow Up'), ('HANDOFF', 'Handoff')], db_index=True, default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.TextField()),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('related_source_model', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('related_source_pk', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_party_interactions', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_party_interactions', to='reminders.paymentreminder')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.partymaster')),
            ],
            options={
                'db_table': 'crm_party_interactions',
                'ordering': ['-happened_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['party', 'status', 'next_follow_up_at'], name='crm_party_i_party_i_d4e654_idx'), models.Index(fields=['party', 'happened_at'], name='crm_party_i_party_i_2356ea_idx'), models.Index(fields=['related_source_model', 'related_source_pk'], name='crm_party_i_related_43dcbc_idx')],
            },
        ),
    ]
