# Generated by Django 6.0.2 on 2026-05-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_internal_crm_module"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customerriskflag",
            new_name="crm_custome_custome_bea333_idx",
            old_name="crm_customer_customer_921db4_idx",
        ),
        migrations.RenameIndex(
            model_name="followuptask",
            new_name="crm_follow__status_09f1b6_idx",
            old_name="crm_follow_u_status_8d2e0b_idx",
        ),
        migrations.RenameIndex(
            model_name="followuptask",
            new_name="crm_follow__assigne_b9b525_idx",
            old_name="crm_follow_u_assigne_1e4a3f_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_leads_phone_3a2c9d_idx",
            old_name="crm_leads_phone_5dcafa_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="crm_leads_assigne_944596_idx",
            old_name="crm_leads_assigne_bf3400_idx",
        ),
    ]
