# Generated by Django 5.2.7 on 2026-06-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_staff_sales_target'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffsalestarget',
            new_name='crm_staff_s_year_69843f_idx',
            old_name='staff_target_year_month_idx',
        ),
        migrations.AlterField(
            model_name='staffsalestarget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
