# Generated by Django 5.2.7 on 2026-07-23 09:50

from django.db import migrations, models
from django.db.models import F


def backfill_stage_changed_at(apps, schema_editor):
    """Seed existing leads with their best-known stage entry time: last-updated
    timestamp, falling back to created_at. New rows are stamped by Lead.save()."""
    Lead = apps.get_model("crm", "Lead")
    Lead.objects.filter(stage_changed_at__isnull=True, updated_at__isnull=False).update(
        stage_changed_at=F("updated_at")
    )
    Lead.objects.filter(stage_changed_at__isnull=True).update(stage_changed_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm",
            "0006_rename_staff_target_year_month_idx_crm_staff_s_year_69843f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="stage_changed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_stage_changed_at, migrations.RunPython.noop),
    ]
