# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_lead_stage_changed_at"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="CRMPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("LEAD", "Lead"),
                            ("ENQUIRY", "Online Enquiry"),
                            ("QUOTED", "Quoted"),
                            ("APPROVED", "Approved"),
                            ("CONVERTED", "Converted to Contract"),
                            ("ACTIVE", "Active Sale/Subscription"),
                            ("LOST", "Lost"),
                            ("WON", "Won"),
                        ],
                        db_index=True,
                        default="LEAD",
                        max_length=20,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "EMI/Subscription"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "EMI/Subscription"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        help_text="Which contract type was created",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "converted_entity_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of DirectSale/Subscription/RentProfile/LeaseProfile",
                        null=True,
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount quoted to customer",
                        max_digits=12,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confirmed contract value",
                        max_digits=12,
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(
                        default=50, help_text="Sales probability percentage"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, help_text="Expected date for conversion", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "crm_pipeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated request number (e.g., ORQ-2026-00001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE_EMI", "Advance EMI"),
                            ("DIRECT_SALE", "Direct Sale"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "preferred_tenure",
                    models.IntegerField(blank=True, help_text="Months", null=True),
                ),
                ("preferred_lucky_number", models.IntegerField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="quantity * unit_price",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST percentage (default 18%)",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="sub_total + gst_amount + delivery_cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUOTE_SENT", "Quote Sent"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("quote_generated_at", models.DateTimeField(blank=True, null=True)),
                ("quote_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft - Awaiting Quote"),
                            ("QUOTED", "Quoted - Awaiting Approval"),
                            ("APPROVED", "Approved - Contract Created"),
                            ("CONVERTED", "Converted - Sale/Subscription Active"),
                            ("REJECTED", "Rejected"),
                            ("LOST", "Lost Lead"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Unified workflow status (separate from status field)",
                        max_length=20,
                    ),
                ),
                (
                    "approved_entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "EMI/Subscription"),
                            ("RENT", "Rent Contract"),
                            ("LEASE", "Lease Contract"),
                        ],
                        help_text="Which contract type was approved",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "auto_conversion_enabled",
                    models.BooleanField(
                        default=True, help_text="Auto-create contract on approval"
                    ),
                ),
                (
                    "conversion_notes",
                    models.TextField(
                        blank=True, help_text="Notes about conversion/approval"
                    ),
                ),
                (
                    "expected_close_date",
                    models.DateField(
                        blank=True, help_text="Expected sale close date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Online Request",
                "verbose_name_plural": "Online Requests",
                "db_table": "online_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineRequestAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("QUOTE_GENERATED", "Quote Generated"),
                            ("QUOTE_SENT", "Quote Sent"),
                            ("QUOTE_ACCEPTED", "Quote Accepted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional context"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Online Request Action",
                "verbose_name_plural": "Online Request Actions",
                "db_table": "online_request_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "requester_role_snapshot",
                    models.CharField(db_index=True, max_length=20),
                ),
                (
                    "requested_customer_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requested_customer_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "requested_customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "requested_customer_address",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "requested_customer_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE_EMI", "Advance EMI"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                            ("DIRECT_SALE", "Direct Sale"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "preferred_lucky_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "requested_tenure_months_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "product_requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(db_index=True, max_length=10)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "interested_product",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "preferred_emi_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("admin_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("CONTACTED", "Contacted"),
                            ("CONVERTED", "Converted"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("QUOTATION", "Quotation"),
                            ("ESTIMATE", "Estimate"),
                            ("DIRECT_SALE", "Direct Sale"),
                            ("SUBSCRIPTION", "Subscription"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(default="PUBLIC_SITE", max_length=40)),
                (
                    "follow_up_required",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "follow_up_on",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("follow_up_note", models.TextField(blank=True, default="")),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "contacted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "converted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "public_leads",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "requester_role_snapshot",
                    models.CharField(db_index=True, max_length=20),
                ),
                (
                    "requested_customer_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requested_customer_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "requested_customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "requested_customer_address",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "requested_customer_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("preferred_lucky_number", models.PositiveSmallIntegerField()),
                ("requested_tenure_months_snapshot", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            (
                                "ON_HOLD_LUCKY_UNAVAILABLE",
                                "On Hold – Lucky ID Unavailable",
                            ),
                            (
                                "ON_HOLD_PRODUCT_NOT_READY",
                                "On Hold – Product Not Ready",
                            ),
                            ("AMENDMENT_REQUESTED", "Amendment Requested"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=32,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "subscription_requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
