# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_crmpipeline_onlinerequest_onlinerequestaction_and_more"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="customerinteraction",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_interactions",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerriskflag",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_risk_flags",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="followuptask",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_follow_up_tasks",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="converted_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_converted_leads",
                to="customers.customer",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
