# Generated by Django 5.2.7 on 2026-07-31 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_alter_lead_interested_product_and_more"),
        ("customers", "0003_fold_address_from_subscriptions"),
        ("lucky_plan", "0002_initial"),
        ("products_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: tables already exist; register/deregister in state, no DDL.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="WorkbenchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("DIRECT_SALE", "Direct Sale"),
                            ("ONLINE_REQUEST", "Online Request"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("VENDOR", "Vendor Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ASSIGNED", "Assigned"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workbench_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workbench_items",
                        to="lucky_plan.batch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbench_items",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbench_items",
                        to="products_core.product",
                    ),
                ),
            ],
            options={
                "db_table": "workbench_item",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkbenchAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("SCHEDULE", "Schedule"),
                            ("QUOTE", "Send Quote"),
                            ("COMPLETE", "Complete"),
                            ("NOTE", "Add Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workbench_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workbench_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="crm.workbenchitem",
                    ),
                ),
            ],
            options={
                "db_table": "workbench_action",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(
                fields=["customer", "module"], name="workbench_i_custome_fdd578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(
                fields=["status", "-created_at"], name="workbench_i_status_f91e44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workbenchitem",
            index=models.Index(
                fields=["assigned_to", "status"], name="workbench_i_assigne_f900f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workbenchaction",
            index=models.Index(
                fields=["workbench_item", "-created_at"],
                name="workbench_a_workben_cbc2ce_idx",
            ),
        ),
            ],
        ),
    ]
