# Generated by Django 6.0.2 on 2026-04-10 02:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manufacturing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0008_employeeattendance_employeeprofile_department_and_more'),
        ('inventory', '0005_alter_stockledger_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingBom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_no', models.CharField(db_index=True, default=manufacturing.models.generate_bom_no, max_length=40, unique=True)),
                ('revision_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=12)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_manufacturing_boms', to=settings.AUTH_USER_MODEL)),
                ('finished_good_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_boms', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'manufacturing_boms',
                'ordering': ['finished_good_inventory_item__product__name', '-revision_no', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.manufacturingbom')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_bom_lines', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'manufacturing_bom_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_no', models.CharField(db_index=True, default=manufacturing.models.generate_production_job_no, max_length=40, unique=True)),
                ('job_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('planned_output_qty', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('completed_output_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('total_issued_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_received_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_scrap_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('wip_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costing_status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('DEFERRED', 'Deferred')], db_index=True, default='PENDING', max_length=12)),
                ('accounting_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('POSTED', 'Posted'), ('DEFERRED', 'Deferred')], db_index=True, default='NOT_REQUIRED', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('posting_notes', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_jobs', to='manufacturing.manufacturingbom')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('finished_good_inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_jobs', to='inventory.inventoryitem')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_production_jobs', to=settings.AUTH_USER_MODEL)),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_jobs', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'manufacturing_production_jobs',
                'ordering': ['-job_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_kind', models.CharField(choices=[('ISSUE', 'Issue'), ('RETURN', 'Return')], db_index=True, default='ISSUE', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('planned_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_posted', models.BooleanField(db_index=True, default=False)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bom_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_issue_lines', to='manufacturing.manufacturingbomline')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_lines', to='inventory.inventoryitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_production_material_issue_lines', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_issue_line', to='accounting.journalentry')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_issue_lines', to='manufacturing.productionjob')),
            ],
            options={
                'db_table': 'manufacturing_production_material_issue_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_posted', models.BooleanField(db_index=True, default=False)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_receipt_lines', to='inventory.inventoryitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_production_receipt_lines', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_receipt_line', to='accounting.journalentry')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='manufacturing.productionjob')),
            ],
            options={
                'db_table': 'manufacturing_production_receipt_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionScrapLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_posted', models.BooleanField(db_index=True, default=False)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_scrap_lines', to='inventory.inventoryitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_production_scrap_lines', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_scrap_line', to='accounting.journalentry')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_lines', to='manufacturing.productionjob')),
            ],
            options={
                'db_table': 'manufacturing_production_scrap_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturingbom',
            index=models.Index(fields=['finished_good_inventory_item', 'status', 'revision_no'], name='manufacturi_finishe_d8df94_idx'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingbom',
            constraint=models.UniqueConstraint(fields=('finished_good_inventory_item', 'revision_no'), name='manufacturing_bom_unique_revision_per_fg'),
        ),
        migrations.AddConstraint(
            model_name='manufacturingbom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'ACTIVE')), fields=('finished_good_inventory_item',), name='manufacturing_bom_single_active_default_per_fg'),
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['status', 'job_date'], name='manufacturi_status_a85b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['finished_good_inventory_item', 'status'], name='manufacturi_finishe_137996_idx'),
        ),
        migrations.AddIndex(
            model_name='productionjob',
            index=models.Index(fields=['bom', 'job_date'], name='manufacturi_bom_id_a04bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='productionmaterialissueline',
            index=models.Index(fields=['production_job', 'is_posted', 'entry_kind'], name='manufacturi_product_dfbfae_idx'),
        ),
        migrations.AddIndex(
            model_name='productionreceiptline',
            index=models.Index(fields=['production_job', 'is_posted'], name='manufacturi_product_7dc45d_idx'),
        ),
        migrations.AddIndex(
            model_name='productionscrapline',
            index=models.Index(fields=['production_job', 'is_posted'], name='manufacturi_product_05998c_idx'),
        ),
    ]
