# Generated by Django 5.2.7 on 2026-08-20 08:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0057_alter_financeaccountcoamapping_purpose_and_more"),
        ("manufacturing", "0002_phase2_production_job_labor_overhead_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLaborLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_name", models.CharField(max_length=120)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("piece_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "wage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_posted", models.BooleanField(db_index=True, default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_labor_lines",
                        to="accounting.employeeprofile",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_production_labor_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "production_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_lines",
                        to="manufacturing.productionjob",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_production_labor_lines",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["production_job", "is_posted"],
                        name="manufacturi_product_00ea5a_idx",
                    )
                ],
            },
        ),
    ]
