# Generated by Django 5.2.7 on 2026-08-25 18:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stocklocation_address_and_more"),
        ("manufacturing", "0003_productionlaborline"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturingBomServiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Standard hours or units for this service.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_lines",
                        to="manufacturing.manufacturingbom",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manufacturing_bom_service_lines",
                        to="inventory.servicecatalogitem",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_bom_service_lines",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
