# Generated by Django 5.2.7 on 2026-08-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0059_customeropeningoutstanding_migration_row"),
        ("inventory", "0026_stocklocation_address_and_more"),
        ("manufacturing", "0004_manufacturingbomserviceline"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingbomserviceline",
            name="default_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional default staff member for this service.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_bom_service_lines",
                to="accounting.employeeprofile",
            ),
        ),
        migrations.AddField(
            model_name="productionlaborline",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the service catalog item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_labor_lines",
                to="inventory.servicecatalogitem",
            ),
        ),
    ]
