# Generated by Django 5.2.7 on 2026-08-26 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0059_customeropeningoutstanding_migration_row"),
        ("manufacturing", "0005_manufacturingbomserviceline_default_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionlaborline",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_labor_lines",
                to="accounting.employeeprofile",
            ),
        ),
    ]
