# Generated by Django 5.2.7 on 2026-08-30 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone as _tz


def _generate_polishing_order_no():
    return f"POL-{_tz.now().strftime('%Y%m%d%H%M%S%f')}"


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0060_financeaccount_opening_balance_locked"),
        ("inventory", "0026_stocklocation_address_and_more"),
        ("manufacturing", "0006_alter_productionlaborline_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PolishingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_no",
                    models.CharField(
                        db_index=True,
                        default=_generate_polishing_order_no,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        help_text="Number of units to be polished.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_labor_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_service_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_polishing_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finished_good_inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="polishing_orders",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_polishing_orders",
                "ordering": ["-order_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolishingMaterialLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material_name", models.CharField(max_length=120)),
                ("unit", models.CharField(blank=True, default="", max_length=40)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "line_total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "polishing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_lines",
                        to="manufacturing.polishingorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_polishing_material_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PolishingLaborLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_name", models.CharField(max_length=120)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "wage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total staff expense for this labor entry.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="polishing_labor_lines",
                        to="accounting.employeeprofile",
                    ),
                ),
                (
                    "polishing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_lines",
                        to="manufacturing.polishingorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_polishing_labor_lines",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PolishingServiceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "charge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "labor_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the labor line that drives this charge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_charges",
                        to="manufacturing.polishinglaborline",
                    ),
                ),
                (
                    "polishing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_charges",
                        to="manufacturing.polishingorder",
                    ),
                ),
            ],
            options={
                "db_table": "manufacturing_polishing_service_charges",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="polishingorder",
            index=models.Index(
                fields=["status", "order_date"], name="manufacturi_status_0cca6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polishingorder",
            index=models.Index(
                fields=["finished_good_inventory_item", "status"],
                name="manufacturi_finishe_fec319_idx",
            ),
        ),
    ]
