# Generated by Django 5.2.7 on 2026-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0007_polishing_order"),
    ]

    operations = [
        # Drop the polishing-specific tables added in 0007 — functionality merged into ProductionJob
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS manufacturing_polishing_service_charges;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS manufacturing_polishing_labor_lines;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS manufacturing_polishing_material_lines;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS manufacturing_polishing_orders;",
            reverse_sql="",
        ),
        migrations.AddField(
            model_name="productionjob",
            name="finishing_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POLISH", "Polish / Lacquer"),
                    ("INSTALLATION", "Installation"),
                    ("WOODWORK", "Wood Work / Improvement"),
                    ("UPHOLSTERY", "Upholstery / Fabric"),
                    ("PAINTING", "Painting / Coating"),
                    ("OTHER", "Other Finishing"),
                ],
                db_index=True,
                help_text="Only used when job_type=FINISHING.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productionjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("MANUFACTURING", "Manufacturing"),
                    ("FINISHING", "Finishing / Post-Production Work"),
                ],
                db_index=True,
                default="MANUFACTURING",
                help_text="MANUFACTURING = normal production; FINISHING = post-production finishing work (polish, install, woodwork, etc.)",
                max_length=16,
            ),
        ),
    ]
