# Generated by Django 5.2.7 on 2026-07-31 06:20

import customers.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import subscriptions.base_models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="KycReviewAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("PARTNER", "Partner"),
                            ("VENDOR", "Vendor"),
                            ("STAFF", "Staff"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("owner_id", models.PositiveIntegerField(db_index=True)),
                (
                    "document_model",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "document_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMIT", "Submitted for Review"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                            ("REQUEST_RESUBMISSION", "Resubmission Requested"),
                            (
                                "EXCEPTION_APPROVE",
                                "Exception Approved (Admin Override)",
                            ),
                            ("EXPIRE", "Expired"),
                            ("UPLOAD", "Document Uploaded"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=30)),
                ("new_status", models.CharField(blank=True, default="", max_length=30)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "upload_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN_UPLOAD", "Admin Upload"),
                            ("SELF_SERVICE_UPLOAD", "Self-Service Upload"),
                            ("CRM_UPLOAD", "CRM Upload"),
                            ("SUBSCRIPTION_REGISTRATION", "Subscription Registration"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "kyc_review_actions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCustomerKycRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("KYC_UPGRADE", "KYC Verification Request"),
                            ("LOGIN_ID_SETUP", "Login ID Setup Request"),
                            ("KYC_DOCUMENT_UPLOAD", "KYC Document Upload Request"),
                        ],
                        db_index=True,
                        default="KYC_UPGRADE",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MORE_INFO", "More Information Needed"),
                            ("IN_PROGRESS", "In Progress"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerKycDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("VOTER_ID", "Voter ID"),
                            ("GST_CERTIFICATE", "GST Certificate"),
                            ("BANK_PROOF", "Bank Proof"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                (
                    "document_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=customers.models.partner_kyc_doc_upload_to
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESUBMISSION_REQUIRED", "Resubmission Required"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                (
                    "upload_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADMIN_UPLOAD", "Admin Upload"),
                            ("SELF_SERVICE_UPLOAD", "Self-Service Upload"),
                            ("CRM_UPLOAD", "CRM Upload"),
                            ("SUBSCRIPTION_REGISTRATION", "Subscription Registration"),
                        ],
                        db_index=True,
                        default="ADMIN_UPLOAD",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Document expiry date. Leave blank for non-expiring documents.",
                        null=True,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "partner_kyc_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("NOT_PROVIDED", "Not Provided"),
                            ("PENDING", "Pending Verification"),
                            ("SUBMITTED", "Submitted – Awaiting Review"),
                            ("VERIFIED", "Verified"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            (
                                "EXCEPTION_APPROVED",
                                "Exception Approved (Admin Override)",
                            ),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "kyc_reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("kyc_rejection_reason", models.TextField(blank=True, default="")),
                (
                    "is_pep",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="Politically Exposed Person (PEP)",
                    ),
                ),
                ("pep_flagged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "aml_cleared",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="AML Screening Cleared",
                    ),
                ),
                ("aml_cleared_at", models.DateTimeField(blank=True, null=True)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                (
                    "customer_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUBLIC", "Public Self-Registration"),
                            ("ADMIN", "Admin Created"),
                            ("PARTNER", "Partner Created"),
                            ("IMPORT", "Imported"),
                        ],
                        db_index=True,
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=subscriptions.base_models.customer_photo_upload_to,
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Human-readable short code for receipts/contracts (auto-generated if blank).",
                        max_length=40,
                    ),
                ),
                (
                    "preferred_reminder_channel",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Customer's preferred channel for payment reminders (SMS / WHATSAPP / EMAIL / CALL). Blank = no preference recorded.",
                        max_length=16,
                    ),
                ),
                (
                    "whatsapp_opted_in",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the customer has explicitly opted in to receive WhatsApp reminders.",
                    ),
                ),
                (
                    "created_by_partner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kyc_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kyc_reviewed_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pep_flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pep_flagged_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("OFFICE", "Office"),
                            ("OTHER", "Other"),
                        ],
                        default="HOME",
                        max_length=10,
                    ),
                ),
                ("line1", models.CharField(help_text="Street address", max_length=200)),
                (
                    "line2",
                    models.CharField(
                        blank=True, help_text="Apartment, suite, etc.", max_length=200
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        help_text="6-digit postal index number",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pin",
                                message="PIN must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_delivery_address", models.BooleanField(default=True)),
                ("is_billing_address", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "dispute_ref",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_DISPUTE", "Payment Dispute"),
                            ("DELIVERY_DISPUTE", "Delivery Dispute"),
                            ("PRODUCT_DEFECT", "Product Defect"),
                            ("BILLING_ERROR", "Billing Error"),
                            ("KYC_ISSUE", "KYC Issue"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("ESCALATED", "Escalated"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("open_due_at", models.DateTimeField(blank=True, null=True)),
                ("review_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolve_due_at", models.DateTimeField(blank=True, null=True)),
                ("review_started_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolution_decision", models.TextField(blank=True, default="")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="contracts.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_customer_disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerKycDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAAR", "Aadhaar Card"),
                            ("PAN", "PAN Card"),
                            ("PASSPORT", "Passport"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("VOTER_ID", "Voter ID"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNSPECIFIED", "Unspecified"),
                            ("ID_PROOF", "Identity Proof"),
                            ("ADDRESS_PROOF", "Address Proof"),
                            ("CUSTOMER_PHOTO", "Customer Photo"),
                            ("PHONE_VERIFICATION", "Phone Verification"),
                            ("DELIVERY_ADDRESS_PROOF", "Delivery Address Proof"),
                            ("GUARANTOR_ID_PROOF", "Guarantor Identity Proof"),
                            ("GUARANTOR_ADDRESS_PROOF", "Guarantor Address Proof"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="UNSPECIFIED",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=subscriptions.base_models.customer_kyc_doc_upload_to
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RESUBMISSION_REQUIRED", "Resubmission Required"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Document expiry date. Leave blank for non-expiring documents (e.g. PAN, Voter ID).",
                        null=True,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "upload_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to="customers.customer",
                    ),
                ),
                (
                    "resubmission_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resubmissions",
                        to="customers.customerkycdocument",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer_kyc_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "commission_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Set true only when admin global referral commission feature is enabled.",
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("commission_approved", models.BooleanField(default=False)),
                ("commission_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commission_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_referral_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referred_by_referrals",
                        to="customers.customer",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_made",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRiskProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "risk_band",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "last_calculated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profile",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_customer_risk_profiles",
                "ordering": ["-last_calculated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSupportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PAYMENT_ISSUE", "Payment Issue"),
                            ("RECEIPT_ISSUE", "Receipt Issue"),
                            ("EMI_ISSUE", "EMI Issue"),
                            ("SUBSCRIPTION_QUERY", "Subscription Query"),
                            ("DRAW_QUERY", "Draw Query"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("internal_notes", models.TextField(blank=True, default="")),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("resolution_summary", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_support_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_requests",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "customer_support_requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
