# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0002_initial"),
        ("customers", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
            model_name="customersupportrequest",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_requests",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="customersupportrequest",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_support_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customersupportrequest",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="support_requests",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="kycreviewaction",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kyc_review_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnercustomerkycrequest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_kyc_requests",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="partnercustomerkycrequest",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_kyc_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnercustomerkycrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_partner_kyc_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnerkycdocument",
            name="partner_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnerkycdocument",
            name="resubmission_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resubmissions",
                to="customers.partnerkycdocument",
            ),
        ),
        migrations.AddField(
            model_name="partnerkycdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_partner_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnerkycdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_partner_kyc_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_phone_91048b_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["kyc_status"], name="customers_kyc_sta_38146a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_name_25d5e3_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["kyc_reviewed_at"], name="customers_kyc_rev_e3f8c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["city"], name="customers_city_98cb62_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_source"], name="customers_custome_59bf06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_code"], name="customers_custome_fdedee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["customer", "is_primary"], name="addresses_custome_0997af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["postal_code"], name="addresses_postal__0e4029_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["city", "state"], name="addresses_city_39f647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["customer", "status"], name="customer_ky_custome_36b037_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["customer", "document_type"],
                name="customer_ky_custome_82503c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerkycdocument",
            index=models.Index(
                fields=["status", "created_at"], name="customer_ky_status_7b80f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["referrer", "created_at"], name="customer_re_referre_9e55ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["referred"], name="customer_re_referre_2f1ff7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreferral",
            index=models.Index(
                fields=["commission_approved"], name="customer_re_commiss_d33c59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreferral",
            constraint=models.UniqueConstraint(
                fields=("referrer", "referred"), name="uq_customer_referral_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="customerriskprofile",
            index=models.Index(
                fields=["risk_band", "last_calculated_at"],
                name="subscriptio_risk_ba_46839d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["customer", "created_at"], name="customer_su_custome_c95449_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["status", "created_at"], name="customer_su_status_31a001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["category", "created_at"], name="customer_su_categor_ec5b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["assigned_to", "created_at"],
                name="customer_su_assigne_b84a88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["payment"], name="customer_su_payment_b110e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["subscription"], name="customer_su_subscri_ef15a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customersupportrequest",
            index=models.Index(
                fields=["resolved_by", "created_at"],
                name="customer_su_resolve_3b5438_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kycreviewaction",
            index=models.Index(
                fields=["owner_type", "owner_id", "created_at"],
                name="kyc_review__owner_t_9c5bcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kycreviewaction",
            index=models.Index(
                fields=["owner_type", "action"], name="kyc_review__owner_t_a33a46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycreviewaction",
            index=models.Index(
                fields=["document_model", "document_id"],
                name="kyc_review__documen_9f115c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partnercustomerkycrequest",
            index=models.Index(
                fields=["partner", "status"], name="customers_p_partner_6ea2cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercustomerkycrequest",
            index=models.Index(
                fields=["customer", "status"], name="customers_p_custome_2d720b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerkycdocument",
            index=models.Index(
                fields=["partner_user", "status"], name="partner_kyc_partner_7ac2b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerkycdocument",
            index=models.Index(
                fields=["partner_user", "document_type"],
                name="partner_kyc_partner_44f668_idx",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
