# Generated by Django 5.2.7 on 2026-07-31 19:38

import customers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: tables already exist; register/deregister in state, no DDL.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name="partnerkycdocument",
            name="file",
            field=models.FileField(
                upload_to=customers.models.partner_kyc_doc_upload_to
            ),
        ),
        migrations.CreateModel(
            name="PincodeDatabase",
            fields=[
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pin",
                                message="PIN must be exactly 6 digits",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "db_table": "pincode_database",
                "indexes": [
                    models.Index(fields=["city"], name="pincode_dat_city_92a913_idx"),
                    models.Index(fields=["state"], name="pincode_dat_state_e05de3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_codes",
                    models.JSONField(
                        default=list, help_text="List of service postal codes"
                    ),
                ),
                (
                    "delivery_days",
                    models.IntegerField(default=3, help_text="Standard delivery days"),
                ),
                (
                    "delivery_cost_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_cost_per_km",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_zones",
                "indexes": [
                    models.Index(
                        fields=["vendor", "is_active"],
                        name="service_zon_vendor__176bfb_idx",
                    ),
                    models.Index(fields=["city"], name="service_zon_city_5679c5_idx"),
                ],
                "unique_together": {("vendor", "city", "state")},
            },
        ),
            ],
        ),
    ]
