# Generated by Django 5.2.7 on 2026-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_pin_partner_kyc_request_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLIC", "Public Self-Registration"),
                    ("ADMIN", "Admin Created"),
                    ("PARTNER", "Partner Created"),
                    ("IMPORT", "Imported"),
                    ("ONLINE", "Online"),
                    ("ONLINE_ENQUIRY", "Online Enquiry"),
                    ("DIRECT_SALE", "Direct Sale"),
                ],
                db_index=True,
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
