# Generated by Django 5.2.7 on 2026-07-31 17:50

import business_setup.models.core
import business_setup.models.print_settings
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: business_setup_* tables already exist (created under the
    # subscriptions app). Register models in state without any DDL.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="BrandDataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("GOOGLE_BUSINESS", "Google Business Profile"),
                            ("YOUTUBE", "YouTube"),
                            ("FACEBOOK", "Facebook"),
                            ("JUSTDIAL", "Justdial"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_configured", models.BooleanField(db_index=True, default=False)),
                (
                    "configuration_hint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "brand_data_sources",
                "ordering": ["provider", "id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessMediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("LOGO", "Logo"),
                            ("STOREFRONT", "Storefront"),
                            ("GALLERY", "Gallery"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("media_url", models.URLField()),
                ("source_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "business_media_assets",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                (
                    "trade_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "business_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "primary_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("website_url", models.URLField(blank=True, default="")),
                (
                    "address_line_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("district", models.CharField(blank=True, default="", max_length=120)),
                ("state", models.CharField(blank=True, default="", max_length=120)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(default="India", max_length=80)),
                ("gstin", models.CharField(blank=True, default="", max_length=32)),
                ("pan_number", models.CharField(blank=True, default="", max_length=32)),
                (
                    "cin_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company Identification Number (Pvt Ltd / LLP only). Printed on letterheads under Companies Act 2013.",
                        max_length=21,
                    ),
                ),
                (
                    "tan_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tax Deduction Account Number. Required if the business deducts TDS.",
                        max_length=10,
                    ),
                ),
                (
                    "udyam_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Udyam / MSME Registration Number (e.g. UDYAM-MH-00-0000000).",
                        max_length=20,
                    ),
                ),
                (
                    "trade_license_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Trade License issued by the local municipal authority.",
                        max_length=64,
                    ),
                ),
                (
                    "shop_act_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shop & Establishment Act registration number (Shops Act license).",
                        max_length=64,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOLE_PROPRIETORSHIP", "Sole Proprietorship"),
                            ("PARTNERSHIP", "Partnership Firm"),
                            ("LLP", "Limited Liability Partnership (LLP)"),
                            ("PRIVATE_LIMITED", "Private Limited Company"),
                            ("OPC", "One Person Company (OPC)"),
                            ("PUBLIC_LIMITED", "Public Limited Company"),
                            ("HUF", "Hindu Undivided Family (HUF)"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "year_of_establishment",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Year the business was established (e.g. 2010). Printed on letterheads.",
                        null=True,
                    ),
                ),
                (
                    "authorized_signatory_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full name of the person authorized to sign invoices and legal documents.",
                        max_length=120,
                    ),
                ),
                (
                    "authorized_signatory_designation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Designation of the signatory (e.g. Proprietor, Director, Partner).",
                        max_length=80,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "bank_ifsc_code",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                (
                    "bank_branch",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UPI ID for QR / payment link on receipts (e.g. businessname@upi).",
                        max_length=80,
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "receipt_prefix",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "default_currency_code",
                    models.CharField(default="INR", max_length=10),
                ),
                (
                    "timezone_name",
                    models.CharField(default="Asia/Kolkata", max_length=64),
                ),
                ("logo_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "business_profiles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicBusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                (
                    "hero_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("hero_subtitle", models.TextField(blank=True, default="")),
                (
                    "support_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "whatsapp_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("whatsapp_link", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("youtube_url", models.URLField(blank=True, default="")),
                ("address_text", models.TextField(blank=True, default="")),
                ("map_url", models.URLField(blank=True, default="")),
                ("business_hours", models.TextField(blank=True, default="")),
                ("public_logo_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "public_business_profiles",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("YOUTUBE", "YouTube"),
                            ("INSTAGRAM", "Instagram"),
                            ("WHATSAPP", "WhatsApp"),
                            ("JUSTDIAL", "Justdial"),
                            ("WEBSITE", "Website"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "brand_social_links",
                "ordering": ["platform", "id"],
            },
        ),
        migrations.CreateModel(
            name="BrandImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("REVIEWED", "Reviewed"),
                            ("APPLIED", "Applied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("payload_snapshot", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="business_setup.branddatasource",
                    ),
                ),
            ],
            options={
                "db_table": "brand_import_batches",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BrandImportedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("BRAND_IDENTITY", "Brand Identity"),
                            ("CONTACT_LOCATION", "Contact & Location"),
                            ("SOCIAL_LINK", "Social Link"),
                            ("MEDIA_ASSET", "Media Asset"),
                            ("PUBLIC_CONTENT", "Public Content"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("field_key", models.CharField(db_index=True, max_length=80)),
                ("value", models.JSONField(blank=True, default=dict)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("APPLIED", "Applied"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_brand_import_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="business_setup.brandimportbatch",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rejected_brand_import_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "brand_imported_items",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BrandProfileSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile_payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand_profile_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="business_setup.brandimportbatch",
                    ),
                ),
            ],
            options={
                "db_table": "brand_profile_snapshots",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessComplianceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RENTAL_AGREEMENT", "Rental Agreement"),
                            ("OWNERSHIP_PROOF", "Ownership Proof"),
                            ("UDYAM_CERTIFICATE", "Udyam Certificate"),
                            ("GST_CERTIFICATE", "GST Certificate"),
                            ("SHOP_LICENSE", "Shop License"),
                            ("BANK_PROOF", "Bank Proof"),
                            ("PAN_OR_TAX_PROOF", "PAN/Tax Proof"),
                            ("CA_OPINION", "CA Written Opinion"),
                            ("ADVOCATE_OPINION", "Advocate Legal Opinion"),
                            ("LEGAL_NOTICE", "Legal Notice"),
                            ("COURT_ORDER", "Court Order / Judgment"),
                            ("LEGAL_AGREEMENT", "Signed Legal Agreement / Contract"),
                            ("SCHEME_APPROVAL_LETTER", "Scheme Approval Letter"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=business_setup.models.core.business_compliance_document_upload_to,
                    ),
                ),
                (
                    "public_visibility",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("PUBLIC_SUMMARY_ONLY", "Public Summary Only"),
                        ],
                        db_index=True,
                        default="PRIVATE",
                        max_length=24,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("NOT_PROVIDED", "Not Provided"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("public_summary", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_business_compliance_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_business_compliance_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_compliance_documents",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessComplianceDocumentReviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.TextField(blank=True, default="")),
                ("expires_at", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "approved_public_summary",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "public_summary_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "source_template_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("evidence_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("last_action_reason", models.TextField(blank=True, default="")),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_state",
                        to="business_setup.businesscompliancedocument",
                    ),
                ),
                (
                    "public_summary_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_business_compliance_public_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_compliance_document_review_states",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessDataBackupJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL_DATABASE_LOGICAL", "Full database logical"),
                            ("SELECTED_SCOPES_EXPORT", "Selected scopes export"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("checksum", models.CharField(blank=True, default="", max_length=128)),
                ("row_counts", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_business_backup_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_data_backup_jobs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessDataRestoreJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PREVIEWED",
                        max_length=12,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "package_checksum",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("selected_scopes", models.JSONField(default=list)),
                ("preview", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_business_restore_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "backup_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restore_jobs",
                        to="business_setup.businessdatabackupjob",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_business_restore_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_data_restore_jobs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BusinessRulePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Default legal controls", max_length=120),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT_INSTALLMENT", "Product Instalment"),
                            ("DIRECT_SALE", "Direct Sale"),
                            ("RENTAL", "Rental"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        default="PRODUCT_INSTALLMENT",
                        max_length=40,
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CONTRACTUAL_WAIVER", "Contractual Waiver"),
                            ("TRADE_DISCOUNT", "Trade Discount"),
                            ("PROMOTIONAL_CREDIT", "Promotional Credit"),
                        ],
                        default="CONTRACTUAL_WAIVER",
                        max_length=40,
                    ),
                ),
                (
                    "selection_method",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("HASH_FAIRNESS", "Hash Fairness"),
                            ("ADMIN_APPROVED", "Admin Approved"),
                            ("PERFORMANCE_BASED", "Performance Based"),
                        ],
                        default="HASH_FAIRNESS",
                        max_length=40,
                    ),
                ),
                (
                    "funding_source",
                    models.CharField(
                        choices=[
                            ("COMPANY_MARGIN", "Company Margin"),
                            ("CUSTOMER_POOL_BLOCKED", "Customer Pool Blocked"),
                        ],
                        default="COMPANY_MARGIN",
                        max_length=40,
                    ),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CA_REVIEW_REQUIRED", "CA Review Required"),
                            ("ADVOCATE_REVIEW_REQUIRED", "Advocate Review Required"),
                            (
                                "APPROVED_FOR_INTERNAL_TEST",
                                "Approved For Internal Test",
                            ),
                            (
                                "APPROVED_FOR_PUBLIC_LAUNCH",
                                "Approved For Public Launch",
                            ),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="ADVOCATE_REVIEW_REQUIRED",
                        max_length=40,
                    ),
                ),
                (
                    "refund_sla_working_days",
                    models.PositiveSmallIntegerField(default=7),
                ),
                ("late_payment_charge_enabled", models.BooleanField(default=False)),
                ("late_payment_charge_configured", models.BooleanField(default=False)),
                (
                    "late_payment_charge_label",
                    models.CharField(default="Late Payment Charge", max_length=80),
                ),
                (
                    "partner_receipt_admin_approval_required",
                    models.BooleanField(default=True),
                ),
                ("kyc_masking_required", models.BooleanField(default=True)),
                (
                    "deposit_refund_requires_inspection",
                    models.BooleanField(default=True),
                ),
                ("gst_documents_require_hsn_sac", models.BooleanField(default=True)),
                (
                    "non_gst_document_labels",
                    models.JSONField(
                        blank=True,
                        default=business_setup.models.core.default_non_gst_document_labels,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_business_rule_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_rule_policies",
                "ordering": ["-is_active", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentPrintSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=business_setup.models.print_settings.document_print_logo_upload_to,
                    ),
                ),
                (
                    "authorized_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=business_setup.models.print_settings.document_print_signature_upload_to,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "business_tagline",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("print_address", models.TextField(blank=True, default="")),
                (
                    "print_phone",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "print_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "print_website",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tax_label", models.CharField(blank=True, default="", max_length=120)),
                ("invoice_terms", models.TextField(blank=True, default="")),
                ("receipt_terms", models.TextField(blank=True, default="")),
                ("delivery_challan_terms", models.TextField(blank=True, default="")),
                (
                    "subscription_contract_terms",
                    models.TextField(blank=True, default=""),
                ),
                ("rent_lease_contract_terms", models.TextField(blank=True, default="")),
                ("purchase_bill_terms", models.TextField(blank=True, default="")),
                ("vendor_voucher_terms", models.TextField(blank=True, default="")),
                ("account_statement_terms", models.TextField(blank=True, default="")),
                ("report_footer_note", models.TextField(blank=True, default="")),
                (
                    "authorized_signatory_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "customer_signature_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "document_layout_density",
                    models.CharField(
                        choices=[
                            ("COMFORTABLE", "Comfortable"),
                            ("COMPACT", "Compact"),
                        ],
                        default="COMFORTABLE",
                        max_length=16,
                    ),
                ),
                ("show_watermark", models.BooleanField(default=True)),
                ("show_logo", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "business_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_print_settings",
                        to="business_setup.businessprofile",
                    ),
                ),
            ],
            options={
                "db_table": "document_print_settings",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailSMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, default="smtp.gmail.com", max_length=255
                    ),
                ),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                (
                    "smtp_username",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("app_password_encrypted", models.TextField(blank=True, default="")),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("from_name", models.CharField(blank=True, default="", max_length=120)),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                ("last_test_success", models.BooleanField(blank=True, null=True)),
                (
                    "last_test_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "db_table": "email_smtp_settings",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["is_active"], name="email_smtp_is_active_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("PRIVACY", "Privacy"),
                            ("REFUND", "Refund / Cancellation"),
                            ("WARRANTY", "Warranty"),
                            ("DELIVERY", "Delivery"),
                            ("RENT_LEASE", "Rental / Lease"),
                            ("LUCKY_PLAN", "Lucky Plan EMI"),
                            ("DIRECT_SALE", "Direct Sale"),
                            ("PAYMENT", "Payment"),
                            ("SERVICE", "Service / Repair"),
                            ("GRIEVANCE", "Grievance"),
                            ("COMPLIANCE", "Compliance"),
                            ("CUSTOMER_SUPPORT", "Customer Support"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                ("content", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_policy_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_policy_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_policy_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "policy_pages",
                "ordering": ["slug", "-version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicyGovernanceMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("INTERNAL", "Internal")],
                        db_index=True,
                        default="PUBLIC",
                        max_length=16,
                    ),
                ),
                (
                    "governance_category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                (
                    "coverage_group",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("requires_legal_review", models.BooleanField(default=True)),
                ("requires_admin_acceptance", models.BooleanField(default=False)),
                (
                    "submitted_for_review_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_due_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("internal_acceptance_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("archive_reason", models.TextField(blank=True, default="")),
                (
                    "source_template_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_policy_governance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_policy_governance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_internal_policy_governance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_policy_governance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_policy_governance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_metadata",
                        to="business_setup.policypage",
                    ),
                ),
            ],
            options={
                "db_table": "policy_governance_metadata",
                "ordering": ["policy__slug", "-policy__version", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=120, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_blocks",
                        to="business_setup.brandimportbatch",
                    ),
                ),
            ],
            options={
                "db_table": "public_content_blocks",
                "ordering": ["key", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="businesscompliancedocument",
            index=models.Index(
                fields=["document_type", "verification_status"],
                name="business_co_documen_0928fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscompliancedocument",
            index=models.Index(
                fields=["public_visibility", "verification_status"],
                name="business_co_public__4d0948_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscompliancedocumentreviewstate",
            index=models.Index(
                fields=["review_status", "approved_public_summary"],
                name="bc_doc_review_status_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businesscompliancedocumentreviewstate",
            index=models.Index(
                fields=["expires_at", "review_status"], name="bc_doc_review_expiry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessrulepolicy",
            index=models.Index(
                fields=["risk_status", "is_active"],
                name="business_ru_risk_st_440138_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businessrulepolicy",
            index=models.Index(
                fields=["plan_type", "risk_status"],
                name="business_ru_plan_ty_1b933e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessrulepolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_business_rule_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessrulepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("refund_sla_working_days__gte", 1)),
                name="chk_business_rule_refund_sla_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="documentprintsettings",
            index=models.Index(
                fields=["is_active"], name="document_pr_is_acti_3cb883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policypage",
            index=models.Index(
                fields=["slug", "status"], name="policy_page_slug_52ae13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policypage",
            index=models.Index(
                fields=["category", "status"], name="policy_page_categor_6d2e8f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="policypage",
            constraint=models.UniqueConstraint(
                fields=("slug", "version"), name="unique_policy_slug_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="policypage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PUBLISHED")),
                fields=("slug",),
                name="unique_published_policy_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="policygovernancemetadata",
            index=models.Index(
                fields=["visibility", "governance_category"],
                name="policy_gov_visibility_cat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policygovernancemetadata",
            index=models.Index(
                fields=["coverage_group", "visibility"], name="policy_gov_group_vis_idx"
            ),
        ),
            ],
        ),
    ]
