# Generated by Django 5.2.7 on 2026-08-10 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_setup", "0002_fold_dryrun_from_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="is_legacy_migration",
            field=models.BooleanField(
                default=False,
                help_text="True if this is an existing business migrating legacy data.",
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="legacy_migration_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="legacy_migration_completed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="legacy_migration_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
