# Generated by Django 5.2.7 on 2026-08-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_setup", "0003_businessprofile_is_legacy_migration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentprintsettings",
            name="show_upi_qr",
            field=models.BooleanField(default=True),
        ),
    ]
