# Generated by Django 5.2.7 on 2026-09-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_setup", "0004_documentprintsettings_show_upi_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="enterprise_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name as printed on the Udyam certificate, which may differ from the trading name.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="enterprise_type",
            field=models.CharField(
                blank=True,
                choices=[("MICRO", "Micro"), ("SMALL", "Small"), ("MEDIUM", "Medium")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="nic_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="National Industrial Classification code declared on the Udyam registration.",
                max_length=20,
            ),
        ),
    ]
