# Generated by Django 5.2.16 on 2026-09-26 03:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_setup', '0005_businessprofile_enterprise_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshStartActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('DRY_RUN', 'Dry Run'), ('EXECUTED', 'Executed')], db_index=True, max_length=20)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fresh_start_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fresh_start_action_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
