# Generated by Django 5.2.16 on 2026-09-26 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_setup', '0006_freshstartactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrulepolicy',
            name='effective_from',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='businessrulepolicy',
            name='effective_to',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
