import type { DocumentPrintSettings } from "@/services/business-setup";

export type DocumentCopyLabel = "Original" | "Customer Copy" | "Office Copy" | "Duplicate";

export type DocumentTermsKey =
  | "invoice_terms"
  | "receipt_terms"
  | "delivery_challan_terms"
  | "subscription_contract_terms"
  | "rent_lease_contract_terms"
  | "purchase_bill_terms"
  | "vendor_voucher_terms"
  | "account_statement_terms";

export type DocumentBrandTheme = {
  businessName: string;
  tagline: string;
  logoPath: string;
  showLogo: boolean;
  showWatermark: boolean;
  layoutDensity: "COMFORTABLE" | "COMPACT" | string;
  phone: string;
  email: string;
  website: string;
  addressLines: string[];
  panLabel: string;
  gstLabel: string;
  taxLabel: string;
  defaultTerms: string[];
  terms: Partial<Record<DocumentTermsKey, string[]>>;
  reportFooterNote: string;
  signatureLabels: {
    authorized: string;
    customer: string;
    receiver: string;
    staff: string;
  };
  colors: {
    ink: string;
    muted: string;
    ivory: string;
    brown: string;
    gold: string;
    border: string;
  };
};

export const documentCopyLabels: DocumentCopyLabel[] = [
  "Original",
  "Customer Copy",
  "Office Copy",
  "Duplicate",
];

const fallbackAddressLines = [
  "Subidha Furniture, Asansol",
  "West Bengal, India",
];

function splitTerms(value?: string | null): string[] {
  return String(value || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function splitAddress(value?: string | null): string[] {
  const lines = splitTerms(value);
  return lines.length ? lines : fallbackAddressLines;
}

export const subidhaDocumentTheme: DocumentBrandTheme = {
  businessName: "Subidha Furniture",
  tagline: "Furniture, Advance EMI, Rent & Lease",
  logoPath: "/logo.png",
  showLogo: true,
  showWatermark: true,
  layoutDensity: "COMFORTABLE",
  phone: "+91 77972 80952",
  email: "support@subidhafurnitureasansol.com",
  website: "subidhafurnitureasansol.com",
  addressLines: fallbackAddressLines,
  panLabel: "PAN: —",
  gstLabel: "GSTIN: —",
  taxLabel: "GSTIN: —",
  defaultTerms: [
    "All amounts and balances are shown from posted business records only.",
    "This document is system generated and valid with authorized signature/stamp where required.",
    "Cancelled, voided, returned, or draft documents must not be treated as normal paid documents.",
  ],
  terms: {},
  reportFooterNote: "Generated by SUBIDHA CORE for audit and business records.",
  signatureLabels: {
    authorized: "Authorized Signature",
    customer: "Customer Signature",
    receiver: "Receiver Signature",
    staff: "Staff Signature",
  },
  colors: {
    ink: "#2f2418",
    muted: "#7c6a56",
    ivory: "#fffaf0",
    brown: "#6f4e27",
    gold: "#b8872f",
    border: "#e7d7bd",
  },
};

export function documentThemeFromSettings(settings?: DocumentPrintSettings | null): DocumentBrandTheme {
  if (!settings) return subidhaDocumentTheme;
  const taxLabel = settings.tax_label?.trim() || subidhaDocumentTheme.taxLabel;
  const logoPath = settings.business_logo_url?.trim() || subidhaDocumentTheme.logoPath;
  return {
    ...subidhaDocumentTheme,
    businessName: settings.business_name?.trim() || subidhaDocumentTheme.businessName,
    tagline: settings.business_tagline?.trim() || subidhaDocumentTheme.tagline,
    logoPath,
    showLogo: settings.show_logo !== false,
    showWatermark: settings.show_watermark !== false,
    layoutDensity: settings.document_layout_density || subidhaDocumentTheme.layoutDensity,
    phone: settings.print_phone?.trim() || subidhaDocumentTheme.phone,
    email: settings.print_email?.trim() || subidhaDocumentTheme.email,
    website: settings.print_website?.trim() || subidhaDocumentTheme.website,
    addressLines: splitAddress(settings.print_address),
    taxLabel,
    gstLabel: taxLabel,
    defaultTerms: splitTerms(settings.invoice_terms).length
      ? splitTerms(settings.invoice_terms)
      : subidhaDocumentTheme.defaultTerms,
    terms: {
      invoice_terms: splitTerms(settings.invoice_terms),
      receipt_terms: splitTerms(settings.receipt_terms),
      delivery_challan_terms: splitTerms(settings.delivery_challan_terms),
      subscription_contract_terms: splitTerms(settings.subscription_contract_terms),
      rent_lease_contract_terms: splitTerms(settings.rent_lease_contract_terms),
      purchase_bill_terms: splitTerms(settings.purchase_bill_terms),
      vendor_voucher_terms: splitTerms(settings.vendor_voucher_terms),
      account_statement_terms: splitTerms(settings.account_statement_terms),
    },
    reportFooterNote: settings.report_footer_note?.trim() || subidhaDocumentTheme.reportFooterNote,
    signatureLabels: {
      ...subidhaDocumentTheme.signatureLabels,
      authorized: settings.authorized_signatory_label?.trim() || subidhaDocumentTheme.signatureLabels.authorized,
      customer: settings.customer_signature_label?.trim() || subidhaDocumentTheme.signatureLabels.customer,
    },
  };
}

export function termsForDocument(theme: DocumentBrandTheme, key?: DocumentTermsKey | null): string[] {
  if (!key) return theme.defaultTerms;
  const terms = theme.terms[key] || [];
  return terms.length ? terms : theme.defaultTerms;
}
