# Generated by Django 6.0.2 on 2026-04-08 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_accountingperiod_and_more'),
        ('subscriptions', '0033_alter_auditlog_action_type_subscriptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True)),
                ('unit_of_measure', models.CharField(default='PCS', max_length=30)),
                ('stock_tracking_enabled', models.BooleanField(db_index=True, default=True)),
                ('opening_stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reorder_level_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('AVG', 'Average')], db_index=True, default='FIFO', max_length=10)),
                ('standard_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_profile', to='subscriptions.product')),
            ],
            options={
                'db_table': 'inventory_items',
                'ordering': ['product__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('bill_date', models.DateField(db_index=True)),
                ('tax_mode', models.CharField(choices=[('GST', 'GST'), ('NON_GST', 'Non-GST')], db_index=True, default='GST', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='accounting.financeaccount')),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill', to='accounting.journalentry')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='accounting.vendor')),
            ],
            options={
                'db_table': 'inventory_purchase_bills',
                'ordering': ['-bill_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='inventory.inventoryitem')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchasebill')),
            ],
            options={
                'db_table': 'inventory_purchase_bill_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('adjustment_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'inventory_stock_adjustments',
                'ordering': ['-adjustment_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.inventoryitem')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('EMI_DELIVERY_OUT', 'EMI Delivery Out'), ('SALE_RETURN_IN', 'Sale Return In'), ('PURCHASE_RETURN_OUT', 'Purchase Return Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=30)),
                ('quantity_in', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('quantity_out', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('movement_date', models.DateField(db_index=True)),
                ('reference_model', models.CharField(db_index=True, max_length=100)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('warehouse_name', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='inventory.inventoryitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_stock_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('posted_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'inventory_stock_ledger',
                'ordering': ['-movement_date', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['stock_tracking_enabled', 'is_active'], name='inventory_i_stock_t_fdf09e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['status', 'bill_date'], name='inventory_p_status_dfc4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['vendor', 'bill_date'], name='inventory_p_vendor__018025_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['status', 'adjustment_date'], name='inventory_s_status_8334ab_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['inventory_item', 'movement_date', 'movement_type'], name='inventory_s_invento_c7fde5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_model', 'reference_id'], name='inventory_s_referen_15f1b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in__gte', Decimal('0.000'))), name='inventory_stock_quantity_in_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_out__gte', Decimal('0.000'))), name='inventory_stock_quantity_out_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_in__gt', Decimal('0.000')), ('quantity_out', Decimal('0.000'))), models.Q(('quantity_out__gt', Decimal('0.000')), ('quantity_in', Decimal('0.000'))), _connector='OR'), name='inventory_stock_exactly_one_side_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockledger',
            constraint=models.UniqueConstraint(fields=('inventory_item', 'movement_type', 'reference_model', 'reference_id'), name='inventory_stock_unique_reference_movement'),
        ),
    ]
