# Generated by Django 6.0.2 on 2026-04-08 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField(db_index=True)),
                ('method', models.CharField(choices=[('FIFO', 'FIFO'), ('AVG', 'Average')], db_index=True, default='FIFO', max_length=10)),
                ('totals_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_valuations',
                'ordering': ['-as_of_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['as_of_date', 'method'], name='inventory_v_as_of_d_8cd1f7_idx')],
            },
        ),
    ]
