# Generated by Django 6.0.2 on 2026-04-09 04:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_product_master_from_inventory(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    Product = apps.get_model("subscriptions", "Product")

    for item in InventoryItem.objects.exclude(product_id=None).iterator():
        updates = {}
        sku = (getattr(item, "sku", None) or "").strip().upper()
        unit_of_measure = (getattr(item, "unit_of_measure", None) or "").strip().upper()

        product = Product.objects.filter(pk=item.product_id).first()
        if product is None:
            continue

        if sku and not (getattr(product, "sku", None) or "").strip():
            updates["sku"] = sku
        if unit_of_measure and not (getattr(product, "unit_of_measure", None) or "").strip():
            updates["unit_of_measure"] = unit_of_measure

        if updates:
            Product.objects.filter(pk=product.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_assetcategory_creditnote_cancel_reason_and_more'),
        ('inventory', '0002_inventoryvaluation'),
        ('subscriptions', '0034_product_sku_product_unit_of_measure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE_IN', 'Opening Balance In'), ('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('EMI_DELIVERY_OUT', 'EMI Delivery Out'), ('EMI_RETURN_IN', 'EMI Return In'), ('SALE_RETURN_IN', 'Sale Return In'), ('PURCHASE_RETURN_OUT', 'Purchase Return Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('location_type', models.CharField(choices=[('STORE', 'Store'), ('WAREHOUSE', 'Warehouse'), ('SHOWROOM', 'Showroom')], db_index=True, default='STORE', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'inventory_stock_locations',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'location_type'], name='inventory_s_is_acti_0ab70b_idx')],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.stocklocation'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['stock_location', 'movement_date', 'movement_type'], name='inventory_s_stock_l_5da8f0_idx'),
        ),
        migrations.RunPython(backfill_product_master_from_inventory, migrations.RunPython.noop),
    ]
