# Generated by Django 6.0.2 on 2026-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockledger_movement_type_stocklocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='delivery_stock_bridge_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_item_type',
            field=models.CharField(choices=[('FINISHED_GOOD', 'Finished Good'), ('ACCESSORY', 'Accessory'), ('RAW_MATERIAL', 'Raw Material')], db_index=True, default='FINISHED_GOOD', max_length=20),
        ),
    ]
