# Generated by Django 6.0.2 on 2026-04-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_delivery_stock_bridge_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_BALANCE_IN', 'Opening Balance In'), ('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('EMI_DELIVERY_OUT', 'EMI Delivery Out'), ('EMI_RETURN_IN', 'EMI Return In'), ('SALE_RETURN_IN', 'Sale Return In'), ('PRODUCTION_ISSUE_OUT', 'Production Issue Out'), ('PRODUCTION_RETURN_IN', 'Production Return In'), ('PRODUCTION_RECEIPT_IN', 'Production Receipt In'), ('PURCHASE_RETURN_OUT', 'Purchase Return Out'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], db_index=True, max_length=30),
        ),
    ]
