# Generated by Django 6.0.2 on 2026-04-10 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_employeeexpenseclaim_branch_and_more'),
        ('branch_control', '0001_initial'),
        ('inventory', '0005_alter_stockledger_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='branch_control.branch'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_locations', to='branch_control.branch'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['branch', 'bill_date'], name='inventory_p_branch__f52644_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['branch', 'is_active'], name='inventory_s_branch__51e95a_idx'),
        ),
    ]
