# Generated by Django 6.0.2 on 2026-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_purchasebill_branch_stocklocation_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockledger",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING_BALANCE_IN", "Opening Balance In"),
                    ("PURCHASE_IN", "Purchase In"),
                    ("PURCHASE_RECEIVE", "Purchase Receive"),
                    ("SALE_OUT", "Sale Out"),
                    ("EMI_DELIVERY_OUT", "EMI Delivery Out"),
                    ("DELIVERY_OUT", "Delivery Out"),
                    ("EMI_RETURN_IN", "EMI Return In"),
                    ("CUSTOMER_RETURN", "Customer Return"),
                    ("SALE_RETURN_IN", "Sale Return In"),
                    ("PRODUCTION_ISSUE_OUT", "Production Issue Out"),
                    ("PRODUCTION_CONSUME", "Production Consume"),
                    ("PRODUCTION_RETURN_IN", "Production Return In"),
                    ("PRODUCTION_RECEIPT_IN", "Production Receipt In"),
                    ("PRODUCTION_OUTPUT", "Production Output"),
                    ("PURCHASE_RETURN_OUT", "Purchase Return Out"),
                    ("VENDOR_RETURN", "Vendor Return"),
                    ("ADJUSTMENT_IN", "Adjustment In"),
                    ("ADJUSTMENT_OUT", "Adjustment Out"),
                    ("STOCK_ADJUSTMENT", "Stock Adjustment"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("SALE_RESERVE", "Sale Reserve (Soft Hold)"),
                    ("SALE_RELEASE", "Sale Release (Reservation Released)"),
                    ("DAMAGE", "Damage Write-off"),
                    ("MAINTENANCE_HOLD", "Maintenance Hold"),
                    ("MAINTENANCE_RELEASE", "Maintenance Release"),
                    ("QUALITY_HOLD", "Quality Hold"),
                    ("QUALITY_RELEASE", "Quality Release"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
