# Generated by Django 6.0.2 on 2026-04-30 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_phase2_stock_movement_types_and_reserved_qty'),
        ('subscriptions', '0059_financialledger_control_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_reason', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_audits', to=settings.AUTH_USER_MODEL)),
                ('stock_adjustment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_audit', to='inventory.stockadjustment')),
            ],
            options={
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('stock_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_profile', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'inventory_warehouses',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], db_index=True, default='ACTIVE', max_length=12)),
                ('source_module', models.CharField(db_index=True, max_length=160)),
                ('source_object_id', models.CharField(db_index=True, max_length=120)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='subscriptions.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_reservations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('RESERVED', 'Reserved'), ('RELEASED', 'Released'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('source_module', models.CharField(db_index=True, max_length=160)),
                ('source_object_id', models.CharField(db_index=True, max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stock_ledger_entries', to='subscriptions.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reorder_rules', to='subscriptions.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reorder_rules', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_reorder_rules',
                'ordering': ['product_id', 'warehouse_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('shortage_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=12)),
                ('demand_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_purchase_needs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_purchase_needs', to='subscriptions.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_needs', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_purchase_needs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'code'], name='inventory_w_is_acti_85c4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['product', 'warehouse', 'status'], name='inventory_s_product_f327f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['source_module', 'source_object_id'], name='inventory_s_source__a650d0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['product', 'warehouse', 'movement_type'], name='inventory_s_product_c0adb1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['source_module', 'source_object_id'], name='inventory_s_source__ed2b7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reorderrule',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='purchaseneed',
            index=models.Index(fields=['status', 'created_at'], name='inventory_p_status_4227d3_idx'),
        ),
    ]
