# Generated by Django 6.0.2 on 2026-05-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_purchase_need_direct_sale_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchaseneed",
            new_name="inventory_p_source__91c45b_idx",
            old_name="inventory_pn_src_sta_pri_idx",
        ),
    ]
