# Generated by Django 5.2.7 on 2026-05-02 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_inventory_pn_src_sta_pri_idx_inventory_p_source__91c45b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='stockadjustmentline',
            name='valuation_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
