# Generated by Django 5.2.7 on 2026-05-02 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stock_adjustment_line_cost_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('last_preview_payload', models.JSONField(blank=True, null=True)),
                ('last_apply_summary', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_stock_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_opening_stock_batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valuation_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('CSV_IMPORT', 'CSV Import')], default='MANUAL', max_length=16)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='inventory.openingstockbatch')),
                ('correction_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_stock_correction_for_entries', to='inventory.stockadjustment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_entries', to='inventory.inventoryitem')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opening_stock_entries', to=settings.AUTH_USER_MODEL)),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_stock_entries', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'inventory_opening_stock_entries',
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['status', 'effective_date'], name='inventory_o_status_91e524_idx'), models.Index(fields=['inventory_item', 'stock_location', 'effective_date'], name='inventory_o_invento_c1b77e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('batch__isnull', False), ('csv_row_number__isnull', False)), fields=('batch', 'csv_row_number'), name='opening_stock_entry_batch_csv_row_uniq')],
            },
        ),
    ]
