# Generated by Django 6.0.2 on 2026-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_alter_purchaseneed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseneed",
            name="source_module",
            field=models.CharField(
                choices=[
                    ("DIRECT_SALE", "Direct Sale"),
                    ("WINNER_DELIVERY", "Winner Delivery"),
                    ("SUBSCRIPTION_DEMAND", "Subscription Demand"),
                    ("GENERAL", "General"),
                ],
                db_index=True,
                default="GENERAL",
                max_length=32,
            ),
        ),
    ]
