# Generated by Django 5.2.7 on 2026-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_purchaseneed_source_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='tax_profile_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
