# Generated by Django 6.0.2 on 2026-05-13 17:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_seed_default_non_gst_business_tax_profile'),
        ('branch_control', '0002_seed_primary_branch_and_backfill_context'),
        ('inventory', '0017_purchasebill_tax_profile_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='allow_over_receive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='over_receive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('request_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIALLY_ORDERED', 'Partially Ordered'), ('ORDERED', 'Ordered'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='branch_control.branch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('source_purchase_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='inventory.purchaseneed')),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='inventory.stocklocation')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='accounting.vendor')),
            ],
            options={
                'db_table': 'inventory_purchase_requests',
                'ordering': ['-request_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_lines', to='inventory.inventoryitem')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaserequest')),
            ],
            options={
                'db_table': 'inventory_purchase_request_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], db_index=True, default='DRAFT', max_length=16)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=160)),
                ('credit_period_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_agreements', to='accounting.vendor')),
            ],
            options={
                'db_table': 'inventory_vendor_agreements',
                'ordering': ['-effective_from', '-created_at', '-id'],
            },
        ),
    ]
