# Generated by Django 6.0.2 on 2026-05-14 19:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_goodsreceipt_allow_over_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='costing_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_cost_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_finished_goods_output_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_labour_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturing_raw_material_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='preferred_stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_inventory_items', to='inventory.stocklocation'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='stock_tracking_status',
            field=models.CharField(choices=[('NOT_PREPARED', 'Not Prepared'), ('PREPARED_NO_STOCK', 'Prepared (No Stock)'), ('STOCK_ACTIVE', 'Stock Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='PREPARED_NO_STOCK', max_length=24),
        ),
    ]
