# Generated by Django 5.2.7 on 2026-06-24 04:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryitem_costing_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_tracking_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lot_tracking_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(db_index=True, max_length=80)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('qr_code', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('received_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('QUARANTINED', 'Quarantined'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('source_model', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_lots', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.inventoryitem')),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='inventory.stocklocation')),
            ],
            options={
                'db_table': 'inventory_lots',
                'ordering': ['expiry_date', 'lot_code', 'id'],
                'indexes': [models.Index(fields=['inventory_item', 'status', 'expiry_date'], name='inventory_l_invento_d5428b_idx'), models.Index(fields=['stock_location', 'status', 'expiry_date'], name='inventory_l_stock_l_de113a_idx'), models.Index(fields=['barcode', 'qr_code'], name='inventory_l_barcode_5e2579_idx')],
                'constraints': [models.UniqueConstraint(fields=('inventory_item', 'lot_code', 'stock_location'), name='inventory_lot_unique_item_code_location'), models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', Decimal('0.000'))), name='inventory_lot_quantity_non_negative')],
            },
        ),
    ]
