# Generated by Django 5.2.7 on 2026-07-12 08:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_inventoryitem_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "inventory_service_catalog_items",
                "ordering": ["category", "name", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "category"],
                        name="inventory_s_status_9571cc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinishedGoodAccessoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charge_mode",
                    models.CharField(
                        choices=[
                            ("FREE", "Free (Included)"),
                            ("CHARGEABLE", "Chargeable"),
                        ],
                        db_index=True,
                        default="FREE",
                        max_length=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Charged price when charge_mode=CHARGEABLE; ignored when FREE.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_default_included",
                    models.BooleanField(
                        default=True,
                        help_text="Pre-selected when creating a sale/subscription.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "accessory",
                    models.ForeignKey(
                        limit_choices_to={"stock_item_type": "ACCESSORY"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_to_finished_goods",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "finished_good",
                    models.ForeignKey(
                        limit_choices_to={"stock_item_type": "FINISHED_GOOD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_links",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_fg_accessory_links",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["finished_good", "charge_mode"],
                        name="inventory_f_finishe_9e12fb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("finished_good", "accessory"),
                        name="uq_fg_accessory_link",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinishedGoodServiceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charge_mode",
                    models.CharField(
                        choices=[
                            ("FREE", "Free (Included)"),
                            ("CHARGEABLE", "Chargeable"),
                        ],
                        db_index=True,
                        default="FREE",
                        max_length=12,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Override price; 0 means use service standard_price when chargeable.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_default_included",
                    models.BooleanField(
                        default=True,
                        help_text="Pre-selected when creating a sale/subscription.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "finished_good",
                    models.ForeignKey(
                        limit_choices_to={"stock_item_type": "FINISHED_GOOD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finished_good_links",
                        to="inventory.servicecatalogitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_fg_service_links",
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["finished_good", "charge_mode"],
                        name="inventory_f_finishe_3e1388_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("finished_good", "service"), name="uq_fg_service_link"
                    )
                ],
            },
        ),
    ]
