# Generated by Django 5.2.7 on 2026-07-12 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_fg_accessory_service_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryVariantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="If True, one variant MUST be selected when this group appears on a billing.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "db_table": "inventory_accessory_variant_groups",
                "ordering": ["category", "subcategory", "name", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="finishedgoodaccessorylink",
            name="uq_fg_accessory_link",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="variant_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human label for this variant within its group, e.g. 'Teak 6ft'.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="finishedgoodaccessorylink",
            name="accessory",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"stock_item_type": "ACCESSORY"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_to_finished_goods",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddIndex(
            model_name="accessoryvariantgroup",
            index=models.Index(
                fields=["is_active", "category"], name="inventory_a_is_acti_0e239e_idx"
            ),
        ),
        migrations.AddField(
            model_name="finishedgoodaccessorylink",
            name="variant_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fg_links",
                to="inventory.accessoryvariantgroup",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="variant_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="inventory.accessoryvariantgroup",
            ),
        ),
    ]
