# Generated by Django 5.2.7 on 2026-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_accessory_variant_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecatalogitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WARRANTY", "Warranty"),
                    ("INSTALLATION", "Installation"),
                    ("MAINTENANCE", "Maintenance / AMC"),
                    ("POLISH", "Polish / Finishing"),
                    ("DELIVERY", "Delivery / Logistics"),
                    ("REPAIR", "Repair"),
                    ("ADDON", "Add-on / Upgrade"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=16,
            ),
        ),
    ]
