# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        ("inventory", "0023_service_type_field"),
        ("products_core", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="inventoryitem",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_profile",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseneed",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_purchase_needs",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseneed",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_purchase_needs",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="reorderrule",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_reorder_rules",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockledgerentry",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_stock_ledger_entries",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="stockreservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="products_core.product",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
