# Generated by Django 5.2.7 on 2026-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_alter_inventoryitem_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="valuation_method",
            field=models.CharField(
                choices=[("FIFO", "FIFO"), ("AVG", "Average")],
                db_index=True,
                default="AVG",
                max_length=10,
            ),
        ),
    ]
