# Generated by Django 5.2.7 on 2026-08-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_update_default_valuation_method_to_avg"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklocation",
            name="address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Physical address for delivery dispatch and warehouse navigation",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="is_default_receiving_location",
            field=models.BooleanField(
                default=False,
                help_text="Default receiving dock for supplier deliveries to this branch",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Contact phone number for location staff",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("STORE", "Store"),
                    ("WAREHOUSE", "Warehouse"),
                    ("SHOWROOM", "Showroom"),
                    ("QUARANTINE", "Quarantine"),
                    ("TRANSIT", "Transit"),
                ],
                db_index=True,
                default="STORE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InventoryReadinessDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key for the warning (e.g., 'PRODUCT_MISSING_SKU_123')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product Master"),
                            ("STOCK", "Stock/Inventory"),
                            ("LOCATION", "Location Setup"),
                            ("CONFIGURATION", "System Configuration"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note on why this warning was dismissed",
                        max_length=255,
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_readiness_dismissals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_readiness_dismissals",
                "ordering": ["-dismissed_at"],
                "indexes": [
                    models.Index(
                        fields=["warning_key", "dismissed_at"],
                        name="inventory_r_warning_88a0f5_idx",
                    ),
                    models.Index(
                        fields=["category", "dismissed_at"],
                        name="inventory_r_categor_452057_idx",
                    ),
                ],
            },
        ),
    ]
