# Generated by Django 5.2.7 on 2026-09-18 09:12

from django.db import migrations
from django.db.models import F

def fix_item_types(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    items = InventoryItem.objects.exclude(stock_item_type=F("product__item_type"))
    for item in items:
        if item.product.item_type:
            item.stock_item_type = item.product.item_type
            item.save(update_fields=["stock_item_type", "updated_at"])

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_backfill_stock_tracking_status"),
    ]

    operations = [
        migrations.RunPython(fix_item_types, reverse_code=migrations.RunPython.noop),
    ]
