# Generated by Django 5.2.7 on 2026-09-18 09:56

from django.db import migrations

def sync_all_accessories(apps, schema_editor):
    ProductRelationship = apps.get_model('products_core', 'ProductRelationship')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    FinishedGoodAccessoryLink = apps.get_model('inventory', 'FinishedGoodAccessoryLink')

    # Get all accessory relationships
    relationships = ProductRelationship.objects.filter(relationship_type="ACCESSORY")

    for rel in relationships:
        if not rel.related_product_id:
            continue
            
        acc_item = None
        if rel.related_variant_sku:
            acc_item = InventoryItem.objects.filter(sku=rel.related_variant_sku).first()
            
        if not acc_item:
            acc_item = InventoryItem.objects.filter(product_id=rel.related_product_id).first()
            
        if not acc_item:
            continue
            
        # Determine the target FG inventory items
        target_fgs = []
        if rel.parent_variant_sku:
            fg_item = InventoryItem.objects.filter(sku=rel.parent_variant_sku).first()
            if fg_item:
                target_fgs.append(fg_item)
        else:
            target_fgs = list(InventoryItem.objects.filter(product_id=rel.product_id))
            
        charge_mode = 'FREE' if rel.is_price_included_in_parent else 'CHARGEABLE'
        for fg in target_fgs:
            FinishedGoodAccessoryLink.objects.update_or_create(
                finished_good=fg,
                accessory=acc_item,
                defaults={
                    'charge_mode': charge_mode,
                    'sale_price': 0,
                    'is_default_included': True,
                    'notes': rel.notes or ""
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_fix_desynced_item_types"),
    ]

    operations = [
        migrations.RunPython(sync_all_accessories, reverse_code=migrations.RunPython.noop),
    ]
