# Generated by Django 5.2.7 on 2026-09-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_backfill_pim_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorbill",
            name="stock_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_vendor_bills",
                to="inventory.stocklocation",
            ),
        ),
    ]
