# Generated by Django 5.2.16 on 2026-09-23 16:46

from django.db import migrations
from decimal import Decimal

def fix_opening_stock_costs(apps, schema_editor):
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    OpeningStockEntry = apps.get_model('inventory', 'OpeningStockEntry')
    
    # We only care about items that are FINISHED_GOOD or ACCESSORY, but let's just do all
    # that have default_stock_location=None or standard_unit_cost=0
    items = InventoryItem.objects.filter(
        default_stock_location__isnull=True
    ) | InventoryItem.objects.filter(
        standard_unit_cost__in=[Decimal("0.00"), Decimal("0"), None]
    )
    items = items.distinct()

    fixed_locs = 0
    fixed_costs = 0
    
    for item in items:
        # Find their first posted opening stock entry
        first_posted = OpeningStockEntry.objects.filter(
            inventory_item=item,
            status="POSTED"
        ).first()

        if first_posted:
            changed = False
            
            if not item.default_stock_location and first_posted.stock_location:
                item.default_stock_location = first_posted.stock_location
                fixed_locs += 1
                changed = True
                
            if not item.standard_unit_cost or item.standard_unit_cost == Decimal("0.00"):
                if first_posted.unit_cost_snapshot and first_posted.unit_cost_snapshot > 0:
                    item.standard_unit_cost = first_posted.unit_cost_snapshot
                    fixed_costs += 1
                    changed = True
            
            if changed:
                item.save(update_fields=['default_stock_location', 'standard_unit_cost'])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_add_stock_location_to_vendorbill'),
    ]

    operations = [
        migrations.RunPython(fix_opening_stock_costs, migrations.RunPython.noop),
    ]
