# Generated by Django 5.2.7 on 2026-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewPlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_places_api_key", models.CharField(blank=True, max_length=255)),
                ("google_place_id", models.CharField(blank=True, max_length=255)),
                ("facebook_page_id", models.CharField(blank=True, max_length=255)),
                ("facebook_page_access_token", models.TextField(blank=True)),
                ("youtube_api_key", models.CharField(blank=True, max_length=255)),
                ("youtube_channel_id", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review platform configuration",
            },
        ),
    ]
