# Generated by Django 5.2.7 on 2026-06-21 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0001_initial'),
        ('crm', '0003_rename_crm_customer_customer_921db4_idx_crm_custome_custome_bea333_idx_and_more'),
        ('subscriptions', '0098_growth_requests_p5b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(max_length=40, unique=True)),
                ('brochure_token_snapshot', models.CharField(blank=True, max_length=80)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('address_text', models.TextField(blank=True)),
                ('preferred_plan', models.CharField(choices=[('RENT', 'Rent'), ('LEASE', 'Lease'), ('LUCKY_EMI', 'Lucky EMI'), ('DIRECT_SALE', 'Direct Sale'), ('NOT_SURE', 'Not Sure')], db_index=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUOTED', 'Quoted'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], db_index=True, default='NORMAL', max_length=20)),
                ('crm_sync_warning', models.TextField(blank=True)),
                ('source', models.CharField(default='BROCHURE', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_brochure_enquiries', to=settings.AUTH_USER_MODEL)),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enquiries', to='brochures.brochuredocument')),
                ('crm_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_enquiries', to='crm.partyinteraction')),
                ('crm_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_enquiries', to='crm.lead')),
                ('crm_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_enquiries', to='crm.partymaster')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BrochureEnquiryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('brochure_product_code', models.CharField(blank=True, max_length=80)),
                ('brochure_product_name', models.CharField(blank=True, max_length=180)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('preferred_plan', models.CharField(blank=True, choices=[('RENT', 'Rent'), ('LEASE', 'Lease'), ('LUCKY_EMI', 'Lucky EMI'), ('DIRECT_SALE', 'Direct Sale'), ('NOT_SURE', 'Not Sure')], max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brochures.brochureenquiry')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_enquiry_products', to='subscriptions.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='brochureenquiry',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='brochures_b_status_0a9e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='brochureenquiry',
            index=models.Index(fields=['assigned_to', 'status', 'created_at'], name='brochures_b_assigne_63686d_idx'),
        ),
    ]
