# Generated by Django 5.2.7 on 2026-06-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0002_brochureenquiry_brochureenquiryproduct_and_more'),
        ('crm', '0003_rename_crm_customer_customer_921db4_idx_crm_custome_custome_bea333_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureEnquiryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS', 'Status'), ('ASSIGNMENT', 'Assignment'), ('PRIORITY', 'Priority'), ('FOLLOW_UP', 'Follow Up')], default='STATUS', max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='crm_link_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='crm_link_status',
            field=models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('LINKED', 'Linked'), ('PARTIAL', 'Partial'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='NOT_ATTEMPTED', max_length=20),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='crm_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='brochures.brochureenquiry'),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='duplicate_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='is_possible_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brochureenquiry',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='brochureenquiry',
            index=models.Index(fields=['phone_normalized', 'brochure', 'created_at'], name='brochures_b_phone_n_0589b8_idx'),
        ),
        migrations.AddField(
            model_name='brochureenquirystatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brochure_enquiry_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brochureenquirystatushistory',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='brochures.brochureenquiry'),
        ),
    ]
