# Generated by Django 5.2.7 on 2026-06-21 14:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brochures", "0003_brochureenquirystatushistory_and_more"),
        ("subscriptions", "0098_growth_requests_p5b"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrochureQuotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quotation_no", models.CharField(max_length=40, unique=True)),
                ("crm_party_id", models.PositiveIntegerField(blank=True, null=True)),
                ("crm_lead_id", models.PositiveIntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("phone_normalized", models.CharField(blank=True, db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location", models.CharField(blank=True, max_length=180)),
                ("address_text", models.TextField(blank=True)),
                ("quotation_type", models.CharField(choices=[("RENT", "Rent"), ("LEASE", "Lease"), ("LUCKY_EMI", "Lucky EMI"), ("DIRECT_SALE", "Direct Sale"), ("MIXED", "Mixed")], db_index=True, max_length=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("ACCEPTED", "Accepted"), ("REJECTED", "Rejected"), ("EXPIRED", "Expired"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=20)),
                ("validity_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("subtotal_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("delivery_charge", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("security_deposit_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_payable_now", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("recurring_monthly_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("grand_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("terms_text", models.TextField(blank=True)),
                ("internal_note", models.TextField(blank=True)),
                ("public_token", models.CharField(db_index=True, max_length=80, unique=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="quotations/")),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brochure", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="quotations", to="brochures.brochuredocument")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_brochure_quotations", to=settings.AUTH_USER_MODEL)),
                ("enquiry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="quotations", to="brochures.brochureenquiry")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="BrochureQuotationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_snapshot", models.JSONField(blank=True, default=dict)),
                ("product_code", models.CharField(blank=True, max_length=80)),
                ("product_name", models.CharField(max_length=180)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("plan_type", models.CharField(choices=[("RENT", "Rent"), ("LEASE", "Lease"), ("LUCKY_EMI", "Lucky EMI"), ("DIRECT_SALE", "Direct Sale")], max_length=20)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("monthly_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("tenure_months", models.PositiveIntegerField(blank=True, null=True)),
                ("security_deposit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("line_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("availability_label", models.CharField(blank=True, max_length=80)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="brochure_quotation_lines", to="subscriptions.product")),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="brochures.brochurequotation")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="BrochureQuotationStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="brochure_quotation_status_changes", to=settings.AUTH_USER_MODEL)),
                ("quotation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="brochures.brochurequotation")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="brochurequotation",
            index=models.Index(fields=["status", "quotation_type", "created_at"], name="brochures_b_status_5afc8a_idx"),
        ),
        migrations.AddIndex(
            model_name="brochurequotation",
            index=models.Index(fields=["enquiry", "created_at"], name="brochures_b_enquiry_250dfd_idx"),
        ),
    ]
