# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brochures", "0004_brochurequotation_brochurequotationline_and_more"),
        ("products_core", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="brochureenquiryproduct",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brochure_enquiry_products",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="brochurequotationline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brochure_quotation_lines",
                to="products_core.product",
            ),
        ),
        migrations.AlterField(
            model_name="productbrochuresettings",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="brochure_settings",
                to="products_core.product",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
