# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
import django.utils.timezone
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0053_alter_customeropeningoutstanding_customer_and_more"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("contracts", "0002_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="EMIScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        default="",
                        help_text="Leave blank to apply to all plan types.",
                        max_length=12,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Percentage discount"),
                            ("FLAT_AMOUNT", "Flat amount off"),
                            ("WAIVE_INSTALLMENTS", "Waive N installments"),
                        ],
                        default="PERCENT",
                        max_length=24,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent value, flat rupee amount, or number of installments to waive.",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateField(db_index=True)),
                ("valid_to", models.DateField(db_index=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of subscriptions this scheme can be applied to. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "subscriptions_emi_schemes",
                "ordering": ["-valid_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmiWaiverSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("waived_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("settlement_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "emi_waiver_settlements",
                "ordering": ["-settlement_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EMI_PAYMENT", "EMI Payment"),
                            ("EMI_WAIVER", "EMI Waiver"),
                            ("PAYMENT_REVERSAL", "Payment Reversal"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        db_index=True,
                        default="EMI_PAYMENT",
                        max_length=20,
                    ),
                ),
                (
                    "entry_direction",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "plan_type_hint",
                    models.CharField(
                        blank=True,
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("allocation_context", models.JSONField(blank=True, default=dict)),
                (
                    "posting_side",
                    models.CharField(blank=True, default="", max_length=6),
                ),
                (
                    "posting_status",
                    models.CharField(db_index=True, default="POSTED", max_length=16),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "financial_ledger",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCollectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partner_collection_requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "plan_type_hint",
                    models.CharField(
                        blank=True,
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("allocation_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Caller-supplied idempotency key; duplicate submissions with the same key are rejected.",
                        max_length=160,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRY_RUN", "Dry Run"),
                            ("MATCHED", "Matched"),
                            ("PARTIAL", "Partial"),
                            ("OVERPAID", "Overpaid"),
                            ("UNLINKED", "Unlinked"),
                            ("MISMATCH", "Mismatch"),
                            ("FLAGGED", "Flagged"),
                            ("LOCKED", "Locked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "variance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                ("is_locked", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_reconciliations",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("AUTO_MATCHED", "Auto Matched"),
                            ("MANUAL_MATCHED", "Manual Matched"),
                            ("FLAGGED", "Flagged"),
                            ("NOTE_ADDED", "Note Added"),
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("STATUS_CHANGED", "Status Changed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=20)),
                ("new_status", models.CharField(blank=True, default="", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "payment_reconciliation_events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RecoveryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("IDENTIFIED", "Identified"),
                            ("NOTICE_SENT", "Notice Sent"),
                            ("FIELD_VISIT", "Field Visit"),
                            ("LEGAL", "Legal"),
                            ("SETTLED", "Settled"),
                            ("WRITTEN_OFF", "Written Off"),
                        ],
                        db_index=True,
                        default="IDENTIFIED",
                        max_length=20,
                    ),
                ),
                (
                    "overdue_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("overdue_emis", models.PositiveIntegerField(default=0)),
                (
                    "first_overdue_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("notice_sent_at", models.DateTimeField(blank=True, null=True)),
                ("field_visit_at", models.DateTimeField(blank=True, null=True)),
                ("legal_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settled_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL", "Full Settlement"),
                            ("PARTIAL", "Partial Settlement"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settlement_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("settlement_approved_at", models.DateTimeField(blank=True, null=True)),
                ("settlement_notes", models.TextField(blank=True, default="")),
                ("settlement_approval_notes", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("last_contact_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "subscriptions_recovery_cases",
                "ordering": ["-first_overdue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseBillingDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("RENT_MONTHLY", "Rent Monthly Demand"),
                            ("LEASE_MONTHLY", "Lease Monthly Demand"),
                            ("SECURITY_DEPOSIT", "Security Deposit Demand"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRY_RUN", "Dry Run"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "billing_period_end",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("due_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "held_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "refundable_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "deducted_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reference_key",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("tax_profile_snapshot", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "rent_lease_billing_demands",
                "ordering": ["-due_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "collection_number",
                    models.CharField(
                        db_index=True,
                        default=payments.models.generate_rent_lease_collection_number,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "external_reference_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("VOIDED", "Voided"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("void_reason", models.TextField(blank=True, default="")),
                (
                    "reversal_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "rent_lease_collections",
                "ordering": ["-payment_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentLeaseDepositTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        db_index=True,
                        default=payments.models.generate_rent_lease_deposit_transaction_number,
                        max_length=64,
                    ),
                ),
                (
                    "external_reference_no",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEMAND_CREATED", "Demand Created"),
                            ("COLLECTED", "Deposit Collected"),
                            ("REFUND_APPROVED", "Refund Approved"),
                            ("REFUNDED", "Refunded"),
                            ("DEDUCTION", "Deduction"),
                            ("DEPOSIT_RECEIPT", "Deposit Receipt"),
                            ("DEPOSIT_REFUND", "Deposit Refund"),
                            ("DEPOSIT_ADJUSTMENT", "Deposit Adjustment"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("VOIDED", "Voided"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("void_reason", models.TextField(blank=True, default="")),
                (
                    "reversal_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "rent_lease_deposit_transactions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedCollectionIdempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("key", models.CharField(max_length=160)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRY_RUN", "Dry Run"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("response_status", models.PositiveSmallIntegerField(default=200)),
            ],
            options={
                "db_table": "unified_collection_idempotency",
            },
        ),
        migrations.CreateModel(
            name="CashCounterSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_date", models.DateField(db_index=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "declared_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        db_index=True,
                        default="OPEN",
                        max_length=28,
                    ),
                ),
                (
                    "variance_approval_request_id",
                    models.IntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_counter_sessions",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "cash_counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="branch_control.cashcounter",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_counter_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sessions_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_cash_counter_sessions",
                "ordering": ["-session_date", "-opened_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unapplied_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNAPPLIED", "Unapplied"),
                            ("PARTIALLY_APPLIED", "Partially Applied"),
                            ("FULLY_APPLIED", "Fully Applied"),
                        ],
                        db_index=True,
                        default="UNAPPLIED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("allocation_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advances",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "cash_counter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advances",
                        to="branch_control.cashcounter",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advances_collected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advances",
                        to="customers.customer",
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advances",
                        to="accounting.financeaccount",
                    ),
                ),
            ],
            options={
                "db_table": "customer_advances",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvanceRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "refund_reference_no",
                    models.CharField(db_index=True, max_length=100),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("refund_date", models.DateField(db_index=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("UPI", "UPI"),
                            ("BANK", "Bank"),
                            ("CARD", "Card"),
                            ("TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSIT", "Bank Deposit"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("VOIDED", "Voided"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("void_reason", models.TextField(blank=True, default="")),
                (
                    "reversal_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.customeradvance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_customer_advance_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advance_refunds",
                        to="customers.customer",
                    ),
                ),
                (
                    "finance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advance_refunds",
                        to="accounting.financeaccount",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_customer_advance_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "customer_advance_refunds",
                "ordering": ["-refund_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DailyCloseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("run_date", models.DateField(db_index=True)),
                ("is_dry_run", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRY_RUN", "Dry Run"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRY_RUN",
                        max_length=20,
                    ),
                ),
                ("blocking_check_count", models.IntegerField(default=0)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_close_runs",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_close_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_daily_close_runs",
                "ordering": ["-run_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositForfeitureTaxInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("invoice_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "forfeited_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST rate applicable on the forfeited deposit (%).",
                        max_digits=5,
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("forfeiture_reason", models.TextField()),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, default="")),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_forfeiture_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_forfeiture_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_forfeiture_invoices",
                        to="contracts.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "deposit_forfeiture_tax_invoices",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Emi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("month_no", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OVERDUE", "Overdue"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emis",
                        to="contracts.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "emis",
                "ordering": ["subscription_id", "month_no"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAdvanceAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("allocation_date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "advance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="payments.customeradvance",
                    ),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_advance_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="contracts.subscription",
                    ),
                ),
                (
                    "emi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advance_allocations",
                        to="payments.emi",
                    ),
                ),
            ],
            options={
                "db_table": "customer_advance_allocations",
                "ordering": ["-allocation_date", "-id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
