# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0054_alter_customerpurchaseenquiry_product_and_more"),
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("contracts", "0003_initial"),
        ("customers", "0002_initial"),
        ("deliveries", "0002_initial"),
        ("lucky_plan", "0002_initial"),
        ("payments", "0001_initial"),
        ("products_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
            model_name="emischeme",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products.",
                related_name="emi_schemes",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="emischeme",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_emi_schemes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emiwaiversettlement",
            name="emi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="waiver_settlements",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="emiwaiversettlement",
            name="lucky_draw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="waiver_settlements",
                to="lucky_plan.luckydraw",
            ),
        ),
        migrations.AddField(
            model_name="emiwaiversettlement",
            name="settled_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="emi_waiver_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emiwaiversettlement",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="waiver_settlements",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="financialledger",
            name="emi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="financialledger",
            name="journal_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="financial_ledger_entries",
                to="accounting.journalentrygroup",
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="approved_emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_collection_requests_approved",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_collection_requests",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_collection_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_partner_collection_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_collection_requests",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="branch_control.branch",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="cash_counter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="branch_control.cashcounter",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collected_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_payments",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partnercollectionrequest",
            name="approved_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="partner_collection_request",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="financialledger",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entry",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="customeradvanceallocation",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_advance_allocation",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="matched_emi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliations",
                to="payments.emi",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliation",
            name="reconciled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reconciliations_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliationevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reconciliation_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreconciliationevent",
            name="reconciliation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="payments.paymentreconciliation",
            ),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_recovery_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="settlement_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoverycase",
            name="subscription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_case",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="rentleasebillingdemand",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_demands",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="contract_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_collections",
                to="contracts.contractreference",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_rent_lease_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_collections",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="demand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_collections",
                to="payments.rentleasebillingdemand",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="finance_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_collections",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_collections",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="rentleasecollection",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_rent_lease_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_deposit_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_deposit_source_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_deposit_transactions",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="demand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_transactions",
                to="payments.rentleasebillingdemand",
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="finance_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_lease_deposit_transactions",
                to="accounting.financeaccount",
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_transactions",
                to="deliveries.rentleasereturninspection",
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_deposit_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposit_transactions",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="rentleasedeposittransaction",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_deposit_source_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unifiedcollectionidempotency",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unified_collection_idempotency_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cashcountersession",
            index=models.Index(
                fields=["session_date", "status"], name="ctrl_ccs_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashcountersession",
            index=models.Index(
                fields=["cash_counter", "session_date"],
                name="ctrl_ccs_counter_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cashcountersession",
            index=models.Index(
                fields=["cashier", "session_date"], name="ctrl_ccs_cashier_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashcountersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("cash_counter", "cashier", "session_date"),
                name="ctrl_ccs_unique_open_per_counter_cashier_date",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["customer", "payment_date"],
                name="customer_ad_custome_da4bb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["finance_account", "payment_date"],
                name="customer_ad_finance_d9c06b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvance",
            index=models.Index(
                fields=["status", "payment_date"], name="customer_ad_status_88b726_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_no__isnull", False)),
                fields=("reference_no",),
                name="uq_customer_advance_reference_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_customer_advance_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvance",
            constraint=models.CheckConstraint(
                condition=models.Q(("unapplied_amount__gte", 0)),
                name="chk_customer_advance_unapplied_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvancerefund",
            index=models.Index(
                fields=["customer", "refund_date"],
                name="customer_ad_custome_f70be8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvancerefund",
            index=models.Index(
                fields=["advance", "refund_date"], name="customer_ad_advance_6d4199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvancerefund",
            index=models.Index(
                fields=["finance_account", "refund_date"],
                name="customer_ad_finance_8fb87b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvancerefund",
            index=models.Index(
                fields=["status", "refund_date"], name="customer_ad_status_9f6b9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvancerefund",
            constraint=models.UniqueConstraint(
                fields=("refund_reference_no",), name="uq_customer_advance_refund_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvancerefund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uq_customer_advance_refund_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvancerefund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_customer_advance_refund_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="dailycloserun",
            index=models.Index(
                fields=["run_date", "status"], name="ctrl_dcr_date_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depositforfeituretaxinvoice",
            index=models.Index(
                fields=["subscription", "status"], name="deposit_for_subscri_4cd361_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depositforfeituretaxinvoice",
            index=models.Index(
                fields=["invoice_date"], name="deposit_for_invoice_607d11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="depositforfeituretaxinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("forfeited_amount__gt", 0)),
                name="chk_forfeiture_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositforfeituretaxinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_invoice_amount__gt", 0)),
                name="chk_forfeiture_total_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="emi",
            index=models.Index(fields=["status"], name="emis_status_51b573_idx"),
        ),
        migrations.AddIndex(
            model_name="emi",
            index=models.Index(fields=["due_date"], name="emis_due_dat_fa734d_idx"),
        ),
        migrations.AddIndex(
            model_name="emi",
            index=models.Index(
                fields=["subscription", "month_no"], name="emis_subscri_71f273_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emi",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="chk_emi_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="emi",
            constraint=models.CheckConstraint(
                condition=models.Q(("month_no__gt", 0)), name="chk_emi_month_positive"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emi",
            unique_together={("subscription", "month_no")},
        ),
        migrations.AddIndex(
            model_name="emischeme",
            index=models.Index(
                fields=["is_active", "valid_from", "valid_to"],
                name="subscriptio_is_acti_53d840_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emiwaiversettlement",
            index=models.Index(
                fields=["subscription", "settlement_date"],
                name="emi_waiver__subscri_c4f0b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emiwaiversettlement",
            index=models.Index(
                fields=["lucky_draw"], name="emi_waiver__lucky_d_3b5b86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emiwaiversettlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gt", 0)),
                name="chk_emi_waiver_settlement_amount_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emiwaiversettlement",
            unique_together={("lucky_draw", "emi")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="payments_payment_aebcb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["method"], name="payments_method_aea958_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["subscription"], name="payments_subscri_9bd444_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["customer"], name="payments_custome_8fefc3_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["emi"], name="payments_emi_id_7a0603_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["branch", "payment_date"], name="payments_branch__c4c434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["cash_counter", "payment_date"],
                name="payments_cash_co_bbfaea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["finance_account", "payment_date"],
                name="payments_finance_5c7ddd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_no__isnull", False)),
                fields=("reference_no",),
                name="uq_payment_reference_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uq_payment_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_payment_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="partnercollectionrequest",
            index=models.Index(
                fields=["partner", "status"], name="partner_col_partner_02b528_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercollectionrequest",
            index=models.Index(
                fields=["subscription", "status"], name="partner_col_subscri_fe82d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercollectionrequest",
            index=models.Index(
                fields=["customer", "status"], name="partner_col_custome_07b038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercollectionrequest",
            index=models.Index(
                fields=["payment_date"], name="partner_col_payment_e7c095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnercollectionrequest",
            index=models.Index(
                fields=["created_at"], name="partner_col_created_31b043_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnercollectionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_partner_collection_request_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(fields=["emi"], name="financial_l_emi_id_be37ba_idx"),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["entry_type"], name="financial_l_entry_t_1f32e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["entry_direction"], name="financial_l_entry_d_9f528f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialledger",
            index=models.Index(
                fields=["created_at"], name="financial_l_created_259daa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialledger",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="ledger_amount_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["advance", "allocation_date"],
                name="customer_ad_advance_fb3ef4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["subscription", "allocation_date"],
                name="customer_ad_subscri_83e84d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customeradvanceallocation",
            index=models.Index(
                fields=["emi", "allocation_date"], name="customer_ad_emi_id_1b76d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customeradvanceallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="chk_customer_advance_allocation_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(fields=["status"], name="payment_rec_status_ccdb77_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["is_flagged"], name="payment_rec_is_flag_67b563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["is_locked"], name="payment_rec_is_lock_acce56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["created_at"], name="payment_rec_created_b22b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["payment"], name="payment_rec_payment_0128fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliation",
            index=models.Index(
                fields=["matched_emi"], name="payment_rec_matched_0e74d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_amount__gte", 0)),
                name="chk_reconciliation_expected_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_amount__gte", 0)),
                name="chk_reconciliation_paid_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["event_type"], name="payment_rec_event_t_a67c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["created_at"], name="payment_rec_created_56304f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationevent",
            index=models.Index(
                fields=["reconciliation"], name="payment_rec_reconci_c05e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recoverycase",
            index=models.Index(
                fields=["stage", "first_overdue_date"],
                name="subscriptio_stage_0d6793_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recoverycase",
            index=models.Index(
                fields=["assigned_to", "stage"], name="subscriptio_assigne_b6250a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["subscription", "demand_type"],
                name="rent_lease__subscri_b99e1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["status", "due_date"], name="rent_lease__status_5728ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasebillingdemand",
            index=models.Index(
                fields=["billing_period_start", "billing_period_end"],
                name="rent_lease__billing_88f25d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("collected_amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_collected_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasebillingdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("deducted_amount__gte", Decimal("0.00"))),
                name="chk_rent_lease_demand_deducted_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasecollection",
            index=models.Index(
                fields=["subscription", "payment_date"],
                name="rent_lease__subscri_1e69df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasecollection",
            index=models.Index(
                fields=["demand", "status"], name="rent_lease__demand__f30002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasecollection",
            index=models.Index(
                fields=["customer", "payment_date"],
                name="rent_lease__custome_29420e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasecollection",
            index=models.Index(
                fields=["plan_type", "status", "payment_date"],
                name="rent_lease__plan_ty_041c43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasecollection",
            index=models.Index(
                fields=["finance_account", "payment_date"],
                name="rent_lease__finance_78107b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", Decimal("0.00"))),
                name="chk_rent_lease_collection_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasecollection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plan_type", "RENT"), ("plan_type", "LEASE"), _connector="OR"
                ),
                name="chk_rent_lease_collection_plan_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasecollection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uq_rent_lease_collection_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasecollection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference_no", ""), _negated=True),
                fields=("external_reference_no",),
                name="uq_rent_lease_collection_external_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["subscription", "transaction_type"],
                name="rent_lease__subscri_13035a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["created_at"], name="rent_lease__created_5f59ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["customer", "transaction_date"],
                name="rent_lease__custome_cafa82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["plan_type", "status", "transaction_date"],
                name="rent_lease__plan_ty_97a4bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentleasedeposittransaction",
            index=models.Index(
                fields=["finance_account", "transaction_date"],
                name="rent_lease__finance_5bdf51_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", Decimal("0.00"))),
                name="chk_deposit_transaction_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plan_type", ""),
                    ("plan_type", "RENT"),
                    ("plan_type", "LEASE"),
                    _connector="OR",
                ),
                name="chk_deposit_transaction_plan_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_number", ""), _negated=True),
                fields=("transaction_number",),
                name="uq_deposit_transaction_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uq_deposit_transaction_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentleasedeposittransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_reference_no", ""), _negated=True),
                fields=("external_reference_no",),
                name="uq_deposit_transaction_external_ref",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedcollectionidempotency",
            index=models.Index(
                fields=["user", "status"], name="unified_col_user_id_446e3c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unifiedcollectionidempotency",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="uniq_unified_collection_idem_user_key"
            ),
        ),
            ],
            database_operations=[]
        )
    ]
