# Generated by Django 6.0.2 on 2026-04-10 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0009_salarysheetline_employeeattendance_overtime_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=12)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'branch_control_branches',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['status', 'is_primary'], name='branch_cont_status_8e0a82_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='branch_control_unique_primary_branch')],
            },
        ),
        migrations.CreateModel(
            name='CashCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cash_counters', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counters', to='branch_control.branch')),
                ('finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counters', to='accounting.financeaccount')),
            ],
            options={
                'db_table': 'branch_control_cash_counters',
                'ordering': ['branch__name', 'name', 'id'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='branch_cont_branch__cc3d10_idx'), models.Index(fields=['assigned_user', 'is_active'], name='branch_cont_assigne_63c061_idx')],
            },
        ),
    ]
