# Generated by Django 5.2.7 on 2026-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentrecord",
            new_name="documents_d_categor_a36cb0_idx",
            old_name="documents_d_categor_idx",
        ),
    ]
