from subscriptions.models_business_setup import BusinessProfile
from subscriptions.models_document_print_settings import DocumentPrintSettings
from subscriptions.services.business_setup_service import get_active_business_profile


DEFAULT_PRINT_TERMS = {
    "invoice_terms": "All amounts and balances are shown from posted business records only.\nThis invoice does not settle payment unless backend receipt/payment records confirm collection.",
    "receipt_terms": "This receipt only confirms the amount shown as received in the system record.\nVoided, cancelled, or reversed receipts are preserved for audit and are not proof of active payment.",
    "delivery_challan_terms": "This challan confirms delivery handling only and does not confirm payment settlement.\nStock, receivable, accounting, and payment records remain governed by backend posted records.",
    "subscription_contract_terms": "Lucky Plan / Advance EMI terms are displayed from backend contract records only.\nWinner benefit, where applicable, waives only eligible future EMI rows as recorded by backend waiver records.",
    "rent_lease_contract_terms": "Rent/lease values are displayed from backend contract records only.\nDeposit refund, deduction, and return condition remain governed by backend deposit and return-inspection controls.",
    "purchase_bill_terms": "This purchase bill copy is generated from backend vendor bill records only.\nVendor payable and stock/accounting effects remain governed by posted backend workflows.",
    "vendor_voucher_terms": "This vendor voucher copy is generated from backend vendor payment records only.\nIt does not create, approve, post, reverse, or settle vendor payable records.",
    "account_statement_terms": "This statement is generated from existing backend report or customer/account records only.\nMissing opening balances, running balances, reconciliation status, or customer totals are not inferred in print views.",
    "report_footer_note": "Generated by SUBIDHA CORE for audit and business records. Print settings affect presentation only.",
}


def _profile_address(profile: BusinessProfile | None) -> str:
    if not profile:
        return ""
    return "\n".join(
        part
        for part in [
            profile.address_line_1,
            profile.address_line_2,
            profile.landmark,
            ", ".join(
                item
                for item in [profile.city, profile.district, profile.state, profile.postal_code, profile.country]
                if item
            ),
        ]
        if part
    )


def _tax_label(profile: BusinessProfile | None) -> str:
    if not profile:
        return ""
    if profile.gstin:
        return f"GSTIN: {profile.gstin}"
    if profile.pan_number:
        return f"PAN: {profile.pan_number}"
    return ""


def get_or_create_document_print_settings() -> DocumentPrintSettings:
    settings = DocumentPrintSettings.objects.filter(is_active=True).select_related("business_profile").first()
    if settings:
        return settings
    profile = get_active_business_profile()
    return DocumentPrintSettings.objects.create(
        business_profile=profile,
        business_name=(profile.trade_name or profile.legal_name) if profile else "",
        print_address=_profile_address(profile),
        print_phone=profile.primary_phone if profile else "",
        print_email=profile.primary_email if profile else "",
        print_website=profile.website_url if profile else "",
        tax_label=_tax_label(profile),
        authorized_signatory_label="Authorized Signature",
        customer_signature_label="Customer Signature",
        **DEFAULT_PRINT_TERMS,
    )
