# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="LuckyDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("committed_hash", models.CharField(max_length=64)),
                (
                    "revealed_seed",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("draw_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("draw_month", models.PositiveIntegerField()),
                ("is_revealed", models.BooleanField(db_index=True, default=False)),
                (
                    "revealed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("waived_emi_count", models.PositiveIntegerField(default=0)),
                (
                    "waived_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "waiver_scope",
                    models.CharField(default="FUTURE_EMI_ONLY", max_length=40),
                ),
                (
                    "winner_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("winner_verified_at", models.DateTimeField(blank=True, null=True)),
                ("winner_rejected_reason", models.TextField(blank=True, default="")),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[("UNSETTLED", "Unsettled"), ("SETTLED", "Settled")],
                        db_index=True,
                        default="UNSETTLED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lucky_draws",
                "ordering": ["-draw_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LuckyDrawBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        db_index=True,
                        help_text="Format: LUCKY-BATCH-YYYY-NNNNN (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Batch enrollment start date"),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Batch enrollment end date or expected close"
                    ),
                ),
                (
                    "expected_draw_date",
                    models.DateField(help_text="Scheduled draw date"),
                ),
                (
                    "actual_draw_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open — taking enrollments"),
                            ("CLOSED", "Closed — no new enrollments"),
                            ("DRAWN", "Drawn — result published (seed pending)"),
                            (
                                "VERIFIED",
                                "Verified — seed published, customer-verifiable",
                            ),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "commitment_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256(seed) — published 14 days before draw for commitment",
                        max_length=256,
                    ),
                ),
                (
                    "seed_hex",
                    models.CharField(
                        blank=True,
                        help_text="256-bit seed (hex) — kept secret until draw_date, then published",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "algorithm_code_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256(algorithm source code) — immutable proof of randomness logic",
                        max_length=256,
                    ),
                ),
                (
                    "eligible_ids_json",
                    models.JSONField(
                        default=dict,
                        help_text='{"count": 100, "ids": [...], "published_at": "ISO-8601"}',
                    ),
                ),
                (
                    "draw_result_json",
                    models.JSONField(
                        blank=True,
                        help_text='{"winner_id": "...", "drawn_at": "ISO-8601", "signature": "..."}',
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lucky Draw Batch",
                "verbose_name_plural": "Lucky Draw Batches",
                "db_table": "subscriptions_luckydrawbatch",
                "ordering": ["-actual_draw_date", "-batch_number"],
            },
        ),
        migrations.CreateModel(
            name="LuckyId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("lucky_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("WON", "Won"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "lucky_ids",
                "ordering": ["batch_id", "lucky_number"],
            },
        ),
        migrations.CreateModel(
            name="LuckyIDDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lucky_id", models.CharField(db_index=True, max_length=50)),
                ("is_eligible", models.BooleanField(db_index=True, default=True)),
                (
                    "ineligibility_reason",
                    models.CharField(
                        blank=True,
                        help_text="If ineligible, why? (Default, EarlyReturn, LeaseTerminated, etc.)",
                        max_length=200,
                    ),
                ),
                ("is_winner", models.BooleanField(db_index=True, default=False)),
                (
                    "waiver_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions_luckyiddraw",
                "ordering": ["batch", "lucky_id"],
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("batch_code", models.CharField(max_length=50, unique=True)),
                ("total_slots", models.PositiveIntegerField()),
                ("duration_months", models.PositiveIntegerField()),
                ("draw_day", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("FULL", "Full"),
                            ("READY_TO_LOCK", "Ready To Lock"),
                            ("LOCKED", "Locked"),
                            ("DRAW_IN_PROGRESS", "Draw In Progress"),
                            ("DRAW_COMMITTED", "Draw Committed"),
                            ("DRAW_COMPLETED", "Draw Completed"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when batch draw eligibility is frozen (LOCKED or beyond).",
                        null=True,
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Days after EMI due_date before status flips to OVERDUE (CTRL-LP-7).",
                    ),
                ),
            ],
            options={
                "db_table": "batches",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status"], name="batches_status_9b1a8e_idx"),
                    models.Index(
                        fields=["start_date"], name="batches_start_d_8bfe41_idx"
                    ),
                    models.Index(
                        fields=["batch_code"], name="batches_batch_c_5ac928_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total_slots__gt", 0)),
                        name="chk_batch_total_slots_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_months__gt", 0)),
                        name="chk_batch_duration_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("draw_day__gte", 1), ("draw_day__lte", 28)),
                        name="chk_batch_draw_day_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DrawAuthorisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("draw_month", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AUTHORISED", "Authorised"),
                            ("REJECTED", "Rejected"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "authorised_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("revocation_reason", models.TextField(blank=True, default="")),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Eligible-pool snapshot at time of authorisation request.",
                    ),
                ),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorised_draws",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draw_authorisations",
                        to="lucky_plan.batch",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_draw_authorisations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draw_authorisations",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DrawCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("snapshot_version", models.PositiveIntegerField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("public_commit_hash", models.CharField(max_length=64)),
                ("seed_commitment", models.CharField(max_length=64)),
                ("committed_at", models.DateTimeField(db_index=True)),
                (
                    "algorithm_version",
                    models.CharField(default="pass7-v1", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMMITTED", "Committed")],
                        default="COMMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draw_commit",
                        to="lucky_plan.batch",
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_draw_commits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draw_commits",
            },
        ),
        migrations.CreateModel(
            name="DrawEligibilitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("snapshot_version", models.PositiveIntegerField(db_index=True)),
                ("sort_order", models.PositiveIntegerField()),
                (
                    "contract_reference",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("emi_schedule_summary", models.JSONField(default=dict)),
                ("row_hash", models.CharField(max_length=128)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draw_eligibility_snapshots",
                        to="lucky_plan.batch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draw_eligibility_snapshots",
                        to="customers.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draw_eligibility_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "draw_eligibility_snapshots",
                "ordering": ["snapshot_version", "sort_order", "id"],
            },
        ),
            ],
            database_operations=[]
        )
    ]
