# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0002_initial"),
        ("customers", "0002_initial"),
        ("lucky_plan", "0001_initial"),
        ("products_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
            model_name="draweligibilitysnapshot",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_eligibility_snapshots",
                to="products_core.product",
            ),
        ),
        migrations.AddField(
            model_name="draweligibilitysnapshot",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_eligibility_snapshots",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lucky_draws",
                to="lucky_plan.batch",
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="draw_commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lucky_draws",
                to="lucky_plan.drawcommit",
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="winner_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winning_draws",
                to="contracts.subscription",
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="winner_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_lucky_draws",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="luckydrawbatch",
            name="draw_performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_draws",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="luckydrawbatch",
            name="draw_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_draws",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="luckyid",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lucky_ids",
                to="lucky_plan.batch",
            ),
        ),
        migrations.AddField(
            model_name="luckydraw",
            name="winner_lucky_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wins",
                to="lucky_plan.luckyid",
            ),
        ),
        migrations.AddField(
            model_name="draweligibilitysnapshot",
            name="lucky_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draw_eligibility_snapshots",
                to="lucky_plan.luckyid",
            ),
        ),
        migrations.AddField(
            model_name="luckyiddraw",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ids",
                to="lucky_plan.luckydrawbatch",
            ),
        ),
        migrations.AddField(
            model_name="luckyiddraw",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lucky_draws",
                to="customers.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="drawauthorisation",
            index=models.Index(
                fields=["batch", "status"], name="draw_author_batch_i_07ff37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drawauthorisation",
            index=models.Index(
                fields=["authorised_at"], name="draw_author_authori_30ddc7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawauthorisation",
            constraint=models.CheckConstraint(
                condition=models.Q(("draw_month__gt", 0)),
                name="chk_draw_auth_month_positive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drawauthorisation",
            unique_together={("batch", "draw_month")},
        ),
        migrations.AddIndex(
            model_name="luckydrawbatch",
            index=models.Index(
                fields=["status", "-actual_draw_date"],
                name="subscriptio_status_d63a89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="luckydrawbatch",
            index=models.Index(
                fields=["batch_number"], name="subscriptio_batch_n_8e324c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckyid",
            index=models.Index(
                fields=["batch", "status"], name="lucky_ids_batch_i_6857d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckyid",
            index=models.Index(
                fields=["batch", "lucky_number"], name="lucky_ids_batch_i_3a0e18_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="luckyid",
            constraint=models.UniqueConstraint(
                fields=("batch", "lucky_number"), name="uq_lucky_id_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="luckyid",
            constraint=models.CheckConstraint(
                condition=models.Q(("lucky_number__gte", 0), ("lucky_number__lte", 99)),
                name="chk_lucky_number_range",
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["batch", "draw_month"], name="lucky_draws_batch_i_f5df98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["is_revealed"], name="lucky_draws_is_reve_ff5fa8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckydraw",
            index=models.Index(
                fields=["revealed_at"], name="lucky_draws_reveale_4fd4bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("draw_month__gt", 0)),
                name="chk_draw_month_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_emi_count__gte", 0)),
                name="chk_lucky_draw_waived_emi_count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="luckydraw",
            constraint=models.CheckConstraint(
                condition=models.Q(("waived_amount__gte", 0)),
                name="chk_lucky_draw_waived_amount_non_negative",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="luckydraw",
            unique_together={("batch", "draw_month")},
        ),
        migrations.AddIndex(
            model_name="draweligibilitysnapshot",
            index=models.Index(
                fields=["batch", "snapshot_version"],
                name="draw_eligib_batch_i_bbbd48_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="draweligibilitysnapshot",
            constraint=models.UniqueConstraint(
                fields=("batch", "snapshot_version", "subscription"),
                name="uq_draw_eligibility_batch_version_subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="luckyiddraw",
            index=models.Index(
                fields=["batch", "is_eligible"], name="subscriptio_batch_i_f1ca0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="luckyiddraw",
            index=models.Index(
                fields=["customer", "is_winner"], name="subscriptio_custome_3d3f00_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="luckyiddraw",
            unique_together={("batch", "lucky_id")},
        ),
            ],
            database_operations=[]
        )
    ]
