# Generated by Django 5.2.7 on 2026-07-31 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0003_initial"),
        ("customers", "0002_initial"),
        ("products_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: the growth_* tables already exist (created originally under the
    # subscriptions app). This registers the models under the `growth` app in
    # Django's migration state without emitting any DDL.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="CustomerGrowthRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("RENEWAL", "Renewal"),
                            ("UPGRADE", "Upgrade"),
                            ("EXCHANGE", "Exchange"),
                            ("PLAN_CONVERSION", "Plan Conversion"),
                            ("EARLY_DELIVERY_INTEREST", "Early Delivery Interest"),
                            ("RENT_TO_LEASE_INTEREST", "Rent-to-Lease Interest"),
                            (
                                "LEASE_TO_PURCHASE_INTEREST",
                                "Lease-to-Purchase Interest",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("CONVERTED", "Converted"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=14,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("risk_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "approval_required",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_as_current",
                        to="products_core.product",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="customers.customer",
                    ),
                ),
                (
                    "requested_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_as_requested",
                        to="products_core.product",
                    ),
                ),
                (
                    "source_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests",
                        to="contracts.subscription",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_requests_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_customer_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowthRequestDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUEST_MORE_INFO", "Request More Info"),
                            ("CANCEL", "Cancel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_request_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "growth_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="growth.customergrowthrequest",
                    ),
                ),
            ],
            options={
                "db_table": "growth_request_decisions",
                "ordering": ["-decided_at"],
            },
        ),
        migrations.CreateModel(
            name="GrowthRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("SERVICE", "Service"),
                            ("DISCOUNT", "Discount"),
                            ("NOTE", "Note"),
                        ],
                        default="PRODUCT",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "growth_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="growth.customergrowthrequest",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="growth_request_lines",
                        to="products_core.product",
                    ),
                ),
            ],
            options={
                "db_table": "growth_request_lines",
                "ordering": ["growth_request_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="OfferPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_code",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(blank=True, db_index=True, null=True)),
                ("end_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("EXPIRED", "Expired"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All Customers"),
                            ("NEW_CUSTOMER", "New Customer"),
                            ("EXISTING_CUSTOMER", "Existing Customer"),
                            ("PARTNER_REFERRED", "Partner Referred"),
                            ("HIGH_TRUST_CUSTOMER", "High Trust Customer"),
                        ],
                        db_index=True,
                        default="ALL",
                        max_length=22,
                    ),
                ),
                (
                    "max_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "display_priority",
                    models.PositiveIntegerField(db_index=True, default=100),
                ),
                ("is_public_visible", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_packages_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_packages_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_offer_packages",
                "ordering": ["display_priority", "package_code"],
            },
        ),
        migrations.AddField(
            model_name="customergrowthrequest",
            name="desired_offer_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests",
                to="growth.offerpackage",
            ),
        ),
        migrations.CreateModel(
            name="OfferPackageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Discount"),
                            ("FLAT", "Flat Amount"),
                            ("PERCENT", "Percentage"),
                        ],
                        default="NONE",
                        max_length=8,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "offer_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="growth.offerpackage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_package_lines",
                        to="products_core.product",
                    ),
                ),
            ],
            options={
                "db_table": "growth_offer_package_lines",
                "ordering": ["offer_package_id", "product_id"],
            },
        ),
        migrations.CreateModel(
            name="PlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_code",
                    models.CharField(db_index=True, max_length=60, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("EMI", "EMI (Lucky Plan)"),
                            ("RENT", "Rent"),
                            ("LEASE", "Lease"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "tenure_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "default_down_payment_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "default_security_deposit_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "default_grace_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "is_lucky_plan_eligible",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("requires_batch", models.BooleanField(default=False)),
                ("requires_lucky_id", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_templates_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_plan_templates",
                "ordering": ["plan_type", "template_code"],
            },
        ),
        migrations.AddField(
            model_name="offerpackage",
            name="plan_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offer_packages",
                to="growth.plantemplate",
            ),
        ),
        migrations.AddField(
            model_name="customergrowthrequest",
            name="desired_plan_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="growth_requests",
                to="growth.plantemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="plantemplate",
            index=models.Index(
                fields=["is_active", "plan_type"], name="growth_pt_active_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerpackage",
            index=models.Index(
                fields=["status", "audience_type"], name="growth_op_status_audience_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offerpackage",
            index=models.Index(
                fields=["start_date", "end_date"], name="growth_op_date_range_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["customer", "status"], name="growth_req_cust_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["status", "priority"], name="growth_req_status_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customergrowthrequest",
            index=models.Index(
                fields=["request_type", "status"], name="growth_req_type_status_idx"
            ),
        ),
            ],
        ),
    ]
