# Generated by Django 5.2.7 on 2026-09-02 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_customer_customer_source"),
        ("growth", "0001_growth_split_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOfferGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Granted to this customer directly"),
                            ("SEGMENT", "Granted from an audience segment"),
                        ],
                        db_index=True,
                        default="INDIVIDUAL",
                        max_length=12,
                    ),
                ),
                ("expires_on", models.DateField(blank=True, db_index=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("decision_note", models.TextField(blank=True, default="")),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_grants",
                        to="customers.customer",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_grants_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_grants",
                        to="growth.offerpackage",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offer_grants_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "growth_customer_offer_grants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "status"], name="growth_cog_cust_status_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_on"],
                        name="growth_cog_status_exp_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["PENDING", "APPROVED"])),
                        fields=("customer", "offer_package"),
                        name="uq_live_offer_grant_per_customer_package",
                    )
                ],
            },
        ),
    ]
