# Generated by Django 5.2.7 on 2026-07-31 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch_control", "0002_seed_primary_branch_and_backfill_context"),
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # State-only: control_* tables already exist (created under subscriptions).
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name="MonthEndCloseRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.PositiveSmallIntegerField(db_index=True)),
                ("period_month", models.PositiveSmallIntegerField(db_index=True)),
                ("is_dry_run", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRY_RUN", "Dry Run"),
                            ("EXECUTED", "Executed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="DRY_RUN",
                        max_length=20,
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="month_end_close_runs",
                        to="branch_control.branch",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="month_end_close_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_month_end_close_runs",
                "ordering": ["-run_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MonthEndCloseCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_key", models.CharField(db_index=True, max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("BLOCKING", "Blocking"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("passed", models.BooleanField(db_index=True, default=True)),
                ("count", models.IntegerField(default=0)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="finance_control.monthendcloserun",
                    ),
                ),
            ],
            options={
                "db_table": "control_month_end_close_check_results",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_model", models.CharField(db_index=True, max_length=120)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                ("action_key", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("request_reason", models.TextField(blank=True, default="")),
                ("decision_reason", models.TextField(blank=True, default="")),
                (
                    "requested_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_approval_requests",
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "risk_level"],
                        name="ctrl_appr_status_risk_idx",
                    ),
                    models.Index(
                        fields=["source_model", "source_id", "status"],
                        name="ctrl_appr_src_status_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "status"],
                        name="ctrl_appr_reqby_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("source_model", "source_id", "action_key"),
                        name="ctrl_appr_unique_pending_per_src_action",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=120)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("BOOL", "Boolean"),
                            ("INT", "Integer"),
                            ("DECIMAL", "Decimal"),
                            ("STRING", "String"),
                            ("JSON", "JSON"),
                        ],
                        default="BOOL",
                        max_length=10,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("BRANCH", "Branch"),
                            ("PLAN_TYPE", "Plan Type"),
                            ("ROLE", "Role"),
                        ],
                        db_index=True,
                        default="GLOBAL",
                        max_length=12,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_policies_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_business_policies",
                "ordering": ["key", "scope_type", "scope_key"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "key", "scope_type"],
                        name="ctrl_pol_active_key_scope_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("key", "scope_type", "scope_key"),
                        name="ctrl_policy_unique_active_key_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ControlException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exception_key", models.CharField(db_index=True, max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("source_model", models.CharField(db_index=True, max_length=120)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=240)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledged_control_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "control_exceptions",
                "ordering": ["-detected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity"],
                        name="ctrl_exc_status_severity_idx",
                    ),
                    models.Index(
                        fields=["exception_key", "status"],
                        name="ctrl_exc_key_status_idx",
                    ),
                    models.Index(
                        fields=["source_model", "source_id"], name="ctrl_exc_source_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "OPEN")),
                        fields=("exception_key", "source_model", "source_id"),
                        name="ctrl_exc_unique_open_per_src",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyCloseCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_key", models.CharField(db_index=True, max_length=80)),
                ("label", models.CharField(max_length=240)),
                ("passed", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("BLOCKING", "Blocking"),
                        ],
                        default="BLOCKING",
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "close_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="payments.dailycloserun",
                    ),
                ),
            ],
            options={
                "db_table": "control_daily_close_check_results",
                "ordering": ["close_run", "id"],
                "indexes": [
                    models.Index(
                        fields=["close_run", "passed"], name="ctrl_dccr_run_passed_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="monthendcloserun",
            index=models.Index(
                fields=["period_year", "period_month", "status"],
                name="control_mon_period__b8254b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthendcloserun",
            index=models.Index(
                fields=["period_year", "period_month", "is_dry_run"],
                name="control_mon_period__489736_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthendclosecheckresult",
            index=models.Index(
                fields=["run", "severity", "passed"],
                name="control_mon_run_id_02dce6_idx",
            ),
        ),
            ],
        ),
    ]
