# Generated by Django 6.0.2 on 2026-04-08 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('subscriptions', '0033_alter_auditlog_action_type_subscriptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('CALL', 'Call'), ('INTERNAL', 'Internal')], db_index=True, max_length=20)),
                ('reminder_type', models.CharField(choices=[('RETAIL_DUE', 'Retail Due'), ('EMI_DUE', 'EMI Due'), ('EMI_OVERDUE', 'EMI Overdue'), ('FOLLOWUP', 'Follow Up')], db_index=True, max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('template_key', models.CharField(blank=True, default='', max_length=80)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('target_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='subscriptions.customer')),
                ('target_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='billing.billinginvoice')),
                ('target_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='subscriptions.payment')),
                ('target_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reminders', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'payment_reminders',
                'ordering': ['scheduled_for', 'due_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'scheduled_for', 'due_date'], name='payment_rem_status_c2f0d7_idx'), models.Index(fields=['target_customer', 'due_date'], name='payment_rem_target__345ddc_idx'), models.Index(fields=['target_subscription', 'due_date'], name='payment_rem_target__4df84d_idx'), models.Index(fields=['target_invoice', 'due_date'], name='payment_rem_target__e1b934_idx')],
            },
        ),
    ]
