# Generated by Django 6.0.2 on 2026-04-08 18:28

import reminders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreminder',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='customer_contact',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='reminder_no',
            field=models.CharField(db_index=True, default=reminders.models.generate_reminder_no, max_length=40),
        ),
    ]
