# Generated by Django 5.2.7 on 2026-06-23 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0003_alter_paymentreminder_reminder_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("CALL", "Call"),
                            ("INTERNAL", "Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "reminders_notification_templates",
                "ordering": ["channel", "key"],
            },
        ),
    ]
