# Generated by Django 5.2.7 on 2026-06-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_notification_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentreminder',
            options={'ordering': ['-id']},
        ),
    ]
