# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
        ("customers", "0001_initial"),
        ("payments", "0001_initial"),
        ("reminders", "0005_alter_paymentreminder_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="paymentreminder",
            name="target_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reminders",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreminder",
            name="target_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reminders",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="paymentreminder",
            name="target_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_reminders",
                to="contracts.subscription",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
