# Generated by Django 5.2.7 on 2026-09-10 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_initial"),
        ("customers", "0006_alter_customer_customer_source"),
        ("reminders", "0006_alter_paymentreminder_target_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_RECEIPT", "Payment receipt"),
                            ("DUE_REMINDER", "EMI / rent due reminder"),
                            ("DELIVERY_SCHEDULED", "Delivery scheduled"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered / handed over"),
                            ("HANDOVER_RETURNED", "Rental returned"),
                            ("DRAW_WINNER", "Lucky draw winner"),
                            ("KYC_VERIFIED", "KYC verified"),
                            ("KYC_REJECTED", "KYC needs attention"),
                            ("CONTRACT_ACTIVATED", "Contract activated"),
                            ("CUSTOM", "Custom message"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "phone_e164",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("OPENED", "Opened in WhatsApp"),
                            ("SENT", "Sent"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(default="WA_ME", max_length=16)),
                (
                    "opted_in_snapshot",
                    models.BooleanField(
                        default=False,
                        help_text="Customer's WhatsApp opt-in at the moment the message was queued.",
                    ),
                ),
                (
                    "source_model",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=40)),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True, max_length=160, null=True, unique=True
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "skip_reason",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_messages",
                        to="customers.customer",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_whatsapp_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_whatsapp_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="whatsapp_messages",
                        to="contracts.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_messages",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="whatsapp_me_status_66bcab_idx",
                    ),
                    models.Index(
                        fields=["event_type", "status"],
                        name="whatsapp_me_event_t_6263c4_idx",
                    ),
                ],
            },
        ),
    ]
