# Generated by Django 5.2.7 on 2026-05-21 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_control', '0002_seed_primary_branch_and_backfill_context'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_no', models.PositiveIntegerField(db_index=True, unique=True)),
                ('scope', models.CharField(db_index=True, max_length=80)),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_checked', models.PositiveIntegerField(default=0)),
                ('total_matched', models.PositiveIntegerField(default=0)),
                ('total_exceptions', models.PositiveIntegerField(default=0)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='branch_control.branch')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconciliation_runs',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('source_type', models.CharField(db_index=True, max_length=100)),
                ('source_id', models.CharField(db_index=True, max_length=120)),
                ('source_label', models.CharField(blank=True, default='', max_length=255)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING_LEDGER', 'Missing Ledger'), ('MISSING_SOURCE', 'Missing Source'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('QUANTITY_MISMATCH', 'Quantity Mismatch'), ('STATUS_MISMATCH', 'Status Mismatch'), ('DUPLICATE_POSTING', 'Duplicate Posting'), ('WRONG_ACCOUNT', 'Wrong Account'), ('NEEDS_REVIEW', 'Needs Review'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('WAIVED_BY_APPROVAL', 'Waived By Approval')], db_index=True, default='NEEDS_REVIEW', max_length=30)),
                ('exception_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('exception_message', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reconciliation_items', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_reconciliation_items', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.reconciliationrun')),
            ],
            options={
                'db_table': 'reconciliation_items',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_evidence', to='contenttypes.contenttype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reconciliation.reconciliationitem')),
            ],
            options={
                'db_table': 'reconciliation_evidence',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['evidence_type', 'object_id'], name='reconciliat_evidenc_bb5e3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MARK_REVIEWED', 'Mark Reviewed'), ('MARK_FALSE_POSITIVE', 'Mark False Positive'), ('REQUEST_CORRECTION', 'Request Correction'), ('LINK_EXISTING_RECORD', 'Link Existing Record'), ('CREATE_ADJUSTMENT_REQUEST', 'Create Adjustment Request'), ('ESCALATE', 'Escalate'), ('CLOSE', 'Close'), ('REOPEN', 'Reopen')], db_index=True, max_length=40)),
                ('note', models.TextField()),
                ('before_status', models.CharField(blank=True, default='', max_length=30)),
                ('after_status', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='reconciliation.reconciliationitem')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconciliation_resolutions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='reconciliat_action_ed729f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['module', 'scope', 'status'], name='reconciliat_module_30071f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrun',
            index=models.Index(fields=['started_at'], name='reconciliat_started_9d81d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['run', 'module'], name='reconciliat_run_id_b40871_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['status', 'severity'], name='reconciliat_status_1497d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['exception_code'], name='reconciliat_excepti_acdaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationitem',
            index=models.Index(fields=['source_type', 'source_id'], name='reconciliat_source__ec7278_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationitem',
            constraint=models.UniqueConstraint(fields=('run', 'module', 'exception_code', 'source_type', 'source_id'), name='reconciliation_unique_item_per_run'),
        ),
    ]
