# Generated by Django 6.0.2 on 2026-05-23 08:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_seed_default_non_gst_business_tax_profile'),
        ('billing', '0013_billinginvoice_tax_profile_snapshot_and_more'),
        ('reconciliation', '0001_initial'),
        ('subscriptions', '0069_businessdatabackupjob_businessdatarestorejob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSourceLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('source_type', models.CharField(choices=[('EMI_PAYMENT', 'EMI Payment'), ('BILLING_RECEIPT', 'Billing Receipt'), ('MONEY_MOVEMENT', 'Money Movement'), ('BANK_STATEMENT_LINE', 'Bank Statement Line'), ('UPI_SETTLEMENT_LINE', 'UPI Settlement Line'), ('CASHIER_DAY_CLOSE', 'Cashier Day Close'), ('JOURNAL_ENTRY', 'Journal Entry'), ('OTHER', 'Other')], db_index=True, max_length=40)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('VOIDED', 'Voided'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('ADJUSTED', 'Adjusted'), ('SUPERSEDED', 'Superseded')], db_index=True, max_length=24)),
                ('event_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('VOIDED', 'Voided')], db_index=True, default='ACTIVE', max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_source_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('related_cancellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='subscriptions.operationalcancellation')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='billing.billinginvoice')),
                ('related_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='accounting.journalentry')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='subscriptions.payment')),
                ('related_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='billing.receiptdocument')),
            ],
            options={
                'db_table': 'financial_source_lifecycle_events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='financial_s_source__ac69a3_idx'), models.Index(fields=['event_type'], name='financial_s_event_t_887027_idx'), models.Index(fields=['event_status'], name='financial_s_event_s_ea736f_idx'), models.Index(fields=['created_at'], name='financial_s_created_b6dce0_idx'), models.Index(fields=['related_payment'], name='financial_s_related_3720ca_idx'), models.Index(fields=['related_receipt'], name='financial_s_related_78ebfb_idx'), models.Index(fields=['related_cancellation'], name='financial_s_related_c21175_idx')],
            },
        ),
    ]
