# Generated by Django 5.2.7 on 2026-07-10 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation", "0002_financialsourcelifecycleevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationSignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SIGNED_OFF", "Signed Off"),
                            ("REVOKED", "Revoked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "signed_off_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "open_item_count_at_sign_off",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of unresolved items at time of sign-off (must be 0 for clean close).",
                    ),
                ),
                ("attestation_note", models.TextField(blank=True, default="")),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reconciliation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sign_off",
                        to="reconciliation.reconciliationrun",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_reconciliation_sign_offs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_off_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_sign_offs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reconciliation_sign_offs",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="reconciliat_status_383d44_idx"
                    ),
                    models.Index(
                        fields=["signed_off_at"], name="reconciliat_signed__a1194d_idx"
                    ),
                ],
            },
        ),
    ]
