# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
        ("payments", "0001_initial"),
        ("reconciliation", "0003_ctrl_fin5_sign_off"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
            model_name="financialsourcelifecycleevent",
            name="related_cancellation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="contracts.operationalcancellation",
            ),
        ),
        migrations.AlterField(
            model_name="financialsourcelifecycleevent",
            name="related_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lifecycle_events",
                to="payments.payment",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
