# Generated by Django 5.2.7 on 2026-07-31 06:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import subscriptions.base_models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalog",
            "0002_rename_catalog_att_categor_baa5e3_idx_catalog_att_categor_862041_idx_and_more",
        ),
        ("contracts", "0002_initial"),
        ("customers", "0002_initial"),
        ("inventory", "0023_service_type_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
            name="ProductCategoryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("slug", models.SlugField(blank=True, default="", max_length=140)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                (
                    "public_title",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("seo_title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "seo_description",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "public_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="public/category/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "db_table": "product_category_master",
                "ordering": ["sort_order", "name", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="product_cat_is_acti_039988_idx",
                    ),
                    models.Index(
                        fields=["is_public", "is_active", "sort_order"],
                        name="product_cat_is_publ_6d7888_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSubcategoryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategories",
                        to="products_core.productcategorymaster",
                    ),
                ),
            ],
            options={
                "db_table": "product_subcategory_master",
                "ordering": ["category__name", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductUnitOfMeasureMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "product_unit_of_measure_master",
                "ordering": ["code", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "code"],
                        name="product_uni_is_acti_0aa9b9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("product_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("base_specs", models.JSONField(blank=True, default=dict)),
                (
                    "sku",
                    models.CharField(
                        blank=True, db_index=True, max_length=60, null=True, unique=True
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="PCS", max_length=30),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "hsn_sac_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=subscriptions.base_models.product_image_upload_to,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "plan_type_default",
                    models.CharField(
                        choices=[("EMI", "EMI"), ("RENT", "Rent"), ("LEASE", "Lease")],
                        db_index=True,
                        default="EMI",
                        max_length=10,
                    ),
                ),
                ("is_emi_enabled", models.BooleanField(db_index=True, default=True)),
                ("is_rent_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_lease_enabled", models.BooleanField(db_index=True, default=False)),
                ("is_rent_ready", models.BooleanField(db_index=True, default=False)),
                ("is_lease_ready", models.BooleanField(db_index=True, default=False)),
                (
                    "is_direct_sale_enabled",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("FINISHED_GOOD", "Finished Good"),
                            ("RAW_MATERIAL", "Raw Material"),
                            ("ACCESSORY", "Accessory"),
                            ("SERVICE", "Service"),
                            ("ADD_ON", "Add-on"),
                        ],
                        db_index=True,
                        default="FINISHED_GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "stock_type",
                    models.CharField(
                        choices=[
                            ("STOCK_ITEM", "Stock Item"),
                            ("MADE_TO_ORDER", "Made to Order"),
                            ("NON_STOCK", "Non-Stock"),
                        ],
                        db_index=True,
                        default="STOCK_ITEM",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UPCOMING", "Upcoming"),
                            ("DISCONTINUED", "Discontinued"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "warranty_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Enable warranty coverage for this product",
                    ),
                ),
                (
                    "warranty_months_manufacturing",
                    models.PositiveIntegerField(
                        default=12, help_text="Manufacturing defect warranty (months)"
                    ),
                ),
                (
                    "warranty_months_structural",
                    models.PositiveIntegerField(
                        default=36,
                        help_text="Structural warranty for furniture (months, 0 = none)",
                    ),
                ),
                (
                    "warranty_months_extended_max",
                    models.PositiveIntegerField(
                        default=12, help_text="Max months for extended warranty plan"
                    ),
                ),
                (
                    "extended_warranty_cost_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7.5"),
                        help_text="Extended warranty cost as % of product price",
                        max_digits=4,
                    ),
                ),
                (
                    "catalog_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.catalogcategory",
                    ),
                ),
                (
                    "category_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products_core.productcategorymaster",
                    ),
                ),
                (
                    "subcategory_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products_core.productsubcategorymaster",
                    ),
                ),
                (
                    "unit_of_measure_master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products_core.productunitofmeasuremaster",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="RentalAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("serial_no", models.CharField(blank=True, default="", max_length=80)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("HANDED_OVER", "Handed Over"),
                            ("RETURNED", "Returned"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                (
                    "condition_grade",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                            ("SCRAP", "Scrap"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_rental_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rented_assets",
                        to="customers.customer",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="inventory.stocklocation",
                    ),
                ),
                (
                    "current_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="contracts.subscription",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_assets",
                        to="products_core.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_rental_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_rental_assets",
                "ordering": ["asset_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("ACCESSORY", "Accessory"),
                            ("RAW_MATERIAL", "Raw Material"),
                            ("SERVICE", "Service"),
                            ("ADD_ON", "Add-on"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "is_price_included_in_parent",
                    models.BooleanField(
                        default=True,
                        help_text="If true, the cost is included in the parent's base price. If false, it acts as an extra add-on cost.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_products",
                        to="products_core.product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_products",
                        to="products_core.product",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions_productrelationship",
                "indexes": [
                    models.Index(
                        fields=["product", "relationship_type"],
                        name="subscriptio_product_7df90d_idx",
                    ),
                    models.Index(
                        fields=["related_product"],
                        name="subscriptio_related_63bc7d_idx",
                    ),
                ],
                "unique_together": {
                    ("product", "related_product", "relationship_type")
                },
            },
        ),
        migrations.AddIndex(
            model_name="productsubcategorymaster",
            index=models.Index(
                fields=["category", "is_active", "name"],
                name="product_sub_categor_3b0a87_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productsubcategorymaster",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="uq_product_subcategory_per_category"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_code"], name="products_product_15b636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["subcategory"], name="products_subcate_6be120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["unit_of_measure"], name="products_unit_of_e0dcdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="products_is_acti_cb485f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gt", 0)),
                name="chk_product_base_price_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["status", "condition_grade"],
                name="subscriptio_status_2488c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["product", "status"], name="subscriptio_product_a0485b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["current_customer", "status"],
                name="subscriptio_current_177708_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalasset",
            index=models.Index(
                fields=["current_subscription", "status"],
                name="subscriptio_current_f0bdc5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_subscription__isnull", False),
                        ("status", "HANDED_OVER"),
                    ),
                    models.Q(("status", "HANDED_OVER"), _negated=True),
                    _connector="OR",
                ),
                name="rental_asset_handedover_requires_subscription",
            ),
        ),
            ],
            database_operations=[]
        )
    ]
