# Generated by Django 5.2.7 on 2026-08-02 01:59

import subscriptions.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=subscriptions.base_models.product_video_upload_to,
            ),
        ),
    ]
