# Generated by Django 5.2.7 on 2026-08-09 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0002_product_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "variant_code",
                    models.CharField(
                        help_text="e.g., BLU, RED, L, M, S", max_length=50
                    ),
                ),
                (
                    "variant_name",
                    models.CharField(
                        help_text="e.g., Blue, Red, Large", max_length=255
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated: SKU-{PRODUCTCODE}-{SEQUENCE}-{VARIANT}",
                        max_length=60,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated: BC-{PRODUCTCODE}-{CHECKSUM}",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "variant_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If null, inherits base_price from product",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Parent product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products_core.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="products_co_product_b3bd31_idx",
                    ),
                    models.Index(
                        fields=["sku", "is_active"], name="products_co_sku_8c482c_idx"
                    ),
                    models.Index(
                        fields=["barcode", "is_active"],
                        name="products_co_barcode_b548ff_idx",
                    ),
                ],
                "unique_together": {("product", "variant_code")},
            },
        ),
    ]
