# Generated by Django 5.2.7 on 2026-08-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0004_brand_and_allow_zero_base_price"),
        ("subscriptions", "0123_add_product_relationship_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productrelationship",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productrelationship",
            name="parent_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this relationship only applies to this specific variant of the parent product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_related_products",
                to="products_core.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="productrelationship",
            name="related_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, attaches a specific variant of the related accessory/raw material.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_parent_products",
                to="products_core.productvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrelationship",
            unique_together={
                (
                    "product",
                    "related_product",
                    "relationship_type",
                    "parent_variant",
                    "related_variant",
                )
            },
        ),
        migrations.AddIndex(
            model_name="productrelationship",
            index=models.Index(
                fields=["parent_variant"], name="subscriptio_parent__f9eedf_idx"
            ),
        ),
    ]
