# Generated by Django 5.2.7 on 2026-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_core", "0005_alter_productrelationship_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrelationship",
            name="parent_variant_sku",
            field=models.CharField(
                blank=True,
                help_text="SKU of the parent PIM variant",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productrelationship",
            name="related_variant_sku",
            field=models.CharField(
                blank=True,
                help_text="SKU of the related PIM variant",
                max_length=150,
                null=True,
            ),
        ),
    ]
