import type { WorkflowModule, WorkflowTask } from "@/features/admin-workflow/types";
import { buildAdminReconciliationRoute } from "@/lib/route-builders";

export const adminWorkflowModules: WorkflowModule[] = [
  {
    id: "customer-master",
    title: "Customer operations",
    description: "Customer onboarding, KYC verification, unified operational profile review, and duplicate prevention across direct-sale and subscription workflows.",
    href: "/admin/customers",
    owner: "Admin operations",
    health: "healthy",
    primaryMetric: "KYC queue",
    supportingMetric: "Profile completeness",
    actions: [
      { label: "Open customers", href: "/admin/customers" },
      { label: "Create customer", href: "/admin/customers/create" },
      { label: "Open collections", href: "/admin/collections" },
    ],
  },
  {
    id: "catalog-control",
    title: "Product catalog",
    description: "Price governance, advance EMI-ready catalog control, and import validation for retail inventory.",
    href: "/admin/products",
    owner: "Catalog team",
    health: "healthy",
    primaryMetric: "Catalog growth",
    supportingMetric: "Import quality",
    actions: [
      { label: "Open products", href: "/admin/products" },
      { label: "Create product", href: "/admin/products/create" },
    ],
  },
  {
    id: "subscription-ops",
    title: "Subscription sale control",
    description: "Lucky ID allocation, batch linkage, contract activation, delivery readiness, and live rent/lease operational compatibility.",
    href: "/admin/subscriptions",
    owner: "Subscription desk",
    health: "attention",
    primaryMetric: "Active contracts",
    supportingMetric: "Winner waivers",
    actions: [
      { label: "Open subscriptions", href: "/admin/subscriptions" },
      { label: "Create subscription", href: "/admin/subscriptions/advance-emi/create" },
    ],
  },
  {
    id: "direct-sale-desk",
    title: "Direct sale desk",
    description: "Retail direct-sale billing, invoice posting, delivery follow-through, and later receivable collection without mixing into subscription flows.",
    href: "/admin/billing/direct-sales",
    owner: "Retail desk",
    health: "attention",
    primaryMetric: "Open receivables",
    supportingMetric: "Retail receipts",
    actions: [
      { label: "Open direct sales", href: "/admin/billing/direct-sales" },
      { label: "Collect direct sale", href: "/admin/finance/collect?workflow=direct-sale" },
      { label: "Open retail receipts", href: "/admin/billing/receipts" },
    ],
  },
  {
    id: "collections",
    title: "Collections & recovery",
    description: "Subscription EMI follow-up, direct-sale receivable recovery, cashier coordination, and receipt-linked payment monitoring.",
    href: "/admin/collections",
    owner: "Collections team",
    health: "attention",
    primaryMetric: "Collections today",
    supportingMetric: "Verification lag",
    actions: [
      { label: "Open collections", href: "/admin/collections" },
      { label: "Collect Advance EMI", href: "/admin/finance/collect?workflow=advance-emi" },
      { label: "Collect direct sale", href: "/admin/finance/collect?workflow=direct-sale" },
    ],
  },
  {
    id: "supplier-payables",
    title: "Supplier payables",
    description: "Vendor master, purchase-bill visibility, settlement history, and payable tracking connected to inventory and finance accounts.",
    href: "/admin/accounting/vendors",
    owner: "Procurement finance",
    health: "healthy",
    primaryMetric: "Open payables",
    supportingMetric: "Posted purchase bills",
    actions: [
      { label: "Open vendors", href: "/admin/accounting/vendors" },
      { label: "Purchase register", href: "/admin/accounting/purchase-bills" },
      { label: "Vendor settlements", href: "/admin/accounting/vendor-settlements" },
    ],
  },
  {
    id: "batch-governance",
    title: "Batch governance",
    description: "Batch readiness, fill rate visibility, draw scheduling, and batch-level risk control.",
    href: "/admin/batches",
    owner: "Lucky plan desk",
    health: "healthy",
    primaryMetric: "Open batches",
    supportingMetric: "Fill rate",
    actions: [
      { label: "Open batches", href: "/admin/batches" },
      { label: "Create batch", href: "/admin/batches/create" },
    ],
  },
  {
    id: "reconciliation",
    title: "Subscription reconciliation",
    description: "Exception handling for subscription, advance EMI, and payment integrity before closeout.",
    href: buildAdminReconciliationRoute(),
    owner: "Finance control",
    health: "critical",
    primaryMetric: "Open exceptions",
    supportingMetric: "Audit readiness",
    actions: [
      {
        label: "Open subscription reconciliation",
        href: buildAdminReconciliationRoute(),
      },
      { label: "Open audit logs", href: "/admin/audit-logs" },
    ],
  },
];

export const defaultWorkflowTasks: WorkflowTask[] = [
  {
    id: "review-overdue",
    title: "Review overdue subscriptions",
    description: "Prioritize collections on contracts with pending advance EMI pressure.",
    href: "/admin/emis/overdue",
    tone: "warning",
  },
  {
    id: "verify-payments",
    title: "Verify posted collections",
    description: "Cross-check subscription and direct-sale references before daily close.",
    href: "/admin/payments/history",
    tone: "info",
  },
  {
    id: "prepare-next-draw",
    title: "Prepare lucky draw execution",
    description: "Confirm commit, reveal, and winner processing readiness.",
    href: "/admin/lucky-draws/create",
    tone: "default",
  },
  {
    id: "inspect-audit",
    title: "Inspect financial audit trail",
    description: "Review immutable actions before reconciliation sign-off.",
    href: "/admin/audit-logs",
    tone: "danger",
  },
];
