# Generated by Django 5.2.7 on 2026-08-29 06:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0003_initial"),
        ("crm", "0011_fold_workbench_from_subscriptions"),
        ("products_core", "0006_productrelationship_parent_variant_sku_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=120)),
                ("reviewer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField(blank=True)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("synced_google", models.BooleanField(default=False)),
                ("synced_facebook", models.BooleanField(default=False)),
                ("synced_whatsapp", models.BooleanField(default=False)),
                ("synced_instagram", models.BooleanField(default=False)),
                ("admin_note", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_reviews",
                        to="crm.partymaster",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products_core.product",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_reviews",
                        to="contracts.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "product_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="reviews/photos/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="product_reviews.productreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_photo",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "status"], name="product_rev_product_445d91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["rating"], name="product_rev_rating_494597_idx"),
        ),
    ]
