# Generated by Django 5.2.7 on 2026-07-08 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MYBILLBOOK", "myBillBook"),
                            ("GENERIC_CSV", "Generic CSV"),
                            ("EXCEL", "Excel"),
                            ("TALLY", "Tally"),
                            ("BUSY", "Busy"),
                            ("MARG", "Marg ERP"),
                            ("VYAPAR", "Vyapar"),
                            ("ZOHO_BOOKS", "Zoho Books"),
                            ("MSSQL", "Microsoft SQL Server"),
                            ("CUSTOM", "Custom ERP"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("MAPPED", "Mapped"),
                            ("VALIDATED", "Validated"),
                            ("PREVIEWED", "Previewed"),
                            ("APPROVED", "Approved"),
                            ("IMPORTING", "Importing"),
                            ("IMPORTED", "Imported"),
                            ("PARTIALLY_IMPORTED", "Partially Imported"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "file_checksum_sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("warning_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("source_headers", models.JSONField(blank=True, default=list)),
                ("preview_summary", models.JSONField(blank=True, null=True)),
                ("reconciliation_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "expected_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("import_started_at", models.DateTimeField(blank=True, null=True)),
                ("import_finished_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_migration_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rolled_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolled_back_migration_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "migration_center_batches",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MigrationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="migration_center.migrationbatch",
                    ),
                ),
            ],
            options={
                "db_table": "migration_center_audit_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MigrationMappingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("dataset_key", models.CharField(db_index=True, max_length=40)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MYBILLBOOK", "myBillBook"),
                            ("GENERIC_CSV", "Generic CSV"),
                            ("EXCEL", "Excel"),
                            ("TALLY", "Tally"),
                            ("BUSY", "Busy"),
                            ("MARG", "Marg ERP"),
                            ("VYAPAR", "Vyapar"),
                            ("ZOHO_BOOKS", "Zoho Books"),
                            ("MSSQL", "Microsoft SQL Server"),
                            ("CUSTOM", "Custom ERP"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("mapping", models.JSONField(default=dict)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="migration_mapping_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "migration_center_mapping_rules",
                "ordering": ["dataset_key", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_key", "source_type", "name"),
                        name="uq_migration_mapping_rule",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MigrationStagingRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField(db_index=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("mapped_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DUPLICATE", "Duplicate"),
                            ("IMPORTED", "Imported"),
                            ("SKIPPED", "Skipped"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("duplicate_matches", models.JSONField(blank=True, default=list)),
                (
                    "duplicate_resolution",
                    models.CharField(
                        choices=[
                            ("NONE", "Not a duplicate"),
                            ("SKIP", "Skip"),
                            ("MERGE", "Merge (fill blanks on existing)"),
                            ("UPDATE", "Update existing"),
                            ("CREATE_NEW", "Create new anyway"),
                        ],
                        default="NONE",
                        max_length=12,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "target_pk",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("extra_targets", models.JSONField(blank=True, default=list)),
                ("prior_state", models.JSONField(blank=True, null=True)),
                ("import_error", models.TextField(blank=True, default="")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="migration_center.migrationbatch",
                    ),
                ),
            ],
            options={
                "db_table": "migration_center_staging_rows",
                "ordering": ["batch_id", "row_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"),
                        name="uq_migration_staging_batch_row",
                    )
                ],
            },
        ),
    ]
