# Generated by Django 5.2.7 on 2026-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migration_center", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migrationbatch",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("WORKBENCH", "Web Workbench (manual entry)"),
                    ("MYBILLBOOK", "myBillBook"),
                    ("GENERIC_CSV", "Generic CSV"),
                    ("EXCEL", "Excel"),
                    ("TALLY", "Tally"),
                    ("BUSY", "Busy"),
                    ("MARG", "Marg ERP"),
                    ("VYAPAR", "Vyapar"),
                    ("ZOHO_BOOKS", "Zoho Books"),
                    ("MSSQL", "Microsoft SQL Server"),
                    ("CUSTOM", "Custom ERP"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="migrationmappingrule",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("WORKBENCH", "Web Workbench (manual entry)"),
                    ("MYBILLBOOK", "myBillBook"),
                    ("GENERIC_CSV", "Generic CSV"),
                    ("EXCEL", "Excel"),
                    ("TALLY", "Tally"),
                    ("BUSY", "Busy"),
                    ("MARG", "Marg ERP"),
                    ("VYAPAR", "Vyapar"),
                    ("ZOHO_BOOKS", "Zoho Books"),
                    ("MSSQL", "Microsoft SQL Server"),
                    ("CUSTOM", "Custom ERP"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
