type PdfSection = {
  heading: string;
  rows: Array<{ label: string; value: string }>;
};

const escapePdfText = (value: string): string => value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const buildContentLines = (title: string, sections: PdfSection[]): string[] => {
  const lines: string[] = [title, "Generated by Subidha Core", ""]; 

  sections.forEach((section) => {
    lines.push(section.heading);
    section.rows.forEach((row) => {
      lines.push(`${row.label}: ${row.value}`);
    });
    lines.push("");
  });

  return lines;
};

export function downloadSimplePdf(fileName: string, title: string, sections: PdfSection[]): void {
  const lines = buildContentLines(title, sections);
  const textCommands: string[] = [];

  let y = 780;
  lines.forEach((line) => {
    textCommands.push(`BT /F1 11 Tf 40 ${y} Td (${escapePdfText(line)}) Tj ET`);
    y -= 16;
    if (y < 60) {
      y = 780;
    }
  });

  const contentStream = textCommands.join("\n");

  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${contentStream.length} >> stream\n${contentStream}\nendstream endobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];

  objects.forEach((obj) => {
    offsets.push(pdf.length);
    pdf += `${obj}\n`;
  });

  const xrefStart = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.forEach((offset) => {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  });

  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.click();
  URL.revokeObjectURL(url);
}

export type { PdfSection };
