export const ROUTES = {
  public: {
    home: "/",
    products: "/products",
    apply: "/apply",
    about: "/about",
    luckyPlan: "/lucky-plan",
    howItWorks: "/how-it-works",
    policies: "/policies",
    rent: "/rent",
    lease: "/lease",
    directSale: "/direct-sale",
    visionTrust: "/vision-trust",
    winners: "/winners",
    winnerHistory: "/winner-history",
    contact: "/contact",
    blog: "/blog",
    login: "/login",
    register: "/register",
    unauthorized: "/unauthorized",
  },

  admin: {
    root: "/admin",
    dashboard: "/admin",

    analytics: "/admin/analytics",
    analyticsRiskMonitor: "/admin/analytics/risk-monitor",
    analyticsChurnAnalysis: "/admin/analytics/churn-analysis",
    operations: "/admin/operations",
    operationsCommandCenter: "/admin/operations/command-center",
    partnerPaymentRequests: "/admin/partner-payment-requests",
    auditLogs: "/admin/audit-logs",

    collections: "/admin/collections",
    leads: "/admin/leads",
    supportRequests: "/admin/support-requests",
    customers: "/admin/customers",
    deliveries: "/admin/deliveries",
    subscriptions: "/admin/subscriptions",
    subscriptionsCreate: "/admin/subscriptions/create",
    subscriptionRequests: "/admin/subscription-requests",
    payments: "/admin/payments",
    paymentsCreate: "/admin/payments/create",
    emis: "/admin/emis",
    emisOverdue: "/admin/emis/overdue",
    batches: "/admin/batches",
    products: "/admin/products",
    partners: "/admin/partners",
    reminders: "/admin/reminders",
    remindersPaymentReminders: "/admin/reminders/payment-reminders",

    crm: "/admin/crm",
    crmLeads: "/admin/crm/leads",
    crmParties: "/admin/crm/parties",

    billing: "/admin/billing",
    billingDirectSales: "/admin/billing/direct-sales",
    billingRegister: "/admin/billing/register",
    billingDailyBook: "/admin/billing/dailybook",
    billingCashBook: "/admin/billing/cashbook",
    billingInvoices: "/admin/billing/invoices",
    billingReceipts: "/admin/billing/receipts",
    billingContracts: "/admin/billing/contracts",
    billingCreditNotes: "/admin/billing/credit-notes",
    billingDebitNotes: "/admin/billing/debit-notes",
    billingDocuments: "/admin/billing/documents",

    inventory: "/admin/inventory",
    inventoryItems: "/admin/inventory/items",
    inventoryLocations: "/admin/inventory/locations",
    inventoryLedger: "/admin/inventory/ledger",
    inventoryMovements: "/admin/inventory/movements",
    inventoryValuation: "/admin/inventory/valuation",
    inventoryAdjustments: "/admin/inventory/adjustments",
    inventoryOpeningStock: "/admin/inventory/opening-stock",
    inventoryStockOnHand: "/admin/inventory/stock-on-hand",

    manufacturing: "/admin/manufacturing",
    manufacturingBoms: "/admin/manufacturing/boms",
    manufacturingJobs: "/admin/manufacturing/jobs",

    serviceDesk: "/admin/service-desk",
    serviceDeskCases: "/admin/service-desk/cases",
    serviceDeskComplaints: "/admin/service-desk/complaints",
    serviceDeskReturns: "/admin/service-desk/returns",
    serviceDeskTickets: "/admin/service-desk/tickets",

    accounting: "/admin/accounting",
    accountingSetup: "/admin/accounting/setup",
    accountingChartOfAccounts: "/admin/accounting/chart-of-accounts",
    accountingJournals: "/admin/accounting/journals",
    accountingPeriods: "/admin/accounting/periods",
    accountingBooks: "/admin/accounting/books",
    accountingBooksCash: "/admin/accounting/books/cash",
    accountingBooksBank: "/admin/accounting/books/bank",
    accountingBooksUpi: "/admin/accounting/books/upi",
    accountingBooksSales: "/admin/accounting/books/sales",
    accountingBooksPurchase: "/admin/accounting/books/purchase",
    accountingGst: "/admin/accounting/gst",
    accountingTaxInvoices: "/admin/accounting/gst/tax-invoices",
    accountingCreditNotes: "/admin/accounting/gst/credit-notes",
    accountingDebitNotes: "/admin/accounting/gst/debit-notes",
    accountingTrialBalance: "/admin/accounting/reports/trial-balance",
    accountingProfitLoss: "/admin/accounting/reports/profit-loss",
    accountingBalanceSheet: "/admin/accounting/reports/balance-sheet",
    accountingAssets: "/admin/accounting/assets",
    accountingDepreciation: "/admin/accounting/depreciation",
    accountingPurchaseBills: "/admin/accounting/purchase-bills",
    accountingVendors: "/admin/accounting/vendors",
    accountingVendorSettlements: "/admin/accounting/vendor-settlements",
    accountingExpenses: "/admin/accounting/expenses",
    accountingBridges: "/admin/accounting/bridges",
    accountingItrPack: "/admin/accounting/exports/itr-pack",
    accountingStaff: "/admin/accounting/staff",
    accountingAttendance: "/admin/accounting/attendance",
    accountingLeave: "/admin/accounting/leave",
    accountingSalary: "/admin/accounting/salary",
    accountingExpenseClaims: "/admin/accounting/expense-claims",
    accountingStaffLedger: "/admin/accounting/staff-ledger",

    branches: "/admin/branches",
    counters: "/admin/counters",
    branchReporting: "/admin/branch-reporting",

    finance: "/admin/finance",
    financeReconciliation: "/admin/finance/reconciliation",
    paymentReconciliation: "/admin/payments/reconciliation",
    financeCommissions: "/admin/finance/commissions",
    financeSettledCommissions: "/admin/finance/commissions/settled",
    financePayoutBatches: "/admin/finance/payout-batches",

    luckyIds: "/admin/lucky-ids",
    luckyDraws: "/admin/lucky-draws",
    luckyDrawsCreate: "/admin/lucky-draws/create",

    reports: "/admin/reports",
    reportsRevenue: "/admin/reports/revenue",
    reportsCollections: "/admin/reports/collections",
    reportsOverdue: "/admin/reports/overdue",
    reportsCustomerAnalytics: "/admin/reports/customer-analytics",
    reportsBatchPerformance: "/admin/reports/batch-performance",
    settings: "/admin/settings",
    settingsUsers: "/admin/settings/users",
    settingsUsersCreate: "/admin/settings/users/create",
    settingsBusiness: "/admin/settings/business",
    settingsFinance: "/admin/settings/finance",
    settingsImports: "/admin/settings/imports",
    settingsMasters: "/admin/settings/masters",
    settingsBusinessSetup: "/admin/settings/business-setup",
    settingsBusinessSetupProfile: "/admin/settings/business-setup/profile",
    settingsBusinessSetupBranches: "/admin/settings/business-setup/branches",
    settingsBusinessSetupFinanceAccounts: "/admin/settings/business-setup/finance-accounts",
    settingsBusinessSetupCashDesks: "/admin/settings/business-setup/cash-desks",
    settingsBusinessSetupStaff: "/admin/settings/business-setup/staff",
    settingsBusinessSetupChartAccounts: "/admin/settings/business-setup/chart-accounts",
    settingsBusinessSetupChecklist: "/admin/settings/business-setup/checklist",

    luckyDraw: "/admin/lucky-draws",
    reconciliation: "/admin/reconciliation",

    legacyLuckyDraw: "/admin/lucky-draw",
    legacyLuckyDrawHistory: "/admin/lucky-draw/history",
    legacyFinanceReconciliation: "/admin/finance/reconciliation",
    legacyReconciliation: "/admin/reconciliation",
  },

  partner: {
    root: "/partner",
    dashboard: "/partner",
    collections: "/partner/collections",
    subscriptionRequests: "/partner/subscription-requests",
    customers: "/partner/customers",
    subscriptions: "/partner/subscriptions",
    payments: "/partner/payments",
    commissions: "/partner/commissions",
    reports: "/partner/reports",
  },

  customer: {
    root: "/customer",
    dashboard: "/customer",
    subscriptions: "/customer/subscriptions",
    subscriptionRequests: "/customer/subscription-requests",
    deliveries: "/customer/deliveries",
    profile: "/customer/profile",
    support: "/customer/support",
    emis: "/customer/emis",
    payments: "/customer/payments",
  },

  cashier: {
    root: "/cashier",
    dashboard: "/cashier",
    collect: "/cashier/collect",
    payments: "/cashier/payments",
  },
} as const;
