# Generated by Django 6.0.2 on 2026-05-22 07:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import settlements.models
import settlements.services.settlement_number_service
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0027_seed_default_non_gst_business_tax_profile'),
        ('billing', '0013_billinginvoice_tax_profile_snapshot_and_more'),
        ('branch_control', '0002_seed_primary_branch_and_backfill_context'),
        ('subscriptions', '0069_businessdatabackupjob_businessdatarestorejob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_no', models.CharField(db_index=True, default=settlements.services.settlement_number_service.generate_bank_statement_import_no, max_length=40, unique=True)),
                ('statement_period_from', models.DateField(db_index=True)),
                ('statement_period_to', models.DateField(db_index=True)),
                ('uploaded_file', models.FileField(blank=True, max_length=500, null=True, upload_to=settlements.models.bank_statement_upload_to)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('PARTIALLY_MATCHED', 'Partially Matched'), ('MATCHED', 'Matched'), ('VOIDED', 'Voided'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=24)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bank_finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_imports', to='accounting.financeaccount')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_bank_statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements_bank_statement_imports',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField()),
                ('reference_no', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('matched_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('PARTIAL', 'Partial'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored'), ('NEEDS_REVIEW', 'Needs Review')], db_index=True, default='UNMATCHED', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlements.bankstatementimport')),
            ],
            options={
                'db_table': 'settlements_bank_statement_lines',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CashierDayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_no', models.CharField(db_index=True, default=settlements.services.settlement_number_service.generate_cashier_day_close_no, max_length=40, unique=True)),
                ('business_date', models.DateField(db_index=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('system_cash_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided')], db_index=True, default='DRAFT', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_cashier_day_closes', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_day_closes', to='branch_control.branch')),
                ('cash_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_day_closes', to='branch_control.cashcounter')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_day_closes', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cashier_day_closes', to=settings.AUTH_USER_MODEL)),
                ('finance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_day_closes', to='accounting.financeaccount')),
            ],
            options={
                'db_table': 'settlements_cashier_day_closes',
                'ordering': ['-business_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('BANK_STATEMENT_LINE', 'Bank Statement Line'), ('UPI_SETTLEMENT_LINE', 'UPI Settlement Line'), ('CASHIER_DAY_CLOSE', 'Cashier Day Close')], db_index=True, max_length=30)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('matched_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('MATCHED', 'Matched'), ('PARTIAL', 'Partial'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided')], db_index=True, default='PROPOSED', max_length=12)),
                ('matched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='accounting.financeaccount')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_settlement_allocations', to=settings.AUTH_USER_MODEL)),
                ('money_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='accounting.moneymovement')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='subscriptions.payment')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_allocations', to='billing.receiptdocument')),
            ],
            options={
                'db_table': 'settlements_settlement_allocations',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UpiSettlementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_no', models.CharField(db_index=True, default=settlements.services.settlement_number_service.generate_upi_settlement_import_no, max_length=40, unique=True)),
                ('settlement_date', models.DateField(db_index=True)),
                ('uploaded_file', models.FileField(blank=True, max_length=500, null=True, upload_to=settlements.models.upi_settlement_upload_to)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADED', 'Uploaded'), ('PARSED', 'Parsed'), ('PARTIALLY_MATCHED', 'Partially Matched'), ('MATCHED', 'Matched'), ('VOIDED', 'Voided'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=24)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('upi_finance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upi_settlement_imports', to='accounting.financeaccount')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_upi_settlement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements_upi_settlement_imports',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UpiSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_ref', models.CharField(db_index=True, max_length=120)),
                ('payment_ref', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('settlement_date', models.DateField(db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('matched_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('PARTIAL', 'Partial'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored'), ('NEEDS_REVIEW', 'Needs Review')], db_index=True, default='UNMATCHED', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('settlement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlements.upisettlementimport')),
            ],
            options={
                'db_table': 'settlements_upi_settlement_lines',
                'ordering': ['settlement_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['bank_finance_account', 'statement_period_from', 'statement_period_to'], name='settlements_bank_fi_20b39e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['status', 'uploaded_at'], name='settlements_status_48045b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['checksum'], name='settlements_checksu_e1c538_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementimport',
            constraint=models.CheckConstraint(condition=models.Q(('statement_period_to__gte', models.F('statement_period_from'))), name='settlements_bank_statement_period_order'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement_import', 'transaction_date'], name='settlements_stateme_23f18e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['matched_status', 'transaction_date'], name='settlements_matched_760d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reference_no'], name='settlements_referen_a316a9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['normalized_reference'], name='settlements_normali_8c88f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='settlements_bank_line_non_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='settlements_bank_line_no_dual_sign'),
        ),
        migrations.AddIndex(
            model_name='cashierdayclose',
            index=models.Index(fields=['cashier', 'business_date', 'status'], name='settlements_cashier_b34d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierdayclose',
            index=models.Index(fields=['branch', 'business_date', 'status'], name='settlements_branch__ca230c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierdayclose',
            index=models.Index(fields=['cash_counter', 'business_date', 'status'], name='settlements_cash_co_3544bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierdayclose',
            index=models.Index(fields=['finance_account', 'business_date', 'status'], name='settlements_finance_74e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['source_type', 'source_id'], name='settlements_source__038e29_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['payment'], name='settlements_payment_bd75a4_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['receipt'], name='settlements_receipt_da1095_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['money_movement'], name='settlements_money_m_24e3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['finance_account'], name='settlements_finance_0a3715_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementallocation',
            index=models.Index(fields=['status', 'created_at'], name='settlements_status_3f6109_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('matched_amount__gt', 0)), name='settlements_allocation_matched_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='settlementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('payment__isnull', False), ('receipt__isnull', False), ('money_movement__isnull', False), _connector='OR'), name='settlements_allocation_requires_target'),
        ),
        migrations.AddIndex(
            model_name='upisettlementimport',
            index=models.Index(fields=['upi_finance_account', 'settlement_date'], name='settlements_upi_fin_de6787_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementimport',
            index=models.Index(fields=['status', 'uploaded_at'], name='settlements_status_471f27_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementimport',
            index=models.Index(fields=['checksum'], name='settlements_checksu_0e6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementline',
            index=models.Index(fields=['settlement_import', 'settlement_date'], name='settlements_settlem_fe0bab_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementline',
            index=models.Index(fields=['matched_status', 'settlement_date'], name='settlements_matched_7841fb_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementline',
            index=models.Index(fields=['transaction_ref'], name='settlements_transac_711cee_idx'),
        ),
        migrations.AddIndex(
            model_name='upisettlementline',
            index=models.Index(fields=['payment_ref'], name='settlements_payment_3f99cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='upisettlementline',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0), ('fee_amount__gte', 0), ('net_amount__gte', 0)), name='settlements_upi_line_non_negative_amounts'),
        ),
    ]
